### ISSUE TITLE
Не принимаются ответы в некоторых упражнениях

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#1]
Буду первым :) 
В разделе 1.4.2. Stream API в заданиях: 0.4. Понятие редукции, 5.3. Промежуточные операции и 8.1. Промежуточные операции - не принимаются ответы, хотя в idea предложенные тесты проходятся, результат выдается вот такой:

> error: invalid flag: /root/job4j_edu/sandbox/0873958f743e2c86017448e9946b0f2a/
Usage: javac <options> <source files>
use --help for a list of possible options

**Comment by kamikhaylov** [comment]
В доп.упражнение 5.3. Промежуточные операции. Метод map(). Map с объектами
Не принимает ответ:
    public static List<User> map(List<Integer> ages) {
        return ages.stream()
                .map(User::new)
                .collect(Collectors.toList());
    }
Ошибка:
error: invalid flag: /root/job4j_edu/sandbox/0873958f75835f7501758420bf7b33b7/
Usage: javac <options> <source files>
use --help for a list of possible options

В IDEA - тест проходит.

**Comment by staskorobeynikov** [comment]
спасибо, указанные задания исправлены
