### ISSUE TITLE
Опечатки в упражнениях

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#10]
Упражнения 1.1.5. Циклы 9.2. Найти сумму каждого второго числа в диапазоне
Даны два целых положительных числа a и b (b > a). Надо сложить каждое второе число в диапазоне [a, b] начиная с первого

Например,

[1, 2] => 1

[1, 3] => 1 + 3 = 4

[1, 5] => 1 + 3 + 5 = 9

[0, 5] => 0 + 2 + 4 + 6 = 12 <<<<< **Цифра 6 вне диапазона [0, 5]**

=========================================================================
=========================================================================

Упражнения 1.1.4. Оператор ветвления 5. Стоит ли играть?
 (при условии что >>>>> читая <<<<< прибыль меньше или равна 0).

**Опечатка в слове - чиСтая- пропущена буква**

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
