### ISSUE TITLE
0. Tomcat - java http server. [#6864 #256686]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1000]
По сообщению Стаса:
"Установите 9 версию, с 10 дальше могут быть проблемы"

Предложил бы это добавить, хотя бы как рекомендацию,
в сам урок, т.к. обычная логика ученика ставить последнюю версию,
если явно не рекомендовано другое.

P.S. это тысячное предложение так то))

**Comment by peterarsentev** [comment]
Спасибо. Мы убрали из курса использование tomcat. Теперь только встроенные серверы через Spring boot.
