### ISSUE TITLE
2. Создания чата на Rest API. [#9143]

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#1001]
2. Создания чата на Rest API. [#9143]12
Уровень : 3. Мидл Категория : 3.4. SpringТопик : 3.4.8. Rest

Можно сказать что в задании практически полностью отсутствует описание.
Что имеется ввиду под -Приложение должно реализовывать чат c комнатами. ?
как должно выглядеть приложение после его запуска?
Прошу Вас по возможности сделать более детальное описание задания.
Спасибо

**Comment by staskorobeynikov** [comment]
Неактуально. Задание это удалено
Закрываю
