### ISSUE TITLE
1. Техническое задание - проект "Работа мечты" [#260362 #258766]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1002]
Цитирую:
3. Добавьте две модели данных - кандидат и кадровик.

По сообщению от Стаса:
Можете вообще ничего не добавлять, просто каркас мавен проекта

Предлагаю на этом этапе исключить п. 3, т.к. 
1) непонятно, что и как там писать
2) как я понимаю, на этом этапе он не нужен

**Comment by peterarsentev** [comment]
Так и сделали. Спасибо.
