### ISSUE TITLE
1. Maven web проект. [#276373 #260639]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1004]
Вопросы и замечания

1. 
Не знаю, насколько это важно.
Заметил вот какую особенность по структуре папок web
В некоторых местах пишут, что структура папок при создании 
(или переделке из обычного проекта) несколько другая, чем 
указано у нас, например
1) у Алишева в этом видео 18 года
https://www.youtube.com/watch?v=hk4rzwH9-kY
структура папок другая
<img width="588" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/152636814-2d1b72b4-c1f2-4e9d-b618-9cac252e6601.png">
2) или вот более свежий пример нашего индийского друга 20 года
тоже несколько другая структура
https://www.youtube.com/watch?v=J212XSlZfDY
<img width="666" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/152636925-12ac26a1-cf6b-4897-9586-7e815e6881b3.png">

Не могли бы разъяснить эти вопросы в курсе?

Предположил бы, что структура папок меняется в зависимости от того, что подключать сначала, Maven web проект, или веб, а потом уже Maven

**Comment by YarTsin** [comment]
Второй вопрос связан с некоторой путаницей в заданиях

В первой задаче
1. Техническое задание - проект "Работа мечты"   [#260362 #258766]
описано техническое задание и сказано создать проект

В следующей задаче
1. Maven web проект. [#276373 #260639]
Сказано сделать с нуля web проект

По запросу в чате Мидлов "Maven web проект"
некоторые люди не понимают, зачем делать два проекта.
(с одним названием)

Как вариант
Предложил бы оставить в тех. задании просто описание проекта
а в "Maven web проект" делать проект, либо показать (добавить инфу), как сделать
из обычного проекта web проект, (например, через меню
File -> Progect Structure -> Facets)

**Comment by peterarsentev** [comment]
Добрый день.
1. Есть документация от maven. Там указана, что папка должна находиться src/main/webapp. Я сделаю документации от maven. Раньше, мы использовали ANT. Там не произвольная папка была, я думаю, что другие люди делают по старинке.
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html 
2. Тут поправили описание.
