### ISSUE TITLE
0. JSP - Java Server Page [#6867 #260920]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1006]
При коммите вылезло несколько ошибок
Возможно нужно что-то подправить
<img width="903" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/152675515-f7b0c20e-54f1-4332-98e3-0b47507d9463.png">

**Comment by staskorobeynikov** [comment]
Неактуально. JSP уже нет в курсе
Закрываю
