### ISSUE TITLE
4. candicates.jsp - список кандидатов. [#276522 #261310]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1007]
В задании 
2. Scriplet. Динамическая таблица. [#276520 #261058]
при создании класса Store мы используем final в строке
private final Map<Integer, Post> posts = new ConcurrentHashMap<>();

в задании 
4. candicates.jsp - список кандидатов. [#276522]
final уже нет.
Предлагаю исправить и написать:
private final Map<Integer, Post> posts = new ConcurrentHashMap<>();
private final Map<Integer, Candidate> candidates = new ConcurrentHashMap<>();

ззззззззззззззззз

После фразы
"Добавим методы findAllCandidates(). findAllPosts(). Метод findAll() удалим."

я бы предложил добавить -
не забудьте исправить файл, posts.jsp, и заменить в нем метод

**Comment by peterarsentev** [comment]
Неактуально. Я переписал на другой блок.
