### ISSUE TITLE
1. Servlet. Web.xml [#6866]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1008]
Вопрос по классу PostServlet
строка
Store.instOf().save(new Post(0, req.getParameter("name")));

в одном из предыдущих занятий, когда делали класс Post
в задании было сказано сделать его с 4 полями.
Теперь или здесь дополнять, или доп. конструктор делать?

ххххххххххххххххх

Получил ошибку, вероятно от нового чекстайла
Name 'POST_ID' must match pattern '^[a-z][a-zA-Z0-9]*$'. [StaticVariableName]
Пока поменял на postId. 
Возможно тоже самое надо сделать и в следующих уроках

ххххххххххххххххх

Вместо метода save предложил бы сделать метод savePost
так как в следующем задании было бы логично сделать
в классе Store метод saveCandidate,
а также исправить это в следующих уроках

**Comment by staskorobeynikov** [comment]
Неактуально. Структура уже другая
Закрываю.
