### ISSUE TITLE
1. JSTL замена Scriplets [#2516 #263363]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1010]
Прошу обратить внимание на обсуждения по этой теме
Не у всех получается запуститься после выполнения задания.

В моем случае, после выполнения задания сразу 
не запустилось, а запустилось после замены импорта на:
"taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
Томкат 9.0.58

Выдавал 500 ошибку (непонятную)
<img width="944" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/153621309-a95bc9c9-25d7-481f-98ac-b4065b3c7478.png">

**Comment by staskorobeynikov** [comment]
Неактуально, все на thymeleaf переделано
Закрываю
