### ISSUE TITLE
1. Загрузка и скачивание файла. [#154183]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1012]
1. Загрузка и скачивание файла. [#154183]

Если мы делаем это задание в рамках проекта Dreamjob
то возможно в web.xml в теге <servlet-class> 
будет servlet, а не servlets
и ссылка будет выглядеть
не 
http://localhost:8080/download
а
http://localhost:8080/dreamjob/download

хххххххххххх

В файле upload.jsp
Idea ругается на тег valign
в строке
<tr valign="top">

и 
незакрытый тег в строке
img src="<c:url value='/download?name=${image}'" width="100px" height="100px"

хххххххххххх

Не очень понятны картинки
по Процессу загрузки и скачивания файлов.
Разве операции проходят не между
Сервером и Браузером?

**Comment by staskorobeynikov** [comment]
Неактуально, сейчас картинки грузятся иным образом
Закрываю
