### ISSUE TITLE
1. Динамический список на массиве. [#158 #265832] каркасы классов в разных папках

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#1013]
> 1. Опишем интерфейс
> package ru.job4j.list;
> 
> 2. Создадим каркас класса:
>  package ru.job4j.collection;
>  

а в следующем задании уже  package ru.job4j.collection.list. Вероятно имеется в виду одна и та-же папка в обоих заданиях? Уточните пожалуйста.

**Comment by staskorobeynikov** [comment]
Везде стоит collection
Закрываю.
