### ISSUE TITLE
Новые функции на курсе. Обновление уроков

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1015]
Пожелания и предложения.
Было бы хорошо в курсе видеть, 
когда появляются новые уроки и особенно,
когда обновляются и дополняются старые.
Думаю, это любому ученику полезно знать,
что появилось нового в теме или улучшилось. 

Как вариант, на обновленных уроках в общей таблице уроков  
можно было бы ставить одноразовый значок UP (update)
и (или) NEW, возможно другие метки (в разработке, to do и т.д.)
Возможно и кураторам это было бы полезно, ориентироваться
по своим меткам что делать, что переделывать и т.д.

Например Тема (в степени UP) или Тема (в степени NEW)
После одноразового посещения этой темы значок гаснет.
Что-то типа такого:

<img width="678" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/154836672-8c0a1711-b87a-4a53-b3d6-5b471c57e135.png">

**Comment by peterarsentev** [comment]
Спасибо. Сделал так. Если обновление было после того, как ученик решил урок, то появляется иконка recycle.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/694978/71dd6d0c-3699-4672-b4ca-c7467eefa587)
