### ISSUE TITLE
Поменять местами упражнения - идут не в порядке изучения материала

### ISSUE THREAD

**Issue by HmViper** [peterarsentev/job4j_features_bugs#1016]
Упражнение 1.4.2. Stream API/ "2.8. Сборка элементов. Сборка в Map, когда есть дубликаты" необходимо поменять местами с "2.6. Сборка элементов. Сборка в произвольную реализацию Map ." так как 2.8 изучается перегруженный метод с 4 параметрами, а в 2.6 с тремя - неверная очередность изучения.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
