### ISSUE TITLE
Postgres на Mac OS

### ISSUE THREAD

**Issue by Krasobas** [peterarsentev/job4j_features_bugs#1017]
Я работаю на Mac OS и у меня возникли проблемы c sql - методом lower() -  он корректно работал для английского языка, но не работал для русского. Раиль предположил, что проблемы с кодировкой и попросил занести сюда этот баг.
![image](https://user-images.githubusercontent.com/36446403/154937935-eb8f4eb9-777f-44ca-8c6e-2494eafe1216.png)

**Comment by peterarsentev** [comment]
Если еще актуально, то нужно посмотреть какая кодировка установлено при создании базы.
Нужно везде ставить UTF-8, тогда будет работать.
https://stackoverflow.com/questions/9961795/utf8-postgresql-create-database-like-mysql-including-character-set-encoding-a
