### ISSUE TITLE
1. Синхронный обмен сообщений [#458496 #267787]

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#1018]
Уровень : 3. Мидл Категория : 3.5. Микросервисы Топик : 3.5.3. Межпроцессорное взаимодействие
Код к данному заданию приложен не полностью, отсутствует целый класс выполняющий немаловажную функцию, 
а именно
import ru.job4j.tracker.service.TrackerService;
слой сервис задействован в данном задании 
https://prnt.sc/_68ekSkOy26r

как следствие, код не протестировать , материал к которому он приложен без кода не удобо-изучаем.
 но, выполнить конечно же таску можно.
что  более Важно, 
следующей таской  - 2. Асинхронное взаимодействие [#458497 #268058]23
Уровень : 3. МидлКатегория : 3.5. МикросервисыТопик : 3.5.3. Межпроцессорное взаимодействие
 идет добавление в проект Кафка и  Зукипер,
и примеры в коде идут прямым продолжением кода из данной таски.
Для тех кто никогда не работал и не видел как это должно работать, выполнение задания усложнено в разы.
и примеры в коде идут прямым продолжением кода из данной таски.
Пожалуйста добавьте не достающий класс,

**Comment by peterarsentev** [comment]
@Halsyon Спасибо. Заменили на проект CheckDev.
