### ISSUE TITLE
1. DbStore. [#281226]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1019]
Не сразу вспомнил(нашёл), как создается и подключается 
база данных к проекту.
Предлагаю дать ссылку на урок для повторения.
(возможно это:
Установка PostgreSQL [#55346] 
https://job4j.ru/profile/exercise/50/task-view/334/solutionId/4000
)
или кратенько напомнить основные этапы подключения 

ххххххххххххххххх

Не очень понятно почему этот метод приватный
private Post create(Post post)
Мы же создаем новые объявления?

ххххххххххххххххх

Похоже что переменная instance 
в этой строке

private static final DbStore instance = new DbStore();

в классе DbStore не используется

Также не используется импорт
import java.io.FileReader;

ххххххххххххххххх

Стас везде сказал добавить логирование,
хотя изначально в задании я этого не нашёл
Предлагаю добавить это в код или в задания
к уроку

**Comment by staskorobeynikov** [comment]
По логированию добавил информацию в актуальную версию курса. В остальном - неактуально
Закрываю.
