### ISSUE TITLE
Баллы за уроки

### ISSUE THREAD

**Issue by OtBbNA** [peterarsentev/job4j_features_bugs#1020]
У вас есть система рейтинга, которая мотивирует людей быть лучше других. Также я заметил, что, по крайней мере, на уровне Джун большинство ответов лежит в самом упражнении. В чем предложение - сначала в упражнении будет краткое описание того, что будет изучаться и текст задания - за это упражнение вы получите максимум баллов - допустим 50. Также ученик может открывать подсказки, каждая из которых будет уменьшать количество очков на 10. Итого со всеми подсказками вы получите максимум 10. Можно еще вынести таблицу где-нибудь в углу с первыми 5 людьми. Не знаю, насколько сильно это будет мотивировать людей, просто пришла в голову такая идея.
![Безыввмянный](https://user-images.githubusercontent.com/96254902/155995114-d20d99af-4306-4dc6-94ec-8ba1c687e92d.png)

**Comment by YarTsin** [comment]
не уверен, что время, потраченное на разработку такой системы окупится, даже мотивацией.

**Comment by itfedorovsa** [comment]
Я считаю, что такая система очень сложна в реализации и настройке, так как каждый человек мыслит по-своему, и у каждого свои способности. Один без подсказок всё поймет, а другой с 5 подсказками так и не поймет как решить. Задачи в курсе не являются вопросами с конкретными ответами типа "Столица России - Москва".

**Comment by peterarsentev** [comment]
@OtBbNA Спасибо за идею. Она интересная, но сложная в реализации. Так же мы уже переименовали рейтинг в скорость, а рейтинг даем за положительные отзывы по разделу обсуждения.
