### ISSUE TITLE
1. HttpSession [#6869]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1021]
Вопросы по теме.
Цитирую:
"У нас есть отдельная кнопка Выйти - ее функционал реализуем отдельно. Для этого определим следующую ссылку в сервлете:"
В сервлете или в posts.jsp?

ххххххххххххххх

Во время работы  с почтой и паролем в файле login.jsp
не очень понятно следующее:
- мы вводим почту и пароль и нам нужно 
искать человека по почте, соответственно,
как я понимаю, мы должны в DbStore добавлять новый 
метод поиска. Об этом в задании не сказано,
или нужно было об этом догадаться самостоятельно?

хххххххххххххххх

По информации из сообщения Стаса:

Меню "должно быть на всех страницах - можно создать одну jsp которая будет содержать все эти пункты, а потом просто подключить ее к каждой Jsp чтобы не дублировать код"

Предложил бы добавить урок с созданием "строки меню с элементами авторизации",
например menu.jsp, которую потом можно было бы  внедрить в основные страницы,
где оно нужно, в целях - не дублировать код.
Соответственно нужно подправить п.2, 3 в задании

ххххххххххххххххххх

Если я правильно понимаю в класс User нужно добавить 2 конструктора - пустой и со всеми полями

**Comment by staskorobeynikov** [comment]
Неактуально
Курс имеет другую структуру
Закрываю.
