### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1023]
Столкнулся с тем, что travis стал платным и отказывается собирать проект
Люди в чате стажера сообщают, что вроде как отменили уроки по travis.
Что теперь делать? Какие мысли у кураторов? 
Раньше говорили, что это нужное дело - сборка проекта на сайте.
Будет ли замена этому сервису?  Некоторые предлагают какой-то GitHub action
Может быть его использовать вместо тревиса?

<img width="497" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/156602665-1cba856b-2d13-46e6-94a2-1e12184cb028.png">

**Comment by GrizzlLearn** [comment]
Было бы круто иметь учебный gitlab CE, он простой как угол дома + будет практика создавать МР, настроивать CI.
У нас в компании прогеры простые CI сами настраивают, считаю это полезным навыком.

**Comment by peterarsentev** [comment]
Заменили на GitHub Actions. 
https://job4j.ru/profile/exercise/31/task-view/1178
