### ISSUE TITLE
исчезает отступ на сайте 

### ISSUE THREAD

**Issue by DmitriyRadomirov** [peterarsentev/job4j_features_bugs#1024]
![полное окно](https://user-images.githubusercontent.com/98541893/156822359-d75b87f4-77cc-4a1e-9143-5d19d432c823.jpg)

При уменьшении окна браузера на пол экрана слипаются элементы "<"  и "Job4j".

**Comment by peterarsentev** [comment]
Уже не актуально. Мы обновили дизайн, теперь нет левой панели.
