### ISSUE TITLE
1. Написать тест на PostServlet. [#2518]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1027]
В задании
0. Что такое Mock-объект. [#6870 #273519]
мы подключали библиотеку
mockito версии 3.5.13
Было сказано, что это самая стабильная версия

В задании
1. Написать тест на PostServlet. [#2518]
сказано подключить эту библиотеку
версии 4.0.0

Уточните, какую лучше версию использовать в итоге?

ххххххххххххххххх

Есть вопросы к тесту
В строке
String path = edit != null ? "/post/edit.jsp" : "/post/posts.jsp";
Как я понимаю второе значение должно быть просто
posts.jsp, т.к. этот файл в корне webapp

package ru.job4j.dream.controller;
У нас сервлеты лежат в папке servlet

**Comment by staskorobeynikov** [comment]
Старайтесь использовать последние версии. В задаче по mockito подчеркивается, что на момент написания задания была другая версия.
По остальному - неактуально, у нас уже нет JSP
Закрываю.
