### ISSUE TITLE
Чаты, ограничения по мату

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1028]
Предложил бы добавить в правила чатов ограничения по мату. Не думаю, что всем ученикам и кураторам приятно наблюдать его в учебном чате, где они пришли учиться, образовываться, это не то место для мата. Все-таки учебное место должно хотя бы  обладать некоторой моралью и этикой и вести людей к свету и добру.

**Comment by ViktorJava** [comment]
за некоторой моралью и этикой, в оперный театр милости просим. А девочки, пожалуйста закрывайте уши когда мужики эмоционально разговаривают

**Comment by YarTsin** [comment]
Вы знаете, мне кажется, должны оставаться хоть какие-то отдельные места, где люди стараются не скатываться по наклонной - театр, церковь и школа - из таких))

**Comment by peterarsentev** [comment]
За этим стараемся следить. Спасибо.
