### ISSUE TITLE
2. Валидация формы JS. [#58531]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1029]
Пока не очень понятно значение символа $
в контексте скрипта.
Это что-то типа "для любого элемента с id '#usr'"?

В некоторых источниках написано, что-то
"Знак доллара обычно используется как ярлык (короткая запись) для функции document.getElementById()"
Может быть дать пояснения этого на курсе? Не все же знают?

**Comment by staskorobeynikov** [comment]
Неактуально, на курсе уже нет JS
Закрываю.
