### ISSUE TITLE
Вопросы в чатах

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1030]
Постоянно сталкиваюсь с тем, что люди 
в чатах неправильно задают вопросы
Предложил бы добавить в Стажере, в разделе
Вводная часть статью, как правильно задавать вопросы
или хотя бы ссылку
https://job4j.ru/posts/3_skills_java_dev_2018.html
а в экзаменах добавил вопрос по этой теме

**Comment by ViktorJava** [comment]
еще нужно добавить ссылку на учебники по русскому языку и ввести жесткие правила и ответственность за нарушение правил, что касается орфографических ошибок. В экзаменах, добавить вопросы, по этим направлениям. Ещё нужны учебники по философии и истории. Я вижу, у некоторых хромают знания в этих направлениях. Ещё нужно методички по улучшению памяти, по ораторскому делу, массовые выступления. Вокал очень нужен при собеседованиях. Главный вопрос: nахуя?!

**Comment by YarTsin** [comment]
1) Я думаю, что если Петр посвятил этому вопросу отдельную статью, то это важно.
2) Я думаю, что правильно заданный вопрос, это половина ответа.
могу ещё дописать аргументов
3) И отвечая на ваш вопрос - неправильно задавая вопрос - тем самым ты создаешь проблему для отвечающих в том, что недостаточно информации для анализа(например) и себе - тем, что людям лень отвечать на неполные вопросы и ответа ты можешь не получить.

**Comment by ViktorJava** [comment]
Все три пункта имеют право на жизнь, хотя с некоторыми можно не согласиться. но это не важно. проверка знаний  нафига? экзамен ради экзамена? Петр своей статьей дал понять, что это нужный навык, а дальше Качайте свой скил в этом направлении.

**Comment by itfedorovsa** [comment]
Данный урок был добавлен. Но не совсем про чат, а в общем про умение программиста формулировать и задавать вопрос правильно https://job4j.ru/profile/exercise/141/task-view/984 Спасибо, закрываю!
