### ISSUE TITLE
2. Создания чата на Rest API. [#9143 #275630]

### ISSUE THREAD

**Issue by PavelRost** [peterarsentev/job4j_features_bugs#1031]
Задание звучит следующим образом:
"1. Реализовать REST Api через Spring Boot
2. Сделать четыре модели Person. Role. Room, Message.
3. Приложение должно реализовывать чат c комнатами."

При виде такого задания, возникает много вопросов, а что конкретно надо реализовывать, а на что можно не тратить время. Указано, что необходимо сделать 4 модели. А надо ли делать контроллеры, сервисы, репозиторий или достаточно хранение в памяти (дальше по урокам окажется, что достаточно в памяти). 
п.3 здесь совсем не понятно, что должно быть сделано - что значит реализовать чат с комнатами? 
Хотелось бы больше конкретики в задании.

**Comment by AshleySunsine** [comment]
Поддерживаю автора.

**Comment by staskorobeynikov** [comment]
Неактуально. Задание удалено
Закрываю
