### ISSUE TITLE
4. Ajax Jquery [#58534]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1032]
В коде два раза вызывается библиотека jquery-3.4.1
https://code.jquery.com/jquery-3.4.1.slim.min.js
https://code.jquery.com/jquery-3.4.1.min.js
так и должно быть?

Да и ещё непонятно, с какой версией языка JS мы работаем?
Можно было бы в начале этого раздела дать такую информацию
Или показать, как её получить

**Comment by staskorobeynikov** [comment]
Неактуально, задач удалена
Закрываю
