### ISSUE TITLE
4.1. JSON формат. [#238554]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1033]
4.1. JSON формат. [#238554]

Не очень понятны ссылки в файле ajax.html
url: 'http://localhost:8080/items/greet',

у нас же проект dreamjob
возможно ссылка должна выглядеть как
http://localhost:8080/dreamjob/greet  ?

хххххх

Довольно долго значения не добавлялись в
список под формой. Помогла команда .reset формы.
Может быть её надо добавить в код?

**Comment by staskorobeynikov** [comment]
Неактуально
Задача удалена
Закрываю
