### ISSUE TITLE
Новые уроки для java программистов по смежным темам

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1035]
Не знаю как обстоят дела на данный момент, просто высказываю свои соображения.

После того, как немного освоился с Java совершенно необходимым оказывается 
знать смежные темы, чтобы быть хоть как-то быть востребованным на рынке.

Предложил бы для облегчения и ускорения решения данных вопросов 
Петру и кураторам поделиться опытом, например: 

1) как Джависту быстрее  и легче освоить Java Script с учетом знаний 
по Java. Новичку в Java сложно быстро освоить второй язык программирования

2) как, по каким параметрам (на что обращать внимание) выбрать хостинг 
(с учетом отключения большого количества бесплатных хостингов)
для размещения (демонстрации) своих веб-проектов
(может быть создать видео на эту тему) Некий минимум знаний администраторов
для программистов

**Comment by peterarsentev** [comment]
@yarmail Спасибо за идею. Мои мысли по поводу этого.
1. JS это отдельное направление. В курсе мы его давали, но потом я убрал, потому что сложно дать чуть и сделать полноценное приложение. У нас есть блок по Angular. В целом все концепции в курсе применимы для любого языка.
2. Я использую https://selectel.ru/en/services/dedicated/ 
3. Элементы DevOps мы даем в курсе и этот материал будет расширять.

**Comment by YarTsin** [comment]
@peterarsentev 
К сожалению не нашёл блока по Angular. 
(Или это отдельный курс и оплата?, было бы интересно) 

Было бы интересна хотя бы одна вводная статья с перечислением технологий, маленьким примером и общим посылом как это примерно устроено, и куда дальше двигаться. Я знаю некоторые изучают Ангуляр или Реакт после Java и становятся довольно интересными с точки зрения найма.
