### ISSUE TITLE
5.4. Протеиновая диета (цикл WILE)

### ISSUE THREAD

**Issue by boris86msk** [peterarsentev/job4j_features_bugs#1036]
Есть предложение о изменении условий задачи, я понимаю это ни как не относится к программированию, но все же "глаз режет" как Иван и Николай так круто прогрессируют за месяц)) Предлагаю: прогресс спортсменов в тяге не умножать а суммировать, к примеру +15 и +20кг в месяц, так же тема протеина "скользкая" можно заменить на к примеру "Мастер спорта" и в цикле считать кто (или за какое время) быстрее сможет выполнить норматив Мастера спорта
Немного занимался штангой в годы университета.

**Comment by itfedorovsa** [comment]
Какие-либо задания формируются исходя из их цели. Цель задания отработать цикл while, а на кошечках-собачках или на Николае-Иване - разницы никакой. На понимание реальных задач это никак не повлияет, а само условие описано интересно) Пришли два новичка и давай на протеине тягать в 2-3 раза больше наперегонки. Переделывать рабочее задание, не получив от этого профита - впустую затраченное время. Спасибо за предложение! Закрываю.
