### ISSUE TITLE
1.1.4. Оператор ветвления - ошибочные упражнения.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1038]
Я считаю, что задачи 1.6-1.8 не соответствуют разделу Упражнения - [1.1.4. Оператор ветвления], так как эти задачи на массив и переборку, решить их по лекциям из раздела 1.1.4. Оператор ветвления не предоставляется возможным. Проверьте, пожалуйста.
![image](https://user-images.githubusercontent.com/101260971/160255468-d5eb626e-506c-4938-9103-a63a3cc00701.png)

**Comment by peterarsentev** [comment]
Спасибо. Убрал их в массивы. По урокам добавил описание String API.
