### ISSUE TITLE
6.5.1. Поиск минимального числа в массиве. [#179803]

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1039]
В лекции разбирается на этом примере поиск минимального числа и результат равен 1 (видно по массиву). В песочнице результат "3" вместо "1", так как поиск минимального числа не прописан в песочнице.
![image](https://user-images.githubusercontent.com/101260971/160456036-d3648732-7dbf-4069-9d72-487b88c44c6d.png)

**Comment by staskorobeynikov** [comment]
В задании все корректно. Там объясняется какой алгоритм для решения мы будем использовать
