### ISSUE TITLE
Опечатки в задании 0.2. Кидаем исключение - throw new RuntimeException

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#104]
https://job4j.ru/edu/task?action=task&taskId=0873958f758d0d5301758d8a5b132e76&number=402159

![image](https://user-images.githubusercontent.com/13130875/101532818-1daa8180-39a6-11eb-8697-d90a49479cdb.png)
![image](https://user-images.githubusercontent.com/13130875/101533054-6e21df00-39a6-11eb-8d16-72e648843d5e.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
