### ISSUE TITLE
Упражнения 1.1.5. Циклы - Некоторые задачи не по уровню.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1040]
В разделе Упражнения 1.1.5 Циклы не по уровню даны задания 1.5-1.8. Лекций к разделу дано не было. Уже общались, что они будут позже, тогда можно будет вернуться к этим задачам. Я считаю, было бы правильным подать эти задачи после прохождения соответствующего материала или сгруппировать по разделам или категориям знаний. Когда решаешь 13-14 задач за 10-20 минут, а потом 20 минут не можешь понять что от тебя хотят в следующей задаче, это вводит в ступор:)
![image](https://user-images.githubusercontent.com/101260971/160457190-a1a9ced7-874a-44fe-b474-20a1fc0b8376.png)

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
