### ISSUE TITLE
1. Читаем файл конфигурации [#858 #281845] малозначительные опечатки

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#1042]
`2) на файла с нарушением шаблона ключ=значение (напр. =значение)`
вероятно на _чтение_ файла

`assertThat(config.value("surname", is(Matchers.nullValue())));`
вероятно пропущена закрывающая скобка после "surname"), а одна из закрывающих скобок в большой группе - лишняя.

**Comment by staskorobeynikov** [comment]
Исправлено
