### ISSUE TITLE
1.1.5. Циклы / 5.9. Крест в псевдографике.

### ISSUE THREAD

**Issue by AKireenkov** [peterarsentev/job4j_features_bugs#1043]
Предлагаю поправить комментарий к шаблону класса для переменных 
 boolean left = ; /* добавить условие, по которому нужно определить ставить ли символ или нет. */
 boolean right = ; /* добавить условие, что нужно ставить элемент в правый угол. */
В соответствии с комментарием. Кажется, он помогает намного быстрее найти решение. Текущие комментарии ставят в тупик
Oт Павел Вальгер17.09.2021 16:15
Если бы я сразу понял, то решил бы задачу в 3 раза быстрее (возможно кому-либо пригодится):
/* добавить условие, по которому нужно определить ставить ли символ или нет. */  - первая диагональ с левого верхнего угла в правый нижний.
/* добавить условие, что нужно ставить элемент в правый угол. */ - вторая диагональ с левого нижнего угла в правый верхний.

**Comment by staskorobeynikov** [comment]
Исправлено
