### ISSUE TITLE
Раздел упражнения - сортировка упражнений относительно пройденных материалов.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1044]
Так как в каждой категории раздела "Упражнения" содержится просто набор упражнений без привязки к знаниям, предлагаю рассмотреть вариант разделения упражнений на те, которые уже были в лекциях (для подкрепления пройденных знаний), и те, которых еще не было (чтобы было понятно, что это сложные упражнения на данный момент, и чтобы их решить, нужны доп знания). А по мере добавления в курс лекций по задачам из данных упражнений, переносить соответствующие упражнения из раздела "сложные" в раздел пройденных материалов (которые для подкрепления).

**Comment by peterarsentev** [comment]
Спасибо за предложения. Но мы лучше сразу выпрямим материал. Я сейчас как раз стал работать над упражнениями.
