### ISSUE TITLE
3. Checkstyle с Maven [#257606 #283869] - ошибки.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1047]
1.) Код для вставки в pom.xml должен начинаться с строки build и до /build
![image](https://user-images.githubusercontent.com/101260971/161432844-f2c37533-358d-4a54-bcb3-5e6967668873.png)
На данный момент код начинается с plugin и до /plugin
![image](https://user-images.githubusercontent.com/101260971/161432941-ba2549d6-cd9f-49e1-b6d7-f2efc36c6bd6.png)
Если просто скопировать и вставить в pom.xml, то не работает.

2.) Ниже нужно выполнить команду mvn validate. Как я догадываюсь, нужно иметь на компьютере физически установленную версию apache maven, иначе командная строка не понимает данных команд. Если подразумевается использование maven, встроенного в Idea, тогда нужно поменять описание команды и скрин команды на скрин шестеренки validate в блоке maven в сайдбаре.  
![image](https://user-images.githubusercontent.com/101260971/161433064-4fa1496e-6269-4435-a3da-6a6025feb5b8.png)
![image](https://user-images.githubusercontent.com/101260971/161433325-4fbb821c-d6c9-4541-91cc-cd973e81670c.png)

**Comment by ViktorJava** [comment]
По первому пункту, вопрос: 
с какой радости **pom.xml** должен начинаться с строки **build** и до **/build**?
Ведь это фрагмент **pom** файла, а фрагмент может начинаться с любой строки.

**Comment by itfedorovsa** [comment]
Закрываю за неактуальностью. Ранее казалось, что нужно править.
