### ISSUE TITLE
0.4. Пользовательские исключения Неточность, путающий момент в формулировке предожения.

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#105]
https://job4j.ru/edu/task?action=task&taskId=0873958f758d0d5301758d8a5b3d2e78&number=402161

![image](https://user-images.githubusercontent.com/13130875/101536546-35d0cf80-39ab-11eb-8cbb-dbe2b4114ed9.png)
Если бы я не знал о непроверяемых исключениях ничего, то данная фраза ввела бы меня в ступор. Только говорилось про не обрабатываемые исключения, потом синонимично называют их не проверяемые. Это путает читателя, лучше сразу ввести понятие не проверяемые. Так будет понятнее.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
