### ISSUE TITLE
1.6. Взаимодействие объектов [#166087] - неточность

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1050]
В лекции мы создаем классы. в том числе и Wolf. По заданию в конце лекции нужно создать новые классы, и в том числе опять Wolf, который уже создан. Приходится либо заменять содержимое Wolf, ломая предыдущую историю, либо придумывать новое название класса Wolf, что в целом может противоречить политике курса "делать как написано в курсе". 
![image](https://user-images.githubusercontent.com/101260971/161528632-2d9a927a-3daa-4669-8d19-109c6868b9ae.png)
![image](https://user-images.githubusercontent.com/101260971/161529179-bfc11a1b-fffd-43c2-9f79-51af73f13eea.png)

**Comment by staskorobeynikov** [comment]
Добавил уточнение, что можно использовать класс из описания
