### ISSUE TITLE
4. Thymeleaf, Циклы. (Middle - Web)

### ISSUE THREAD

**Issue by alxkzncoff** [peterarsentev/job4j_features_bugs#1055]
В первом задание раздела Web (1. Генератор HTML) мы создаем первую страницу index. Классы создаем в пакете dreamjob (ru.job4j.dreamjob). В четвертом задании (4. Thymeleaf, Циклы) в примере мы уже работаем в пакете dream (ru.job4j.dream). Если делать все в точности как в задании то получится два пакета dream и dreamjob из-за чего происходит некорректное отображение страницы posts, она прост не загружается. Нужно либо в первом задании изменить пакет на dream, либо в четвертом на dreamjob, чтобы не было путаницы.

**Comment by staskorobeynikov** [comment]
Исправлено
