### ISSUE TITLE
5. Реализация интерфейса [#2519]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1056]
5. Реализация интерфейса [#2519]

Вопрос по заданию 3
Цитирую:
"3. Добавить в модель Candidate поле city_id." 
Если я правильно понимаю, 
В модели это должно называться cityId
Возможно автор имел ввиду таблицу
candidate c колонкой city_id?

хххххххххххх

Мы вводим в задание работу с датами в разных форматах
В каком формате вы рекомендовали бы сохранять дату в моделях,
какой для этого проекта лучше подходит вариант?
например
import java.sql.Timestamp;
import java.time.Instant;

или 

import java.time.LocalDateTime;

или другие какие-то варианты?

хххххххххххх

Хотел бы отметить, что задание 
для новичка очень трудное, возможно из-за того,
что новые вводные заставляют перелопачивать весь проект,
и легко можно что-то упустить(потерять)

хххххххххххх

5. Реализация интерфейса [#2519 #283323]
В переписке со Стасом получил довольно странные разъяснения
по поводу работы с index.jsp, но постеснялся ещё
его дергать (думаю он очень занят)
Надеюсь в задании это в дальнейшем будет как-то пояснено
"index.jsp перенесите в папку WEB-INF
в остальных местах сделайте соответствующее перенаправление"
Не очень понятно, зачем только этот файл переносить 
в служебную папку, где лежит роутер

**Comment by staskorobeynikov** [comment]
Неактуально, задача удалена
Закрываю.
