### ISSUE TITLE
0.5. Иерархия исключений и множественный catch. Путающий момент

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#106]
![image](https://user-images.githubusercontent.com/13130875/101541888-0b831000-39b3-11eb-8c8a-92681dc54349.png)

Ощущение, что текст пишут разные авторы. Уже 3 способ назвать не проверяемые исключения, чем угодно синонимично. Пожалуйста, выберите единообразный способ называть исключения и придерживайтесь его. Ибо это очень путает новичков, догадываться, что же хотел сказать автор. Под управляемыми, проверяемыми исключениями, или ошибками работы программы во время Runtime.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
