### ISSUE TITLE
4.1. Разрыв зависимости StartUI от Scanner - добавить инфо.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1060]
В интерфейсе имеем 2 метода, нужно добавить информацию про второй метод askInt. В примере в лекции askStr и "Введите id" не совпадают по типу.
![image](https://user-images.githubusercontent.com/101260971/163625552-8b7cb91b-b14f-41f4-a917-5d786a5225e8.png)

**Comment by staskorobeynikov** [comment]
Исправлено
