### ISSUE TITLE
4.2. Статические методы. 

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1061]
В примере в этой лекции появляется **this.**showMenu();. В последний раз данный кусок кода показывается в лекции 2.7. Реализация класса StartUI. Вывод заявки по id без "this".
![image](https://user-images.githubusercontent.com/101260971/163626921-bb27c1c4-ead5-4b64-9e64-a2412032a82e.png)

***************************************************************************************************************************************

![image](https://user-images.githubusercontent.com/101260971/163626966-de3848ae-4e16-413a-9d2d-4dd2f6861613.png)

**Comment by andreiHi** [comment]
исправлено
