### ISSUE TITLE
Упражнения (Стажер): 3.8. Исключить элементы из двумерного массива.

### ISSUE THREAD

**Issue by ra1kard** [peterarsentev/job4j_features_bugs#1062]
**ИСХОДНЫЕ ДАННЫЕ:**
```
package ru.job4j.array;

import java.util.Arrays;

public class CheckSumIndexes {
    public static int[] collectNewArray(int[][] data, int sum) {
        return new int[0];
    }
}
```
```
package ru.job4j.array;

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

public class CheckSumIndexesTest {
    @Test
    public void collectNewArray() {
        int[][] data = {
                {1, 2, 3, 4},
                {5, 6, 7, 8},
                {9, 10, 11, 12} ,
                {13, 14, 15, 16}
        };
        int[] rsl = CheckSumIndexes.collectNewArray(data, 3);
        int[] expected = {1, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 16};
        assertThat(rsl, is(expected));
    }
}
```
___________________________________________________
**КАК ВЫПОЛНЯЛ:**
Нобходимо выполнить 2 условия:

> 1. Если сумма индексов при переборе двумерного массива равна sum, то элемент с такими индексами должен принять значение 0.

Сделал, значения: 4, 7, 10, 13 заменяются на "0" (см. пример вывода на скрине):

![Screenshot_1323](https://user-images.githubusercontent.com/36276455/163670508-40350779-29c1-4b9d-a051-3f6186cba200.png)

А затем выполнил условия:

> 2. Выходной одномерный массив не должен содержать значения 0.

Получился ожидаемый результат в одномерном массиве без чисел 4, 7, 10, 13 (см. пример вывода внизу на скрине).
___________________
**ВОПРОСЫ:**
1) Разве первое условие не предполагает, что последнее значение "16" тоже необходимо заменить на "0"? (см. скрин, подчеркнуто красным);
2) Выводя на экран получившийся результат с нулями, подумал, что начинать следует с единицы и заканчивать цикл проверки раньше на единицу. И чтобы выполнить задание я так и сделал. Но может об этот стоит упомянуть в условии? Или я что-то не так понял?
3) Иногда понять условия задачи помогают несколько тестов и их сравнение, но в данном случае, тест только один. Может стоит добавить еще примеров?

Моё промежуточное решение в [коммите](https://github.com/ra1kard/job4j_elementary/commit/782800a6c5959d2524150083fb2c61a6a61809f8) (тесты проходят, но правда еще не сделал с использованием метода Arrays.copyOf())

P.S. Допускаю, что намеренно не все разжевывается, но вдруг в условии все таки ошибка, поэтому создал issue.

**Comment by peterarsentev** [comment]
Мы поправили это задание.
1. Элемент со значением 16 имеют индексы 3 и 3. Сумма этих индексов 6. То есть элемент занулять не надо.
