### ISSUE TITLE
3. Дополнительная литература [#504870]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1063]
Уровень : 3. Мидл Категория : 3.2.1. Web
Как я понимаю, в этом разделе добавляется работа с 
Spring boot,  Thymelaef и другими новыми технологиями.
Предложил бы немного пересмотреть эту тему 
и добавить туда необходимую литературу по этим технологиям

**Comment by itfedorovsa** [comment]
Добавлено. Спасибо!
