### ISSUE TITLE
Docker и Github [#504782] невозможно соединить docker и github без платной подписки docker

### ISSUE THREAD

**Issue by KarnaukhovKirill** [peterarsentev/job4j_features_bugs#1064]
Нужна подписка, минимум 5 баксов. Многие бы заплатили, но и оплатить не получиться с наших карт. 

![изображение](https://user-images.githubusercontent.com/79538096/163711498-b415714a-ba9f-4b8e-9fd7-92f645073f03.png)

**Comment by peterarsentev** [comment]
Да. Мы убрали эту задачу. Не такая критичная.
