### ISSUE TITLE
1.2.4. Полиморфизм 9.1 Зависимость от System.out

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1065]
1. Без рефакторинга тестов не получится сделать коммит из-за ошибок.
2. StringBuilder, buffer.append и тд встречаются впервые, сложно понять что конкретно происходит в этом классе.
![image](https://user-images.githubusercontent.com/101260971/163849936-ff322777-6b1f-4e3e-8a14-759ef866fe89.png)

**Comment by peterarsentev** [comment]
Добавил описание. Спасибо.
