### ISSUE TITLE
0.2. Кидаем исключение - throw new RuntimeException - добавление информации

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1066]
В эту лекцию я бы добавил фразу из пункта 3 Code quality principles, объясняющую, что нужно отделять исключения от основной логики, не используя if-else-throw. Эта информация сразу ставит все на свои места и позволяет не допускать ошибок, так как решение через if-else-throw изначально кажется приемлемым.

**Comment by peterarsentev** [comment]
Добавил. Спасибо.
