### ISSUE TITLE
Новое меню Компании

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1070]
Странное поведение списка компаний
При выборе пункта меню Компании открывается 1 страница списка
<img width="758" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/164944860-4abc9f4d-1bcb-405c-8e25-5132244e703e.png">
При двигании позунка вниз или прокрутки колесом вниз
открывается вторая страница списка, но обратно на первую страницу не попасть
<img width="753" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/164944902-f8cfffcc-da60-4268-bec0-2c8713b588c6.png">
Возможно нужно поменять реакцию на колесо прокрутки или например добавить номера страниц

**Comment by YarTsin** [comment]
Да, и вероятно было бы неплохо указывать основные города, где присутствует компания, а то вакансия понравится, а потом выяснится, что они берут на работу только во Владике

**Comment by peterarsentev** [comment]
Поправили. А по поводу городов тут не важно. Сейчас удаленно все.
