### ISSUE TITLE
1.3.4. Сортировка 0. Сортировка - лекция и задание не сходятся.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1075]
В лекции пример обратной сортировки дается на примере Collections.reverseOrder(), а задание на обратную сортировку дается на  реализацию компаратора, переопределяющего метод compare(a, b), где обратная сортировка реализуется сменой параметров между собой (как уже объяснил ментор), в лекции этого нет. Просьба просмотреть лекцию на предмет соответствия лекции и задания. (Либо я дурак, и это как-то само собой должно пониматься, не исключаю).

**Comment by peterarsentev** [comment]
Спасибо. Я добавил описание.
