### ISSUE TITLE
6.9. Жадный алгоритм. Сдача в кофе машине

### ISSUE THREAD

**Issue by erikmarino** [peterarsentev/job4j_features_bugs#1076]
Опечатка в тексте
В этом задании нужно реализовать механизм возврата монет в лендинговых аппаратах.

Скорее всего имели ввиду Вендинговых, а не Лендинговых.

![image](https://user-images.githubusercontent.com/103319161/166867031-edace548-4b04-4bf0-861c-0853ebffa260.png)

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
