### ISSUE TITLE
1.4.1. Lambda 4. Зона видимости в лямбда-выражениях и исключения - поправить код задания

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1077]
В задании код считает сумму индексов, а не сумму значений в массиве.
![image](https://user-images.githubusercontent.com/101260971/167476191-a9cb34c7-ec17-48d9-bf67-64a9a5656ad4.png)

**Comment by andreiHi** [comment]
поправил
