### ISSUE TITLE
1.4.1. Lambda 5. Подсчет функции в диапазоне. - Добавить инфы в условие задачи. 

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1078]
Добавить инфы в условие задачи. 
-где реализовать задание (пакет, класс).
-что реализовать конкретно (метод и тесты к нему). Я сначала понял, что реализацию нужно делать в тестах, а метод не нужно.
-в том числе не понял предыдущее, так как не добавлена инфа где это делать (текстом в коммент или загрузить на GitHub).
В общем, привести задание в привычный для job4j вид.

**Comment by andreiHi** [comment]
поправил
