### ISSUE TITLE
1.4.2. Stream API - внести изменения.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1079]
Рекомендации по применению Stream API даются только аж в 6 и 8 задачах. Логичнее было бы эти рекомендации дать сразу при
объяснении что такое Stream API и как этим пользоваться. Иначе несколько задач делай как хочешь, а потом исправляй косяки, потому что потом в 6 задаче тебе будет объяснено как нужно было делать (каждый метод с новой строки и тд).

**Comment by peterarsentev** [comment]
Спасибо. Я добавил новую задача для этого элемента.
