### ISSUE TITLE
1.2.2. Наследование / 1. Что такое наследование.

### ISSUE THREAD

**Issue by kunjut** [peterarsentev/job4j_features_bugs#1080]
Наследование, это когда есть отношение IS-A
Не понятно, почему в уроке, про пример с коробкой и материалом говорится "Это и есть наследование"? 
Ведь между изделием и материалом нет отношения IS-A

**Comment by peterarsentev** [comment]
@kunjut Подскажи в каком это уроке ? В что такое наследование я не вижу.

**Comment by kunjut** [comment]
Во втором абзаце этого урока.

> Начнем мы с наследования в жизни, а не в программировании. Представьте, что вы изготавливаете коробки. За основу вы можете взять дерево, металл или пластик. Каждое из этих веществ обладает особыми свойствами, которые так же будут присущи вашему изделию (коробке). То есть, свойства родительского элемента стали доступны дочернему элементу. Это и есть наследование.

Я из него понял, что между изделием(коробка) и материалом(дерево, металл, пластик) можно сказать IS-A,
если материал - родительский элемент, а изделие - дочерний.

Хотя это не так? Ведь изделие не является материалом?

У меня возникла путаница, когда в задании я привел пример наследования из жизни: ребенок и родитель, показалось похожие примеры. Но все же ребенок не является родителем. Также как и изделие материалом.

**Comment by peterarsentev** [comment]
Согласен. Пример неправильный. Переделал на транспорт.
