### ISSUE TITLE
1.4.3. Улучшенное Java API 3. Optional в банковских переводах - перенести?

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1082]
На момент этой задачи требуемые методы уже переписаны на стрим, поэтому ни пример в лекции, ни задание невозможно выполнить. Эту лекцию можно перенести до лекции, где переписываем методы на стримы или по-другому организовать, иначе в этой задаче просто нечего делать в существующем проекте.

**Comment by peterarsentev** [comment]
Согласен. Убрал задачу, потому что она дублируется. Новую придумать не смог на Optional.
