### ISSUE TITLE
Раздел Массивы. Упражнение 0.5. Индексы в массивах

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1084]
![image](https://user-images.githubusercontent.com/88712756/168470264-1a2c5a29-35c2-4fee-8daf-14325afec071.png)
Платформа пропускает неверное решение. последний элемент массива не может определяться через длину. Предлагаю просто поменять во втором тесте последние значение массива на любую другую цифру.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
