### ISSUE TITLE
1.2.2. Наследование 5. Вызов переопределенного метода родителя - super.method

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1085]
Исправить ошибку в лекции в 2 местах в названии класса PizzaExtraChees**a**ExtraTomato на PizzaExtraChees**e**ExtraTomato, так как в классе PizzaShop написано верно через Chees**e**, а в именах наследников получается ошибка.

**Comment by andreiHi** [comment]
исправили
