### ISSUE TITLE
Lambda/Stream API 1.4.4. Контрольные вопросы 3. Дополнительная литература - добавить статью.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1086]
https://habr.com/ru/post/346782/ - предлагаю добавить в доп литературу к теме Lambda/Stream API данную статью про Optional. Понятно расписано, включая инфу, что Optional особенно важен для работы со Spring и другими фреймворками.

Также книга Герберт Шилдт. Java 9. Полное руководство. 10е издание. Лямбда-выражения: Глава 15 (стр. 459), Stream API: глава 29 (стр. 1123), Optional: В главе 20 классы "Optional" (стр. 733-736).

**Comment by andreiHi** [comment]
спасибо 
добавили
