### ISSUE TITLE
1.4.1. Lambda 2.3. Fuction. Рассчитать значение по формуле - в чем суть упражнения?

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1087]
В таком виде (скрин) задача просто просит нас подставить это выражение в пустое место. Собственно, в чем смысл задачи? Видимо, нужно вместо выделенного куска написать формулу функции x^2 + bx + c.
![image](https://user-images.githubusercontent.com/101260971/168876616-188f3014-85c7-4046-923b-9701bc918462.png)

**Comment by peterarsentev** [comment]
поправил.
