### ISSUE TITLE
0.4. Пользовательские исключения. [#219367]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1089]
https://job4j.ru/profile/exercise/24/task-view/193

Не знаю, может это только у меня, но какой-то лишний блок на кнопке,
проверьте пожалуйста

<img width="574" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/169117289-cbc4bdd1-6666-4fbb-880e-acbcde86afb8.png">

**Comment by peterarsentev** [comment]
@yarmail Еще повторяется? Мы поправили дизайн. Он не подгрузилось что-то.
