### ISSUE TITLE
3.5.6. Определение сервисов - Spring Discovery [#504786]

### ISSUE THREAD

**Issue by velesov7493** [peterarsentev/job4j_features_bugs#1090]
+ Последнее предложение обрывается на середине.
+ Отсутствует абзац "Задание", поэтому непонятно, что именно требуется сделать.
![изображение](https://user-images.githubusercontent.com/80103728/169657886-7f2076b3-4aeb-478c-b98f-7036b6a39d93.png)

**Comment by peterarsentev** [comment]
Спасибо. Этот урок убрал. Решили, что без Spring Cloud лучше. Определение сервисов будет через docker.
