### ISSUE TITLE
2.1.2. Generic 0. Что такое обобщенные типы (generics) - откорректировать задание.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1091]
![image](https://user-images.githubusercontent.com/101260971/169903631-16d97d68-56c6-4591-932a-1a5e785722ff.png)

Поправить задание, так как из этой строки понимается, что ошибки компиляции исправляются только закомментированием строк. По лекции и так понятно что нужно сделать, но всё же некорректно, я считаю.

**Comment by peterarsentev** [comment]
@itfedorovsa Уточни, а что неправильно? Я так понимаю, то что мы явно указываем, что нужно убрать код, а не изменить его, чтобы он работал?

**Comment by itfedorovsa** [comment]
@peterarsentev Там еще во всех методах print нужно wildcards править, чтобы заработало. Редактированием одних строк задачу не сделать.

**Comment by itfedorovsa** [comment]
Исправлено.
