### ISSUE TITLE
2.1.1. Iterator 5.1.4. FlatMap для Iterator<Iterator> - обобщения.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1092]
![image](https://user-images.githubusercontent.com/101260971/169904531-6ae3f924-5423-42db-aa54-00a8be569fd8.png)
Обобщенные классы даются только в следующей лекции, а в этой мне лично было непонятно как создавать обобщенный класс, пришлось гуглить. Ранее в курсе это нигде не упоминалось. Я вижу решение этого недочета помещением раздела Generic перед разделом Iterators.

**Comment by peterarsentev** [comment]
Поправил.
