### ISSUE TITLE
2.4. Данные об осадках (Упражнения Java Core)

### ISSUE THREAD

**Issue by SweetMustard993** [peterarsentev/job4j_features_bugs#1093]
Невозможно выполнить задание, так проверочный результат в тесте имеет случайный порядок, который невозможно достичь сортировкой или изменением типа мапы. При этом сами значения корректные и соответствуют тем значениям, что у казаны в тесте, но при этом имеют другой порядок, из-за этого тест не выполняется

**Comment by andreiHi** [comment]
![image](https://user-images.githubusercontent.com/29897507/170818994-77fe3a3b-6307-47db-8629-5ed2cd89d05f.png)
все отлично работает 
проверьте еще раз

**Comment by SweetMustard993** [comment]
Ну если учесть что ваш способ единственно верный, то да. Но в тексте задания ни где явно не указан порядок, который должен быть получен. Указано лишь то как должны быть посчитаны значения. И с точки зрения формулировки задания, мое решение тоже верно, но тест на нем не выполняется, потому что порядок другой. Ну и решение, которое вы приводите не очевидно, так как ожидаешь, что задание направлено на отработку тех методов, которые разбирались ранее в уроках или упражнениях, но метод forEach, который используется в вашем решении, до момента этого упражнения не встречался. Как и лямбды, они вообще через одну тему будут изучаться. Думаю комментарии других о схожем затруднении говорят о том, что не я один иду не по тому пути решения, который вы изначально задумывали в этом упражнении

**Comment by SweetMustard993** [comment]
![image](https://user-images.githubusercontent.com/94182162/171284232-401853ef-89df-4b77-9d57-bb85193d749d.png)

Вот мое решение, пользовался теми методами, которые мы прошли ранее. При этом подсчет верный, но тест не пройдет

**Comment by andreiHi** [comment]
Можно использовать вот такую проверку 
        assertThat("List equality without order",
                rsl, containsInAnyOrder(expected.toArray()));
так как порядок не важен.
Задачу поправим, спасибо.
