### ISSUE TITLE
2.3. Индексы символов (Упражнения Java Core)

### ISSUE THREAD

**Issue by SweetMustard993** [peterarsentev/job4j_features_bugs#1094]
В тестовых данных содержится ошибка,  например: третье вхождение буквы "l" в исходную строку имеет индекс 9, в тесте указано 8. В описании сказано, что в реализации не нужно учитывать пробелы, но это ни как не связано с индексом символа в исходной строке

**Comment by peterarsentev** [comment]
Спасибо. Поправил. Добавил еще тестов.
