### ISSUE TITLE
2.1.3. List 4. Используя контейнер на базе связанного списка создать контейнер Stack - дополнить

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1095]
Предлагаю добавить слово "класса" как указано на скрине, а то по началу путает присутствие объекта ForwardLinked<T> в классе
SimpleStack. Так сразу будет понятно, что дополнять нужно другой класс. 
![image](https://user-images.githubusercontent.com/101260971/170475109-9e339172-e6bd-4da4-a948-1905424e43cb.png)

**Comment by andreiHi** [comment]
исправлено
