### ISSUE TITLE
6.6.3. Двухмерный массив. If.

### ISSUE THREAD

**Issue by Sarabik** [peterarsentev/job4j_features_bugs#1096]
Приведенный в лекции код будет работать только при условии, что работа идет с массивом, где количество строк равно количеству элементов в каждой строке. И только поэтому он там и работает. Там как раз на входе int[3][3]. 

public class MatrixFind {
    public static void find(int[][] array, int el) {
        System.out.println("Find el : " + el);
        for (int row = 0; row < array.length; row++) {
            for (int cell = 0; cell < **array.length**; cell++) {
                int val = array[row][cell];
                if (val == el) {
                    System.out.println("row : " + row + ", cell : " + cell);
                }
            }
        }
    }
Мне кажется надо переписать пятую строку на:
for (int cell = 0; cell < **array[row].length**; cell++) {

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
