### ISSUE TITLE
2.1.3. List 7. ListIterator - неправильный импорт?

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1097]
При вставке тестов из лекции импорт org.hamcrest.core.Is; не определяется. Тесты заработали через import static org.hamcrest.Matchers.is; Ранее в тестах тоже всегда был matchers. Если действительно нужно через matchers, тогда заменить в тестах импорт core на matchers. 
![image](https://user-images.githubusercontent.com/101260971/170819280-368a7009-eb72-443d-b20a-fa3761bfe389.png)
![image](https://user-images.githubusercontent.com/101260971/170819401-466ec47c-96f1-4e94-a24f-67be003334cb.png)

**Comment by andreiHi** [comment]
поправил
