### ISSUE TITLE
Низкий приоритет. Некорректно отображается прогресс обучения в профиле ученика

### ISSUE THREAD

**Issue by alaktyushin** [peterarsentev/job4j_features_bugs#1098]
Добрый день!

Некорректно отображается прогресс обучения в профиле ученика:
"Выполнено / всего: - 384 из 571", тогда как суммируя количества по доступным 3-м уровням должно быть 384 из 626 (267 + 142 + 217).
Соответственно, процент выполнения также должны быть скорректирован.
Скриншот прилагаю:
![Screenshot 2022-05-31 at 13 52 30](https://user-images.githubusercontent.com/13076929/171158256-c0d3f01c-f485-412c-a93e-285df0e5e179.png)

С уважением,
Андрей Лактюшин

**Comment by velesov7493** [comment]
Поддерживаю. Вот похожее замечание от меня - [#1049](https://github.com/peterarsentev/job4j_features_bugs/issues/1049)

**Comment by Natemily** [comment]
Плюсую.
Хотела как раз написать про это.

**Comment by peterarsentev** [comment]
Поправил. Но еще не обновлял. В чате маякну.
