### ISSUE TITLE
1.2. Входные данные в тесте [#297750] 

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1099]
В описании к задаче среди объявленных переменных имеется “int x = 1;”
![image](https://user-images.githubusercontent.com/106254908/171232738-bf851ded-e7bc-48b0-b7fa-bf95cc3d7053.png)

После указанных условий, предлагается выполнить тест, в котором входные данные изменились. “x” из условий уже равен 2 (об этом нигде не сообщается, но это влияет на конечный результат). 

![image](https://user-images.githubusercontent.com/106254908/171232778-7c5c5799-ef01-4eef-98f7-e418c80e4a1b.png)

Ожидаемое возвратное значение 40. А из-за того, что в условиях 1, метод возвращает 10, а не 40 (в тесте 40, поскольку там значение 2).

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
