### ISSUE TITLE
Небольшая несостыковка в меню

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1100]
По состоянию на 4 июня 2022 в общем меню показано,
что выполнены все задания
<img width="724" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/171992822-3ab45131-a1b5-4fc1-81b5-2f09d9700e77.png">
По факту, открываем меню и видим
<img width="418" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/171992841-0f2c714e-6270-405d-a4c4-53b526a9ddf2.png">
Предположу, что это только у меня в связи с тем, что я долго занимаюсь и мне вручную добавляли (обновляли задания)
Также собираюсь это задание делать, так что возможно, на момент проверки куратором оно будет сделано.

**Comment by peterarsentev** [comment]
поправили. проверь.
