### ISSUE TITLE
Тестовый курс - небольшие орфографические правки

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1101]
https://github.com/peterarsentev/course_test
<img width="617" alt="Screenshot_3" src="https://user-images.githubusercontent.com/46091342/171997656-cf70193f-9436-41d0-8481-2c008f5b0909.png">

**Comment by peterarsentev** [comment]
@yarmail Сделай PR, я залью изменения.

**Comment by yarmail** [comment]
> @yarmail Сделай PR, я залью изменения.

@peterarsentev Простите, я не понимаю, вы не могли бы расшифровать свое сообщение подробнее?

**Comment by YarTsin** [comment]
> @yarmail Сделай PR, я залью изменения.

@peterarsentev  
Если я правильно понял - PR - это pull request. 
Отправил предложения по изменению README в проект.
