### ISSUE TITLE
Баг отображения процентов пройденного уровня.

### ISSUE THREAD

**Issue by grfoger** [peterarsentev/job4j_features_bugs#1103]
![image](https://user-images.githubusercontent.com/84062558/172164269-71f2d4f6-2610-4132-82b1-21c89634f450.png)

При полностью пройденном Джуне (пролистал списки уроков и новых не нашёл) в прогрессе обучения уровень отображается на 92%, хотя раньше показывал 100%

**Comment by peterarsentev** [comment]
проверь сейчас. мы поправили. @grfoger

**Comment by grfoger** [comment]
![Screenshot_2022-06-20-18-58-24-283_com.yandex.browser.jpg](https://user-images.githubusercontent.com/84062558/174640578-28f2cb24-475c-41cc-992c-5b6ed634dca1.jpg)

У меня осталось, к сожалению

**Comment by grfoger** [comment]
Теперь порядок. Супер. Спасибо
