### ISSUE TITLE
Не композиция, а агрегация

### ISSUE THREAD

**Issue by kunjut** [peterarsentev/job4j_features_bugs#1104]
[https://job4j.ru/profile/exercise/24/task-view/198](url)
В уроке говорится о том что будем применять Композицию, а по факту применяется Агрегация, т.к. передаваемый объект ConsoleInput создается вне ValidateInput

**Comment by peterarsentev** [comment]
Агрегация - это когда объект А может жить без объекта B. 
Композиция - это когда объект А не может быть без объекта В.
Тут какой вариант? @kunjut

**Comment by kunjut** [comment]
Т.е. в данном случае ValidateInput не построится без ConsoleInput и поэтому композиция.

Я руководствовался тем что, если объект передается и создается вне, т.е. может входить в другие объекты, то это агрегация, а композиция более строгое отношение, когда объект создается внутри объекта и больше никуда не может входить. Такое рассуждение не применимо для отличия агрегации и композиции?

**Comment by peterarsentev** [comment]
Нет. Ты про ссылки говоришь, а не про отношения. Композиция, агрегация - это отношения объектов.
A is B - композиция. ValidateInput  - это обертка над объектов ConsoleInput.
A has B - агрегация. У tracker есть объекты Item, но он создается без них. то есть в коде нигде прописывать new Item не нужно.
