### ISSUE TITLE
Ошибка в описании задачи 6.6.3. Двухмерный массив. If. [#306727]

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1105]
В уроке дан пример кода (скрин ниже), в котором ошибка во внутреннем цикле:

![image](https://user-images.githubusercontent.com/106254908/172471019-bc2e3253-bb3d-41ba-9368-9f9c0b38fa6c.png)

Вероятно должно быть так:
for (int row = 0; row < array.length; row++) {
            for (int cell = 0; cell < array[row].length; cell++) {

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
