### ISSUE TITLE
 Упражнения SQL/ 1. SELECT 

### ISSUE THREAD

**Issue by dima-abc** [peterarsentev/job4j_features_bugs#1106]
В данном разделе последние 4 теста не работают.(5.3,6.1,6.2,6.3). На любой запрос правильный или не правильный одна ошибка: 
 **Задача решена не верно (При обработке данных произошла ошибка. Ошибка при выполнении запроса select * from subjects;. null), попробуйте еще раз**

**Comment by AJIEKCanderG** [comment]
я думал у меня глюки и не проходит решение по ошибке))

**Comment by AJIEKCanderG** [comment]
![DISTINCT ON 1](https://user-images.githubusercontent.com/70632594/173331281-2327f508-beb1-4c12-95eb-6fe5851784e3.jpg)
![DISTINCT ON](https://user-images.githubusercontent.com/70632594/173331291-f1d18a9d-5160-41ee-bb2c-476038c60562.jpg)

**Comment by peterarsentev** [comment]
Поправил.

**Comment by AJIEKCanderG** [comment]
> 6.1,6.2,6.3
а эти тоже поправил? у меня всё равно не проходит

**Comment by peterarsentev** [comment]
Да. там тоже баги. Поправим.

**Comment by peterarsentev** [comment]
Да. там тоже баги. Поправим.

**Comment by peterarsentev** [comment]
Теперь поправил. Проблема в том, что мы используем HSQLDB, а в ней чуть другой синтаксис без ON.
