### ISSUE TITLE
2.2.1. Ввод-вывод - 0.3-0.4 Buffered-лекции. Добавить инфу?

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1110]
В данных лекциях написано про то, что это обертки и что без них работа медленная, но само понятие буфер, и как он работает, не раскрыто. Нашел вот такой ответ, можно подогнать его в лекцию. Максимально доступно объяснено. P.s. Нужно проверить, так как источник - ответ на StackOverflow.

"Как понятно из названия, буферизованный поток – это поток, имеющий буфер.

Предположим, Вы записываете какие-то данные на диск, вызывая метод write(...) потока. При использовании буферизованного потока, после вызова write(...) данные не пишутся на диск, они сохраняются в буфере потока. На диск данные попадают либо при явном вызове flush(), либо при закрытии потока.

В чем выгода? – В том, что при каждом вызове write(...) Вы не трогаете диск, а пишите на него бОльшими блоками данных.

Аналогично, при чтении, считывается бОльший блок данных, чем нужен Вам. При последующем чтении Вы получаете информацию не с диска, а из буфера.

В общем случае выгода заключается в том, что при каждом чтении/записи Вы не трогаете сам непосредственный источник данных, чтение/запись на который происходит медленнее, чем чтение/запись из буфера."

https://ru.stackoverflow.com/questions/604505/io-%D0%92-%D1%87%D0%B5%D0%BC-%D0%B2%D1%8B%D0%B3%D0%BE%D0%B4%D0%B0-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B1%D1%83%D1%84%D0%B5%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0-%D0%98-%D0%BA%D0%B0%D0%BA-%D1%8D%D1%82%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82

**Comment by YarTsin** [comment]
https://ru.stackoverflow.com/questions/604505/io-В-чем-выгода-использования-буферизации-ввода-И-как-это-работает
покрасивше ссылочка))

**Comment by itfedorovsa** [comment]
Добавлено.
