### ISSUE TITLE
2.3.2. Query 1. Inner join - добавить пример?

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1112]
Я считаю, в этой лекции нет базового примера, как должен выглядеть код без алиасов.
Иначе нужно вглядываться и пытаться понять что на что было поменяно p/pp. 
То есть чтобы из такой версии было показано, что меняются названия таблиц на псевдонимы:
```
select name, seria, number from people 
join passport 
on people.passport_id = passport.id;
```
Типа passport на p, people на pp, а после и их поля.

Можно еще добавить, что слово AS также можно сокращать. А также, что сокращение с пробелом заключается в "".
Взято отсюда, очень понятно объяснено шаг за шагом про алиасы: https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-column-alias/

**Comment by ShamRail** [comment]
@peterarsentev исправил https://job4j.ru/tracker/issue/view/540
