### ISSUE TITLE
Упражнения SQL 1. SELECT 4.1. Сортировка результатов выборки 1 - опечатка (вместо GROUP BY должно быть ORDER BY)

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#1113]
В тексте упражнения, в первом абзаце написано: "Для того, чтобы отсортировать строки результатов выборки, необходимо использовать оператор GROUP BY". Однако, данный оператор используется для группировки, должно быть написано: "Для того, чтобы отсортировать строки результатов выборки, необходимо использовать оператор ORDER BY"
[https://prnt.sc/p6aL3BN_HmbP](https://prnt.sc/p6aL3BN_HmbP)

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
