### ISSUE TITLE
2.3.3. Outer join Хранилище машин

### ISSUE THREAD

**Issue by Rozovod** [peterarsentev/job4j_features_bugs#1116]
Возможно имеет смысл уточнить условие задания. Сразу может быть не понятно, что речь идет не о деталях кузова, двигателя и трансмиссии, а о типах этих частей. Пока не подсказали ребята из чата, долго мудрил, заполняя таблицы списком деталей и пытаясь связать эти таблицы. Может даже имеет смысл написать один пример заполнения строки из таблицы Машина, например: 'BMW X5', 'Внедорожник', 'Дизельный двигатель 3.0', 'Автомат'; Но, естественно, вместо названий типов этих частей машины референсы на другие таблицы.

**Comment by ShamRail** [comment]
@peterarsentev https://job4j.ru/tracker/issue/view/538
