### ISSUE TITLE
Ошибка в диапазоне значений char, 9.3. Преобразование примитивных типов

### ISSUE THREAD

**Issue by ducknowledges** [peterarsentev/job4j_features_bugs#1117]
<img width="812" alt="char from 0 to 65535" src="https://user-images.githubusercontent.com/46027009/176494882-545e0a22-8596-4862-bef6-1bd7d7407563.png">

Диапазон значений `char от 0 до 65535` согласно спецификации языка Java
[4.2.1. Integral Types and Values ](https://docs.oracle.com/javase/specs/jls/se17/html/jls-4.html#jls-4.2.1)

При попытке присвоить значение `65536` получаем ошибку(см. ниже):
<img width="566" alt="Error" src="https://user-images.githubusercontent.com/46027009/176496989-9564e155-73f0-4403-a06f-143783e06ffa.png">

**Comment by staskorobeynikov** [comment]
Исправлено
