### ISSUE TITLE
2.3.5. JDBC 1. Sql схема для проекта Tracker - убрать travis и codecov

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1119]
Если travis и codecov из проекта убрали, то эта информация уже неактуальна.
![image](https://user-images.githubusercontent.com/101260971/176731186-250d4bf2-bbf5-468c-9687-261d40044a55.png)

**Comment by ShamRail** [comment]
@peterarsentev исправил https://job4j.ru/tracker/issue/view/537
