### ISSUE TITLE
2.3.5. JDBC 0.2. PreparedStatement - исправить ошибку.

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1120]
Returning нужно исправить на return.
![image](https://user-images.githubusercontent.com/101260971/176992285-759efc1e-0419-4999-87d4-369b5dd3eb08.png)

**Comment by ShamRail** [comment]
@peterarsentev исправил https://job4j.ru/tracker/issue/view/536
