### ISSUE TITLE
Документирование проекта

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1121]
Предложил бы после уроков
https://job4j.ru/profile/exercise/31/task-view/232
2. Что такое JavaDoc [#313879]

и
https://job4j.ru/profile/exercise/31/task-view/233
3. Генерация документации по JavaDoc   [#313880]

добавить кратенькое описание, что такое
package-info.java и  module-info.java,
которые предлагает создать Idea,
и как ими правильно пользоваться

К сожалению мало путной нашёл информации в инете.

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by peterarsentev** [comment]
Добавили. но без описания Module. Для него рано.
