### ISSUE TITLE
2.3.5. JDBC

### ISSUE THREAD

**Issue by ViktorJava** [peterarsentev/job4j_features_bugs#1123]
В блоке **2.3.5. JDBC** всего 6 заданий. Выполнено 7 заданий из 6 и 117 процентов выполнения. На скриншоте всё видно и понятно:
[Скриншот](https://prnt.sc/ZJODwufxH7at)
![bug](https://user-images.githubusercontent.com/54469691/177166744-300bd2a3-5aa8-4ba6-81ae-3c118b393add.png)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
