### ISSUE TITLE
2.3.6. Проект. Агрегатор Java вакансий 2. Парсинг HTML страницы. - сайт из лекции не работает. 

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1124]
Приведенный в начале лекции сайт sql.ru не работает минимум четвертый месяц (судя по дате в комментариях). Также прилагаемые скрины с этого сайта почти нечитаемые. Предлагаю рассмотреть вариант смены данного сайта на другой рабочий заодно со сменой скринов на читаемые. Либо заменить sql.ru на тот же хабр, где мы делаем задание.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
