### ISSUE TITLE
Пропал доступ к уровню.

### ISSUE THREAD

**Issue by alaktyushin** [peterarsentev/job4j_features_bugs#1131]
Добрый день!

Пропал доступ к уровню Мидл (я выполняю сейчас упражнения этого уровня, около полутора десятков уже выполнены). Сейчас не вижу даже выполненных заданий, а также не могу войти в задания на доработке.

**Comment by peterarsentev** [comment]
Я закрыл старый уровень. Напиши мне в личку. Я новый открою.
