### ISSUE TITLE
1. Интеграция Rest сервисов через RestTemplate [#96916]

### ISSUE THREAD

**Issue by dima-abc** [peterarsentev/job4j_features_bugs#1132]
В самом уроке все прелестно но.
1. Нет реализации метода @GerMaping("/{id}") (в общем не критично понятно как сделать)
2. В задании в описании модели Employee "Модель Employee содержит обязательно данные: имя и фамилия, ИНН, дата найма, **а также ссылку на список его аккаунтов (в качестве аккаунтов используйте модель Person, в котором используются поля login и пароль),** которыми сотрудник пользуется для доступа к ресурсам корпоративной площадки." 
Фраз ссылка на список его аккаунтов меня ввело в заблуждение и я день лепил связи @ManyToOne @OneToMany, пришлось обращаться к Петру за разъяснениями.
3. **Добавьте контроллер EmployeeController,  в котором добавьте метод получения всех сотрудников со всеми их аккаунтами, добавление нового аккаунта, изменение и удаление существующих аккаунтов.**
Опять же я понял что у Employee есть список и в него пихаем персон, но как сказал Петр Employee не знает ничего о Person, тогда получается что добавьте метод получения всех сотрудников со всеми их аккаунтами, добавление нового аккаунта, изменение и удаление существующих аккаунтов мы должны реализовать в PersonController работая через RestTemlate с нужными нам Employee.

**### Итог как я понял разъяснение Петра основная суть в том что Employee ничего не знает про Person.**

**Comment by itfedorovsa** [comment]
На данный момент этот урок убран/заменён другим. Спасибо! Закрываю.
