### ISSUE TITLE
Не отображается задание 1.2.0.1 Качество кода

### ISSUE THREAD

**Issue by finansist138** [peterarsentev/job4j_features_bugs#1136]
Не отображается задание 1.2.0.1, в него можно зайти через поле "Новые уроки" слева, но если урок не прошел, к примеру, проверку CI, то в урок уже нельзя попасть.

**Comment by itfedorovsa** [comment]
На данный момент уроки из этого раздела перенесены в другие разделы, а раздел "Качество кода" убран. Спасибо! Закрываю.
