### ISSUE TITLE
0. Что такое деревья? [#4956]

### ISSUE THREAD

**Issue by Mystery32** [peterarsentev/job4j_features_bugs#1137]
В данном задании при описании теории допущена ошибка, указана фраза: "Значение левого потомка должно быть меньше или равно родительскому. "  и далее идёт описание данной фразы: left < parrent. Т.е. фразу необходимо скорректировать в "Значение левого потомка должно быть меньше родительского. "

**Comment by staskorobeynikov** [comment]
Исправлено
