### ISSUE TITLE
 Упражнения / 1.1.5. Циклы / 1.7. Симметричное число [Опечатка в тексте]

### ISSUE THREAD

**Issue by ducknowledges** [peterarsentev/job4j_features_bugs#1138]
<img width="443" alt="Screen Shot 2022-07-17 at 21 09 58" src="https://user-images.githubusercontent.com/46027009/179410819-e5bd3e52-ea18-46df-b4a5-722492618892.png">
Строка : Симметричным считается число **которое в котором** числа идущие по порядку в прямом и обратном порядке равны друг другу.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
