### ISSUE TITLE
4. Аттестация [#504878]

### ISSUE THREAD

**Issue by olegpan1** [peterarsentev/job4j_features_bugs#1140]
Опечатки!

1. Метод averageScoreByPupil() - в этом методе необходимо найти сумму баллов по всем предметам у всех учеников, при этом считая количество суммируемых элементов - после этих подсчетов мы просто делим общий балл на количество суммируемых элементов;  - _должно быть averageScore()_ 

2. Метод averageScoreBySubject() - реализация этого метода будет отличаться от предыдущего тем, что мы считаем сумму баллов по всем предметам каждого ученика. Получив сумму баллов, мы создаем объект типа Label с именем ученика, а в качестве второго параметра в конструктор передаем сумму баллов по предметам, разделенную на количество предметов ученика. Полученный объект добавляем в список, который и возвращаем в конце метода; - _должно быть averageScoreByPupil()_

**Comment by staskorobeynikov** [comment]
Исправлено
