### ISSUE TITLE
1. Принципы Kiss, Dry и Yagni - проверить код

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1143]
Просьба проверить код задания. Я считаю, что в методах min и max мы сами должны сами задавать компаратор, либо всегда подразумевать единую реализацию компаратора, например, naturalOrder, так как наши методы считают конкретное значение, а не просто вычисляют какое-то значение(любое). И какой-либо отличный от нашей реализации пришедший в аргументе компаратор будет ломать написанную логику, соответственно, возвращаться будет неправильное значение. 
![image](https://user-images.githubusercontent.com/101260971/180426245-15c32eac-1dd3-4a25-86f6-ff56e6ba6022.png)

**Comment by peterarsentev** [comment]
Спасибо. Переделал задание.
