### ISSUE TITLE
Добавить инфу в Рейтинги

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1144]
Периодически в чатах народ спрашивает, каков механизм работы рейтинга. 
На взгляд не очень понятно.
Предложил бы дать короткое описание например где-то здесь:
<img width="693" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/180649194-a723751b-fdbc-4944-a969-589ddf58126b.png">

**Comment by itfedorovsa** [comment]
Данный пункт был изменён и с недавних пор называется "Скорость прохождения". А рейтинг служит как количество лайков под комментариями этого автора. Спасибо, закрываю!
