### ISSUE TITLE
Ошибка Уведомлений на сайте курса.

### ISSUE THREAD

**Issue by dima-abc** [peterarsentev/job4j_features_bugs#1146]
Когда переходим в список уведомлений проверенных задач, активная ссылка перехода на само задания не работает при нажатии на ссылку перехода не происходит.

**Comment by dima-abc** [comment]
![изображение](https://user-images.githubusercontent.com/60465961/181440091-b6fff298-6a81-45b2-ac8d-f9b9237a182e.png)

**Comment by itfedorovsa** [comment]
На данный момент функционал работает. Спасибо, закрываю!
