### ISSUE TITLE
Бот не проверяет задание.

### ISSUE THREAD

**Issue by QuickMixKZ** [peterarsentev/job4j_features_bugs#1148]
С недавних пор в форме для отправки ссылки на коммит домашнего задания, пропала возможность вставки ссылки. Теперь для этого необходимо переключаться в режим редактирования HTML - кода, и там рукам и вставлять тэг ссылки.

Если вставить ссылку, и забыть переключиться из режима редактирования HTML, то при отправке задания на проверку, ничего не сохранится, и ничего не будет отправлено, т.е. будет пустое сообщение И если потом отредактировать своё сообщение, корректно вставив ссылку на коммит, то бот уже не проверит этот коммит.

**Comment by peterarsentev** [comment]
Спасибо. Я убрал из редактора все кнопки. Ссылки теперь ставлять просто в текст.
