### ISSUE TITLE
Не работает ссылка на исправление задачи от CI_Bot

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1149]
Не работает ссылка на исправление задачи, прилагаемая ботом (и в случае комментариев ментора, и в случае сборки), скрины ниже.

прилагаемая ссылка: 
![image](https://user-images.githubusercontent.com/106254908/181728954-23c8c862-3d2c-48a1-8311-5e07e1364051.png)

Результат перехода по ссылке:
![image](https://user-images.githubusercontent.com/106254908/181729084-29413793-8139-430a-adc5-4a920ab51bb3.png)

**Comment by peterarsentev** [comment]
Поправили.
