### ISSUE TITLE
3. Банковские переводы

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#1150]
Мне кажется что  в тестах не правильно указано условие проверки :
 public void transferMoneySourceNull() - assertThat(bank.findByRequisite(user.getPassport(), "5546").getBalance()).isEqualTo(150D);
public void transferMoneyDestinationIsNull() - assertThat(bank.findByRequisite(user.getPassport(), "5546").getBalance()).isEqualTo(150D);

Разве мы не должны проверять на получение false или true методом transferMoney?. 
что то типо такого assertThat(rsl).isFalse();

**Comment by staskorobeynikov** [comment]
Сценарии проверки могут быть разные. Любой подход имеет место быть. Можно также поместить 2 проверки. 
Закрываю.
