### ISSUE TITLE
Мотивация НЕОБХОДИМО ЕЕ ДОПОЛНИТЬ.

### ISSUE THREAD

**Issue by RustamSaydam** [peterarsentev/job4j_features_bugs#1151]
По началу в СТАЖЕРЕ мне нравились после каждой темы - "Мини Мотивация" и каждый раз, когда я ее видел, все больше и больше хотелось посмотреть что там, но при этом завершить задачи, а потом я смотрю их в других темах нет..

Это может быть забвно, но на мой взгляд это необходимо в конце каждой теме, отвлечься немного, воодушевиться и так далее, как говорится, мелочь а приятно.

Мне кажется многим эта вещь заходила))

Людям можно бесконечно говорить о их целях, и надеждах, но гараздо приятнее когда в заданиях ты прошел блок и тебе дарят надежду, воодушевляют, конверсия пройденных курсов увеличится это факт!

**Comment by peterarsentev** [comment]
Спасибо. Медленно, то я добавляю в каждый блок такие уроки.
