### ISSUE TITLE
При переходе к следующему заданию в секции "Сообщения" остается висеть сообщение из предыдущего задания.

### ISSUE THREAD

**Issue by diac** [peterarsentev/job4j_features_bugs#1152]
Я стал замечать, что после отправки задания на проверку путем нажатия на кнопку "Сохранить и  перейти далее", иногда мое сообщение из выполненного задания остается "висеть" на экране нового задания. Перезагрузка страницы в браузере решает данную проблему.
Проблема проявляется случайно, не в 100% случаев.

На скриншоте видно, что еще до нажатия на кнопку "Отправить на проверку" в секции "Сообщения" осталось сообщение из предыдущего задания.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/2841616/182630863-090ae3a7-2721-4fd2-adc9-5bb1fbb75dd1.png">

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
