### ISSUE TITLE
В "Упражнениях" кнопка "Было решено: ?" - не работает.

### ISSUE THREAD

**Issue by fedorovse** [peterarsentev/job4j_features_bugs#1153]
![image](https://user-images.githubusercontent.com/59428290/183052284-a1b92494-c141-4c75-8d11-7df85a1e184a.png)

Даже когда решил упражнение, нельзя посмотреть, как его делали другие.

**Comment by staskorobeynikov** [comment]
Проверьте сейчас. Функционал добавлен
