### ISSUE TITLE
Про словарь @yarmail А можешь привести примеры таких слов? 

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1157]
@yarmail А можешь привести примеры таких слов? Если ты жаргон, то я стараюсь его из курса обрать.
Например, коммит заменить на фиксация изменений.

_Originally posted by @peterarsentev in https://github.com/peterarsentev/job4j_features_bugs/issues/886#issuecomment-1170796982_

**Comment by YarTsin** [comment]
Ой, да все что угодно, связанное с Джава, например: 
1) Вот пример аббревиатур от Михаила
https://t.me/liferefactoring/96

2) Короткие емкие определения Терминов, например, что такое **Spring Framework**:
По сути Spring Framework представляет собой просто контейнер _`внедрения зависимостей`_, с несколькими удобными слоями (например: доступ к базе данных, прокси, аспектно-ориентированное программирование, RPC, веб-инфраструктура MVC). Это все позволяет вам быстрее и удобнее создавать Java-приложения.
https://habr.com/ru/post/490586/
**Внедрение зависимостей** (В Спринг)- также известное как DI, это  — это стиль настройки объекта, при котором поля объекта задаются внешней _`сущностью`_. Другими словами, объекты настраиваются внешними объектами. DI — это альтернатива самонастройке объектов. Это может выглядеть несколько абстрактно, так что посмотрим пример...
**Сущность** (в терминах Java) - ... 
Огромный плюс знания терминов - зная, и проговаривая - Что это - вы уже в начале пути вопросов - Как это связано, и Как это работает

3) ИМХО зря вы убираете разные жаргоны. Я бы в сознании людей давал бы ассоциативные связи 
между терминами, и как раз словарь в этом может помочь. Вы же понимаете что существует куча 
"пониманий", переводов  зарубежных терминов, в книгах один перевод, в статьях другой, люди третье говорят, и людей, особенно новичков, это все путает и пугает. И вообще, лучше хоть какое-то название "вот этой штуки, которая вот тута", чем вообще никакого))
И в хорошем словаре можно с делать как в Вики, например:
Фиксация изменений (в Гит) - правильный термин, означающий то и то ...
Коммит - жаргонный неправильный термин, см правильный - Фиксация изменений

4) Понятно, что работы здесь очень много, но, мне кажется и отдача - в понимании, что это все такое, тоже не маленькая

**Comment by peterarsentev** [comment]
https://job4j.ru/profile/exercise/2/task-view/1179 сделал урок.
