### ISSUE TITLE
2. Аттестация [#49777 #329460]

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#1158]
Мне кажется не правильное описание по использованию методов :
4. Метод bestStudent() - для реализации данного метода можно использовать метод **averageScoreBySubject**
5. Метод bestSubject() - для реализации данного метода можно использовать метод **averageScoreByPupil** 

Наверное должно быть наоборот?

**Comment by aswsx** [comment]
Нет, все верно. Для определения лучшего студента надо вычислить средний балл по предметам каждого студента. И наоборот

**Comment by staskorobeynikov** [comment]
По описанию все верно
Закрываю
