### ISSUE TITLE
Время выполнения задания

### ISSUE THREAD

**Issue by DashaSinkova** [peterarsentev/job4j_features_bugs#1160]
Здравствуйте!
Было бы очень здорово добавить к задачам учет времени их выполнения. 
К примеру, кнопку таймер, на которую можно нажать во время старта решения и в дальнейшем переключать на паузу.
После решения складывать время и выводить результат, сколько заняла задача.

![image](https://user-images.githubusercontent.com/35614404/183268359-a8d4fef7-68ae-4e82-8a9d-2dea9c2bcfc0.png)

**Comment by DashaSinkova** [comment]
Благодаря этому функционалу у ученика выработается привычка рассчитывать примерное время, которое может занять задача

**Comment by aswsx** [comment]
Могу порекомендовать ресурс https://wakatime.com/dashboard
Он считает конкретное время, потраченное на работу в Idea и выводит результат в очень красивом и наглядном виде. Вплоть до времени работы над каждым классом

**Comment by dmarakov** [comment]
А я увы не очень согласен с целью данной фичи. Боюсь, что оценить задачу ученику будет просто невозможно.
Каждая задача - это новый материал для изучающего и проэстимировать ее не представляется возможным.
Возможную выгоду может получить сам курс, что бы найти какие-то узкие места в виде задач, которые у большого числа людей вызывают сложности, такие задачи нужно как-то переработать или раздробить на несколько.
Так же в возможную выгоду тут можно будет приписать вырабатывание привычки трекать свое время у учащегося.

**Comment by peterarsentev** [comment]
Мы добавили что-то подобное, но там время показалось предельно странным. Есть задачи, где время завершения занимает 20 дней. 
На обучение приходят много людей, кто никогда не программировал и им нужно больше времени для решения. Если они везде не будет вписываться по времени, то у них пропадает мотивация заниматься. В целом тут главное двигаться вперед, а скорость это второстепенное.
