### ISSUE TITLE
 Виды сборщиков мусора [#6852]

### ISSUE THREAD

**Issue by olegpan1** [peterarsentev/job4j_features_bugs#1162]
Как можно отсюда что-то понять????
Особенно раздел Вид сборки: Compacting, Non-compacting and Copying - такое ощущение, что оттуда поудаляли часть информации, а оставшиеся фразы разбросали в случайном порядке.

Вот так  понятнее выглядит:

Виды сборки мусора:

1) Non-compacting
Удаляет "мертвые" объекты  по месту их нахождения. 
Преимущество : не нужно производить лишние действия, нужно просто удалить неиспользуемые объекты. 
Недостаток:  приводит к фрагментации памяти, так-как "мертвые" объекты идут не по порядку и между ними остаются свободные пространства памяти, в которые не всегда можно поместить новый объект, и это приводит к неэффективному использованию памяти. 

2) Compacting
Удаляет "мертвые" объекты, после чего  "живые" объекты собирает подряд в одну область памяти .
Преимущество: отсутствует фрагментация памяти и легко можно выделять память для новых объектов.
Недостаток: требуется дополнительное время на компоновку "живых" объектов в одном месте.

3) Copying
Копирует "живые" объекты в отдельную часть памяти, после чего очищает область памяти где находились "живые" и "мертвые" объекты.
Преимущество:  нет препятствий выделению памяти для новых объектов. 
Недостаток: требуется время на копирование.

**Comment by itfedorovsa** [comment]
Исправлено. Спасибо!
