### ISSUE TITLE
Замечание к оформлению заданий

### ISSUE THREAD

**Issue by aswsx** [peterarsentev/job4j_features_bugs#1163]
Задание 1. select fetch [#331990]14
Уровень : 3. МидлКатегория : 3.3. HibernateТопик : 3.3.3. HQL, Criteria
https://job4j.ru/profile/exercise/93/task-view/490
В тексте задания написано:
"В прошлом уроке мы познакомились с простыми примерами выполнения запросов на языке запросов HQL"
Однако по порядку предыдущим заданием является создание SQL схемы для площадки продажи автомобилей, которое находится в другом разделе (3.3.2). Поэтому понять какой прошлый урок имеется в виду не представляется возможным.
Предлагаю в такие задания добавлять непосредственно ссылку на прошлый урок

**Comment by staskorobeynikov** [comment]
Неактуально, задание удалено
