### ISSUE TITLE
Job4j/Упражнения SQL/2. WHERE/1.8. Предложение WHERE с несколькими условиями с помощью OR 2 

### ISSUE THREAD

**Issue by ducknowledges** [peterarsentev/job4j_features_bugs#1165]
Опечатка
Для представленной ниже схемы **customers** --НУЖНО--> Для представленной ниже схемы transaction
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/46027009/183934320-7eb02228-bf8c-4646-8710-a68d7bc8bf85.png">

**Comment by staskorobeynikov** [comment]
Исправлено
