### ISSUE TITLE
0.4. Пользовательские исключения. [#219367 #302498] (front)

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1168]
https://job4j.ru/profile/exercise/24/task/193/302498
Небольшие непонятки во фронте
Браузер хром последней версии

<img width="730" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/184544531-de97c600-3084-4188-ade9-232da81dee71.png">

**Comment by staskorobeynikov** [comment]
Это у Вас какое-то расширение установлено в Chrome. Можете поэкспериментировать и опытным путем определить какой. У меня лично такое накладывает Google переводчик
Закрываю.
