### ISSUE TITLE
4. Принципы раннего возврата и охранных выражений [#504875]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1169]
https://job4j.ru/profile/exercise/24/task-view/955

Небольшие ошибки

<img width="348" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/184548785-becd86b3-e502-4ead-bfeb-c251cb9fd874.png">

**Comment by staskorobeynikov** [comment]
исправлено
