### ISSUE TITLE
4. Аттестация [#504878] Повторы?

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1171]
https://job4j.ru/profile/exercise/29/task-view/958

Нашёл случайно два очень похожих задания,
возможно есть какие-то несостыковки

<img width="1201" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/184698806-92b34337-2485-460a-afe2-92528b3d6910.png">

**Comment by YarTsin** [comment]
4. Аттестация [#504878]
Также в этом задании я заметил использование Record. Возможно имеет смысл рассказать о нем и его отличиях от класса в Разделе Классы и объекты (если этого ещё не было сделано)

**Comment by staskorobeynikov** [comment]
Так и должно быть - одну решаем на Stream, Одну на коллекциях
По Record задача в разработке.
Закрываю.
