### ISSUE TITLE
Отсутствует возможность прикрепить скриншот к задаче

### ISSUE THREAD

**Issue by KateStulova** [peterarsentev/job4j_features_bugs#1173]
Для закрытия некоторых задач (напр., задачи "0. Настройка окружения для Maven. [#274134]" и "1. Создание проекта через maven. [#274135]") требуется прикрепить скриншот, но кнопка для этого отсутствует. Прошу реализовать возможность добавления скриншота.
<img width="1190" alt="Снимок экрана 2022-08-17 в 01 27 04" src="https://user-images.githubusercontent.com/53825155/184996708-99e6cc05-ac50-4068-94ee-676fa5c91c18.png">

**Comment by QuickMixKZ** [comment]
Попробуйте перетаскивание.

**Comment by KateStulova** [comment]
@QuickMixKZ 
Да, drag&drop работает. 
Но это не очевидно. Хотелось бы видеть кнопку с возможностью прикрепления скриншота.

**Comment by staskorobeynikov** [comment]
Кнопка была удалена чтобы не загромождать интерфейс. Используйте просто вставку из буфера.
Закрываю
