### ISSUE TITLE
3.1.2. Общие ресурсы - убрать jcip?

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1174]
В лекциях "3. Immutable объекты" и "4. Thread без общих ресурсов" присутствует код из библиотеки jcip, которая по курсу будет установлена только в следующем разделе, в результате чего при добавлении кода из этих лекций в проект требуется самостоятельно добавлять jcip. Предлагаю рассмотреть вариант либо удаления кусков jcip из этих лекций(он там вроде и не особо нужен), либо переноса этих лекций вперед, либо лекции по jcip назад, либо еще как-то поработать над этим моментом.
![image](https://user-images.githubusercontent.com/101260971/185128537-496b2a04-d258-43c5-9725-b844230f53e2.png)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
