### ISSUE TITLE
Не работает :: numeric в блоке SQL

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1176]
Задание не проходит проверку, т.к невозможно верно обработать ::
https://job4j.ru/profile/sqlExercise/2/show/24
![image](https://user-images.githubusercontent.com/13130875/185347948-88d816ea-7b7e-4bce-bd86-98d9fe96cc42.png)

**Comment by staskorobeynikov** [comment]
Там его и не нужно использовать. В описании просто описан возможный функционал, нигде в заданиях не стоит использовать его
Закрываю.
