### ISSUE TITLE
Открытие решений других учеников до выполнения задачи.

### ISSUE THREAD

**Issue by QuickMixKZ** [peterarsentev/job4j_features_bugs#1179]
Чтобы посмотреть решение других учеников, ещё до того, как сам решил задачу, достаточно у кнопки убрать атрибут disabled.
![resheniya](https://user-images.githubusercontent.com/89402431/185539575-79d3ecf4-056e-4a6d-97d1-b641fd7a1e52.png)

**Comment by QuickMixKZ** [comment]
Всё ещё проще, можно ссылку в адресной строке дописать, чтобы к решениям перейти.

**Comment by AlexeySapsay** [comment]
> Всё ещё проще, можно ссылку в адресной строке дописать, чтобы к решениям перейти.

спасибо, помогло!

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
