### ISSUE TITLE
Дополнить задание в SQL упражнениях

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1180]
Не понятно, про какую сумму говорит автор? может amount? или нужно считать SUM ?
методом тыка- нашел что amout.
![image](https://user-images.githubusercontent.com/13130875/185605899-d31edc06-5e45-497c-bfa3-33302068ec0b.png)
https://job4j.ru/profile/sqlExercise/1/show/41

**Comment by staskorobeynikov** [comment]
исправлено
