### ISSUE TITLE
4. Преобразование List в Map. [#110226]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1183]
https://job4j.ru/profile/exercise/3/task-view/254

Мне кажется в этих строках не хватает запятых

<img width="689" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/185805441-14893fa5-a9f2-436f-bbd9-f2107d407b51.png">

**Comment by staskorobeynikov** [comment]
Поправил
