### ISSUE TITLE
https://job4j.ru/profile/exercise/104/task-view/526

### ISSUE THREAD

**Issue by VadimDedeiko** [peterarsentev/job4j_features_bugs#1184]
![изображение](https://user-images.githubusercontent.com/31100031/185806497-f253052a-8967-4ff9-b536-57de30003b18.png)

**Comment by VadimDedeiko** [comment]
грамматическая ошибка. нужно вызовы

**Comment by staskorobeynikov** [comment]
Задание удалено.
Закрываю.
