### ISSUE TITLE
Некоторые вопросы по цифрам задач

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1186]
Очередной раз закрыл все задания Стажера. В цифрах по заданиям вижу
некоторые непонятности. Может быть там что-то подкрутить или я что-то упускаю?
<img width="699" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/186858509-2850c24b-689d-4eb5-9d01-5e216b249640.png">
И по общим цифрам
<img width="335" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/186858528-51c424eb-200a-4238-9025-abbbdc43cecf.png">

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
