### ISSUE TITLE
Опечатка в задании 5.3. Построить шахматную доску в псевдографике.

### ISSUE THREAD

**Issue by repoevgenii** [peterarsentev/job4j_features_bugs#1190]
[Опечатка в задании 5.3. Построить шахматную доску в псевдографике.](https://job4j.ru/profile/exercise/14/task-view/76)
![опечатка](https://user-images.githubusercontent.com/91419969/187191136-6c1360ce-1a46-41e8-aef2-fd256dfa3c77.jpg)

**Comment by staskorobeynikov** [comment]
Исправлено
