### ISSUE TITLE
Предложение добавить в CheckStyle разрешение для джава док коментариев

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1193]
Прошу добавить многострочные комментарии для создании описания в файле. Например такие
Очень хотелось бы делать для себя пометки, о работе данного класса и его применимости. 
Удаление комментариев очень ограничивает возможность работать с кодом и делать пометки.

![image](https://user-images.githubusercontent.com/13130875/187426890-54afda0b-baf9-485a-8d3a-de3523dab6ce.png)

![image](https://user-images.githubusercontent.com/13130875/187425762-98ea4a93-3b47-4938-900d-585a2876bc59.png)

**Comment by peterarsentev** [comment]
@AlexeySapsay Так а что сейчас? Он не пропускает?

**Comment by peterarsentev** [comment]
@AlexeySapsay Закрываю. Он все же пропускает, но не дает вставлять ссылки на внешние ресурсы, А они тут и не нужны.
