### ISSUE TITLE
2. Триггеры [#504803]

### ISSUE THREAD

**Issue by dima-abc** [peterarsentev/job4j_features_bugs#1194]
https://job4j.ru/profile/exercise/179/task-view/798
отличное задание и очень хорошо все раскрыто, но!

Внесите ясность со словами "насчитать налог" и "высчитать налог" в задании 1), 2) соответственно.
Переговорив с начальником фин отдела и глав бухам пришли к общему мнение что;
Насчитать налог - это к цене прибавить сумму налога от это цена (дапустим 20% от ндс). то есть цена 100 насчитываем налог получаем 100 * 1.2 = 120.
Высчитать налог - это из цены выделить сумму налога то есть цена 100, мы высчитываем налог из цена 100*0,2 = 20.
Разумно предположить что для выполнения задания в таблицу products необходима добавить дополнительное поле налога (tax).
Надеюсь мая мысль ясна.

**Comment by itfedorovsa** [comment]
Исправлено. Оставлено "насчитать" с пояснением "прибавить налог к цене". Спасибо!
