### ISSUE TITLE
добавить  дополнение в текс упражнения на уровень изоляции транзакций

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1196]
Очень не хватает в упражении понимания, как я должен догадаться, что нужно открыть второй терминал psql для второй транзакции? для меня это не понятно, думаю что для других тоже. 

зайти в psql можно набрав  в поиске винды psql
жмем интер до последней строчки, когда надо вводить пароль

![image](https://user-images.githubusercontent.com/13130875/187982566-da3a7492-492c-4cb0-b35a-ea76b99c53ac.png)

открываем еще одно окно psql для второй транзакции и повторяем все действия по входу
вводим в 1окно команды для первой транзакции и
соответственно во второе окно- для второй транзакции
(админы, это хорошо было бы отразить в статье, а не методом проб и ошибок догадываться)

**Comment by itfedorovsa** [comment]
Изменения внесены. Спасибо!
