### ISSUE TITLE
Добавить сотые доли процента в прогресс обучения

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1198]
Т.к 1 процент может стоит 5-6 задач, то хотелось бы видеть минимальные шаги в прогрессе, даже после 1 завершонной задачи. Как сделанно в прогресс баре ниже, с отображением сотых долей процента. Это мотивирует и дает силы продолжать, когда видишь продвижение, даже на 1 шаг в перед.

![image](https://user-images.githubusercontent.com/13130875/188115554-e93124c1-2a84-433e-9341-e804e2b17734.png)

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by peterarsentev** [comment]
Сделали.
