### ISSUE TITLE
Добавить  дополнение в текст урока

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1199]
4.4. Транзакции. Работа с транзакциями в PostgreSQL [#504813 #338912]
добавить дополнение, что команды из урока стоит выполнять в PostgreSQL , т.к в ИДЕА rollback and savepoin не будут работать вовсе

**Comment by staskorobeynikov** [comment]
А можно пример не работы? все команды проверил в IDEA, все работает

**Comment by peterarsentev** [comment]
Закрываю.
