### ISSUE TITLE
 2. IndexControl. Таблица и вид.[2092#348558]

### ISSUE THREAD

**Issue by peterarsentev** [peterarsentev/job4j_features_bugs#12]
Стоит пояснить что НУЖНО прописать НОВЫЙ бин в WebConfig, +- так же, как это сделано у меня
+ стоило пояснить что @Service && @Controller && @Repository - это уже сами по себе Бины и их нужно засунуть в контекст.

**Comment by ShamRail** [comment]
Задание уточнено. Добавлено описание данных аннотаций.
