### ISSUE TITLE
Подправить текст в уроке

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1204]
https://job4j.ru/profile/exercise/179/task-view/818
Много однако. Это перегружает и выглядит странно. Возможно лучше использовать- и? или другое подходящее слово

![image](https://user-images.githubusercontent.com/13130875/188219410-a16de061-8316-44ee-a588-c33d1cca3f82.png)

**Comment by staskorobeynikov** [comment]
Исправлено
