### ISSUE TITLE
лишнее слово в тексте урока

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1206]
![image](https://user-images.githubusercontent.com/13130875/188220417-9729791d-699f-4bd4-a83e-04c78ea50fbf.png)
здесь можно бес слова **создается**, оно может быть убрано без потери смысла

https://job4j.ru/profile/exercise/179/task-view/818

**Comment by staskorobeynikov** [comment]
Исправлено
