### ISSUE TITLE
Тёмный фон сайта

### ISSUE THREAD

**Issue by Arcady555** [peterarsentev/job4j_features_bugs#1207]
Уважаемый Пётр!
Насколько сложно сделать на сайте возможность менять фон с белого(с черными буквами) на черный(с белыми буквами)? Было б гораздо удобней работать с вами в ночное время)))
Спасибо!

**Comment by peterarsentev** [comment]
Не буду делать. Уже была поддержка, потом мы ее убрали. У нас много картинок в тексте, их тоже нужно переделывать. а это огромный объем работы. 
Если совсем туго, то можно поставить плагин в браузере и настроить цвета в нем.
