### ISSUE TITLE
4.3.5. Множественное логическое выражение И [#424794]

### ISSUE THREAD

**Issue by tutbora** [peterarsentev/job4j_features_bugs#122]
Отсутствует в задании  условие размещения ссылки на выполненный урок, может это не критично и подразумевается, но если выполнять задание досконально и точно, то ссылку не нужно размещать)
а на самом деле нужно, для проверки задания)
и такие моменты я буду указывать, как замечу, по идее весь сайт можно пропустить через проверку орфографических ошибок и за раз обо всех узнать.

**Comment by staskorobeynikov** [comment]
На самом деле про ссылку есть
2. Залейте код в репозиторий.
**3. Добавьте ссылку на коммит** и переведите ответственного на Петра Арсентьева.

Но чтобы было похоже на предыдущее задание - поправил
