### ISSUE TITLE
не открывается гиперссылка в уроке

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1224]
![image](https://user-images.githubusercontent.com/13130875/188281300-bfa736e4-f894-46fd-bc71-26610607129d.png)
https://job4j.ru/profile/exercise/183/task-view/919

пустая страница и такой запрос
![image](https://user-images.githubusercontent.com/13130875/188281319-229f5615-d809-447a-83e8-3db464162ebc.png)

**Comment by staskorobeynikov** [comment]
Исправлено
