### ISSUE TITLE
неверно указан перевод паттерна MVC

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1227]
![image](https://user-images.githubusercontent.com/13130875/188284206-998b3e6d-c422-45ed-92ed-007308ce322e.png)
https://job4j.ru/profile/exercise/183/task-view/921

Model View Controller (MVC)- лучше сразу расшифровать абревиатуру, как делали в предыдущих статьях, в данной пропустили расшифровку. Это позволит сразу запомнить правильное название и потом не путаться

![image](https://user-images.githubusercontent.com/13130875/188284225-5969ef75-342e-4929-82d9-0c73b646544b.png)

**Comment by itfedorovsa** [comment]
Исправил. Спасибо!
