### ISSUE TITLE
путаница в названиях пакетов

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1228]
в упражнении указан пакет
![image](https://user-images.githubusercontent.com/13130875/188288866-6b358cd4-e8a0-48f7-97da-3574d364c0b7.png)
https://job4j.ru/profile/exercise/183/task-view/918

а в упражнении уже указан другой пакет
![image](https://user-images.githubusercontent.com/13130875/188288921-679a440e-ce2c-4d9f-bc86-b5f7bf42032f.png)
https://job4j.ru/profile/exercise/183/task-view/921

посмотрев решения других участников видно, что одни решают задания используя первое название, другие второе. Конечно это не большая проблема в учебном проекте. Но это плохой пример задания требований, когда можно их интерпретировать двояко. Хотелось бы согласованности в пакетах.  Предлагаю оставить первый вариант с package ru.job4j.dreamjob;
т.к с него начался проект, и вероятно так и предполагал автор назвать его, а package ru.job4j.dream появился в следствии опечатки, ибо названия очень близки, можно сделать такое предположение.

**Comment by itfedorovsa** [comment]
Заменил на dreamjob во всех уроках. Спасибо!
