### ISSUE TITLE
ошибка в названии класса

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1230]
![image](https://user-images.githubusercontent.com/13130875/188289816-ce504604-b59d-4552-a83e-67bb89ea5959.png)

https://job4j.ru/profile/exercise/183/task-view/921

возможно пакет control лучше называть контроллер- ибо такое имя отражает полную суть объектов, находящихся в пакете. И такие стандарты, на сколько мне известно. Называть контроллер и пакеты с контроллерами- controller.
Если не так, то пожалуйста, поправьте меня

**Comment by staskorobeynikov** [comment]
Исправлено
