### ISSUE TITLE
Предложение по поводу экзаменов

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#1231]
![изображение](https://user-images.githubusercontent.com/83451847/188289977-ecc64d03-ee42-428c-9cad-b3aed69c6203.png)
предлагаю сделать тут выбор ученику:
1. только аудио-связь
2. видео-связь

видео-связь позволит более полно погрузиться в атмосферу реальных собеседований.

**Comment by peterarsentev** [comment]
Мне лично самому будет сложно так подготавливаться. Все же львиная большая - это знания, а не атмосфера. Да и отношение ко мне во многом дружеское, а не собеседовании может кто угодно быть.
Пока делать не будем так.
