### ISSUE TITLE
3.2.0. Основы Git 3.1. Добавить изменения в последний коммит - внести уточнение

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1232]
В лекции сначала говорится, что не должно быть 2 коммитов по одной задаче (решение + поправка), а потом написано, что исправлять первый коммит нельзя, так как коллеги уже могут работать с предыдущим коммитом. Нужно внести уточнение как в итоге действовать. Например, ответ ментора: "Все определяется теми правилами, которые определены на проекте. Поэтому полезно активно общаться с лидом и коллегами". На данный момент лекция сама себе противоречит.

**Comment by AlexeySapsay** [comment]
хорошее замечание, надеюсь поправят!

**Comment by itfedorovsa** [comment]
Исправлено.
