### ISSUE TITLE
0. Spring Boot [#348573] - Опечатки

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#124]
=========================================
-- настройки проекта:
```
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
```

-- нужно поставить "=" вместо ":".

=========================================

```

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Accident</title>
</head>
<body>
Index page
</body>
</html>
```
-- Заменить "Accident" на "Forum".
-- Убрать первую пустую строку, она не нужна. 

=========================================

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.2.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>
```
-- слетела подсветка

=========================================

2. Создайте виды и контроллеры.
index.jsp - список тем.
reg.jsp - регистрация пользователя.
login.jsp - авторизация пользователя.
edit.jsp - создание и редактирование темы.
post.jsp - тема и обсуждения.
-- Не понятно, тут из сразу ПОЛНОСТЬЮ Реализовывать или просто объявить и позже их доделать???

=========================================

**Comment by dmitrytishchenko** [comment]
поправил
