### ISSUE TITLE
Опечатка в задаче 3. Замена if-else-throw на if-throw

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#125]
Опечатка в задаче 3. Замена if-else-throw на if-throw [#402157]
![image](https://user-images.githubusercontent.com/13130875/101940408-7f155f00-3bf7-11eb-8e65-887d842a105a.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
