### ISSUE TITLE
Тесты - Принципы ООП в Java

### ISSUE THREAD

**Issue by igor-grigoriev** [peterarsentev/job4j_features_bugs#1252]
В тесте есть вопрос - Опишите процесс создания объекта. Выбираю вариант ответа - Объявляется ссылка типа класса объект которого хотим создать затем ей присваивается объект который создается с помощью ключевого слова new. Результат теста говорит что на этот вопрос дан неверный ответ - при этом в качестве правильного ответа указывает этот же вариант

**Comment by itfedorovsa** [comment]
Ваш ответ правильный, ошибка была в системе. Исправлено. Спасибо!

**Comment by GitHubfilipich** [comment]
Есть вопрос в тесте:
"Наследование это:"
Правильным в тесте указывается следующий вариант:
"Если можно использовать объект наследника то возможно и использование родителя"
Считаю, что это неверный вариант, простой пример: наследника типа String можно поместить в массив String[], а его родителя Object в этот же массив поместить нельзя. На мой взгляд, правильным является другой вариант: "Если можно использовать объект родителя то возможно и использовать и объект наследника."

**Comment by GitHubfilipich** [comment]
Есть вопрос в тесте:
"Классы, объекты и методы
Какие утверждения верны?"
При неправильном ответе выдаётся рекомендация:
"Посмотрите [видео](http://job4j.ru/courses/start/lesson_6.html) 6-го урока вводного курса "Java в аналогиях"."
- ссылка, связанная со словом "видео" (https://job4j.ru/courses/start/lesson_6.html), не существует, необходимо поправить
