### ISSUE TITLE
ошибка в задании

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1261]
![image](https://user-images.githubusercontent.com/13130875/189358628-8a0754a1-52d0-4bef-89ee-c48148f93c8e.png)
как указывали раннее нет метода create, использовали метод add в postStore. Нужно заменить тут create на add, что бы это не вызывало путаницы

https://job4j.ru/profile/exercise/184/task-view/930

**Comment by staskorobeynikov** [comment]
Исправлено
