### ISSUE TITLE
контроль, заменить на контроллеры- для единообразия названия слоев, и отсуствия путаницы

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1262]
![image](https://user-images.githubusercontent.com/13130875/189365812-c1dc8f15-bf98-49dd-ab3a-9045b9b2f2c2.png)
https://job4j.ru/profile/exercise/185/task-view/931
Заменить контроллер на контроллеры, ибо о множественном числе идет речь дальше в предложении
![image](https://user-images.githubusercontent.com/13130875/189366143-8929ed02-2e38-48ee-a9fb-956528e48e42.png)

**Comment by staskorobeynikov** [comment]
Исправлено
