### ISSUE TITLE
CI Bot ругается на код из задания 5.0. Цикл for. Определение

### ISSUE THREAD

**Issue by GHMember** [peterarsentev/job4j_features_bugs#1264]
Перенес в IDE из описания задания этот код for (i = 0; result = i <= 5; i++), выполнил задание и запушил его на GitHub. Код с таким условием компилируется, но Ci Bot теперь после каждого пуша присылает мне сообщение: "Нарушения по стилю checkstyle. Коммит Лог * CI Bot собрал Ваш проект и нашел ошибки. Вам нужно поправить сборку и заново оставить ссылку на изменения. Если Вы не знаете как поправить, то в тексте комментария напишите, что не знаете, как поправить ошибку в сборке.".

**Comment by staskorobeynikov** [comment]
Добавил уточнение для чего такой код представлен в описании
