### ISSUE TITLE
перегруженное не понятное предложение

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1265]
![image](https://user-images.githubusercontent.com/13130875/189411053-4e2438ed-c2ec-4d9a-9987-16b140878cb2.png)
https://job4j.ru/profile/exercise/185/task-view/936

**Comment by AlexeySapsay** [comment]
![image](https://user-images.githubusercontent.com/13130875/189412364-da73c770-01ac-41ea-95bb-7e58fdc6df86.png)
возможно здесь надо единстве**нном**

**Comment by staskorobeynikov** [comment]
поправил
