### ISSUE TITLE
скорректировать код задания, т.к в предыдущих заданиях у нас не было таких эндпоинтов в контроллерах

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1266]
![image](https://user-images.githubusercontent.com/13130875/189415192-9d0f13cd-1f91-4627-8e96-05984e7d4974.png)
https://job4j.ru/profile/exercise/185/task-view/936

**Comment by staskorobeynikov** [comment]
Поправил
