### ISSUE TITLE
Опечатка 1. Наследование, композиция и агрегация 

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#127]
Опечатка при разметке страницы
агрегация вероятно должна быть вынесена в блок текста вне блока кода. Как сделано с наследование и композицией

![image](https://user-images.githubusercontent.com/13130875/101943773-c18d6a80-3bfc-11eb-8500-9dda96367e64.png)

**Comment by AlexeySapsay** [comment]
![image](https://user-images.githubusercontent.com/13130875/101944275-80e22100-3bfd-11eb-8572-5a5b2b6695ca.png)

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
