### ISSUE TITLE
не верный пакет

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1270]
![image](https://user-images.githubusercontent.com/13130875/189476094-996b232d-f04a-47a8-a26e-2c5638659d70.png)
если опираться на задания раннее, то пакет должен называться dreamjob. dream- вносит путаницу
https://job4j.ru/profile/exercise/186/task-view/934

**Comment by AlexeySapsay** [comment]
![image](https://user-images.githubusercontent.com/13130875/189476253-d1d16c1c-2d05-4bc7-b7ca-9e0139863a7f.png)
лишнее слово

**Comment by staskorobeynikov** [comment]
Поправил
