### ISSUE TITLE
предложение дополнить задание

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1271]
![image](https://user-images.githubusercontent.com/13130875/189476958-04fe35c4-513c-4e8d-b2a9-e9a681db4953.png)
т.к редактировать чекбокс о публикации нельзя, предложил бы добавить еще редактирование чексбокс публикации вакансии на страницу редактирования вакансии. Ибо в противном случае этот чекбокс бесполезен, его можно один раз выставить, в момент создания вакансии и все. 

https://job4j.ru/profile/exercise/186/task-view/934

**Comment by AlexeySapsay** [comment]
![image](https://user-images.githubusercontent.com/13130875/189478162-26df0987-00da-4c2b-9c81-9a9af6614bee.png)
так же не понятно, добавить список городов в редактирование и создание постов и кандидатов? Или достаточно добавить для постов?

**Comment by itfedorovsa** [comment]
Обновил задание. Добавил информацию о добавлении списка городов в создание и редактирование вакансий и кандидатов. Спасибо!
