### ISSUE TITLE
поправить нумерацию заданий

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1272]
пропало 3е задание в разделе
![image](https://user-images.githubusercontent.com/13130875/189480694-042cb5a2-3a3b-4cc0-b47b-b5c9e65f46d4.png)
https://job4j.ru/profile/exercise/186

**Comment by staskorobeynikov** [comment]
С нумерацией все хорошо. Там одна скрытая задача, которая на доработке и будет добавлена несколько позднее.
