### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Svetlana44** [peterarsentev/job4j_features_bugs#1276]
Absent вместо Present
map.computeIfAbsent(1, key -> "first" + "_" + key); // вычисляем значение для ключа, который есть в отображении
![image](https://user-images.githubusercontent.com/66846228/189543075-9cfa70ce-8979-429c-9163-160097e8c7a9.png)

**Comment by staskorobeynikov** [comment]
там в комментарии ошибка. исправил
