### ISSUE TITLE
дополнение по условию задания

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1277]
в задание
https://job4j.ru/profile/exercise/186/task/934/341765
кроме  пунктов:
Задание.

1. Добавьте справочник городов. Добавьте в форму создания и редактирования список городов.

2. Загрузите изменения в репозиторий. Оставьте ссылку на коммит.

3. Переведите ответственного на Арсентьева Петра.

пожалуй стоит добавить еще пункт, указанный ментором, т.к наверняка он будет требоваться и для других учеников

0. В таблицу вывода Post добавьте вывод добавленного города

**Comment by staskorobeynikov** [comment]
Поправил
