### ISSUE TITLE
https://job4j.ru/profile/sqlExercise/1/show/43

### ISSUE THREAD

**Issue by Dimarik1Krasnodar93** [peterarsentev/job4j_features_bugs#1286]
![image](https://user-images.githubusercontent.com/87864463/190184971-0884a1ac-b08f-4c6a-ac8d-8680a2bab62f.png)
в тестах по SQL - в упражнениях еще не сделал упражнение и сразу же пишет "Задание решено верно". Пишет даже до начала выполнения задания

**Comment by peterarsentev** [comment]
Спасибо. Взяли в работу.

**Comment by peterarsentev** [comment]
Поправили.
