### ISSUE TITLE
Раздел ТЕСТЫ 

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1287]
![image](https://user-images.githubusercontent.com/88712756/190322457-ab91a252-d429-470e-9e12-e176436f7d94.png)

В разделе тесты есть не активный пункт меню, без вопросов, судя по всему баг.

**Comment by ghost** [comment]
Пункт 1. 2222 Вопросов 2

**Comment by itfedorovsa** [comment]
Убрал этот раздел. Спасибо!
