### ISSUE TITLE
6.0.3.1. Массивы и цикл for-earch [#420758]. Грамматическая ошибка

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#129]
Вместо
"В этом уроке мы познакомимся с интересной конструкцией, которая в большинстве случаев **упростить** работу с массивами в цикле for() - цикл for-each()."

Или так:
"В этом уроке мы познакомимся с интересной конструкцией, которая в большинстве случаев **упростит** работу с массивами в цикле for() - цикл for-each()."

Или так:
"В этом уроке мы познакомимся с интересной конструкцией, которая в большинстве случаев **упрощает** работу с массивами в цикле for() - цикл for-each()."

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
