### ISSUE TITLE
Не верная формулировка задания Упражнения 1.4.1. Lambda 5.2. Optional. Методы isPresent(), isEmpty(), get()

### ISSUE THREAD

**Issue by Svetlana44** [peterarsentev/job4j_features_bugs#1292]
В задании написано вернуть индекс значения. А получается-вернуть само значение.

![2022-09-18_19h53_17](https://user-images.githubusercontent.com/66846228/190919019-d580d04c-3f87-449f-a2a3-3f2d63cf38bc.png)

**Comment by itfedorovsa** [comment]
В этом упражнении все правильно.  В Optional помещается любое "значение". Конкретно в задании индекс и будет являться этим "значением", то есть тем, что мы хотим в него поместить. По заданию нужно найти наше "значение"(индекс) и поместить его в Optional в методе indexOf(), после чего в методе get() проверить его на присутствие и вернуть. Закрываю обращение.
