### ISSUE TITLE
добавить пропущенное слово- быть

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1294]
![image](https://user-images.githubusercontent.com/13130875/191058803-54b7d5f6-3a26-489f-8c70-c5c32e222f31.png)
https://job4j.ru/profile/exercise/24/task-view/955

Уроки
1.2.5. Исключения
4. Принципы раннего возврата и охранных выражений

**Comment by staskorobeynikov** [comment]
Исправил
