### ISSUE TITLE
поправить текст для лучшей читаемости

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1295]
![image](https://user-images.githubusercontent.com/13130875/191063652-e593fbdd-c4d6-4ffc-8b35-113f7402b45b.png)
последнее предложение предполагает вопрос что встретить? на который не дается ответ.
И это запутывает
Лучше переформулировать так: По той же причине не рекомендуется использовать метки в коде;

Уроки
1.2.5. Исключения
4. Принципы раннего возврата и охранных выражений

https://job4j.ru/profile/exercise/24/task-view/955

**Comment by staskorobeynikov** [comment]
Поправил немного по-другому
