### ISSUE TITLE
опечатка в тексте

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1296]
В первом случае не надо мягкий знак. Во втором случае ошибка в заводиться, надо заводить
![image](https://user-images.githubusercontent.com/13130875/191067557-4ca52dec-5389-4e18-8898-b278ae6a4894.png)
https://job4j.ru/profile/exercise/24/task-view/955

Уроки
1.2.5. Исключения
4. Принципы раннего возврата и охранных выражений

**Comment by staskorobeynikov** [comment]
Исправлено
