### ISSUE TITLE
ошибка в названии класса в задании и в примере. Указаны разные классы

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1297]
![image](https://user-images.githubusercontent.com/13130875/191069737-e115cd95-d292-418d-ae32-14c2412d75aa.png)

https://job4j.ru/profile/exercise/24/task-view/955
Уроки
1.2.5. Исключения
4. Принципы раннего возврата и охранных выражений

**Comment by staskorobeynikov** [comment]
Исправлено
