### ISSUE TITLE
быть или не быть? опечатка в тексте

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1299]
лишнее быть
![image](https://user-images.githubusercontent.com/13130875/191084349-d3691ee6-dd69-4174-bc09-cde812bd5e93.png)
https://job4j.ru/profile/exercise/24/task-view/955

Уроки
1.2.5. Исключения
4. Принципы раннего возврата и охранных выражений

**Comment by staskorobeynikov** [comment]
Исправлено
