### ISSUE TITLE
0.3. BufferedReader. опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#13]
В задании:  2. Уровень - Джуниор / Блок 2. Ввод-вывод / 1. Ввод-вывод / 0.3. BufferedReader есть опечатки:
Один пото**м** оборачивается
Базовый пото**м** - это поток
в символьный пото**м**, если

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
