### ISSUE TITLE
Утверждения с коллекциями [#504885]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1300]
https://job4j.ru/profile/exercise/192/task-view/965
Подчеркнуто красным - думаю не нужно и неправильно
Подчеркнуто зеленым, вот так думаю правильно
<img width="673" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/191236817-98613298-ded7-4868-ab42-a96737f1e8d9.png">

**Comment by itfedorovsa** [comment]
Верхняя строка действительно лишняя. Arrays.stream возвращает объект Stream, у которого есть метод toList(), чем и можно пользоваться. toSet() у него нет, поэтому сборка в Set идет через класс Collectors. Спасибо, закрываю.
