### ISSUE TITLE
Не рабочая проверка упражнения https://job4j.ru/profile/topics/4/task_code/18/136324

### ISSUE THREAD

**Issue by Svetlana44** [peterarsentev/job4j_features_bugs#1302]
В тесты не импортирован класс Shell ?
![2022-09-21_12h56_56](https://user-images.githubusercontent.com/66846228/191493516-2a2d4af0-62e4-406d-9d65-27182c6b7c82.png)

**Comment by itfedorovsa** [comment]
Исправлено. Спасибо!
