### ISSUE TITLE
3.2.4. Архитектура Web приложений 2. Связь слоев через Spring DI. - внести правки

### ISSUE THREAD

**Issue by itfedorovsa** [peterarsentev/job4j_features_bugs#1304]
1) Предлагаю дополнить лекцию раскрытием понятия Spring DI: в названии и в задании Spring DI упоминается, а в лекции нет. То есть добавить хотя бы фразы типа "Spring DI - это...", "DI - это ..." и тд.
Например, отсюда https://javarush.ru/groups/posts/spring-framework-java-1
2) Сделать форматирование кода, очень неудобно с ним работать в виде обычного текста.
3) Поправить расчет ID, так как 3 уже есть, а при создании следующего будет id 5.
![image](https://user-images.githubusercontent.com/101260971/191743805-9d201f5f-3360-4a77-ab67-375908b4dfff.png)
4) savePost из этой лекции существует только в этой лекции. В других лекциях и в проекте это createPost. Вводит в заблуждение.
![image](https://user-images.githubusercontent.com/101260971/191745979-20979911-58b0-4e9f-924b-459319432345.png)

**Comment by peterarsentev** [comment]
@itfedorovsa Спасибо. Мы сделали отдельный блок Spring Core | AOP. Он идет сразу в "Стажере."
