### ISSUE TITLE
Добавить тему с обучением разработки Диаграмм зависимостей классов

### ISSUE THREAD

**Issue by RustamSaidov** [peterarsentev/job4j_features_bugs#1305]
В задании 2. Крестики-нолики. Тестовое задание. [#793 #345297]
требуется разработать диаграмму для создания приложения для игры в Крестики-Нолики. но дело в том, что никакого материала, который нас бы этому обучал - нет. Приходится интуитивно что-то додумывать и доискивать в интернете.
Данную проблему мне порекомендовал вынести сюда мой ментор.

Рустам Саидов. 23.09.2022

**Comment by AlexeySapsay** [comment]
вот хорошая прилажуха, для визуализации
https://www.jetbrains.com/help/idea/class-diagram.html#analyze_class

**Comment by peterarsentev** [comment]
@RustamSaidov Спасибо. Руслан. У нас есть блок проектирование UML. Он идет отдельно от основного курса, так как это проектирование. Из курса по максимуму убраны элементы с проектированием систем.
