### ISSUE TITLE
1. Что такое итератор. [#4951 #246493] предполагаемые уточнения лексики.

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#1310]
Цитата: Многократный вызов этого метода должен быть одинаковым. (о хэзНекст())

Результат многократного вызова этого метода должен быть одинаковым. Многократный вызов любого метода одинаков О_о, а результат не всегда.

**Comment by itfedorovsa** [comment]
Исправлено. Спасибо!
