### ISSUE TITLE
Ошибка в упражнении Упражнения 1.1.4. Оператор ветвления 2.1. Четно-красивое трехзначное число

### ISSUE THREAD

**Issue by aswsx** [peterarsentev/job4j_features_bugs#1315]
Ошибка в задании Job4j
Упражнения
1.1.4. Оператор ветвления
2.1. Четно-красивое трехзначное число

ru.job4j.condition.Task20

![image](https://user-images.githubusercontent.com/61579000/193407955-bc355d21-6d06-49a8-bb3f-3177fa63f76a.png)
Число 100 не является четно-красивым

**Comment by itfedorovsa** [comment]
Исправлено! Спасибо!
