### ISSUE TITLE
Ошибка в названии метода. Урок 1.1.4 Оператор ветвления. Упражнение 4.3.5. Множественное логическое выражение И

### ISSUE THREAD

**Issue by alshevskiy** [peterarsentev/job4j_features_bugs#1316]
<img width="1303" alt="Снимок экрана 2022-10-01 в 18 43 40" src="https://user-images.githubusercontent.com/111909057/193417244-39390ebf-3b72-4f52-9f4b-b53ffcb416d2.png">

Необходимо исправить название метода на "isFalse()"

**Comment by staskorobeynikov** [comment]
исправлено
