### ISSUE TITLE
Ошибка в упражнении Упражнения 1.1.4. Оператор ветвления 3.1. Изменить число в зависимости от его знака

### ISSUE THREAD

**Issue by aswsx** [peterarsentev/job4j_features_bugs#1317]
![Capture](https://user-images.githubusercontent.com/61579000/193439156-b41fa6c3-daac-42c9-95e2-7e3ddc117059.PNG)

**Comment by itfedorovsa** [comment]
Здесь ошибки нет. Неотрицательные числа должны превращаться в ноль по условию задачи. Закрываю обращение.
