### ISSUE TITLE
1.1.4. Оператор ветвления   Задача 2.1. Четно-красивое трехзначное число

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1320]
Ошибка в тесте на 100. Трехзначное положительное число называется "четно-красивым", если каждая из его цифр - четная.

1 - НЕ четное.

 @Test
    public void when100ThenYes() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task20.numCheck(100);
        String expected = "Да" + ln;
        assertThat(out.toString(), is(expected));
    }

**Comment by itfedorovsa** [comment]
Спасибо! Исправлено.
