### ISSUE TITLE
4. CompletableFuture

### ISSUE THREAD

**Issue by MrRocketR** [peterarsentev/job4j_features_bugs#1327]
public static void thenComposeExample() throws Exception {
CompletableFuture<Void> result = goToTrash().thenCompose(a -> buyProduct("Milk"));
result.get(); // wait calculations;
}

Idea подчеркивает a.

Плюс по тексту в некоторых местах встречается ComputableFuture вместо CompletableFuture.

**Comment by itfedorovsa** [comment]
Спасибо! Исправлено.
