### ISSUE TITLE
https://job4j.ru/profile/exercise/13/task-view/65

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1330]
При запуске теста выходят ошибки, связанные с кодировкой.
Может заменить на латиницу rsl и expected?

Или надо в уроке прописать, что нужно настроить, чтобы не выходила эта ошибка
![Снимок](https://user-images.githubusercontent.com/106574154/194403575-21ece9b4-c195-4936-a5ee-02cf9a62b2a5.PNG)

**Comment by staskorobeynikov** [comment]
переписал на английский текст
