### ISSUE TITLE
https://job4j.ru/profile/topics/13/task_code/306/138289

### ISSUE THREAD

**Issue by kirillkrohmal** [peterarsentev/job4j_features_bugs#1331]
Возникает ошибка при данном условии в тесте:

@Test
    public void when6Then0() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task30.numModify(6);
        String expected = "0" + ln;
        assertThat(out.toString(), is(expected));
    }

**Comment by itfedorovsa** [comment]
Решил это упражнение, у меня проблем не возникло. Возможно, Вы неправильно прочитали условие или допустили ошибку в коде. Все числа, кроме отрицательных, должны становиться нулем. Отрицательные числа должны становиться положительными. Закрываю обращение.
