### ISSUE TITLE
Дублирование информации

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1333]
Не знаю, может быть так и задумано, но наблюдаю
частичное дублирование информации в занятиях.
Возможно имеет смысл удалить дублирование 
и перераспределить (или добавить) блоки информации
по теме. Тема тестирования интересная
 
 
https://job4j.ru/profile/exercise/12/task-view/959 
6. DSL c AssertJ [#504879]

и 

https://job4j.ru/profile/exercise/192/task/961/344796
Подключение библиотеки AssertJ [#504881 #344796]

**Comment by staskorobeynikov** [comment]
Так и задумано. На стажере просто используем готовое, там все тесты на JUnit5. А на джуниоре уже небольшое погружение в тонкости.
Закрываю.
