### ISSUE TITLE
2. Тестовое задание - проект "Pooh JMS"

### ISSUE THREAD

**Issue by MrRocketR** [peterarsentev/job4j_features_bugs#1339]
Вот здесь опечатка:
 ConcurrentHashMap> queue = new ConcurrentHashMap<>();
Должно видимо быть:
ConcurrentHashMap<String, ConcurrentLinkedQueue> queue = new ConcurrentHashMap<>();
И var text = queue.get(name, emptyQueue()).poll();
Непонятно, что такое emptyQueue.

**Comment by itfedorovsa** [comment]
Исправлено. Спасибо!
