### ISSUE TITLE
7. Scanner [#504791]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1341]
https://job4j.ru/profile/exercise/45/task-view/786
Цитата
"
Пример #1
Пусть надо из потока данных вычленить только числа
"

Если вместо 5 подставить букву B, то на выходе получаются числа 
от 1 до 4 и далее вывод прерывается.
Таким образом не получается фильтрации всего списка

Возможно нужно изменить формулировку утверждения,
или подправить пример, если это возможно.

**Comment by itfedorovsa** [comment]
Спасибо, исправил! Поправил код, чтобы выводил все числа из потока, как в условии.
