### ISSUE TITLE
1. Log4j. Логирование системы. [#95335 #3971]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1344]
Я заметил, что файл *.properties имеет очень странную кодировку ISO-8859-1
и поэтому неадекватно относится к русскому языку. 

Чтобы файл настроек адекватно относился к русскому языку
я изменил кодировку файлов *.properties
Для этого я изменил следующую настройку:
File - Settings - Editor - File Encodings
Default encoding for properties files:
Было: Properties Default: ISO-8859-1
Стало: UTF-8

Предложил бы добавить эту информацию для работы с файлами
*.properties

**Comment by itfedorovsa** [comment]
Внес эту полезную информацию в этот урок. https://job4j.ru/profile/exercise/45/task/310/310752 Спасибо!
