### ISSUE TITLE
5.2. Создать программу, вычисляющую факториал. https://job4j.ru/profile/exercise/14/task-view/75

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1349]
В каркасе int result = 0;
Но правильно int result = 1; 
Разве нет? Или так задумано, что ученик сам должен дойти до этого?

**Comment by itfedorovsa** [comment]
Чтобы работать с переменной, нужно ее инициализировать. Так как это каркас, установлено пустое значение, то есть 0. А по ходу решения задачи Вы уже вносите изменения. Если в каркасе сразу туда 1 поставить, то получится, что часть задачи уже решена. Закрываю.
