### ISSUE TITLE
Интерфейс в ночном режиме

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#135]
Восприятие субъективное, но: при включённом ночном режиме ядерный белый на большую часть экрана, и плохо различимый чёрный на тёмном фоне текст условия задачи. Больно и плохо различимо.
![Screenshot_3](https://user-images.githubusercontent.com/75887570/101987616-0d9ce580-3cb7-11eb-97da-6236778892ba.png)

**Comment by peterarsentev** [comment]
Темного интерфейса больше не будет.
