### ISSUE TITLE
поправить импорты в классе и тест

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1350]
в задании https://job4j.ru/profile/exercise/64/task-view/383
в классе теста **ReportEngineTest** не верные импорты и ошибка в коде
![image](https://user-images.githubusercontent.com/13130875/195978441-393b23a0-0401-4ef5-b23e-2a610212a5a1.png)

Вот верные:

import org.junit.jupiter.api.Test;

import java.util.Calendar;

import static org.assertj.core.api.Assertions.*;
import static ru.job4j.ood.srp.ReportEngine.DATE_FORMAT;

**Comment by AlexeySapsay** [comment]
еще ошибка в названии ассерта
![image](https://user-images.githubusercontent.com/13130875/195978482-4019521d-7474-4c2c-a7ba-762932f9b2f8.png)

**Comment by AlexeySapsay** [comment]
![image](https://user-images.githubusercontent.com/13130875/195978738-58adea0a-2dac-45ed-b4cc-74373a95a5f0.png)
 Не понятно как это изобразить отчет с помощью строк. Если у меня возник вопрос, вероятно он возникнет и у других. Можно добавить пример, изображения отчета строками

**Comment by AlexeySapsay** [comment]
ошибка в коде
![image](https://user-images.githubusercontent.com/13130875/195991196-a0902aac-a8ff-498b-8100-83654e58e350.png)


добавить дженерик


![image](https://user-images.githubusercontent.com/13130875/195991163-7b0b09da-d70b-42a2-ac6f-4069c5dbeb65.png)

**Comment by itfedorovsa** [comment]
Исправлено. Спасибо!
