### ISSUE TITLE
7.0. Горячие клавиши IDEA [#504903] значимая некорректность информации.

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#1361]
`- Ctrl + Shift + Z. Повторяет действие после отката. Например, вы отменили действие, которое сделали, и поняли, что его нужно вернуть. Чтобы это сделать, используйте Ctrl + Shift + Z. Каждое нажатие повторит вперёд одно действие. То есть если вы откатили 2 операции, то вернуть их вперед также можно будет 2 раза.  `

Тут речь явно о ctrl+Y, по крайней мере на виндовсах до 10 и всяких офисных пакетах это традиционные антагонисты  - сочетания crtl Z/Y.
Указанное в тексте сочетание Ctrl + Shift + Z вообще ничего видимого не даёт. 

`- Ctrl + Y. Удаляет строку, на которой находится курсор, целиком. `
Очевидно не работает. 

Вообще в сети есть какие-то споры и петиции чтобы ЖетБрэйнс привели свои клавиши в соответствие с Виндоус, что они, подозреваю, и сделали.

**Comment by SamisheUN** [comment]
https://www.jetbrains.com/help/rider/Reference_Keyboard_Shortcuts_Index.html#manage_projects

Тут так-же ктрлY указано как redo.

**Comment by itfedorovsa** [comment]
Вы привели пример из шорткатов Visual Studio. Мы работаем в Intellij. 
https://www.jetbrains.com/help/rider/Keymaps_Comparison_Windows.html?keymap=secondary_intellij#basic_editing
Здесь в колонке для Intellij IDEA шорткаты именно такие, как в уроке. Всю жизнь пользуюсь undo/redo через Ctrl + Z / Ctrl + Shift + Z и в виндоус, и в офисных пакетах. В том числе и в IntelliJ IDEA. Может у Вас другая локализация винды или сторонних программ, отличная от рф? Название IDE именно Intellij IDEA?

**Comment by itfedorovsa** [comment]
Добрый вечер! Вы привели шорткаты из Rider. Мы работаем в Intellij IDEA.
https://www.jetbrains.com/help/idea/reference-keymap-win-default.html#basic_editing
Всю жизнь пользуюсь undo/redo через Ctrl + Z / Ctrl + Shift + Z и в виндоус, и в офисных пакетах. В том числе и в IntelliJ IDEA. В официальной документации шорткаты такие же, как в уроке. Пока не имею представления, почему у вас они поменяны местами.

**Comment by SamisheUN** [comment]
Закрывайте тогда.
