### ISSUE TITLE
Не прописан каркас класса.

### ISSUE THREAD

**Issue by Solalexus** [peterarsentev/job4j_features_bugs#1365]
В уроке 6.6.4. Двухмерный массив. Таблица умножения. [#33491] отсутствует каркас класса.
![2022-10-28_15-13-42](https://user-images.githubusercontent.com/115551286/198585210-e1441916-01b8-4f65-bb31-ba1d4ffa4bbf.png)

**Comment by peterarsentev** [comment]
Спасибо. Поправил.
