### ISSUE TITLE
4.1.3. Блок-схемы [#313435] Предложение

### ISSUE THREAD

**Issue by Burlakov03** [peterarsentev/job4j_features_bugs#1366]
Использовать другой построитель блок схем https://programforyou.ru/block-diagram-redactor . Здесь по госту

**Comment by peterarsentev** [comment]
Спасибо. Я в целом не ожидаю от ученик, что они будут рисовать схемы по госту. 
Индустрия разработки движется быстро и эти госты просто не нужны.
