### ISSUE TITLE
14. Вывод на консоль надписи "H-e-l-l-o-,-f-r-i-e-n-d!"  малозначительная недоговорка в условии.

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#1367]
В задании указано просто вывести надпись, но при выводе через print**ln**

Expected: is "H-e-l-l-o-,-f-r-i-e-n-d!"
     but: was "H-e-l-l-o-,-f-r-i-e-n-d!\n"
     
    тест написан таким образом, что проверят именно print, таким образом стоило бы упомянуть что надпись нужно вывести без перевода указателя на новую строку.
    
  Поясню:
    Например в задании 12. Вывод Ping Pong на консоль по условию нужно вывести две строки, и тест принимает именно комбинацию с окончанием на переход строки. Хотя об этом нет ни слова в описании.

**Comment by itfedorovsa** [comment]
Спасибо, дополнил условие задачи! Закрываю.
