### ISSUE TITLE
3. Liquibase. Интеграционные тесты. [#504894]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1370]
Не очень понятно, зачем мы 2 раза используем настройки базы H2
Возможно имеет смысл оставить какие-то одни настройки
<img width="661" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/199356470-53363569-79a9-4271-91f2-5ef9afa41ace.png">
-------
<img width="669" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/199356477-5c9d960d-92f4-40ee-9575-10ddf1782619.png">

**Comment by itfedorovsa** [comment]
Файлы настроек перенесены в папку db, где они и должны быть. Спасибо, закрываю.
