### ISSUE TITLE
Не удаляются сообщения

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1372]
Давно созданные сообщения не удаляются.
Может быть так и запрограммировано, а может и глюк.
<img width="790" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/199613680-cc20548c-7ec3-411d-8731-86a71c25b1b4.png">

**Comment by itfedorovsa** [comment]
Спасибо! Данный функционал временно убран для доработки. Закрываю.
