### ISSUE TITLE
Job4j Уроки 3.2.7. Авторизация и аутентификация 2. HttpSession

### ISSUE THREAD

**Issue by MrRocketR** [peterarsentev/job4j_features_bugs#1373]
Вот в этом уроке: 3.2.7. Авторизация и аутентификация 1. Страница login.html  по тексту идет:

Optional<User> userDb = userService.findUserByEmailAndPassword

А тут Уроки 3.2.7. Авторизация и аутентификация 2. HttpSession по тексту будет:
 Optional<User> userDb = userService.findUserByEmailAndPwd

**Comment by itfedorovsa** [comment]
Спасибо, исправил!
