### ISSUE TITLE
Ошибка в тесте.

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#1374]
Добрый вечер. Может у меня уже глаз замылился, но здесь же в последнем тесте 111, а не 11 должно быть?
https://job4j.ru/profile/topics/13/task_code/330/new_task

**Comment by itfedorovsa** [comment]
Добрый. Нет, должно быть 11, так как в числе 100 мы 1 уменьшаем на 1, а 0 увеличиваем на 1. Получаем 011. 0 в начале числа сокращается, получаем 11. Спасибо, закрываю.
