### ISSUE TITLE
1. Что такое клиент - серверное приложение. [#504837 #289958]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1375]
https://job4j.ru/profile/exercise/182/task/917/289958

Возможно вначале разговора о сборках Спринг следует упомянуть 
или сделать отдельный урок про Spring Initializer
https://start.spring.io/
как начальную точку сборки Spring приложений,
Преимущества использования этого инструмента в том 
(как я понимаю), что через этот сборщик мы не 
должны получить ошибки между разными версиями 
библиотек (как некая страховка)

**Comment by peterarsentev** [comment]
Описание сервиса start.spring.io добавили в новый раздел Spring boot. 
В блоке веб про это пока не нужно знать.
