### ISSUE TITLE
Ошибка в тесте.

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#1376]
Добрый день.
Ошибка в тесте 4.
Не может быть треугольника со сторонами 2, 2, 4. Это прямая)
https://job4j.ru/profile/topics/13/task_code/332/new_task

**Comment by itfedorovsa** [comment]
На текущий момент уже было мной исправлено ранее по комментарию под уроком. Спасибо! Закрываю.
