### ISSUE TITLE
Лишние переменные в каркасе https://job4j.ru/profile/exercise/2/task-view/101

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1377]
int lastIndex = ...;
            int currentIndex = ...;

Эти переменные лишние.
Задача решается без них.

**Comment by itfedorovsa** [comment]
Данные переменные помогают "более явно" решать задачу. У всех учеников разный уровень, и сразу собрать выражение без вспомогательных переменных некоторым может быть трудно. А особенно на начальных стадиях эти переменные помогают лучше понимать "что к чему". Спасибо, закрываю.
