### ISSUE TITLE
Ошибка в тестах управжнения

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#1380]
В первых трех тестах ожидаемое число не соответствует реальному числу разных цифр а числе.
Четвертый тест - ок.
https://job4j.ru/profile/topics/13/task_code/353/new_task

**Comment by itfedorovsa** [comment]
На текущий момент все тесты корректные. Возможно, уже было отредактировано ранее. Спасибо! Закрываю.
