### ISSUE TITLE
форматирование кода

### ISSUE THREAD

**Issue by redgad13** [peterarsentev/job4j_features_bugs#1382]
В лекции про CI BOTa, ну или еще где-то, я бы добавил фразу про горячие клавиши:
ctrl + alt + L
чтобы ускорить процесс и закрыть хотя бы часть требований бота)

**Comment by itfedorovsa** [comment]
CI Bot проверяет саму сборку проекта + некоторые правила. Большинство этих правил прописано в Checkstyle, который проверяет оформление кода. По Checkstyle урок идет вскоре после CI бота https://job4j.ru/profile/exercise/1/task-view/36. Урок по горячим клавишам IDEA есть в разделе Массивы https://job4j.ru/profile/exercise/2/task-view/983. Обращение закрываю. Спасибо.
