### ISSUE TITLE
4. Формы. Загрузка файла на сервер. [#504855]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1384]
https://job4j.ru/profile/exercise/186/task-view/935

Не очень понятно какую роль здесь играет перечисление импортов,
возможно оно здесь случайно

<img width="671" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/200915204-fb570035-f701-48eb-89ef-59d9988be03c.png">

**Comment by itfedorovsa** [comment]
В этом уроке даётся достаточно сложный незнакомый код, где сразу много новых классов используется, поэтому дан список импортов, чтобы избежать проблем с возможным подтягиванием учеником других классов с таким именем вместо нужного. Разобраться с ошибками потом будет сложно, если не тот импорт подтянуть. Спасибо, закрываю.
