### ISSUE TITLE
6.7.4. Выигрышные комбинации в сокобан [#53859]

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1386]
https://job4j.ru/profile/exercise/2/task-view/115 

Считаю нужно добавить ещё 1 тест в это задание, тк можно написать программу, которая просто будет проверять наличие 'X' в диагонали и все текущие тесты будут проходить.
Иначе говоря, нужен тест с 'X' в диагонали и результатом isFalse.
Пример теста:
   public void whenDataNotMonoByFalseThenFalse() {
        char[][] input = {
                {' ', ' ', ' ', ' ', ' '},
                {' ', ' ', ' ', ' ', ' '},
                {'X', ' ', 'X', 'X', 'X'},
                {' ', ' ', 'X', ' ', ' '},
                {' ', ' ', 'X', ' ', ' '},
        };
        boolean result = MatrixCheck.isWin(input);
        assertThat(result).isFalse();
    }

**Comment by itfedorovsa** [comment]
Саму сетку, видимо, Вы неправильно дали, но из текста понял, что нужен тест, дающий false на совпадение X по диагонали. Проверил, добавил. Спасибо! Закрываю.
