### ISSUE TITLE
Урок Интерфейс Collection [#504820 #257920]

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1388]
![image](https://user-images.githubusercontent.com/114805887/201470226-38303ba4-7719-40b6-ba6d-3ad5ab7920e5.png)
поэтому все объекты коллекций можно перебирать в так называемом улучшенном цикле for или в цикле for-each.
Опечатка?

**Comment by itfedorovsa** [comment]
Подскажите, в чем именно здесь опечатка?

**Comment by ghost** [comment]
улучшенный цикл for или for-each, это же одно и тоже

**Comment by itfedorovsa** [comment]
Тут имелось в виду название этого цикла. Улучшенный for или (по-другому) for-each. Изменил эту строку, чтобы не было недопониманий. Спасибо, закрываю.
