### ISSUE TITLE
2. Liquibase. Добавление новых скриптов. [#504893 #357421]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1389]
https://job4j.ru/profile/exercise/194/task/973/357421
Мне кажется в урок нужно обязательно добавить "спасательный круг".
Вася ученик, начинающий, он может (и допустит) ошибку.

Что делать, если он все-таки неправильно выполнил задачу и случайно получил
ошибку от liquibase:update - change sets check sum
(в уроке только написано, как делать правильно)

Можно ли подправить цепочку всех скриптов и сделать подсчет сумм
заново?

Возможно, если я правильно понимаю ситуацию, одно из решений,
это набрать в терминале (или выбрать в меню)
mvn liquibase:clearCheckSums

**Comment by itfedorovsa** [comment]
Спасибо, добавил!
