### ISSUE TITLE
Ошибка в описании задачи

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1390]
Опечатка в слове составить - оставить
![image](https://user-images.githubusercontent.com/114805887/201907267-ada2bf11-1535-4ebc-a511-13f31235d07d.png)

**Comment by itfedorovsa** [comment]
Здесь нет опечатки. Задание - удалить дубликаты, то есть "оставить" уникальные номера задач. Закрываю.
