### ISSUE TITLE
Ошибка в коде. Уровень стажер /1.2.5. Исключения/0.5. Иерархия исключений и множественный catch.

### ISSUE THREAD

**Issue by alshevskiy** [peterarsentev/job4j_features_bugs#1392]
<img width="754" alt="Снимок экрана 2022-11-17 в 10 48 49" src="https://user-images.githubusercontent.com/111909057/202431005-d720dcb3-bbf9-420b-add2-60e9d304155b.png">

Не хватает " ; "

**Comment by itfedorovsa** [comment]
Спасибо, исправлено! Закрываю.
