### ISSUE TITLE
Задание https://job4j.ru/profile/exercise/33/task-view/238

### ISSUE THREAD

**Issue by GHMember** [peterarsentev/job4j_features_bugs#1393]
Опечатка в аргументах интерфейсов Function от которых расширяются интерфейсы UnaryOperator и BinaryOperator:
"@FunctionalInterface
public interface UnaryOperator<T> extends Function<T, T> {}
@FunctionalInterface
public interface BinaryOperator<T> extends BiFunction<T,T,T> {}"

Должно быть: 
"@FunctionalInterface
public interface UnaryOperator<T> extends Function<T, R> {}"
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/Function.html

"@FunctionalInterface
public interface BinaryOperator<T> extends BiFunction<T,U,R> {}"
https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/function/BiFunction.html

**Comment by itfedorovsa** [comment]
Здесь нет опечатки. Вы предоставили документацию к интерфейсам Function и BiFunction, а пишете про UnaryOperator и BinaryOperator. Последние принимают и возвращают один и тот же тип, поэтому <T,T> и <T,T,T>. Закрываю.
https://docs.oracle.com/javase/8/docs/api/java/util/function/UnaryOperator.html
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/function/BinaryOperator.html
