### ISSUE TITLE
1. Stack, Heap, Metaspace [#504932]

### ISSUE THREAD

**Issue by vechkitov** [peterarsentev/job4j_features_bugs#1397]
Урок: [1. Stack, Heap, Metaspace [#504932]](https://job4j.ru/profile/exercise/58/task/1012/361828)
1) В стеке для метода main() еще будет переменная args, ссылающаяся на объект String[] в Heap'е.
![image](https://user-images.githubusercontent.com/47697448/202731950-e1e83957-d6f2-4d18-9d10-cf881c0ff209.png)

2) В стеке для метода action() еще будет переменная this, ссылающаяся на объект Example в Heap'е.
![image](https://user-images.githubusercontent.com/47697448/202732688-32d69273-1b52-4771-a597-e520973c947a.png)

**Comment by itfedorovsa** [comment]
Спасибо! Уже было добавлено ранее по Вашему комментарию к уроку. Закрываю.
