### ISSUE TITLE
3.3.2. Конфигурирование 2. HQL

### ISSUE THREAD

**Issue by MrRocketR** [peterarsentev/job4j_features_bugs#1402]
public static void insert(Session session) {
        try {
            session.beginTransaction();
            session.createQuery(
                            "INSERT INTO Item (name) VALUES (:fName)")
                    .setParameter("fName", "new name")
                    .executeUpdate();
            session.getTransaction().commit();
        } catch (Exception e) {
            session.getTransaction().rollback();
        }
    }

Падает с ошибкой   org.hibernate.hql.internal.ast.ErrorTracker reportError

ERROR: line 1:39: expecting EOF, found ')'

**Comment by itfedorovsa** [comment]
Спасибо! Раздел Insert в этом уроке был переписан (исправлен на актуальное решение). Закрываю.
