### ISSUE TITLE
Инструменты [#504887 #344774]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1403]
https://job4j.ru/profile/exercise/192/task-view/967
Уже не первый раз сталкиваюсь с вопросом о том,
что некоторые ученики не очень понимают где правильно создавать 
.gitignore и это выливается в кучу ненужных файлов в комите

Предложил бы дополнить 4 пункт.
Было
"4. Т.к. по умолчанию git индексирует все файлы, а нам нужны лишь те, что относятся к нашему репозиторию и не зависят от нашего окружения, поэтому создаем файл .gitignore"

Стало (как-то так)
4. Т.к. по умолчанию git индексирует все файлы, а нам нужны лишь те, что относятся к нашему репозиторию и не зависят от нашего окружения, поэтому создаем файл .gitignore  **обязательно в корне проекта** - в папке job4j_design, рядом с pom.xml

**Comment by itfedorovsa** [comment]
Спасибо, добавил! Закрываю.
