### ISSUE TITLE
Job4j Уроки 1.4.4. Контрольные вопросы 2. Аттестация

### ISSUE THREAD

**Issue by EgorMoroshkin** [peterarsentev/job4j_features_bugs#1407]
В 4 и 5 методе в задании перепутаны методы которые предлагается использовать
`4. **Метод bestStudent()** - для реализации данного метода можно использовать **метод averageScoreBySubjec**t за исключением следующих особенностей:

- в данном методе мы рассчитываем суммарный балл, а не средний - поэтому вместо average() нужно использовать метод sum();

- терминальной операцией будет не метод collect(), а использование метода max(), в который будем передавать компаратор. При этом компаратор определит объект Tuple, у которого значение Score будет максимальным;

- orElse() для того чтобы вернуть значение по умолчанию.

5. **Метод bestSubject()** - для реализации данного метода можно использовать **метод averageScoreByPupil** за исключением следующих особенностей:`

**Comment by staskorobeynikov** [comment]
В чем путаница?

**Comment by staskorobeynikov** [comment]
В чем путаница?

**Comment by itfedorovsa** [comment]
Я уже отредактировал этот урок ранее по обращению в комментарии к уроку. Спасибо! Закрываю.
