### ISSUE TITLE
Юзабилити. Прогресс 100% другим цветом

### ISSUE THREAD

**Issue by enovoselovhi** [peterarsentev/job4j_features_bugs#1408]
Прошу выделить другим цветом прогресс бар который пройден на 100%, например отлично подойдет зеленый цвет
![изображение](https://user-images.githubusercontent.com/3658587/203543973-8088039f-dcae-40cb-8481-b3e5899b84da.png)

**Comment by peterarsentev** [comment]
Сделали. Спасибо.
