### ISSUE TITLE
Тест Lambda и Stream API

### ISSUE THREAD

**Issue by igor-grigoriev** [peterarsentev/job4j_features_bugs#1409]
После прохождения теста выдается такой результат
![Результат](https://user-images.githubusercontent.com/108431961/203789073-43758acf-df01-4dbf-bb80-b6512f6c1801.png)
5. Какие функциональные интерфейсы из пакета java.util.function поддерживают функции высшего порядка?
    Ответ: Consumer, Function, Predicate, Supplier, Пишет неправильный ответ.
11. Расскажите, какой шаблон проектирования используется внутри Stream API?
    Ответ: Pupeline, Decorator, Builder, Strategy. Пишет неправильный ответ.
    Если выбрать только Builder тоже пишет неправильный ответ.
18. Возможно ли прервать выполнение потока по аналогии с break?
    Ответ: dropWhile, takeWhile. Пишет неправильный ответ.
19. Возможно ли пропустить элемент потока по аналогии с continue?
    Ответ: skip, filter. Пишет неправильный ответ.

**Comment by itfedorovsa** [comment]
5. Исправил. Все варианты являются правильным ответом.
11. Исправил. Помимо этих четырех, там еще шаблон Фабричный метод применяется. Добавил в варианты. Итого все варианты правильные.
18. Правильный ответ takeWhile - "Брать, пока условие истинно, остальное отсеять". А dropWhile это отсеивать, пока условие истинно, это не подходит под работу оператора break.
19. То же самое. Continue - пропуск одной итерации. Правильный ответ - filter, он пропускает или не пропускает, проверяя каждый элемент. skip не подходит под continue, так как пропускает 1 и более элементов.
Спасибо, закрываю!

**Comment by GitHubfilipich** [comment]
Обнаружил несответствия ответов материалам курса и документации:
1) Вопрос: Для чего используется ключевое слово var?
Ответы "Такого ключевого слова нет в Java." и "Так можно именовать переменные" указаны как неправильные, хотя в уроке [1.4.3. Улучшенное Java API 2. Local-Variable Type Inference](https://job4j.ru/profile/exercise/35/task-view/262) дословно написано: "var не является ключевым словом согласно спецификации языка", "var можно использовать в качестве имени переменной".
2) Вопрос: Какие функциональные интерфейсы из пакета java.util.function поддерживают функции высшего порядка?
Указан как правильный ответ "Supplier метод Supplier and(Supplier other) " - при этом в описании интерфейса [Supplier](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/function/Supplier.html) нет метода **and**.
3) Вопрос: Что делает метод map?
а) Указан как неправильный ответ "Преобразовывает элемент потока в пару ключ-значения. Используется для HashMap." - вот пример такого функционала:
.map(integer -> {
                    var hashMap = new HashMap<Integer, Integer>();
                    hashMap.put(Integer.valueOf(integer), Integer.valueOf(integer));
                    return hashMap.entrySet().stream().findFirst();
                })
б) Указан как неправильный ответ "Преобразовывает один элемент в потоке в другой поток." - вот пример такого функционала:
.map(value -> Stream.of(value.toString()))
4) Вопрос "Что делает метод flatMap?"
Указан как правильный ответ "Преобразовывает элемент потока в другой поток" - считаю это некорректным ответом, поскольку преобразование элемента в поток выполняет указанная в методе flatMap функция, а сам метод flatMap уже проебразовывает этот поток в возвращаемый поток элементов (а не потоков).
