### ISSUE TITLE
[New feature] Copy summary button

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1410]
Т.к практически в каждом занятии, мы копируем заголовок урока и вставляем его в виде комментария при коммите, то было бы здорово иметь отдельную кнопку, которая позволит по нажатия скопировать заголовок урока в буфер обмена и по ctrl + v его было бы удобно вставить в сообщение коммита.
Исключительно вопрос удобства, но кажется этой фичей пользовался бы каждый студент на курсе.

**Comment by peterarsentev** [comment]
Спасибо. Добавили.
