### ISSUE TITLE
2.2. Функциональный интерфейс [#247497 #266703]

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1413]
- в интерфейсе можно добавлять статические и методы с реализацией по умолчанию (помечаются ключевым словом default). Так вот в функциональном методе таких методов может быть сколько угодно. Такие методы уже будут содержать реализацию;

Должно быть : Так вот в функциональном интерфейсе таких методов?

**Comment by staskorobeynikov** [comment]
Исправлено
