### ISSUE TITLE
Опечатка - "WANR", должно быть "WARN"

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1418]
"Обратите внимание, что Threshold для приемника CONSOLE_LOG выставлен на уровень **[WANR]([url](url))**, а для FILE_LOG на уровень DEBUG,"

[](https://job4j.ru/profile/exercise/47/task-view/956
)

![Uploading image.png…]()

**Comment by itfedorovsa** [comment]
Спасибо, исправил!
