### ISSUE TITLE
Ошибка в названии пути. 

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1419]
Полагаю, что "io" здесь лишнее.
package ru.job4j.**io**.serialization.xml;

![image](https://user-images.githubusercontent.com/106254908/205855359-16e82e8f-d023-4a1f-9e17-0572e72813a2.png)

https://job4j.ru/profile/exercise/174/task-view/328

**Comment by itfedorovsa** [comment]
Исправил, спасибо!
