### ISSUE TITLE
1. Произвести автоматическое тестирование всех сервлетов.[2518#357478]

### ISSUE THREAD

**Issue by VladimirGladkilh** [peterarsentev/job4j_features_bugs#142]
В задании упоминается класс ValidateService, но в ходе работы над проектом он не создавался.
Есть ощущение что "структура поехала" т.к. мы имеем один класс для работы с БД, который явно перегружен однотипными методами со схожим функционалом, но с разными классами.

**Comment by ShamRail** [comment]
Задание переписано.
