### ISSUE TITLE
Усовершенствование упражнений в Java Core

### ISSUE THREAD

**Issue by Burlakov03** [peterarsentev/job4j_features_bugs#1423]
Было бы круто когда ты решишь задачу что бы было оптимальное решение от руководства, что бы можно было посмотреть на какие то недочеты в своем коде, просмотр других тоже помогает, но каждый во что горазд и не понятно какой более оптимальный для данной задачи, ввиду своего не достаточного уровня мастерства.

**Comment by peterarsentev** [comment]
@Burlakov03 А можешь скинуть ссылку на упражнение, где тебе хотелось бы посмотреть идеальное решение? Спрашиваю, потому что упражнения - это отработка синтаксиса языка, где нет оптимизации по алгоритму написать или дизайну приложения.

**Comment by Burlakov03** [comment]
https://job4j.ru/profile/topics/29/task_code/161/146232. Не я просто посмотрел как Коробейников решил и подумал что круто получилось и его вариант более лучший моего первоначального. "Спрашиваю, потому что упражнения - это отработка синтаксиса языка, где нет оптимизации по алгоритму написать или дизайну " - наверное да просто думаю что для каждой задачи есть более менее лучшее решение, ну или как вариант просматривать все решения, просто там не поймешь кто по уровню какой.

**Comment by peterarsentev** [comment]
Я понял. Мы к решениям добавим рейтинги и обсуждения. Это даст возможность посмотреть решения с высоким рейтингом и обсудить их. 
Так же планируем добавить возможность отправить  свое решение на проверку другим ученикам.
