### ISSUE TITLE
Категории: Стажер, Джуниор, Мидл

### ISSUE THREAD

**Issue by newNano** [peterarsentev/job4j_features_bugs#1425]
Если можно - верните, пожалуйста, предыдущее отображение заданий по категориям при их выборе.
Т.е чтобы при выборе одной из трех категорий отображались задания только этой конкретной категории и не больше.

**Comment by peterarsentev** [comment]
![image](https://user-images.githubusercontent.com/694978/210747913-11ab2cb5-6adb-41cb-bb7c-9d6d7a262a25.png)
@newNano У тебя не работает?

**Comment by peterarsentev** [comment]
Вернули. Спасибо.
