### ISSUE TITLE
Отсутсвуют варианты ответов после прохождения тестовых экзаменов

### ISSUE THREAD

**Issue by IvanM13th** [peterarsentev/job4j_features_bugs#1426]
Предлагаю добавить варианты ответов и выбранный пользователь вариант без указания(или с указанием, тут на ваше усмотрение) правильного ответа, тк вопросов много и можно даже не вспомнить, какие варианты там предлагались.

![image](https://user-images.githubusercontent.com/114656684/207792783-cd269d5a-d498-4510-90af-64f8a15e8164.png)

**Comment by peterarsentev** [comment]
Спасибо. Добавим.

**Comment by peterarsentev** [comment]
Сделали. Закрываю.
