### ISSUE TITLE
Ошибка в названии раздела главы. 

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1427]
Дублируется название главы. Вместо дублирующего "Клиентские сокеты..." должно быть по идее "Серверные сокеты".

![image](https://user-images.githubusercontent.com/106254908/207841942-c692f67e-4a39-41c7-be91-e9b6fd6114f7.png)

[ссылка](https://job4j.ru/profile/exercise/49/task-view/331)

**Comment by itfedorovsa** [comment]
Спасибо, исправлено! Закрываю.
