### ISSUE TITLE
Орфографическая ошибка в слове "Логирование"

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1428]
[ссылка ](https://job4j.ru/profile/exercise/47/task/322/367706)

В слове "Логирование" должна быть единственная буква "Г". 

![image](https://user-images.githubusercontent.com/106254908/207893469-74a2da16-001a-4ded-90a7-8ee198775eba.png)

**Comment by itfedorovsa** [comment]
Спасибо, исправлено! Закрываю.
