### ISSUE TITLE
1.8. Состояние объекта [#167388 #372205] Стажёр

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1430]
В задаче мало теории и не объяснены некоторые моменты.
1. Не хватает схем, что от чего берется и куда ложится.
2. Действительно, про геттер и сеттер нужно написать в теории урока.
3. Не понятно как another.value = 0 обнуляет second.value. В моём обывательском понимании это 2 разных объекта и second.value должен оставаться равным 5. 
4. Надо написать, что обнуление second.value идёт вручную. Просто по условиям задачи, как будто идёт автоматическое обнуление. Например, в массивах, при записи значения из одной ячейки в другую через переменную, автоматически обнулялась одна ячейка, а тут вручную обнуляем.

**Comment by peterarsentev** [comment]
Поправили.
