### ISSUE TITLE
9.2. Математические операторы и составные операторы присваивания

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#1431]
Пункт внутри ссылается на следующим за ним пункт 9.3 !!

Ранее мы разбирали такое понятие как преобразование типов:

[Ссылка](https://job4j.ru/profile/exercise/6/task-view/37)

просьба не забывать об этом, потому что при выполнении математических операций это также важно. Советуем еще раз освежить это в памяти.

**Comment by itfedorovsa** [comment]
На текущий момент данная информация находится в уроке 9.3 и ссылается на 9.2. Возможно, уже было исправлено ранее. Спасибо! Закрываю.
