### ISSUE TITLE
Нет верного ответа в экзаменационном билете "Базовый синтаксис Java"

### ISSUE THREAD

**Issue by Futsey** [peterarsentev/job4j_features_bugs#1432]
Здравствуйте. Не хочу быть занудой, но в глаза бросилось.
В одном из вопросов отсутствует верный вариант ответа. В указанном варианте мы должны получить Dog Kotov, однако строка System.out.println(name); в методе main() не позволит нам сделать это и мы фактически получим:
Dog
Kotov
Выходит. чтобы привести код к варианту ответа нам необходимо использовать вместо println просто print + либо пробел, либо исправить правильный вариант на DogKotov.
Скрин задачи:
![Безымянный](https://user-images.githubusercontent.com/89212538/208300581-a3765dd3-4b7e-40aa-841b-855b156e8231.png)

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
