### ISSUE TITLE
Опечатка 1.1.1 - 3.4 Первая программа

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1437]
https://job4j.ru/profile/exercise/1/task/805/373509

![typo 1](https://user-images.githubusercontent.com/67908722/209413347-a3234412-6e12-4f16-b50a-823ab9ef6025.png)

![typo 1 2](https://user-images.githubusercontent.com/67908722/209413350-44afaf48-7136-4d77-93ac-b7c59b13642e.png)

**Comment by itfedorovsa** [comment]
Исправлено, спасибо! Закрываю.
