### ISSUE TITLE
Опечатка 1.1.1 - 7. Правила написания кода.

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1438]
https://job4j.ru/profile/exercise/1/task/1015/373515

![typo 2](https://user-images.githubusercontent.com/67908722/209413459-6b0c94ae-465c-4760-9b03-1f42ebaa853e.png)

![typo 2 1](https://user-images.githubusercontent.com/67908722/209413461-2c7836a5-4734-4b6a-8049-250127c3c751.png)

**Comment by itfedorovsa** [comment]
Исправлено, спасибо! Закрываю.
