### ISSUE TITLE
Опечатка  1.2.4. Полиморфизм 1. Что такое полиморфизм. 

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1439]
https://job4j.ru/profile/exercise/23/task/164/373785

![typo 3](https://user-images.githubusercontent.com/67908722/209413589-07590a7e-2714-4eb8-b433-896099cf682f.png)

**Comment by itfedorovsa** [comment]
Исправлено, спасибо! Закрываю
