### ISSUE TITLE
Опечатка && - 1.1.4. Оператор ветвления 4.3.1. Сокращенный оператор && 

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1440]
https://job4j.ru/profile/exercise/13/task/59/374149

![typo 4](https://user-images.githubusercontent.com/67908722/209413625-6d24053f-a92c-445e-b6ec-825d97eb8be2.png)

![typo 4 1](https://user-images.githubusercontent.com/67908722/209413640-20a58549-19c5-46f0-ab0c-4c4c80746b22.png)

**Comment by itfedorovsa** [comment]
Исправлено, спасибо! Закрываю
