### ISSUE TITLE
Опечатка || - 1.1.4. Оператор ветвления 4.3.2. Сокращенный оператор || 

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1441]
https://job4j.ru/profile/exercise/13/task/60/374151

![typo 5](https://user-images.githubusercontent.com/67908722/209413661-622941df-df96-44a2-a9a3-bf11e1fc0871.png)

![typo 5 1](https://user-images.githubusercontent.com/67908722/209413679-7aade0f9-9425-40d0-b7bd-1554b4e28d57.png)

**Comment by itfedorovsa** [comment]
Исправлено, спасибо! Закрываю
