### ISSUE TITLE
Опечатка -  1.1.5. Циклы 5.5. Простое число 

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1443]
https://job4j.ru/profile/exercise/14/task/78/374370

![typo 6](https://user-images.githubusercontent.com/67908722/209451262-1e1c8487-7653-4775-85af-2e4ea9e78f0f.png)

**Comment by itfedorovsa** [comment]
Исправлено, спасибо! Закрываю
