### ISSUE TITLE
Некоторые вопросы по авторизации на курсе

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1445]
Работаю в Хроме последних версий для Windows 7
Ситуация такая, я в новой вкладке перехожу на адрес
https://job4j.ru/profile/login
и ввожу свои данные, вхожу, получаю доступ к урокам

Если я создам в браузере новую вкладку 
и снова перейду в ней по адресу
https://job4j.ru/profile/login
то мне снова придется вводить свои данные для получения доступа.
То есть программа меня "не узнает".
Это не страшно, но не очень удобно.
<img width="776" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/209638058-228817b9-8243-45dc-b438-3e9168d45cba.png">

**Comment by peterarsentev** [comment]
@yarmail Вообще это настройки браузера. У меня например, даже если закрывать браузер и потом его открывать повторно, то я буду авторизован в систему. 
У тебя настройки может какие есть?

**Comment by YarTsin** [comment]
@peterarsentev 
Да, возможно, я отключаю в браузере историю и что-то ещё, так что возможно это моя проблема. 
Думаю, если больше никто не жаловался, можно закрывать
