### ISSUE TITLE
Тестирование окна курса

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1446]
Посмотрел пару уроков по тестированию (на кой-то ляд)) и заметил вот что.
При уменьшении ширины рабочего окна до минимума пропадает
имя и фамилия ученика. Не знаю, это баг или фича?

<img width="648" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/209638868-45e869f5-37a5-4737-b76e-c5e074f8862b.png">

**Comment by peterarsentev** [comment]
Это поправили. Спасибо.
