### ISSUE TITLE
1. Побитовые операции [#504964]  прошу посмотреть задачу 2. 

### ISSUE THREAD

**Issue by SevaStopAll** [peterarsentev/job4j_features_bugs#1447]
В задаче 2. 
Даны два числа K, N. Необходимо вычислить арифметическое выражение вида:

K * 2^N, используя только битовые операции. (Здесь знак ^ означает степень числа).

Реализация:
Умножение числа на 2 в степени N эквивалентно сдвигу влево на N позиций.
K << N = 3 << 4 = 11 << 4 = **110000** (Вот здесь один ноль лишний) (2 ^ 6 + 2 ^ 5 = 96). 
Возможно, надо поправить, что **сдвигу влево на (N-1) позиций.**

**Comment by itfedorovsa** [comment]
В данном примере "11 << 4" было лишним, удалил. Непонятен Ваш расчёт 2 ^ 6 + 2 ^ 5 = 96. У нас формула K * 2^N, то есть 3 * 2^4. Получается при 3 << 4 число 3 (в битовом представлении) сдвигается влево 4 раза, что равно четырём умножениям на 2 (то же, что и 2^4). Получаем 110000 или 48. Проверить можно так:

![image](https://user-images.githubusercontent.com/101260971/211922045-3fad9ad5-cd4c-40d2-b82d-0e142c9f0fcb.png)

Спасибо, закрываю!
