### ISSUE TITLE
Опечатка. Раздел "0.1. Связи между таблицами [#373615 #375394]"

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1449]
Убрать лишнюю букву "t"
![image](https://user-images.githubusercontent.com/106254908/209820549-21ba8648-6994-4032-ab7b-ff90d17bde43.png)

[https://job4j.ru/profile/exercise/51/task-view/336](https://job4j.ru/profile/exercise/51/task-view/336)

**Comment by itfedorovsa** [comment]
На момент проверки уже исправлено. Спасибо! Закрываю.
