### ISSUE TITLE
5.1. Зона видимости переменных

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1451]
Вопрос по теории в данном разделе. Странно что у вас работает. У меня такое не работает. Может версия джавы другая или ошибка? IDEA не компилирует такой код.
![image](https://user-images.githubusercontent.com/67908722/210041898-d92df857-8103-46f9-8fc3-fbb2fe386114.png)

![image](https://user-images.githubusercontent.com/67908722/210041985-21fcbb45-cbeb-46e9-b3c4-59a855f0d735.png)

**Comment by itfedorovsa** [comment]
Так и не должно работать. Над этим примером написано, что это частный случай первой ситуации, где показывается пример, когда происходит ошибка компиляции. В вашем случае она же и происходит, так как 2 переменных в одной зоне видимости недопустимы. Возможно, Вас сбила с толку цифра 2 в следующем примере, но это уже другой пример, а Ваш пример относится всё еще к пункту 1. Закрываю.
