### ISSUE TITLE
Категория : 1.2. ООПТема : 1.2.5. Исключения -> 0.2. Кидаем исключение - throw new RuntimeException

### ISSUE THREAD

**Issue by RomansTelemost** [peterarsentev/job4j_features_bugs#1452]
Конечно же не бесконечно)
Все мы знаем что будет если
byte a = 127;
a++;
и вот а уже -128.

Просто система сделает круг. Большой. от 10 до ~2 147 000 000 и потом с - 2 147 000 000 до 2х
![image](https://user-images.githubusercontent.com/67908722/210114809-c03e6438-f587-4a74-9b92-b543792198a8.png)

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю.
