### ISSUE TITLE
6.7.1. Моно строка в матрице. [#214126 #377308]

### ISSUE THREAD

**Issue by SergeyDevStart** [peterarsentev/job4j_features_bugs#1456]
Разве из этого не следует, что если строка полностью пустая, то метод должен вернуть true? Или мы не рассматриваем варианты, когда строка полностью пустая?
![Screenshot_3](https://user-images.githubusercontent.com/120316055/210533465-f130ba26-3ce3-487a-a60c-0cbdc0125f91.png)

**Comment by staskorobeynikov** [comment]
уточнил информацию
Закрываю
