### ISSUE TITLE
1.8. Класс использующий сам себя [#167388 #328315]

### ISSUE THREAD

**Issue by MichaelZalogin** [peterarsentev/job4j_features_bugs#1457]
Опечатка по тексту. 
![image](https://user-images.githubusercontent.com/96498880/210651121-437fb68c-8186-4f36-9e38-34f2dbabbc72.png)
И далее по тексту встречаются неверные окончания слов и избыток знаков препинания.

**Comment by staskorobeynikov** [comment]
Поправил
Закрываю.
