### ISSUE TITLE
2. Интерфейс Deque [#504943]

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1459]
- pop() – позволяет удалить головной удалить из очереди и вернуть его. Если очередь пуста – будет сгенерировано исключение NoSuchElementException.
 Ошибка в описании метода.

**Comment by staskorobeynikov** [comment]
ссылка на документацию
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Deque.html#pop()
закрываю

**Comment by ghost** [comment]
pop() – позволяет удалить головной удалить
