### ISSUE TITLE
Нет условия в темном режиме.

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#146]
В тёмном режиме цвет текста такой же, как и цвет фона.
![Screenshot_4](https://user-images.githubusercontent.com/75887570/102026422-9010cc80-3dbf-11eb-996c-e97ba661b699.png)
![Screenshot_5](https://user-images.githubusercontent.com/75887570/102026424-9141f980-3dbf-11eb-8dfe-d7285d5fd765.png)
![Screenshot_6](https://user-images.githubusercontent.com/75887570/102026426-91da9000-3dbf-11eb-8aa7-f5582c320097.png)

**Comment by peterarsentev** [comment]
Темного интерфейса больше не будет.
