### ISSUE TITLE
Опечатка в тесте Базовый синтаксис.

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#1461]
Так можно создавать массив?
![1](https://user-images.githubusercontent.com/114805887/211046131-6b286b91-76d3-4c5e-8a3a-4f512aca0bee.JPG)
Оракл не рекомендует
![image](https://user-images.githubusercontent.com/114805887/211046687-470f7271-ad1f-4c33-a01f-920f68f98077.png)
Или я чересчур душен?

**Comment by itfedorovsa** [comment]
У нас в курсе тоже так не рекомендуется. Спасибо, отредактировано!
