### ISSUE TITLE
Ошибка в тесте Базовый синтаксис

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1462]
На вопрос Что из нижеперечисленного является кодировкой? Я каждый раз выбираю следующие варианты:
-windows-1251
-utf-8
-utf-16
И каждый раз получаю одну и ту же рекомендацию:

Что из нижеперечисленного является кодировкой?
Отметьте все варианты, являющиеся кодировкой.

Юникод кодировкой не является. Это таблица символов.

1.1.2. Типы данных 9.4. Символы в Java и их особенности

Java 9, Полное руководство - Герберт Шилдт. Глава 3 (Раздел "Символы").

Но я и не выбирал юникод, откуда эта ошибка берет свои ноги непонятно.

**Comment by itfedorovsa** [comment]
ASCII тоже кодировка. Дописал подробнее, что все остальные являются кодировками, кроме Юникода. https://ru.wikipedia.org/wiki/ASCII Закрываю
