### ISSUE TITLE
Ссылка не работает

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1466]
Ссылка [в уроке 2](https://job4j.ru/profile/exercise/179/task-view/811) в источнике 2 не работает.

![image](https://user-images.githubusercontent.com/106254908/211300921-8a29374d-c09b-4e73-8e52-e201976dc25f.png)

https://kb.objectrocket.com/postgresql/postgres-cursor-1487

**Comment by staskorobeynikov** [comment]
убрал
