### ISSUE TITLE
4. Перенос методов в Stream API [#279131 #208080]

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#1467]
Мне кажется что в тесте вместо assertThat(strings).containsAll(expected) нужно assertThat(strings).hasSameElementsAs(expected) потому что, если в генераторе убрать все filter  тест проходит . 
![image](https://user-images.githubusercontent.com/56088833/211372306-a498d74d-0f9d-463e-a5ab-557f4771a445.png)
![image](https://user-images.githubusercontent.com/56088833/211372360-f39f32eb-ec3e-424b-b6b1-853280c335d9.png)

**Comment by staskorobeynikov** [comment]
исправлено
