### ISSUE TITLE
Не точности в тексте урока "0. Монитор, мьютекс, критическая секция"

### ISSUE THREAD

**Issue by digest15** [peterarsentev/job4j_features_bugs#1469]
По статье:

Я понимаю что цель максмально просто и коротко объяснить понятия, но это только путает еще больше... Что такое монитор из статьи я вообще не понял...

_"Критическая секция - код внутри метода, обозначенного как synchronized. То есть это область памяти, с которой одновременно может работать только одна нить" .... "Синхронизация доступа к критической секции позволяет избежать "состояния гонки"_ - "Критическая секция" это уже защищенный кусок кода или это кусок кода нужнающийся в защите (от конкурентного доступа)?

_"При обращении к объекту нить получает его мьютекс, и, если он свободен, занимает критическую секцию, либо ждет, пока ее освободит другая нить, если мьютекс занят." ... "Если монитор захвачен - работа метода продолжается, а если нет, то нить останавливается и встает в очередь ожидания освобождения монитора."_ - так что нить захватывает: монитор, мютекс, поток?

_"Монитор в Java выполнен в виде ключевого слова synchronized." ... "Блок synchronized {} - это и есть критическая секция"_ - так монитор или критическая секция?

_"Монитор в Java выполнен в виде ключевого слова synchronized. При вызове non-static synchronized метода, он пытается захватить монитор объекта, у которого он вызван"_ - монитор пытается захватить монитор?

Мне кажеться нужно объясять понятия немного более "по взрослому". Например:

"Монитор" - от слова Мониторинг, это подход при котором проверяется состояние некоторого объекта, если он свободен доступ разрешен, если занят доступ запрещен. В java это реализовано авто генерацией такого кода в местах где указано ключевое слово synchronized с проверкой состояния Мютекса.

"Мютекс" - это название объекта имеющего два состояния занят/свободен, в java мютекс есть у каждого объекта и он не доступен для программиста.

"Критическая секция" - это защищенный кусок кода от конкурентного доступа.

А потом уже объяснить что объект на котором происходит блокировка принято так же называть монитором, что такое вход/выход из монитора и т.д.

**Comment by itfedorovsa** [comment]
Спасибо, внёс соответствующие правки! Закрываю.
