### ISSUE TITLE
Объекты нужно поменять на ссылки

### ISSUE THREAD

**Issue by Paronian** [peterarsentev/job4j_features_bugs#1473]
5.1. Зачем нужно приведение типов [#310019]
то мы выполняем повышающее приведение, т.е. в данном случае привели классы Dog и GuineaPig к более общему типу Animal, но при этом объекты dog и guineaPig ссылаются на объекты классов Dog и GuineaPig.

Думаю здесь нужно писать "...типу Animal, но при этом переменные или ссылки (а не объекты) dog и guineaPig ссылаются..."

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
