### ISSUE TITLE
Ошибки в экзамене, коллекции, Стажер

### ISSUE THREAD

**Issue by SiuSpacecowboy** [peterarsentev/job4j_features_bugs#1475]
![image](https://user-images.githubusercontent.com/91426901/211849600-ab6ae843-e5d5-46c2-9176-e1ebcbe1e880.png)
В данном вопросе требуется выбрать коллекцию, однако в ответе правильных решений несколько
2)
![image](https://user-images.githubusercontent.com/91426901/211849977-88482f85-16d0-4921-bb1a-7862c6987a99.png)
Коллекции Dequeue не существует, ошибка в правописании

**Comment by StanislavMontag** [comment]
поддерживаю
при первой попытке сдачи

![brokenExam](https://user-images.githubusercontent.com/2221885/212494493-9a4745b6-e1f7-4b0e-b24b-b702202376c5.jpg)
при второй 
![изображение](https://user-images.githubusercontent.com/2221885/212494528-8d1cd4ff-a045-48ef-97d4-8b9d5d4c64a4.png)
хотя выбирал только два варианта
и правильными во второй раз оказались не те варианты, что были указаны в первый раз

**Comment by itfedorovsa** [comment]
Спасибо, отредактировал вопрос на выбор нескольких элементов. ugress, Вы 2 раза выбирали разные ответы, если я правильно вижу, так как правильный ответ выделен галочками, то есть все варианты здесь правильные. Закрываю.
