### ISSUE TITLE
1. Spring mock [#2096 #378636]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1476]
https://job4j.ru/profile/exercise/102/task/521/378636

Про подключение зависимостей
Насколько я понимаю в пакете spring-boot-starter-test
уже есть junit, может быть можно убрать его из зависимостей?
<img width="441" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/212145121-d21684ca-7c71-4423-bea9-5672b075fe42.png">

**Comment by staskorobeynikov** [comment]
убрал
