### ISSUE TITLE
Ошибка в коде.

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1477]
[В уроке](https://job4j.ru/profile/exercise/55/task-view/348) допущены ошибки:

![image](https://user-images.githubusercontent.com/106254908/212294085-dbbfe7c2-45d9-4a93-8a11-84ef0ef7fbe4.png)

1) орфографическая (ConsoleOutput), пропущена буква "t"
2) ошибка в коде... в конструкторе ValidateOutput 2 параметра, первым из которых является объект класса Output, а уже второй ConsoleOutput.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
