### ISSUE TITLE
2. Каркас шахматной доски [#792]

### ISSUE THREAD

**Issue by staskorobeynikov** [peterarsentev/job4j_features_bugs#148]
Недостаток в описании.

Нумерация ячеек не соответствует нарисованной доске...А8(0, 0), а должно быть А8(0, 7)...это запутывает...

**Comment by AlexeySapsay** [comment]
более того , были изменены другие файлы проекта, отчего при решении задачи проект необходимо обновить  отдельно, необновляя остальные проекты(сокобан), что бы не затереть уже решенные задачи.


Для быстрого и безопасного обновления проекта chess необходим выполнить не большую последовательность действий:

Цитирую: 
Stas Korobeinikov, [08.01.21 20:02]

Наиболее эффективно
Будет скачать зип архив
Распаковать его
И просто папку по шахматам себе скопировать с заменой
Это будет быстрее всего
И прогресс по сокобану не потеряешь

**Comment by staskorobeynikov** [comment]
исправлено
