### ISSUE TITLE
Список рекомендуемой литературы c конца блока "раскидать" по модулю

### ISSUE THREAD

**Issue by SkMihail** [peterarsentev/job4j_features_bugs#1485]
В конце каждого блока есть список рекомендуемой литературы, думаю было бы удобно раскидать эти список по главам непосредственно в задания где знакомимся с темами.  т.е. например 

2. Типы данных:

           а) Java 8, Полное руководство - Герберт Шилдт. Глава 3. Типы данных (стр. 75 - 93)
           б) Библиотека профессионала. Java. Том 1. Основы - Кей Хостманн, Гари Корнелл.  Глава 3. Типы данных (стр. 61 - 75)

Занести в раздел 
Job4j / Уроки / 1.1.2. Типы данных / 0. Что такое переменная

В самом уроке это можно вынести перед объявлением задания.

**Comment by itfedorovsa** [comment]
Спасибо, литература почти их всех заданий теперь также представлена в соответствующих уроках. Закрываю

**Comment by SkMihail** [comment]
Вам, спасибо! заметил сейчас ссылку на литературу в упражнении, и мотивирует открыть учебник прочитать!
