### ISSUE TITLE
Опечетаки

### ISSUE THREAD

**Issue by Slepchenko** [peterarsentev/job4j_features_bugs#1486]
2.4.5. Java Memory Model / 2. Клонирование объектов. Shallow clone и deep clone / 2. Клонирование объектов. Shallow clone и deep clone [#504933]

1.
происходит клонирование исходного объекта. Далее **демонстрируется изменений значений** полей клонированного объекта, в результате видим, что изменения клонированного объекта произошли независимо от исходного объекта:

2.
Данную тему спрашивают на собеседованиях, поэтому копирование объектов в Java важно знать. Копирование объектов используется для их передачи по сети. **Есть есть** две виртуальные машины (здесь и на другом конце), то можно передать объект и работать с ним в другой виртуальной машине.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
