### ISSUE TITLE
4. Блокировки

### ISSUE THREAD

**Issue by digest15** [peterarsentev/job4j_features_bugs#1488]
1. "так как в synchronized блокировки нужно снимать только в обратном порядке" - нужно или возможно, разве программист может повлиять на этот процесс?

2. "аналогичны методам wait(), notify() и notifyAll(), с которыми мы знакомы из прошлых уроков." - я еще не знакомился с этими методами в предыдущих уроках...

3.  В разделе объяснения интерфейса Condition, есть кусок кода в котором в блоке finally есть снятие блокировки, но по коду выше нет установки этой блокировки - так и нужно или это ошибка?

4. ReadWriteLock. "Блокировку чтения могут удерживать несколько "читателей", но только до тех пор, пока не появится "писатель". Блокировка записи является эксклюзивной." - я понимаю что это почти дословный перевод первого обзаца javadoc этого интерфейса, но если я правильно понимаю заложенную в него логику, то это совместимость блокировок на чтение и запись, наподобии блокировок SQL, читатели не конфликтуют между собой, а писатель конфликтует со всеми. Поток не может взять блокировку на запись, если уже есть блокировка на чтение или запись, не может взять блокировку чтения, если есть блокировка записи, но несколько потоков могут свободно взять блокировку чтения. Тут можно привести таблицу совместимтости блокировок. Это очень важный момент, из текста урока этого не понятно..., я понял так: что читалели могут работать, пока не придет писатель, он всех выгонит и будет делать свой дела....

**Comment by itfedorovsa** [comment]
Спасибо! 
1) Отредактировано. 
2) Урок перенесён после wait() 
3) В первой строке устанавливается блокировка, к которой применяется Condition
![image](https://user-images.githubusercontent.com/101260971/216611423-fba65901-013d-4820-bc26-207babb508fa.png)

4) Дописал про это подробнее. Таблицы блокировок как таковой не существует, так как блокировки всего 2 и всего 3 условия, которые могут быть. Выгоняет ли писатель читателей точного ответа не нашел, скорее всего после появления в очереди писателя, к читателям никто не присоединяется, а при освобождении всех блокировок чтения писатель получает блокировку. Иначе просто заставить отпустить читателей свои блокировки как-то не укладывается.
Закрываю.
