### ISSUE TITLE
Не правильное отображение шкалы прогресса 

### ISSUE THREAD

**Issue by RuslanGRA** [peterarsentev/job4j_features_bugs#1490]
На уровне стажер в папке 1.1.0. Вводная не правильно отображается шкала прогресса. В этой папке содержится всего 8 уроков, а программа показывает 10 уроков из 8 что приводит к отображению не 100% пройденного материала а 125%.

![2023-01-18_23-15-08](https://user-images.githubusercontent.com/55834274/213287411-49dbc7ea-a5e9-47c3-bc41-88f9b795bf37.png)
![2023-01-18_23-16-05](https://user-images.githubusercontent.com/55834274/213287445-391cf1b3-1ee3-444b-9763-03cee52b2440.png)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
