### ISSUE TITLE
1.6. Особенности обучения взрослых [#504940 #382811]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1491]
https://job4j.ru/profile/exercise/141/task-view/1020

Предложил бы добавить к описанию метод (цикл) Девида Колба,
который, по моему мнению, описывает хороший подход
к обучению программированию. 

(двигаемся по спирали вверх, часто циклов может быть несколько):
Пробуем решить конкретную задачу имеющимися средствами и знаниями, активно экспериментируем
Смотрим что получилось, анализируем результат
Намечаем дальнейший план с учетом результатов и новой изученной теории из разных источников
Пробуем ещё раз, уже находясь на новом уровне теоретических и практических знаний

Вот примерная картинка показывающая процесс
<img width="595" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/213423554-7c63234e-7d37-47f7-9dff-cc0fbbe2bad6.png">

Вот видео на данную тему
https://www.youtube.com/watch?v=bJakF93Tpjs

**Comment by WhiteVax** [comment]
Не плохое обьяснение в данном видео.

**Comment by Serge-In** [comment]
Спасибо за коммент, попробую этот метод на практике. 
Начну с выполнения задания к уроку, а не с чтения урока - как обычно.

**Comment by peterarsentev** [comment]
Спасибо. Ознакомился с видео. Идея хорошая, но абстрактная. Чтобы ее использовать нужны не дюжинные аналитические способности. В курсе хотелось бы видеть четкую последовательность действий.

**Comment by YarTsin** [comment]
@peterarsentev 
Так я и расписал конкретику вначале, перед картинкой. 
Метод Колба на практике (цикл)
1. Пробуем решить конкретную задачу имеющимися средствами и знаниями, активно экспериментируем
2. Смотрим что получилось, анализируем результат
3. Намечаем дальнейший план с учетом результатов и новой изученной теории из разных источников
4. Пробуем ещё раз, уже находясь на новом уровне теоретических и практических знаний
(повторить цикл до решения задачи)

Или это тоже сильно абстрактно?
