### ISSUE TITLE
7. Правила написания кода. Java Code Conventions. [#504935]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1492]
https://job4j.ru/profile/exercise/1/task-view/1015

Цитата:
"Каждый отступ должен быть равен по длине 4 пробелам."

Предложил бы добавить - "как правило это 1 нажатие 
клавиши Tab"

ххххххххххх

Предложил бы добавить ссылку на Требования к проекту
примерно в таком виде:

Примечания
Кроме выше перечисленных требований по Правилам 
написания кода на курсе присутствуют 
Требования к написанию проекта: 
https://github.com/ShamRail/job4j_requirements/wiki
По мере продвижения по курсу
рекомендуем вам также изучать этот документ
(понятные вам разделы)

**Comment by itfedorovsa** [comment]
Спасибо, добавил про табуляцию. А до ближайшего проекта, где понадобятся новые требования, ученикам на той стадии еще очень далеко, поэтому нет смысла голову забивать непонятной информацией. Закрываю.
