### ISSUE TITLE
1.2. Правила обучения на проекте Job4j [#1150 #4034]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1493]
https://job4j.ru/profile/exercise/141/task/5/4034

Цитата:
2. Оценить время завершения первого уровня. В первом уровне - 250 задач.

Количество задач уже перевалило за 300, может быть пример сделать без привязки
к реальным цифрам, чтобы постоянно не исправлять?

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано. Закрываю
