### ISSUE TITLE
Ошибка в схеме зависимостей урок - 3. Архитектура проекта - Аргегатор Java Вакансий [#260359 #383360]

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1495]
В уроке https://job4j.ru/profile/exercise/56/task/361/383360 на диаграмме вместо "Store" должен быть "Scheduller". 

![image](https://user-images.githubusercontent.com/106254908/213861299-16e96218-89a4-4c96-8863-48927c3b8899.png)

**Comment by peterarsentev** [comment]
@knownasmars А у нас нет отдельного элемента для sсheduller. Класс Grabber реализует загрузку планировщика от quarzt.
Grabber знает о хранилищах, парсере и модели данных.
Или у тебя был отдельный класс для планировщика?

**Comment by peterarsentev** [comment]
@knownasmars Понял откуда проблема. Спасибо. Поправим.
метод init(Parse, Store, Scheduller) - нужно поправить.
