### ISSUE TITLE
Перепроверьте тесты SQL. Очень много ошибок.

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1496]
Привожу только часть примеров:
1)
![image](https://user-images.githubusercontent.com/106254908/213922251-ccc4f31a-a32e-4c20-b11a-2b31fb522aa5.png)
здесь ошибка в том, что правильный ответ не включает опцию с SELECT, так как он относится DQL, исходя из информации рекомендуемого же Вами источника: 
![image](https://user-images.githubusercontent.com/106254908/213922300-2a312dfb-c805-49eb-986f-3fa1fc706aed.png)

2)
второй пример касается этого вопроса
![image](https://user-images.githubusercontent.com/106254908/213922322-c8e79f40-0e70-425e-998f-ee5339cc5d28.png)
для one-to-one также может быть создана вспомогательная таблица если подразумевается двунаправленная зависимость (например человека ищут по паспорту и паспорт по человеку)

3) 
![image](https://user-images.githubusercontent.com/106254908/213922624-2b11606a-f643-4616-a5a0-8caf2ee7b1a3.png)
здесь ошибка в правильном ответе, не может PRIMARY KEY содержать null

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Остальные тесты sql тоже проверил, вроде всё норм. Закрываю
