### ISSUE TITLE
Автоматическая проверка ознакомительных заданий

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1497]
Добрый день, уважаемая команда job4j. Мне кажется, что интересным нововведением могла бы послужить возможность автоматической проверки задания, где все, что требуется это ознакомится с материалом.
В моем понимании это снизит нагрузку на менторов курса, т.к зачастую большинство таких заданий просто закрывается, т.к не требует какой-то обратной связи.
Но что бы оставить возможность задать вопрос ментору по заданию, возможно, что реализация будет следующей:

- сделать две кнопки
- по первой задание автоматически переходит в статус "Выполнено"
- по второй стандартный воркфлоу, который уже существует, т.к задание падает на ментора.

**Comment by peterarsentev** [comment]
Спасибо. Но лучше ученики сами будут отписывать. Если сравнивать время на эти задачи, то они не существенны.
