### ISSUE TITLE
4. Потоки байтовых массивов (ByteArray Streams) [Опечатка в аргументах конструктора]

### ISSUE THREAD

**Issue by WhiteVax** [peterarsentev/job4j_features_bugs#1499]
https://job4j.ru/profile/exercise/45/task-view/1078
![Screenshot 2023-01-28 002338](https://user-images.githubusercontent.com/73067145/215217957-2f611650-6ee8-47fc-995e-6686ff184229.png)

**Comment by itfedorovsa** [comment]
Спасибо, исправлено! Закрываю
