### ISSUE TITLE
3. Загрузка классов в JVM - опечатка

### ISSUE THREAD

**Issue by Niaktes** [peterarsentev/job4j_features_bugs#1500]
https://job4j.ru/profile/exercise/196/task/1053/385683

Ближе к концу текста, в блоке "Принципы загрузки классов":
"- Видимость
Область видимости загрузчика ограничена только классами, которые были загружены им или его родителями. Загрузчик не владеет данными о классах, которые загружали его предки."

Мне кажется, здесь опечатка. Возможно, должно быть "загрузчик не владеет данными о классах, которые загружали его наследники"

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
