### ISSUE TITLE
Тест Система ввода-вывода IO, NIO. Вопрос про консоль.

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#1505]
Вопрос
Получение консоли
На что будет указывать ссылка console, если мы вызовем следующую команду в IDEA?
Console console = System.console();
Правильный ответ: null

Я выбирал null на первой сдаче и на пересдаче, но почему то правильный ответ не засчитывается.
![Снимок экрана_20230203_092928](https://user-images.githubusercontent.com/73255714/216528438-c76766a9-9c73-41c7-8561-a36cfe055277.png)

**Comment by itfedorovsa** [comment]
Спасибо, исправлено! Закрываю
