### ISSUE TITLE
Тема : 3.1.1. Threads 9. ThreadLocal

### ISSUE THREAD

**Issue by egorbekhterev** [peterarsentev/job4j_features_bugs#1506]
При использовании модификатора private переменная t1 недоступна из классов FirstThread и SecondThread.
![thread_local](https://user-images.githubusercontent.com/99808603/216547345-ba6151f8-e1b1-411a-a2f0-11cd3dd46423.png)
![thread_local_1](https://user-images.githubusercontent.com/99808603/216547707-c9f77c4f-b282-4956-9094-6ea8c11be6ab.png)

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
