### ISSUE TITLE
Job4j Упражнения 1.1.4. Оператор ветвления 45. Произвести увеличение/уменьшение до ближайшего "круглого" числа

### ISSUE THREAD

**Issue by davcorp01** [peterarsentev/job4j_features_bugs#1509]
По заданию вывод в консоль может быть "Увеличено до n" либо "Уменьшено до n". Есть тест when20Then20, правильным ответом в котором "Увеличено до 20", что не логично, т.к. на входе 20 и на выходе 20 и никакого увеличения не происходит.
КМК, решить добавлением доп. проверки не проблема, но обычно, в рамках курса подобные задачи по условию решаются: ДА / НЕТ / Без изменений.

ИМХО исправить тест или дополнить требования по задаче.

**Comment by itfedorovsa** [comment]
Спасибо, добавлено условие вывести "Без изменений", если входящее число уже круглое. Закрываю.
