### ISSUE TITLE
9. HTML form. Создание страницы кандидата

### ISSUE THREAD

**Issue by Rozovod** [peterarsentev/job4j_features_bugs#1511]
Во втором пункте задания скорее всего имелось ввиду CandidateController, так как задание относится к созданию страницы с формой создания резюме кандидата. 

<img width="1110" alt="Снимок экрана 2023-02-12 в 14 22 18" src="https://user-images.githubusercontent.com/92817176/218308031-05b9d349-1bb1-4dcb-ba15-8a81882ac50e.png">

**Comment by Rozovod** [comment]
И добавить в задании пункт о создании кнопок не только в навигационной панели, но и на главной странице. Так как в следующем задании, в примере на фото они уже есть.

<img width="840" alt="Снимок экрана 2023-02-12 в 14 32 37" src="https://user-images.githubusercontent.com/92817176/218308578-622aaf72-f0ae-4187-9ce6-27f3daceace1.png">

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю.
