### ISSUE TITLE
1.1.7. Контрольные вопросы и тестовое задание. Впечатления о блоке

### ISSUE THREAD

**Issue by muraviev-aa** [peterarsentev/job4j_features_bugs#1513]
Здравствуйте!
https://job4j.ru/profile/exercise/16/task/1092/393048
Нашел опечатки в тексте:
![image](https://user-images.githubusercontent.com/103278793/219944133-95ff4b22-1d60-4a8e-8b0e-027318295279.png)
сделаНа...............................тренировкЕ
![image](https://user-images.githubusercontent.com/103278793/219944326-3e824a9b-fb8c-4a5f-972c-5b15d182a8db.png)
блоК
Спасибо!

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
