### ISSUE TITLE
в уроке \задании - 6.4.2. Обход массива с последнего элемента | [#361619]

### ISSUE THREAD

**Issue by AlekseiBB** [peterarsentev/job4j_features_bugs#1514]
добрый день.
в уроке \задании - 6.4.2. Обход массива с последнего элемента | [#361619]
данные 3 переменные 
            int lastIndex = ...;
            int currentIndex = ...;
            result[currentIndex] = ...;
но в решении говорят необходимо решить в 1 строку.

может стоить убрать данные которые вводят в заблуждение при выполнении ?

**Comment by peterarsentev** [comment]
@AlekseiBB Можешь уточнить, где в описании требуют написать в одну строку?

**Comment by peterarsentev** [comment]
Поправил. Посмотрел в чем смысл и понял, что лишнее написали.
