### ISSUE TITLE
1.2. Вызов метода объекта [#166085 #393789]

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1515]
1) Возможно в классе Student имеет смысл изменить название метода "song" на "**sing**", т.к. метод принято называть **глаголом** + не будет путаницы со стрингом с именем "song" в следующем задании.

2) Также стоит отредактировать **пункт 3** в задании "Внутри метода сделайте if else.", указав, что от ученика требуется конструкция switch-matcher или как она описана в идее "enhanced switch". Или как-то намекнуть на это, например "используйте самую оптимальную и самую новую/короткую конструкцию ветвления"

**Comment by peterarsentev** [comment]
@Sveeta2000 
1. Поправил. Спасибо.
2. А этот пункт не увидел в описании. Можешь картинку добавить с указанием этого текста?

**Comment by Sveeta2000** [comment]
Вот в этом уроке - 1.3. Вызов метода с аргументами. [#166086 #393805]
![image](https://user-images.githubusercontent.com/112828576/221370077-d57bfb7f-7f72-4b93-a824-6ed4c4864ccf.png)

**Comment by itfedorovsa** [comment]
> 
Switch применяется вместо if-else только в случаях, когда все условия имеют конкретные значения. Типа если "1", то делаем одно, а если "2", то делаем другое. В остальных случаях switch не может заменить if-else. Дополнил условие про возможность сделать через switch. Спасибо, закрываю.
