### ISSUE TITLE
Хранилище машин [#1733] опечатка

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#1518]
Хранилище машин [#1733]
опечатка в задании
2. Вывести кузовы, которые не используются НИ в одной машине. 
to be вывести кузовА ....

**Comment by Popov-Ruslan** [comment]
"Кузовы" тоже допустимо

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
