### ISSUE TITLE
Опечатка в интерфейсе окна уроков

### ISSUE THREAD

**Issue by Popov-Ruslan** [peterarsentev/job4j_features_bugs#1519]
В правой нижней части окна при наведении на кнопку "Решения", которая слева от кнопок "Предыдущая" и "Следующая" - всплывает подсказка "Решения других учениОков станут доступны после выполнения урока".
И кнопки "Предыдущая" и "Следующая" лучше заменить на "Предыдущий" и "Следующий", ведь речь идет об уроках.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
