### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1520]
В уроке https://job4j.ru/profile/exercise/73/task-view/409

вместо Mutual Extension должно быть Mutual Exclusion

**"Мьютекс (первые буквы от MUTual EXtension - взаимное исключение) - простейший тип синхронизатора нитей. "**

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
