### ISSUE TITLE
0. Монитор, мьютекс, критическая секция [#6857] опечатка

### ISSUE THREAD

**Issue by SevaStopAll** [peterarsentev/job4j_features_bugs#1521]
Мьютекс (первые буквы от MUTual EXtension - взаимное исключение) - простейший тип синхронизатора нитей. 

Extension, скорее всего, заменяется на exclusion. 
![Безымянный](https://user-images.githubusercontent.com/115623776/222062272-5b2b1bca-942d-46be-90e9-e08904c8dbe6.png)

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
