### ISSUE TITLE
В задаче 0. CAS - операции [#6859 #397673] изменить каркас

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1522]
В каркасе к заданию 
0. CAS - операции [#6859 #397673]
нужно поменять AtomicReference<Integer> на AtomicInteger.
сейчас:
public class CASCount {
    private final AtomicReference<Integer> count = new AtomicReference<>();
станет:
public class CASCount {
    private final AtomicInteger count = new AtomicInteger<>();

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
