### ISSUE TITLE
Неточная формулировка

### ISSUE THREAD

**Issue by Paronian** [peterarsentev/job4j_features_bugs#1523]
Урок: 6.3. Статические вложенные классы [#504951 #376325]
Ссылка: [https://job4j.ru/profile/exercise/20/task-view/1031](url)

Из последних строк вывода:

- Из экземпляра этого класса есть доступ ко всем переменным и методам внешнего класса (обычным и статическим, включая private).

Может быть по другому сформулировать? Из статического вложенного класса можно получить доступ ко всем переменным и методам внешнего класса (в том числе и к обычным, включая private), через ссылку на объект внешнего класса.

**Comment by itfedorovsa** [comment]
Спасибо, урок отредактирован! Закрываю.
