### ISSUE TITLE
Интерфейс ответов в экзаменах

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1524]
Уже несколько раз замечал в чате Стажер, что люди не совсем понимают,
что показывает программа, какие ответы сделал курсант, а какие правильные.
Примеры:
https://t.me/job4j_trainee/168450
https://t.me/job4j_trainee/166259
https://t.me/job4j_trainee/166250
https://t.me/job4j_trainee/166245
Возможно было бы полезным переработать интерфейс таким образом, чтобы
было более понятно, какие ответы выбрал курсант, а какие программа.
P.S. 
На первое сообщение вы сами обратили внимание, 
https://t.me/job4j_trainee/168482
может быть ещё и содержание тестов перепроверить))

**Comment by MichaelZalogin** [comment]
Поддерживаю!

**Comment by itfedorovsa** [comment]
Проблемный вопрос проверил, уже отредактирован. Остальное приняли во внимание.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
