### ISSUE TITLE
5.1. Зачем нужно приведение типов [#310019] В каком пакете выполнять дз?

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1525]
Добавьте, пожалуйста в описание задания в каком пакете следует его выполнять. В обоих "поли" пакетах у меня уже есть транспорт в том или ином виде. 

**5.1. Зачем нужно приведение типов [#310019]**

![image](https://user-images.githubusercontent.com/112828576/224030687-3dac7f39-6c7f-4577-a18a-d43a07485097.png)

**Comment by itfedorovsa** [comment]
Спасибо, добавлено! Закрываю
