### ISSUE TITLE
Job4j Упражнения 1.1.4. Оператор ветвления 57. Определить тип треугольника

### ISSUE THREAD

**Issue by davcorp01** [peterarsentev/job4j_features_bugs#1526]
Ответ от Sergey Fedorov 07.02.2023 14:39

Убрал StringJoiner из тестов, чтобы устранить путаницу. Теперь все результаты нужно выводить просто через println(). В случае с составным ответом, собирать через StringJoiner с разделителем-пробелом и выводить.

Вопрос: на каком этапе прохождения курса до "Операторов ветвления" включительно, разбирали  "StringJoiner"
Я конечно допускаю, что есть гугл, книжки, и т.п. но все же..

**Comment by itfedorovsa** [comment]
StringJoiner разбирается в этом уроке в разделе ООП https://job4j.ru/profile/exercise/22/task-view/995 . При невозможности/нежелании узнать о StringJoiner из гугла, книжек и т.п., можно ознакомиться с ним из данного урока в курсе. Упражнения не обязательно проходить в точности c поданным материалом, более того, упражнения в курсе сделаны просто для личной тренировки и не имеют менторской поддержки, а о необходимости применения StringJoiner указано во многих упражнениях. Спасибо, закрываю
