### ISSUE TITLE
Большая сложность восприятия статьи 8. FP - функциональное программирование

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1527]
После прочтения статьи о функциональном програмировании, осталось очень двоякое впечатление, т.к статья очень сложна для восприятия, особенно на текущем уровне. Мне кажется было бы здорово ее переработать и написать более понятным языком, раз уж она находится на уровне стажер.

**Comment by peterarsentev** [comment]
@dmarakov Спасибо. урок переписали.
