### ISSUE TITLE
Изменить название проекта (Уроки курса МИДЛ 3.4.6. Rest. Задания 4. 5. 6.)

### ISSUE THREAD

**Issue by nikegreen** [peterarsentev/job4j_features_bugs#1528]
Изменить название проекта (в котором нужно делать изменения и сдавать задания) с "job4j_chat" на "job4j_auth" в четырёх заданиях.
Курс мидл: 3.4.6. Rest.
В заданиях:
4. Обработка исключений и Spring REST   [#504797]
5. ResponseEntity   [#504799]
6. DTO   [#504800]
7. Валидация моделей в Spring REST   [#504801]

Написано работать с приложением: "2. Для приложения job4j_chat:".
По факту в предыдущих заданиях было приложение:  job4j_auth.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
