### ISSUE TITLE
12.0. Написать тесты на StartUI. [#785] (Правка по английскому)

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1529]
В самой первой рамке с кодом в методе main: "/* _another_ action**s** */" должно быть -> ""/* **other** action**s** */ , тк **another** используется со словами в **единственном** числе. 
"Другие действия" = "other actions". (Как подсказка - в слове "another" - "an" это артикль соединенный в одно слово с "other", что говорит о единственном числе)
![image](https://user-images.githubusercontent.com/112828576/224741747-9df2f7f0-2d40-4615-91bb-0f03fdac289c.png)

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю.
