### ISSUE TITLE
1.2.2. Классы и объекты - 6.2, 6.3

### ISSUE THREAD

**Issue by OrkVasya** [peterarsentev/job4j_features_bugs#1530]
Если можно для тем 6.2 (Локальные и анонимные внутренние классы) и 6.3 (Статические вложенные классы) расширить описание того, для чего конкретно они нужны. 

Напр., для локального класса есть такое описание:
"**Локальный класс применяется, когда нужно написать класс, который планируется использовать в пределах одного метода или другого блока кода. Локальные классы следует писать короткими, чтобы не ухудшать читаемость кода.**"
Но не понятно, в каких случаях появляется необходимость его использования.

Для статического:
"**Cтатическим элементам не требуется ссылка на какой-либо объект. Статический вложенный класс не привязан к объекту, объект статического вложенного класса не хранит в себе ссылку на внешний класс. Статический вложенный класс можно использовать, когда прямая связь между вложенным и внешним классом не требуется.**"
Но без "жизненного" примера не понятно, почему его нельзя сделать отдельно, а не вложенным.

**Comment by itfedorovsa** [comment]
Добавил в урок https://job4j.ru/profile/exercise/20/task-view/1030 основные виды применения вложенных классов, в урок https://job4j.ru/profile/exercise/20/task-view/1031 добавил строку в локальный класс. Все вложенные классы очень ситуативны и имеют очень редкое применение (кроме лямбд). Вкратце: внутренний, если класс является частью внешнего класса (машина-тормоза), статический вложенный - если класс имеет отношение, но не является конкретной частью, (машина-инструкция по применению), в том числе просто выделение отдельного функционала по тому же признаку, анонимный - одноразовый класс (лямбды и т.д), локальный - инкапсуляция какого-либо кода внутри другого класса. Очень ситуативно, так как расположить можно в любом блоке кода. Примеров даже в интернете очень мало по ним. Спасибо, закрываю
