### ISSUE TITLE
опечатка

### ISSUE THREAD

**Issue by knownasmars** [peterarsentev/job4j_features_bugs#1533]
в [лекции ](https://job4j.ru/profile/exercise/187/task-view/939) https://job4j.ru/profile/exercise/187/task-view/939

опечатка 
Метод databaseClient создает **экземляр** Sql2o. Подробнее про него **погорим** позже;
должно быть **"экземПляр" и "поговорим"**

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
