### ISSUE TITLE
Опечатка 11. План выполнения запросов [#504898]

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#1534]
Однако в проектах реальная картина может быть совсем иной – количество записей будет исчисляться десятками миллионов строк, в таблицах будет множество индексов и при выполнении запросов придется выполняться 10 JOIN.

**Comment by EliseevSergey** [comment]
ещё одна
Таким образом, стоимость запуска оеперации также включает стоимость запуска ее дочерних элементов.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
