### ISSUE TITLE
Опечатка в 3.5.4. Docker / 2. Управление образами

### ISSUE THREAD

**Issue by MrRocketR** [peterarsentev/job4j_features_bugs#1536]
В тексте, где: 
3. Запускаем контейнер в фоновом режиме. -d позволяет запустить контейнер в фоновом режиме, при этом в самом контейнере запускается терминал, за это отвечает ключ -it (-i + -t)

docker run -d -it **opendjdk** bash

Опечатка в команде.

Должно быть: 

docker run -d -it **openjdk** bash

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
