### ISSUE TITLE
Предложение. Для заданий  - где нужно только поставить маркер "Ознакомлен". Опционально.

### ISSUE THREAD

**Issue by avpetrov27** [peterarsentev/job4j_features_bugs#1537]
Предложение.
Для заданий  - где нужно только поставить маркер "Ознакомлен"(например, 4.0. Что такое Interface. [#504946]) **опционально** **предлагать**: описать сущность своими словами и ключевые особенности, сделать предположение где и как это уместно использовать и прочее.

**Comment by peterarsentev** [comment]
Спасибо за предложение. В курсе много заданий, так что не думаю, что нужно еще добавлять. Мы лучше уделим вниманию эффективности.
