### ISSUE TITLE
Опечатка 3. Отладчик при работе с Базой Данных [#504953]

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#1539]
Устанавливаем точку останова на строке 71 и запускаем отладчик:

**Comment by EliseevSergey** [comment]
и  ещё
 Точку останова располагаем на строке 74 и переходим к ней по команде Resume Program.

**Comment by itfedorovsa** [comment]
ru.wikipedia.org/wiki/Точка_останова  
Здесь ошибки нет. Закрываю
