### ISSUE TITLE
Непонятно поставлено задание 3. final [#334073]

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1540]
**3. final [#334073]**

**Вот текст задания:**

_"Задание.

1. Ниже представлен код, он содержит ряд ошибок компиляции. Вам необходимо его исправить, при этом сделать таким образом:

- класс Airbus нельзя было наследовать;

- метод printCountEngine() должен выводить реальное количество двигателей, которое присуще той или иной модели самолета. Поэтому если модель самолета A380 - количество двигателей должно равняться 4, для всех остальных моделей - используем в качестве значения константу COUNT_ENGINE.

- чтобы не допускать дублирования кода следует использовать дополнительную переменную и тернарный оператор. Код метода должен уместиться на двух строках."_

**Что смутило:**

1. Если в первом пункте имеется ввиду что Эирбас не должен быть наследником / не должен наследоваться от другого класса(Эиркрафт), то лучше изменить формулировку нп более однозначную, тк настоящая формулировка создает впечатление что от класса Эирбас нельзя наследоваться.
2. По тексту задания **сложно понять, что я могу менять в коде, а что - нет**. Можно же вообще файналы убрать везде, где они не нужны..
3. Возможно, для того чтобы продемонстрировать особенности работы с файнал модификатором надо сделать отдельные 3 маленьких урока(с точечными заданиями), каждый для отдельных вариантов использования(1 - с простыми переменными и объектами, 2 - с методами, которые нельзя переопределить при наследовании, 3 - с классами/обобщение всех вариантов использования). Тк в данном задании непонятно на чем акцент и получается каша.

**Comment by itfedorovsa** [comment]
Модификатор final очень простой, разбивать на 3 урока задание на добавление final - лишнее. Поправил описание задания на более понятное. Спасибо, закрываю.
