### ISSUE TITLE
2. Экзамен. Структуры данных и алгоритмы. [#1000 #404507]

### ISSUE THREAD

**Issue by AleksFromBuk** [peterarsentev/job4j_features_bugs#1542]
один из вопросов "зашит" на неверный ответ, то есть при действительно-верном ответе получится обратный результат
![image](https://user-images.githubusercontent.com/78998655/228222485-ee4610c7-5786-4f8d-b252-ea9b5bda4a07.png)

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
