### ISSUE TITLE
Тест - Базовый синтаксис Java.

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#1544]
Ответ 5, но проверка показала ошибку.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/48833977/228469067-0219f1c1-2de0-42f1-9aac-c5007bdff0e8.png">

Ответ верный, но проверка показала, что упущен ответ.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/48833977/228471855-b6e658d7-a241-446d-bb7e-491014e56c59.png">

Проверка отметила ошибки.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/48833977/228473490-31d84258-16d7-4b7b-8803-6f475a279d74.png">

**Comment by itfedorovsa** [comment]
Спасибо, на данный момент уже отредактировано. Закрываю
