### ISSUE TITLE
Ошибка в инструкции к Сокобан

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#1545]
Вероятно, должно быть File - New - Project from version control

<img width="313" alt="image" src="https://user-images.githubusercontent.com/48833977/228475954-525a1033-d50d-4448-af5f-7a9423d4635a.png">

**Comment by peterarsentev** [comment]
Спасибо. Уже не актуально, мы убрали эту задачу.
