### ISSUE TITLE
Правила Checkstyle

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#1546]
Правила Checkstyle
https://job4j.ru/profile/exercise/19/task-view/1061

В этом уроке предложил бы добавить инфу о правке ошибок через Refactoring (Shift + F6)

**Comment by itfedorovsa** [comment]
С помощью Shift + F6 можно переименовывать переменную, метод, класс и т.д., не более. Это описано в уроке по горячим клавишам IDEA. Спасибо, закрываю.
