### ISSUE TITLE
Job4j Упражнения 1.3.4. Сортировка 1.5. Получение компаратора. Метод thenComparing()

### ISSUE THREAD

**Issue by aseldom** [peterarsentev/job4j_features_bugs#1547]
https://job4j.ru/profile/topics/30/task_code/144/new_task

Иногда бывает так , что необходимо задать приоритет порядка следования элементов. Например, сначала нам нужно отсортировать элементы по одному признаку, но если **признаки** равны, то сортировать по другому признаку.

**Comment by itfedorovsa** [comment]
На данный момент уже отредактировано. Спасибо, закрываю
