### ISSUE TITLE
Отправка на проверку

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#1548]
При нажатии на кнопку "Сохранить и перейти далее" происходит переход на новую тему, при этом в новой теме уже присутствует комментарий и статус от предыдущей темы. Чтобы комментарий исчез нужно обновить страницу.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/48833977/229334940-ef4ef356-bc64-4e97-8d2f-7b01d5bdd79c.png">
<img width="958" alt="2" src="https://user-images.githubusercontent.com/48833977/229334937-0d8ec9db-fc1f-4638-83e6-a48a3e124a1b.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/48833977/229334935-f0d9fc16-d124-459b-a445-c0dccf674c03.png">

**Comment by peterarsentev** [comment]
@MrShmiTT Можешь сейчас проверить повторяется у тебя? Мы пробовали найти ошибку, но не можем ее повторить.

**Comment by MrShmiTT** [comment]
> @MrShmiTT Можешь сейчас проверить повторяется у тебя? Мы пробовали найти ошибку, но не можем ее повторить.

Сейчас воспроизвести не удалось.

**Comment by peterarsentev** [comment]
Спасибо. Закрою тогда.
