### ISSUE TITLE
Копирование названия урока

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#1549]
При нажатии на значок для копирования, копирует название только с первым номером (хэшем).
9. Изменить программу Tracker из 2-го модуля [#10039]

Ожидаем:
9. Изменить программу Tracker из 2-го модуля [#10039 #406556]

<img width="485" alt="image" src="https://user-images.githubusercontent.com/48833977/229426110-8884ee65-3140-40c3-a6a4-ee1d2aaff920.png">

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
