### ISSUE TITLE
13. Работа со строками. StringBuilder, StringJoiner, StringBuffer.

### ISSUE THREAD

**Issue by OrkVasya** [peterarsentev/job4j_features_bugs#1550]
В описании String.join() опечатка вкралась.
![image](https://user-images.githubusercontent.com/1465438/229635722-37a2211d-c54a-4dff-988e-404c0cd4b022.png)
Полагаю, тут должно быть "разделитель".

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
