### ISSUE TITLE
2. Экзамен. ООП. [#791] ТЕСТ - что вызывает трудности в понимании ЗАДАНИЙ

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1551]
![image](https://user-images.githubusercontent.com/112828576/229868626-a2cdd697-8aa5-4e07-82c1-d8ce49c58564.png)
1. Формулировка задания сбила с толку "Выберите все сигнатуры методов, которые при объявлении внутри одного класса могут привести к неопределенности" - стоит пояснить в задании "**сигнатуры которые конфликтуют хотя бы с одной другой сигнатурой**" - так формулировка будет однозначной.

2. **Сколько абстрактных методов должен и может содержать абстрактный класс?** - в данном вопросе гадаешь, нужно ответить как положено делать(хотя бы 1 метод) или как позволяет синтаксис языка(без методов)? - понятно, что вопрос "с подвохом", но тем не менее стоит дать пояснение в задании что имеется ввиду именно **синтаксическая возможность**, а не то, как обычно делают и рекомендуют делать 

3. **Можно ли из метода получить несколько значений?** - В Java мы не можем вернуть несколько значений из метода, только одно. Но мы можем возвратить массив, список или мапу, содержащие нужные нам объекты.  - Везде так пишут на эту тему. 

Общая рекомендация по составлению тестов(в универе проходили такую дисциплину) задание в тесте всегда должно быть исчерпывающе понятным, не двусмысленным. Дистракторы(неверные ответы) должны быть хоть и похожими на правду, но на 100% неверными, они не должны вводить тестируемого в заблуждение.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
