### ISSUE TITLE
10. Найти сумму каждого второго числа в диапазоне

### ISSUE THREAD

**Issue by davcorp01** [peterarsentev/job4j_features_bugs#1554]
ДД.
Или по тексту задания ошибка в части "сложите каждое второе число", или в примере в задании - складывается каждое третье...
ну и в тесте соответственно.

https://job4j.ru/profile/topics/14/task_code/112/new_task

**Comment by itfedorovsa** [comment]
Каждое третье - это через 2 друг от друга. Каждое второе - это через 1 друг от друга. В примере и тестах складываются первый, третий, пятый и т.д. элементы. Тут всё правильно. Дописал в условие, что складывать нужно через один. Спасибо, закрываю!
