### ISSUE TITLE
1. Синхронный обмен сообщений [#458496]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1555]
1. Название раздела
3.5.3. Межпроцессорное взаимодействие
предложил бы заменить на 
Взаимодействие между сервисами,
мне кажется так будет более корректно

2.  Как я понимаю в примере используется технология RestTemplate
которая, насколько я знаю, на данный момент является устаревшей.
Предложил бы отметить это в задании и добавить примеры с более
новой технологией WebClient

**Comment by peterarsentev** [comment]
Спасибо. Этот момент переделали.
