### ISSUE TITLE
Job4j Экзамены SQL. CREATE, UPDATE, INSERT

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#1559]
После прохождения теста выдаёт результаты
_____

слитно должно быть "неправильными".
Вопросы с не правильными ответами:

**Comment by peterarsentev** [comment]
Поправили. Спасибо.

**Comment by GitHubfilipich** [comment]
Привет!
В экзамене 2. Джуниор / 2.3. SQL, JDBC / 2.3.8. Контрольные вопросы / 2. Экзамен. Sql есть такой вопрос
<img width="467" alt="image" src="https://github.com/peterarsentev/job4j_features_bugs/assets/25512771/6cc8acdf-6ec4-4fc1-86c3-c6f93bbadc38">
В строке "UPDATE t1 SET col2 = 'Пётр';" неверно указано имя поля ("col2"), такая команда просто падает с ошибкой - нужно исправить имя поля.
