### ISSUE TITLE
select is DQL not DML

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#1560]
![Screenshot 2023-04-15 at 16 13 05](https://user-images.githubusercontent.com/73255714/232226164-76c0e18d-1758-426f-b416-4e9d8b986965.png)

**Comment by EliseevSergey** [comment]
Это было в Job4j > Экзамены > SQL. CREATE, UPDATE, INSERT

**Comment by GHMember** [comment]
В документации Oracle https://docs.oracle.com/en/database/oracle/oracle-database/21/cncpt/sql.html#GUID-90EA5D9B-76F2-4916-9F7E-CF0D8AA1A09D указано следующее: "DML statements are the most frequently used SQL statements and enable you to: Retrieve or fetch data from one or more tables or views (SELECT)."

**Comment by EliseevSergey** [comment]
ок- закрываем. просто иногда  select выделяют в некий DQL, как на страничке здесь:
https://www.geeksforgeeks.org/sql-ddl-dql-dml-dcl-tcl-commands/

**Comment by EliseevSergey** [comment]
не работает тест.
я отметил все варианты и тест всё равно не проходит. Вот скриншот
![Screenshot 2023-04-18 at 10 52 55](https://user-images.githubusercontent.com/73255714/232710708-63d6df38-bdaf-43e1-b000-7f111601b5b8.png)

А вот то что мне выдало в конце
![Screenshot 2023-04-18 at 10 57 25](https://user-images.githubusercontent.com/73255714/232710866-0176a600-e1b3-4810-8f75-c40e86455f7e.png)

**Comment by GHMember** [comment]
У меня тоже самое, поэтому тут и отписал

**Comment by itfedorovsa** [comment]
Раньше были все варианты правильные. Ученики так же писали, что select - это dql. В разных источниках по-разному написано. Смотря что подразумевать под select. Вернул все варианты как правильный ответ. Спасибо, закрываю!
