### ISSUE TITLE
Декомпозировать "10. Реализовать собственную структуру данных - HashMap [#1008]"

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1561]
Друзья, добрый день. Мне кажется что было бы здорово, разбить эту задачу хотя бы на две подзадачи, т.к осилить такого монстра за один раз довольно сложно, как с технической стороны вопроса, так и с психологической. При виде такой огромной задачи, немного опускаются руки, непонятно за что браться в первую очередь, работает ли то, что ты реализовал?
В общем мне кажется, что данному заданию нужен какой-то рефакторинг, очень оно выделяется на фоне остальных.
Заранее спасибо.

**Comment by GHMember** [comment]
Поддерживаю

**Comment by peterarsentev** [comment]
Спасибо. Мы расписали схему реализации и добавили еще одну подводящую задачу.
