### ISSUE TITLE
Опечатки по тесту.

### ISSUE THREAD

**Issue by MichaelZalogin** [peterarsentev/job4j_features_bugs#1562]
Задание 4. TODO list [#3786]. 
Много опечаток по тексту в разделе "задание". Предлагаю свой вариант текста с небольшими орфографическими правками:

2. Виды.
    - Страница со списком всех заданий. В таблице отображаем имя, дату создания и состояние (выполнено или нет).
    - На странице со списком добавить кнопку "Добавить задание". 
    - На странице со списком добавьте три ссылки: "Все", "Выполненные" и "Новые". При переходе по ссылкам в таблице нужно отображать: все задания, только выполненные или только новые.
    - При клике на задание переходим на страницу с подробным описанием задания.
    - На странице с подробным описанием добавить кнопки: "Выполнено", "Редактировать" и "Удалить".
    - Если нажали на кнопку "Выполнить", то задание переводится в состояние выполнено.
    - Кнопка "Редактировать" переводит пользователя на отдельную страницу для редактирования.
    - Кнопка "Удалить" удаляет задание и переходит на список всех заданий.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
