### ISSUE TITLE
Тест по основам git - два одинаковых варианта ответа

### ISSUE THREAD

**Issue by mihanchik94** [peterarsentev/job4j_features_bugs#1563]
В вопросе "С помощью какой команды можно просмотреть список всех веток"  присутствует 2 одинаковых варианта ответов.

**Comment by itfedorovsa** [comment]
В нижнем варианте точка в конце стоит, они разные.
![image](https://user-images.githubusercontent.com/101260971/234989575-f4bdef56-af85-43a6-9678-7a97d9d9b242.png)
Сделал варианты ответов жирными, чтобы проще разглядеть было. Спасибо, закрываю!
