### ISSUE TITLE
0. Обзор Docker [#504776]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1564]
https://job4j.ru/profile/exercise/175/task/771/411450

Возможно уже пришла пора обновить данный урок?
Текущая LTS версия Ubuntu уже Ubuntu Jammy 22.04 (LTS)
Обновился Virtual Box до 7 версии
Несколько поменялся порядок установки и настройки.
В существующем уроке некоторые картинки очень маленькие
и уже не очень точные

Выделение памяти для Убунту - там минимум 25 гигов, я бы предложил 50
резервировать, для убунту и всего дополнительного, что туда
потом будет засовываться 

Если я правильно понял c самого начала уже сам вызов команд с sudo
просит пароли и ещё что-то (пока не разобрался, делал через su)
т.е. разбираться с правами надо уже на самом раннем этапе, а не 
после, при настройке docker
Как я понимаю sudo может использовать только администратор,  
находящийся в файле Sudoers. Таким образом возможно имеет смысл,
перед тем как работать c Docker сделать небольшой вводный урок 
с Linux (Ubuntu) - pазделить этот урок как минимум на 2.
Не имеет ли смысла разделить урок на несколько частей:
- общие вопросы виртуализации 
- установка Virtual Box на Windows, 
- установка Ubuntu на Virtual box (и возможно работа c Ubuntu - основы)
- установка Docker на Ubuntu?

В уроке не очень понятен следующий вопрос. 
требуется ли в настройках сети Virtual Box Тип подключения
вместо NAT делать Сетевой мост (для какой-то проброски портов)
Некоторые курсы предлагают поменять тип подключения

**Comment by YarTsin** [comment]
Во время начала работы с Докером столкнулся с ошибкой Убунту 
User is not in the sudoers file и написал небольшую инструкцию для
начинающих Linux для её решения. Надеюсь она будет полезна курсантам:
--------

Для начинающих Ubuntu (для версии ubuntu 22.04)
При проведении работ с Ubuntu возникла такая ошибка
User is not in the sudoers file
т.е. юзеру не хватает прав для выполнения операции,
надо поднимать права.
(В моем случае компьютер назван "ubuntu", пользователь "user1")

Один из способов это сделать - добавить пользователя в группу sudo или wheel
(если такие есть в вашем linux)

~ Проверяем наличие соответствующих групп
1) можно просто вывести в терминал список групп 
в сортированном виде и посмотреть
user1@ubuntu:~$ cat /etc/group | sort

2) можно попробовать найти группу и вывести только её
user1@ubuntu:~$ cat /etc/group | grep sudo
у меня есть

user1@ubuntu:~$ cat /etc/group | grep wheel
у меня такой нет

~ Используем права суперпользователя root и открываем консоль под ним.
user1@ubuntu:~$ su
Password: (ваш админский паспорт)
Вывод:
root@ubuntu:/home/user1#  

~ Добавляем своего пользователя в группу которую нашли 
root@ubuntu:/etc# sudo adduser user1 sudo

~ Выходим из аккаунта суперпользователя (возвращаемся в свой аккаунт)
root@ubuntu:/etc# exit

~ Проверяем свои права
user1@ubuntu:/etc$ su - user1
Вывод:
Password: (вводим свой пароль)
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details. (все нормально)

~ Проверяем свое присутствие в группе sudo
user1@ubuntu:~$ groups
Вывод:
user1 sudo vboxsf

После этого можно под своим пользователем использовать sudo, то есть повышенные права

**Comment by peterarsentev** [comment]
@yarmail Спасибо. Внес правки.
