### ISSUE TITLE
5. PriorityQueue [#504944] несоответствия в примере

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1569]
![image](https://user-images.githubusercontent.com/112828576/235663824-62fa3671-2013-4d3a-9a71-9391f3d67aed.png)
В примере прямо перед выводами есть некоторые несоответствия, по тексту поле **amount 1000** имеют транзакции с номерами **1, 4 и 8**, тогда как в примере кода это номера **2, 5 и 8** (у поля id съехала нумерация, из-за чего задвоился id 3 и пропал id 7 - обвела розовым на скрине)
На третьей картинке красным выделена первая транзакция, тогда как должна быть выделена вторая. В общем небольшая путаница в номерах))

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
