### ISSUE TITLE
В упражнении '19. Предложение WHERE с оператором NOT BETWEEN' некорректно изложен принцип работы оператора

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#1570]
Возможно вместо:
"При этом иногда необходимо сделать выборку строк чтобы при проверке условия значение в столбце **не выходило** за пределы диапазона значений. В этом случае нам поможет оператор NOT BETWEEN."
Стоит написать:
"При этом иногда необходимо сделать выборку строк, чтобы при проверке условия использовались только те значения в столбце, которые находятся за пределами диапазона значений. В этом случае нам поможет оператор NOT BETWEEN."

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
