### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by MichaelZalogin** [peterarsentev/job4j_features_bugs#1572]
1. Ошибка во вкладке "Обуждения" в слове "Уведомление"
2. Задание ToMany [#301848 #413106]. Опечатка по тексту "Этот скрипт будет описать изменения".
3. Опечатка ToOne [#6873 #413088]. "Если этого не делает, то загрузка данных будет медленно."
4. ManyToMany [#331986] в скрипте 006_ddl_create_participates_table.sql необходимо добавить четвертую строчку UNIQUE (item_id, user_id)
5. LazyInitializationexception [#331987] "Рассмотрим, это на примере стратегии извлечения Lazy" Лишняя запятая.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
