### ISSUE TITLE
14. Архивировать проект [#861]

### ISSUE THREAD

**Issue by GHMember** [peterarsentev/job4j_features_bugs#1574]
В методе packFiles первый аргумент имеет тип `List <File>`, а по заданию этот метод должен в качестве первого аргумента принимать то, что возвращает метод search класса Search. А он возвращает тип `List<Path>`. В связи с этим приходится делать довольно бессмысленную конвертацию из одного типа в другой. Причем, ментор отклоняет такой вариант, принимает только когда в методе packFiles первый аргумент меняешь на тип `List<Path>`.

**Comment by itfedorovsa** [comment]
Спасибо, отредактировано! Закрываю
