### ISSUE TITLE
Каркасы и проверки менторов

### ISSUE THREAD

**Issue by grave42** [peterarsentev/job4j_features_bugs#1576]
Я не понимаю почему, вы даете каркасы классов, для доработки методов. Я ими пользуюсь в своём проекте, пишу работоспособную программу. Добавляю на проверку. Затем ментор отклоняет и указывает "можно было 1 строкой" т.о. часть кода из каркаса выбрасывается.

Я не понимаю для чего нужно ужимать весь код, до тяжелочитаемого вида и настолько его сокращать.

Пишите хотябы в задании тогда "Поменяйте каркас, напишите максимально ёмкий код" и так к каждому заданию.

**Comment by peterarsentev** [comment]
@grave42 Здравствуй. Можешь прислать примеры?

**Comment by peterarsentev** [comment]
Нашел одно задание, где каркас был избыточный. Его поправил. Это задание с записью массива с конца. Если будут еще такие каркасы, то пишите. Все поправим. Спасибо.
