### ISSUE TITLE
RESTFul. Дополнительные знания

### ISSUE THREAD

**Issue by Futsey** [peterarsentev/job4j_features_bugs#1583]
Предположу, что по тексту имеется ввиду URI == расширенная версия URL. Другими словами в тексте задачи опечатка.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/89212538/7c42815c-5167-4a95-b9ed-19835029afb3)

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
