### ISSUE TITLE
ошибка в указании модификаторов класса

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1586]
разве здесь не дефолтный модификатор доступа? получается можно явно указать модификатор файнал или не явно- дефолтный. Если я правильно понимаю
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/8d850c69-1349-4c6e-b437-47c32b3c31f6)

https://job4j.ru/profile/exercise/20/task-view/1032

**Comment by peterarsentev** [comment]
Нет. У локального класса нет модификаторов доступа. локальный класс, как и переменная.
нет смысла писать default String name = ""; Тоже и для локальных классов.
