### ISSUE TITLE
SQL. Неверный ожидаемый результат в задании (6.2. Предложение DISTINCT 2)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1590]
> В ожидаемом результате выводится таблица где вместо столбца id выводится столбец name.
> Решением является следующая строка, которая не соответствует условию задачи:
> `SELECT DISTINCT (name) AS id, name, (grade) FROM subjects ORDER BY name DESC`

**Условие задачи:**
Для представленной ниже схемы subjects напишите запрос, которые выполнит выборку уникальных строк по столбцу name, в выборку должны попасть данные из столбцов id, name и grade. При этом результирующая выборка должна быть отсортирована по полю name по убыванию.

**Схема базы данных:**
```
CREATE TABLE subjects(
    id int not null primary key,
    name text,
    grade int,
    start_date timestamp
);
```

**Данные:**
```
INSERT INTO subjects VALUES(1, 'Math', 75, current_date);
INSERT INTO subjects VALUES(2, 'English', 85, current_date);
INSERT INTO subjects VALUES(3, 'Math', 50, current_date);
INSERT INTO subjects VALUES(4, 'Computer Science', 95, current_date);
INSERT INTO subjects VALUES(5, 'English', 75, current_date);
INSERT INTO subjects VALUES(6, 'Computer Science', 85, current_date);
```

**Ваш запрос:**
`SELECT DISTINCT (id), name, (grade) FROM subjects ORDER BY name DE`

**Решение(ERROR):**
Неверный тип столбца. Ожидалось VARCHAR получено INTEGER. 

**Результат** 
```
ID;NAME;GRADE;
1;Math;75;
3;Math;50;
2;English;85;
5;English;75;
4;Computer Science;95;
6;Computer Science;85;
```
 
**Ожидаемые данные** 
```
ID;NAME;GRADE;
Math;Math;50;
Math;Math;75;
English;English;75;
English;English;85;
Computer Science;Computer Science;85;
Computer Science;Computer Science;95;
```

**Comment by peterarsentev** [comment]
@DFG-ru У тебя же в запросе не хватает полей.
Distinct - это список полей для уникальности, а после идут поля, которые нужно вывести.
SELECT DISTINCT (id), name, (grade) FROM subjects ORDER BY name DE

**Comment by DFG-ru** [comment]
> @DFG-ru У тебя же в запросе не хватает полей. Distinct - это список полей для уникальности, а после идут поля, которые нужно вывести. SELECT DISTINCT (id), name, (grade) FROM subjects ORDER BY name DESC

В условии сказано, что уникальность проверяется по столбцу "_name_", а остальные столбцы просто выводятся. Но не в этом суть. Суть в том, что **_ожидаемый результат_** в задании выводит столбец "_id_" с содержимым соседнего столбца, просто дублируя его. Вот на примере:

**Как должно быть в ожидаемом результате:**
```
ID;NAME;GRADE;
1;Math;75;
3;Math;50;
2;English;85;
5;English;75;
4;Computer Science;95;
6;Computer Science;85; 
```

**Что имеем:**
```
ID;NAME;GRADE;
Math;Math;50;
Math;Math;75;
English;English;75;
English;English;85;
Computer Science;Computer Science;85;
Computer Science;Computer Science;95; 
```
