### ISSUE TITLE
Изменение порядка следования комментариев

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1592]
Очень хотелось бы, чтобы комментарии в заданиях отображались в порядке **от нового к старому** сверху вниз!
На данный момент приходится долго скроллить вниз, чтобы прочитать свежие комментарии от ребят на актуальные темы.

**Comment by quarvin** [comment]
Также крайне неудобно, что необходимо скроллить в самый низ ленты обсуждений, чтобы добавить новый комментарий. После скроллинга теряется текст задания и приходится открывать дополнительную вкладку.

Желал сейчас добавить фидбек о пройденном блоке, но пришлось пролистывать 119 комментариев других студентов :/

Хотелось бы, чтобы комментарий можно было бы написать в самом верху ленты обсуждений, а не скроллить вниз, ища кнопку ответить. С точки зрения UX дизайна это крейне привычно и удобно!

**Comment by quarvin** [comment]
К тому же замечательно было бы увидеть возможность форматировать текст, как, например, в данном поле, где я сейчас пишу этот комментарий. 
<img width="429" alt="image" src="https://github.com/peterarsentev/job4j_features_bugs/assets/113067498/d5e8d9be-7332-45fe-96f7-4749f01f8ca0">

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
