### ISSUE TITLE
[BUG] Некорректная работа кнопки  "Сохранить и перейти далее"

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1593]
# Сохраняется текст в поле "Отправить на проверку" на странице следующего задания при отправке ответа с помощью кнопки "Сохранить и перейти далее"

## Шаги:

1. Открыть любое задание
2. В поле "Отправить на проверку" вставить любой текст
3. Нажать кнопку "Сохранить и перейти далее"

## Ожидаемый результат:

- Открылась страница следующего задания
- Поле "Отправить на проверку" пустое

## Фактический результат:

- Открылась страница следующего задания
- _**Поле "Отправить на проверку" заполнено данными с предыдущей страницы**_

<img width="520" alt="image" src="https://github.com/peterarsentev/job4j_features_bugs/assets/113067498/299810cf-df8a-4b57-a9cc-777ed8aee2a0">

> Google Chrome: **Версия 110.0.5481.177 (Официальная сборка), (arm64)**

**Comment by peterarsentev** [comment]
@BroadRey, подскажи, а воспроизводиться стабильно?

**Comment by peterarsentev** [comment]
Закрываю.
