### ISSUE TITLE
Курс Джуниор 10. Реализовать собственную структуру данных - HashMap [#1008 # [#1008 #427398]]

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1594]
В 10 задании по теме мап мы создаем свой интерфейс с именем Мар из-за чего код в классе Юзер из предыдущих заданий перестает корректно работать тк там мы использовали настоящий Мар интерфейс. Возможно стоит упомянуть для учеников что класс Юзер можно удалить, либо в 10ом задании делать интерфейс не Мар, а с другим именем, чтобы не было конфликтов в пакете с этой группой уроков

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
