### ISSUE TITLE
[BUG] Некорректная работа кнопки "Копировать название"

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1595]
# Добавляются лишние символы в буфер обмена при нажатии на кнопку "Копировать название"

## Шаги:

1. Перейти на [страницу](https://job4j.ru/profile/exercise/13/task-view/60)
2. Нажать на кнопку "Копировать название"

## Ожидаемый результат:

- В буфер обмена скопировался текст "**4.3.2. Сокращенный оператор || [#333784]**"
- Название задания не изменилось

## Фактический результат:

- В буфер обмена скопировался текст "**4.3.2. Сокращенный оператор || [#333784  [#333784 #427802]]**"
- Название задания изменилось на "**4.3.2. Сокращенный оператор || [#333784  [#333784 #427802]]**" (см. скрин)
<img width="485" alt="image" src="https://github.com/peterarsentev/job4j_features_bugs/assets/113067498/5b43cf1c-c234-480c-aabf-661bc9bd5080">

> Google Chrome: Версия 114.0.5735.198 (Официальная сборка), (arm64)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
