### ISSUE TITLE
[BUG] Невозможно удалить собственный комментарий/ответ

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1596]
# Невозможно удалить собственный комментарий/ответ на чужой комментарий после подтверждения удаления

## Шаги:

1. Открыть [задание](https://job4j.ru/profile/exercise/2/task-view/101)
2. Нажать кнопку "Загрузить обсуждения"
3. Нажать кнопку "Ответить" под любым имеющимся комментарием
4. Добавить новый ответ/комментарий с текстом "Тестовый комментарий"
5. Удалить комментарий, добавленный в пункте 4, с помощью кнопки-крестика
7. Подтвердить удаление комментария

## Ожидаемый результат:

- Комментарий удален

## Фактический результат:

- Ничего не произошло

> Google Chrome: **Версия 110.0.5481.177 (Официальная сборка), (arm64)**

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
