### ISSUE TITLE
2. Экзамен. Ввод-вывод. [#571 #428117] Ошибка в вопросе онлайн теста

### ISSUE THREAD

**Issue by fedorovse** [peterarsentev/job4j_features_bugs#1597]
Вопрос звучит так: Какой / какие из перечисленных классов не наследуются от интерфейсов InputStream и OutputStream?
Но ведь InputStream и OutputStream это абстрактные классы, а не интерфейсы. Поправьте, пожалуйста.

**Comment by peterarsentev** [comment]
Спасибо. Поправили. InputStream и OutputStream - это абстрактные классы.
