### ISSUE TITLE
1. Виды сборщиков мусора [#6852 # [#6852 #428230]]

### ISSUE THREAD

**Issue by GHMember** [peterarsentev/job4j_features_bugs#1598]
О Parallel GC

Oт Красов Василий[#404224]06.09.2022 12:35
"Плюс: пошустрее чем Serial GC. Минус: недостаточно быстрый, по сравнению с Serial" - это ведь взаимоисключающее выражение

**Comment by peterarsentev** [comment]
Спасибо. Поправил.
