### ISSUE TITLE
[BUG] Некорректная работа кнопки "Копировать код"

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1599]
# Не копируется часть исходного кода класса Triangle при нажатии кнопки "Копировать код"

## Шаги:

1. Перейти на [страницу](https://job4j.ru/profile/exercise/20/task-view/142)
2. Найти исходный код класса Triangle
3. Нажать на кнопку "Копировать код"

## Ожидаемый результат:

- В буфер обмена скопировался весь исходный код класса

# Фактический результат:

- Копирование произошло только до 27 строки кода (см. скрин)

<img width="483" alt="image" src="https://github.com/peterarsentev/job4j_features_bugs/assets/113067498/e90b782f-be85-449d-ab8f-04713a077ac4">

> Google Chrome: Версия 114.0.5735.198 (Официальная сборка), (arm64)

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
