### ISSUE TITLE
Нужно добавить тест. (Упражнения / 1.1.4. Оператор ветвления / 49. Необычные пары)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1600]
> Нужно добавить тест на условие "первая буква первой строки равна последней букве второй строки", иначе задачу можно решить без использования составного уравнения

**Условие:**
Метод принимает две строки, на выходе метод должен вернуть булево значение. Метод необходимо реализовать таким образом, чтобы:

1. Если обе строки пустые - метод должен вернуть true.

2. Если первая буква первой строки равна последней букве второй строки И последняя буква первой строки равна первой букве второй строки - метод должен вернуть true.

3. Во всех остальных случаях метод должен вернуть false.

Для извлечения символов из строки используйте метод charAt() класса String.

**Решение которое должно быть по условию задачи**
```
package ru.job4j.condition;

public class PairsCharString {
    public static boolean check(String l, String r) {
      	if (l == "" && r == "") {
            return true;
        }
	if (l.charAt(0) == r.charAt(r.length() - 1) && l.charAt(l.length() - 1) == r.charAt(0)) {
            return true;
        }
        return false;
    }
}
```

**Решение не по условию задачи**
```
package ru.job4j.condition;

public class PairsCharString {
    public static boolean check(String l, String r) {
      	if (l == "" && r == "") {
            return true;
        }
	if (l.charAt(0) == r.charAt(r.length() - 1)) == r.charAt(0)) {
            return true;
        }
        return false;
    }
}
```

**Прилагаю готовый тест**
```
@Test
public void checkFalse() {
    boolean rsl = PairsCharString.check("eagle", "like");
    assertThat(rsl, is(false));
}
```

**Comment by peterarsentev** [comment]
Спасибо. Добавил.
