### ISSUE TITLE
[BUG] Опечатка в названии класса

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1601]
# Неверное название класса в уроке 0.1. java.lang.NullPointerException [#219364]

## Шаги:

1. Перейти на [страницу](https://job4j.ru/profile/exercise/24/task-view/190)
2. Пролистать до первого пункта задания

## Ожидаемый результат:

- Первый пункт задания состоит из следующего текста:
"Ниже представлен класс ru.job4j.ex.FindMaxLength. Запустите этот класс."

# Фактический результат:

- Первый пункт задания состоит из следующего текста:
"Ниже представлен класс ru.job4j.ex.**_FindMaxLenght_**. Запустите этот класс."

> Google Chrome: Версия 114.0.5735.198 (Официальная сборка), (arm64)

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
