### ISSUE TITLE
[BUG] Не исчезает уведомление о новом обсуждении при переходе в другие разделы

### ISSUE THREAD

**Issue by quarvin** [peterarsentev/job4j_features_bugs#1602]
## Предварительные шаги:

1. Получить уведомление о новом обсуждении

## Шаги:

1. Перейти на страницу уведомлений о новых обсуждениях
2. Очистить список уведомлений
3. Перейти в раздел "Уроки", выбрав соответствующий пункт в меню навигации 

## Ожидаемый результат:

- Синий значок с количеством новых уведомлений исчез

# Фактический результат:

- Синий значок с количеством новых уведомлений по-прежнему отображается

<img width="479" alt="image" src="https://github.com/peterarsentev/job4j_features_bugs/assets/113067498/a04eb792-5ab0-49de-81d5-22828ee8c9c3">

> Google Chrome: Версия 114.0.5735.198 (Официальная сборка), (arm64)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
