### ISSUE TITLE
Подключение css/js через Thymeleaf

### ISSUE THREAD

**Issue by ibobrov** [peterarsentev/job4j_features_bugs#1603]
Предлагаю добавить маленький туториал в блок веб.

Оригинальное собщение в тг, в Job4j 3. Middle:

"Илья, [16.07.2023 23:24]
В блоке веб чего-то совсем нет js и css. Не то чтобы мне надо было. Но я не сразу догадался как подключить css тот же из под спринга. Оказалось всё очень просто... "<script th:src="@{/js/bootstrap.5.3.0/bootstrap.min.js}"></script>". Было бы достаточно просто намекнуть что под это дело в resources заводится static, а тайлифом это подключается.

Илья, [16.07.2023 23:28]
Сразу и пример очень простенький. Бустрап закинул локально а не через sdn."

+Туда же css/img (для футера картинка/лого/иконка сайта в браузере)

**Comment by ibobrov** [comment]
th:src и с ref работает тоже (th:ref), методом тыка выяснил.

**Comment by peterarsentev** [comment]
Добавили урок. https://job4j.ru/profile/exercise/183/task-view/1159 
Спасибо.
