### ISSUE TITLE
Экзамен "Java Collection. Продвинутый уровень"

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1604]
Неправильный ответ в вопросе:
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/112828576/8cac3954-ef8c-4b5d-b4d8-f2be04234e82)
В таблице из урока худшая сложность **О(n)** , как и в других источниках в интернете
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/112828576/f8f7f0fd-fd7a-47a4-bd3e-6b200e8de42f)

Также у двух вопросов в тесте некорректная формулировка, вводящая в заблуждение:
"Сколько ключей **с значением null** может хранится в HashMap?" - так как в мапах мы имеем ключ и значение -> и понять это можно как "ключи соотносящиеся со значением" ключ равен х, значение равно null. тогда как в задании имеется ввиду "Сколько ключей **равных** null может хранится в HashMap?". 

Для тестов очень важно, чтобы формулировка задания не имела двоякой интерпретации. Ученик должен думать над самим вопросом а не над тем, о чем его хотели спросить))

**Comment by peterarsentev** [comment]
@Sveeta2000 
1. Тут же указывается, что в карте нет коллизий. Если в карте есть коллизии, то время конечно будет O(n).
2. Тут поправили. Спасибо.

**Comment by Sveeta2000** [comment]
1. Написано дословно "присутствуют коллизии" :) на скриншоте видно даже))

**Comment by Sveeta2000** [comment]
Не знаю, приходит ли оповещение по закрытым темам в гитхабе, поэтому тут продублирую:
В задании чётко написано что "присутствуют коллизии", не наоборот)) это видно в скриншоте задания
--
Светлана Кашина  пятница, 28 июля 2023г., 16:13 +03:00 от Petr Arsentev  ***@***.*** :
