### ISSUE TITLE
Про Docker Compose

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1605]
В теме:
6. Многоэтапная сборка [#504902
частично затрагивалась тема Docker Compose

Не знаю, будет ли отдельная тема про Docker Compose,
но предложил бы несколько ссылок для ознакомления.
По документации можно начать  здесь:
https://docs.docker.com/compose/compose-file/02-model/
https://docs.docker.com/compose/compose-file/build/
И маленький пример с пояснениями, как это работает
https://github.com/yarmail/docker_compose

**Comment by peterarsentev** [comment]
Спасибо. Добавил ссылки.
