### ISSUE TITLE
Нужно добавить тест. (Упражнения / 1.1.4. Оператор ветвления / 58. Счастливый билет)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1606]
> Нужно добавить тест на проверку на неравенство четных сумм как сказано в условии. Иначе задачу можно решить проверкой четности без проверки равенства.

**Условие:**
Пусть выигрышным считается такой билет, где сумма первых трех цифр входящего числа равна сумме последних трех цифр этого числа, и обе эти суммы являются четными.

**Решение которое должно быть по условию задачи**
```
package ru.job4j.condition;

public class Task58 {
    public static void isWinning(int number) {
        int first = (number / 100000 + number / 10000 % 10 + number / 1000 % 10);
      	int second = (number % 10 + number / 10 % 10 + number / 100 % 10);
      	boolean even = first % 2 == 0 & second % 2 == 0;
      	System.out.println(first == second & even ? "Да" : "Нет");
    }
}
```

**Решение не по условию**
```
package ru.job4j.condition;

public class Task58 {
    public static void isWinning(int number) {
        int first = (number / 100000 + number / 10000 % 10 + number / 1000 % 10);
      	int second = (number % 10 + number / 10 % 10 + number / 100 % 10);
      	System.out.println(first == second ? "Да" : "Нет");
    }
}
```

**Прилагаю готовый тест**
```
@Test
    public void when532336ThenNo() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task58.isWinning(532336);
        String expected = "Нет" + ln;
        assertThat(out.toString(), is(expected));
    }
```

**Comment by peterarsentev** [comment]
@DFG-ru А в чем смысл твоего теста? У нас есть аналогичный. Или твое решение проходит наш тест, но не проходит твой?

**Comment by DFG-ru** [comment]
Просто в условии задания сказано что нужно проверить равны ли 2 суммы и проверить являются ли они четными. Я же смог решить это задание просто сравнив две суммы, без проверки четности. Поэтому я и дал вам тест в котором суммы равны, но не являются четными.

**Comment by DFG-ru** [comment]
Оу, я не то число в тесте написал... Четное с нечетным спутал...
Вот подходящее число для теста: 151214.
В нем равны суммы, но они нечетные.
