### ISSUE TITLE
Нужно добавить тест. (Упражнения / 1.1.4. Оператор ветвления / 62. Расположены ли цифры трехзначного числа в порядке возрастания)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1608]
> Нужно добавить тест для ситуации когда в трехзначном числе десятки больше чем сотни и сотни меньше единиц.

**Условие:**
Написать код, который проверяет, располагаются ли цифры этого числа в порядке возрастания (первая - наименьшая, третья - наибольшая, все цифры разные), и выводит в консоль "Да", если располагаются, и "Нет", если не располагаются.
Например, для числа 156 вывод будет: Да

**Решение которое должно быть по условию задачи**
```
package ru.job4j.condition;

public class Task62 {
    public static void isRising(int number) {
        System.out.println(number % 10 > number / 100 && number / 10 % 10 < number % 10 ? "Да" : "Нет");
    }
}
```

**Решение не по условию**
```
package ru.job4j.condition;

public class Task62 {
    public static void isRising(int number) {
        System.out.println(number % 10 > number / 100 ? "Да" : "Нет");
    }
}
```

**Прилагаю готовый тест**
```
@Test
    public void when264ThenNo() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task62.isRising(264);
        String expected = "Нет" + ln;
        assertThat(out.toString(), is(expected));
    }
```

**Comment by peterarsentev** [comment]
Спасибо. Добавил.
