### ISSUE TITLE
Ошибка в тесте (Упражнения / 1.1.4. Оператор ветвления / 73. Является ли средняя цифра трехзначного числа меньше остальных)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1609]
> В названии теста указано проверка числа 101, а внутри проверяется 100

**Условие:**
Написать код, который определяет, является ли средняя цифра этого числа меньше остальных. Вывести в консоль "Да", если является, и "Нет", если не является.

Например, для числа 426 вывод будет: Да.

@Test
    public void when101ThenNo() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task73.midDigitLess(100);
        String expected = "Нет" + ln;
        assertThat(out.toString(), is(expected));
    }

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
