### ISSUE TITLE
5.2. BufferedOutputStream [#252490  [#252490 #432504]] и 5.1. BufferedReader [#252489 # [#252489 #432475]]

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1610]
В уроках  **5.1. BufferedReader** [#252489 # [#252489 #432475]] и **5.2. BufferedOutputStream** [#252490  [#252490 #432504]]  по непонятным причинам расходится код домашнего задания, в первом уроке метод не статический, в втором этот же метод уже статический, не понятно почему так. Выглядит как будто хотели что-то исправить и исправили только в одном из уроков(отмечено желтым). 
Также в задании неправильно указана сигнатура метода save (отмечено голубым)
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/112828576/bcece541-0994-4f5a-b4c8-4beb1885e9bd)
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/112828576/6677f089-6670-48b1-8298-cf17739668de)

**Comment by peterarsentev** [comment]
Спасибо. Поправил.
