### ISSUE TITLE
Java IDE онлайн в браузере (Github Codespaces)

### ISSUE THREAD

**Issue by apereslavtsev** [peterarsentev/job4j_features_bugs#1611]
С недавних пор у меня остался только рабочий ноут, на котором нет админских прав и нельзя установить java окружение для разработки. 

Вышел из ситуации с помощью GitHub codespaces (удаленная виртуальная машина от github, в которой можно работать из браузера), на котором с помощью docker можно установить все необходимое для работы с java. 

Вдруг кому-то будет полезно если слабый пк, или тоже нет админских прав.
Единственный минус - бесплатно всего 60 часов работы в месяц, 

Docker файлы настройки, по которым устанавливается java и PostgreSQL можно посмотреть в проекте: 
https://github.com/apereslavtsev/job4j_todo/tree/master/.devcontainer

**Comment by peterarsentev** [comment]
Спасибо. Антон. Посмотрел, буду иметь ввиду.
