### ISSUE TITLE
Добавили урок. https://job4j.ru/profile/exercise/183/task-view/1159

### ISSUE THREAD

**Issue by ibobrov** [peterarsentev/job4j_features_bugs#1613]
Добавили урок. https://job4j.ru/profile/exercise/183/task-view/1159 
Спасибо.

_Originally posted by @peterarsentev in https://github.com/peterarsentev/job4j_features_bugs/issues/1603#issuecomment-1656675263_

**Comment by ibobrov** [comment]
https://job4j.ru/profile/exercise/188/task/945/429747

В этой задаче фильтр заблочит статик 

```java
private boolean isAlwaysPermitted(String uri) {
        return uri.startsWith("/users/register") || uri.startsWith("/users/login")
                || uri.startsWith("/js") || uri.startsWith("/css") || uri.startsWith("/img");
}
```

**Comment by peterarsentev** [comment]
Спасибо. Добавил.
