### ISSUE TITLE
 3.2.2. Html, Bootstrap, Thymeleaf \ Статические ресурсы: CSS, JS 

### ISSUE THREAD

**Issue by Slepchenko** [peterarsentev/job4j_features_bugs#1615]
Проблема со ссылкой на jquery: https://code.jquery.com/jquery-3.7.0.min.js 

![изображение](https://github.com/peterarsentev/job4j_features_bugs/assets/60807965/f274bd7e-da9d-4117-8d34-e95b4a90ea97)

**Comment by peterarsentev** [comment]
Он тебе файл отдает. Тебе его нужно сохранить. Нажми сохранить как и выбери файл.
