### ISSUE TITLE
Reply: SQL. Ошибка компиляции схемы задачи (6.3. Предложение DISTINCT 3)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1617]
> _Поправили ошибку. У нас схема запускается через H2, а синтаксис описали PostgreSQL. 
> Попробуй, если не получиться, то снова заведи ошибку._
> 
> _Originally posted by @peterarsentev in https://github.com/peterarsentev/job4j_features_bugs/issues/1591#issuecomment-1662558435_

> Задание заработало, но по какой то причине при выборке уникальных значений по "price" игнорирует скобки столбца "id" и выводит все строки таблицы т.к. в "id" все значения уникальны.

**Условие:**
Для представленной ниже схемы products напишите запрос, который выполнит выборку уникальных строк по столбцу price. В выборке должны быть отображены все столбцы, сортировка должна быть по полям name, price и count.

**Схема базы данных:**
```
CREATE TABLE products(
    id int not null primary key,
    name text,
    price int,
    count int
);
```

**Данные:**
```
INSERT INTO products VALUES(1, 'bread', 50, 10);
INSERT INTO products VALUES(2, 'milk', 75, 15);
INSERT INTO products VALUES(3, 'sugar', 105, 30);
INSERT INTO products VALUES(4, 'bread', 50, 10);
INSERT INTO products VALUES(5, 'milk', 68, 15);
INSERT INTO products VALUES(6, 'sugar', 105, 30);
INSERT INTO products VALUES(7, 'bread', 45, 10);
INSERT INTO products VALUES(8, 'milk', 75, 15);
INSERT INTO products VALUES(9, 'sugar', 105, 30);
INSERT INTO products VALUES(7, 'bread', 45, 10);
INSERT INTO products VALUES(8, 'milk', 75, 15);
INSERT INTO products VALUES(9, 'sugar', 105, 30);
```

**Запрос согласно условию задачи:**
`SELECT DISTINCT (id), (name), price, (count) FROM products ORDER BY name, price, count ASC`

**Результат:**
```
ID;NAME;PRICE;COUNT;
7;bread;45;10;
1;bread;50;10;
4;bread;50;10;
5;milk;68;15;
2;milk;75;15;
8;milk;75;15;
3;sugar;105;30;
6;sugar;105;30;
9;sugar;105;30;
```

**Запрос без столбца id:**
`SELECT DISTINCT (name), price, (count) FROM products ORDER BY name, price, count ASC`

**Результат:**
```
NAME;PRICE;COUNT;
bread;45;10;
bread;50;10;
milk;68;15;
milk;75;15;
sugar;105;30;
```

**Ожидаемые данные**
```
ID;NAME;GRADE;
Math;Math;50;
Math;Math;75;
English;English;75;
English;English;85;
Computer Science;Computer Science;85;
Computer Science;Computer Science;95;
```

**Comment by peterarsentev** [comment]
Спасибо. Переписал реализацию на PostgreSQL. Теперь синтаксис для упражнений одинаковый.
