### ISSUE TITLE
4.2. Транзакции. Свойства ACID [#504811  [#504811]] Не рабочие ссылки на доп материал

### ISSUE THREAD

**Issue by Svetlana44** [peterarsentev/job4j_features_bugs#1620]
По теме 4.2. Транзакции. Свойства ACID [#504811  [#504811]]
на странице
https://job4j.ru/profile/exercise/179/task-view/806
не рабочая ссылка в дополнительных материалах (1, 4, 6)
https://www.bmc.com/blogs/acid-atomic-consistent-isolated-durable/
https://proselyte.net/tutorials/sql/sql-transactions/
https://codingsight.com/understanding-dirty-read-problem-sql-server/
![2023-08-06_11h00_47](https://github.com/peterarsentev/job4j_features_bugs/assets/66846228/3bc3845f-5f83-4827-8fd2-87cd5231ebea)
![2023-08-06_11h07_18](https://github.com/peterarsentev/job4j_features_bugs/assets/66846228/487158f8-0999-40fd-afdb-0cb9ea3dbbd1)
![2023-08-06_11h05_22](https://github.com/peterarsentev/job4j_features_bugs/assets/66846228/2831c2ed-c4dd-4f62-a5ea-4cdbc0c5aceb)

**Comment by staskorobeynikov** [comment]
Указанных ссылок нет
Еще удалил одну, страница не была найдена
