### ISSUE TITLE
SQL. Проблемы с выводом и ожидаемым результатом (6.3. Предложение DISTINCT 3)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1622]
> В ожидаемом результате вместо id дублируется другой столбец, а также компилятор игнорирует скобки столбца id в запросе DISTINCT и выводит строки по уникальным значениям столбца id (то есть все строки).

**Условие:**
Для представленной ниже схемы products напишите запрос, который выполнит выборку уникальных строк по столбцу price. В выборке должны быть отображены все столбцы, сортировка должна быть по полям name, price и count.

**Схема базы данных:**
```
CREATE TABLE products(
    id int not null primary key,
    name text,
    price int,
    count int
);
```

**Данные:**
```
INSERT INTO products VALUES(1, 'bread', 50, 10);
INSERT INTO products VALUES(2, 'milk', 75, 15);
INSERT INTO products VALUES(3, 'sugar', 105, 30);
INSERT INTO products VALUES(4, 'bread', 50, 10);
INSERT INTO products VALUES(5, 'milk', 68, 15);
INSERT INTO products VALUES(6, 'sugar', 105, 30);
INSERT INTO products VALUES(7, 'bread', 45, 10);
INSERT INTO products VALUES(8, 'milk', 75, 15);
INSERT INTO products VALUES(9, 'sugar', 105, 30);
INSERT INTO products VALUES(7, 'bread', 45, 10);
INSERT INTO products VALUES(8, 'milk', 75, 15);
INSERT INTO products VALUES(9, 'sugar', 105, 30);
```

**Запрос по условию задачи:**
`SELECT DISTINCT (id), (name), price, (count) FROM products ORDER BY name, price, count ASC`

**Результат:**
```
id;name;price;count;
7;bread;45;10;
1;bread;50;10;
4;bread;50;10;
5;milk;68;15;
2;milk;75;15;
8;milk;75;15;
3;sugar;105;30;
6;sugar;105;30;
9;sugar;105;30;
```

**Должно быть результат:**
```
id;name;price;count;
7;bread;45;10;
1;bread;50;10;
5;milk;68;15;
2;milk;75;15;
3;sugar;105;30;
```

**Ожидаемые данные в задаче**(вместо id дублирует price)
```
id;name;price;count;
45;bread;45;10;
50;bread;50;10;
68;milk;68;15;
75;milk;75;15;
105;sugar;105;30;
```

**Comment by AlexeyEsipov** [comment]
Исправил скрипт ответа
