### ISSUE TITLE
Поиск задания по номеру задания в трекере

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1624]
К сожалению не работает (по крайней мере у меня)
поиск в трекере по номеру задания - вообще ничего не выдает.
Пробовал по-разному: [#504947], #504947, 504947, руками набирал.
Возможно вроде бы раньше была, но с течением времени отвалилась, или её отключили.
Проверьте пожалуйста, иногда бывает удобнее и быстрее работать 
с номером задания чем с названием.

<img width="354" alt="Screenshot_1" src="https://github.com/peterarsentev/job4j_features_bugs/assets/46091342/535103fa-7458-429d-b896-e74af97400f4">

**Comment by peterarsentev** [comment]
Добавил. Спасибо.
