### ISSUE TITLE
Не заполнен урок 2. Spring boot. embedded server. [#504900 #384525]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1625]
Урок: 2. Spring boot. embedded server. [#504900 #384525]
https://job4j.ru/profile/exercise/103/task/980/384525

К сожалению до сих пор не заполнен этот урок.
Если я правильно понимаю, то ссылка на документацию должна быть
(на текущую версию) куда-то сюда:
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.webserver

И речь должна быть о том, что каждое веб-приложение Spring Boot 
включает встроенный веб-сервер. И далее информация о том, 
как мы можем это дело настроить

**Comment by staskorobeynikov** [comment]
Исправлено
