### ISSUE TITLE
Нужно добавить тест. (Упражнения / 1.1.5. Циклы / 69. Определить количество общих делителей двух чисел в порядке возрастания)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1627]
> В существующих тестах в задаче взяты числа, которые сводят решение к подсчету количества делителей минимального числа из входящих чисел, что не хорошо при большей выборке данных. Происходит это из за того, что в минимальном числе все делители присутствуют во втором числе.
> 
> К примеру 4 и 8:
> у 4 делители - 1, 2, 4
> у 8 делители - 1, 2, 4, 8
> Общих делителей 3
> 
> Для решения достаточно посчитать делители минимального числа не обращая внимания на второе число. Подобное проходит со всеми тестами в задаче.
> 
> Для корректного составления решения нужно добавить тест с числами 40 и 60:
> у 40 делители - 1, 2, 4, 5, 8, 10, 20
> у 60 делители - 1, 2, 4, 5, 6, 10, 12, 15, 20, 30
> Общих делителей 6. Это уже меньше чем общее количество делителей 40. Поэтому такой тест подойдет для проверки корректности решения.

**Условие:**
Написать код, который определяет и выводит в консоль количество общих делителей входящих чисел.
1 и само число тоже считаются делителями.

**Решение которое должно быть по условию задачи**
```
package ru.job4j.loop;

public class Task69 {
    public static void loop(int num1, int num2) {
        int count = 0;
      	int length = Math.max(num1, num2);
      	for (int i = 1; i <= length; i++) {
	    if (num1 % i == 0 && num2 % i == 0 ) {
                count++;
            }
        }
      	System.out.println(count);
    }
}
```

**Мое решение задачи**
```
package ru.job4j.loop;

public class Task69 {
    public static void loop(int num1, int num2) {
        int count = 0;
      	int min = Math.min(num1, num2);
      	for (int i = 1; i <= min; i++) {
            count += min % i == 0 ? 1 : 0;
        }
      	System.out.println(count);
    }
}
```

**Прилагаю готовый тест**
```
@Test
    public void when40And60Then6() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task69.loop(40, 60);
        String expected = "6" + ln;
        assertThat(out.toString(), is(expected));
    }
```

**Comment by AlexeyEsipov** [comment]
Добавил тест.
