### ISSUE TITLE
В упражнении 73. Является ли средняя цифра трехзначного числа меньше остальных блока Java Core ошибка ожидаемого значения в тесте when101ThenNo

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#1628]
По заданию нужно написать код, который определяет, является ли средняя цифра этого числа меньше остальных. Вывести в консоль "Да", если является, и "Нет", если не является.

Например, для числа 426 вывод будет:

Да

Для числа 101 вывод согласно теста "Нет", а должен быть "Да"

![1](https://github.com/peterarsentev/job4j_features_bugs/assets/73313501/e8e3f738-3d71-4971-9899-3e38d297af48)

**Comment by AlexeyEsipov** [comment]
Исправил наименование теста и его код
