### ISSUE TITLE
Добавить обрамление кода в редактор кода https://job4j.ru/

### ISSUE THREAD

**Issue by timk01** [peterarsentev/job4j_features_bugs#1629]
В гитхабе он есть, в гитлабе тоже. 
Можно ли добавить его раздел "отправить на проверку"

![изображение](https://github.com/peterarsentev/job4j_features_bugs/assets/25296074/25a736cf-dde4-4340-9a55-da0bab26fa38)

А-ля пишешь такой код:
int a = 6; 
тыкаешь кнопочку <> (перед "отправить...") - и код внезапно преображается.
какие плюсы: 
удобней читать
сразу есть отличие от кода и текста
есть корелляция с идеей, легче воспринимать/вспоминать

**Comment by peterarsentev** [comment]
@timk01 Подскажи, а где это нужно в курсе? Весь код мы передаем через github. Ученикам только вначале курса нужно одну или две задачи так сделать.

**Comment by timk01** [comment]
Да, скорее вначале. Где "устные задания" и не нужно кидать ссылку на код в ГХ.
Если там дальше таких заданий и вовсе нет - не критично. Наверное.

> @timk01 Подскажи, а где это нужно в курсе? Весь код мы передаем через github. Ученикам только вначале курса нужно одну или две задачи так сделать.

**Comment by peterarsentev** [comment]
Закрываю. В курсе всегда пару задач таких.
