### ISSUE TITLE
Сертификат

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1630]
Предложил бы разработать и выпускать (если ещё нет) 
цифровой сертификат (картинку с именем) об окончании
курса на русском и английском языке как это делают другие конторы.
Можно было бы прикреплять к резюме, на сайтах поиска работы,
к гиту, да мало ли где ещё он может пригодится?

Что вы думаете по этому поводу?
Если хотите можно опрос провести в чатике, посмотреть общее мнение.

**Comment by peterarsentev** [comment]
Да. Напиши мне. Я тебе пришлю сертификат.
