### ISSUE TITLE
Изменить формулировку у экзамена

### ISSUE THREAD

**Issue by timk01** [peterarsentev/job4j_features_bugs#1631]
![image_2023-08-27_20-39-55](https://github.com/peterarsentev/job4j_features_bugs/assets/25296074/b918cd6e-b9c4-4c0d-86dd-e4712c71c384)

Изменить базовый тип - которых 8 - на просто "тип данных". Это намного точнее.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
