### ISSUE TITLE
кривой (?) помник к трекере

### ISSUE THREAD

**Issue by timk01** [peterarsentev/job4j_features_bugs#1632]
https://job4j.ru/profile/exercise/19/task-view/229

есть разный помник - в уроке (выше) и в архиве который предлагают скачать ранее в начале "трекера"

вероятно поэтому вылезает например ошибка уже на этапе тестов (там 3 страницы, ребята с чата говорят вероятно всему виной жакоко)

![image_2023-08-31_18-04-14](https://github.com/peterarsentev/job4j_features_bugs/assets/25296074/a4501f81-a4f0-4b38-a36f-5310f1ff00c3)

**Comment by timk01** [comment]
не разобрался как тут добавлять файлы (как приложение), но да, без жакоки собрался без ошибок 

![изображение](https://github.com/peterarsentev/job4j_features_bugs/assets/25296074/5d035a71-c68f-4a62-8ab0-9c02db4557b1)

**Comment by timk01** [comment]
![изображение](https://github.com/peterarsentev/job4j_features_bugs/assets/25296074/3b3f986a-25ca-4c7d-bd9e-d0f0a806664a)
так - пашет.

**Comment by peterarsentev** [comment]
Спасибо. Поправил описание и поправил настройки pom.xml
