### ISSUE TITLE
Спойлеры для задач (уроков)

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1633]
Предлагаю применять спойлеры к большим урокам.
не как подсказки, а как компактное и аккуратное оформление страницы. 
Попробую привести пример, (вроде здесь поддерживается)
(примерный макет)
---

Урок № такойто
На этом уроке мы пройдем такую тему: Тема
Из предыдущих уроков мы знаем. что
<details>
<summary>Информация из предыдущих  уроков</summary>
Полезно тем, что не надо давать ссылку на другую страницу,
которая может измениться, а можно кратко сформулировать здесь.
Мы не зависим от других страниц.
Те, кто этот материал помнят (ушлые и опытные) не кликают сюда,
а просто читают дальше,
Для новичков (которым надо все разжевать) тоже полезно, 
не надо никуда ходить, все здесь.
</details> 

Мы оставляем открытым только основной важный текст, все вспомогательное
заворачивая в спойлер
Например, пример кода для пояснений

<details>
<summary>Код примера</summary>
Какой-то код<br>
Какой-то код<br>
Какой-то код<br>
Какой-то код <br>
</details> 

Тоже самое с разделами, например, Домашняя Работа
<details>
<summary>Домашняя работа</summary>
Какой-то код<br>
Какой-то код<br>
Какой-то код<br>
Какой-то код <br>
</details> 

Или  Дополнительная литература
<details>
<summary>Дополнительная литература</summary>
Литература<br>
Литература<br>
Литература<br>
Литература <br>
</details> 

Вывод: говоря языком программистов, мы делаем некую оптимизацию на странице,
увеличиваем удобство пользования страницей. 
<details>
<summary>Некоторые плюсы:</summary>
~ Пользователь быстрее может сориентироваться на большой странице и  <br>
"торкнуть" (как говорит Петр") именно в тот раздел, который ему сейчас больше нужен. <br>
~ Благодаря такой компоновки по каждой теме можно дать много материала <br>
(столько сколько нужно для начала понимания новичкам) <br>
~ как я говорил, мы можем отцепится ссылками от других страниц <br>
~ опытным не нужны все вспомогательные разделы, они откроют только самое важное <br>
~ когда при открытии страницы можно её сразу целиком охватить зрением, <br>
проще ориентироваться, чем полчаса проматывать <br>
~ возможно что-то ещё <br>
</details>

**Comment by peterarsentev** [comment]
@yarmail Спасибо, можешь уточнить, какой по объему урок большой, а какой приемлемый ?

**Comment by YarTsin** [comment]
@peterarsentev  
Хороший  вариант как мне кажется, такой (по крайней мере для новичков),
это один, максимум 2 экрана на стационарном компьютере.
(грубо говоря ~40-80 строк текста в текстовом редакторе)
 Соответственно можно сделать логическое более мелкое разбиение на уроки,
 или использовав спойлеры довести большие уроки до этого размера.
 Тогда ученику будет более комфортно работать с таким объемом текста в одном уроке
 ИМХО.

**Comment by peterarsentev** [comment]
Спасибо. Решение такое. Мы добавим оценку времени на чтение текста. Оценим сколько средник урок занимает. Это время будем использовать за основу. Если текст урока занимает в два раза больше, то мы его перепишем.
