### ISSUE TITLE
2. Экзамен. Базовый синтаксис. [#226 #4068]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1634]
Может быть имеет смысл добавить вопрос:
Что такое Java Core? 
Во многих местах видел этот термин, но не понимал, что это означает.
Нашёл одно определение, возможно это правильно?

Что такое Java Core.
Core Java - термин Sun, используемый для обозначения Java Standard Edition (Java SE), стандартной версии и набора связанных технологий.

**Comment by YarTsin** [comment]
Вопрос. 11. 
Расскажите о таблице истинности?
Ссылка 
https://habr.com/ru/post/449190/ 
не работает, доступ закрыт

Таблица истинности также упоминается в новом уроке 
https://job4j.ru/profile/exercise/42/task-view/1044
Побитовые операции

Предлагаю,
1. Либо дать ссылку на другой источник,
2. Либо сделать такую тему в курсе и давать ссылку на неё

**Comment by peterarsentev** [comment]
Спасибо. Добавил ссылку на проверенный источник.
https://ru.wikipedia.org/wiki/Таблица_истинности
