### ISSUE TITLE
Литералы

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1635]
Может быть имеет смыл рассказать побольше о литералах?
В Стажере я встретил это слово только в 
теме
https://job4j.ru/profile/exercise/6/task-view/1000
9.4. Символы в Java и их особенности [#504920]

однако, как я понимаю они используются более широко.
https://javarush.com/groups/posts/literaly-v-java

**Comment by peterarsentev** [comment]
Я все же не хотел из курса делать справочник по языку Java. Литерал - это любые данные и все. Больше ничего не нужно про них знать. Я в своей практике никогда их не использовал.
