### ISSUE TITLE
Опечатка в названии метода 17. Scanner [#504791 #436836]

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1636]
17. Scanner [#504791 #436836]
В следующей строке урока опечатки в методе has**NEXT**TYPE и has**NEXT**Int
"Причем большинство методов можно разделить на **hasTYPE** и nextTYPE, где TYPE - это тип по шаблону которого будет происходить отделение токенов друг от друга. Например, **hasInt(),** nextInt()."
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Scanner.html

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
