### ISSUE TITLE
1. Побитовые операции [#504964]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1637]
https://job4j.ru/profile/exercise/42/task-view/1044

Немножко странным выглядит размещение 
урока 1. Побитовые операции [#504964]
в разделе 2.1.6. Map 

Может быть эта тема относится больше к базовому синтаксису?
(например, В экзамене 2. Экзамен. Базовый синтаксис. [#226 #4068] 
есть вопрос про таблицу истинности из этого урока)

Проверьте пожалуйста

**Comment by peterarsentev** [comment]
Тема побитовых операций - сложная. Поэтому ее проходим во втором уровне. На первом уровне все должно быть легко.
Булева логика и побитовые операции разные темы.
