### ISSUE TITLE
Неправильное определение языка в редакторе

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1638]
На примере
https://job4j.ru/profile/exercise/2/task-view/88

Довольно часто в редакторе неправильно определяется язык кода,
может быть отключить эту функцию (лучше никак чем неправильно)
или сделать везде одну настройку, например "text"

А то некоторые примеры очень странно выглядят

<img width="565" alt="Screenshot_1" src="https://github.com/peterarsentev/job4j_features_bugs/assets/46091342/e882e391-d2b5-460c-b1ba-aab35fb558cc">

**Comment by peterarsentev** [comment]
Поправил. Спасибо. Там не прописан язык. Поэтому подхватывает не то что нужно.
