### ISSUE TITLE
Вывод в виде изображения

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1639]
Это не замечание, это скорее наблюдение.
На примере урока: 
https://job4j.ru/profile/exercise/6/task-view/1000

По моему опыту проще, компактней и удобней после вывода
копировать вывод из консоли в урок в виде текста, чем в виде картинок.
Думаю это, в объемах всего курса может сэкономить определенное
количество места и времени составителя урока (и не только).

Например думаю лучше так:
Вывод:
123

Вывод:
131

чем так:
<img width="629" alt="Screenshot_1" src="https://github.com/peterarsentev/job4j_features_bugs/assets/46091342/3bb0593c-38de-4962-868d-d715842eb640">

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
