### ISSUE TITLE
1. Техническое задание - проект Tracker [#432596]

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#164]
> Задание
> нарисуйте схему взаимодействия.
> Сделай screenshot диаграмму и загрузите ее на сервис **www.prnt.sc.**

Сервис, у меня по крайней мере, не работает корректно, (просто обновляется страница загрузки, не отвечая ссылкой) при этом в поле комментария на курсе есть опция привязки картинки к ответу. 

Как вариант предлагаю уточнить возможность в задании.

**Comment by staskorobeynikov** [comment]
если возникают проблемы - то просто прикладывайте картинку
