### ISSUE TITLE
15. Вывод на консоль надписи "+++!!!!??" (1)

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1641]
15. Вывод на консоль надписи "+++!!!!??" (1)
https://job4j.ru/profile/topics/1/task_code/246/173808

Некоторые не понимают как решать, т.к. самый простой способ,
просто сделать 3 команды SOUT

Думаю было бы хорошо немного подробнее указать, 
что использовать для решения

**Comment by AlexeyEsipov** [comment]
Изменил (уточнил) текст задания и добавил объяснение задания
