### ISSUE TITLE
2. Перегрузка конструктора [#173890 #219459]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1642]
2. Перегрузка конструктора [#173890 #219459]
https://job4j.ru/profile/exercise/21/task/148/219459

На данный момент эта тема находится в разделе Наследование
Job4j/Уроки/1.2.3. Наследование
однако по сути (как я понимаю) никакого отношения к наследованию 
она не имеет.

Предложил бы перенести её в раздел 
Job4j/Уроки/1.2.2. Классы и объекты
например после урока 
1.7. Конструктор   [#173889 #208803]
https://job4j.ru/profile/exercise/20/task/139/208803

**Comment by peterarsentev** [comment]
Согласен. Поправили.
