### ISSUE TITLE
5. Курсор в SQL [#504816] Опечатки

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1647]
В данном примере опечатка - пропущено слово NEXT 
"Сейчас наш курсор находится на позиции 10, давайте прочитаем еще несколько строк с направлением NEXT:

FETCH FROM cursor_products;
FETCH FROM cursor_products;"
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/112828576/ab4f29f8-d895-4553-b0dc-96940e345633)

"**Соответственно** эти запросы вернут нам, **соответственно**, 11 и 12 строки." - > Эти запросы вернут нам, соответственно, 11 и 12 строки.

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
