### ISSUE TITLE
2. Экзамен. Коллекции. [#10097 #4100] 

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1649]
https://job4j.ru/profile/exercise/32/task/234/4100

Вопрос 14 Расскажите о методах Map.
Далее идет ссылка на материал, в котором указаны только основные методы CRUD

Может быть имеет смысл уточнить вопрос, например:
14 Расскажите об основных методах Map

**Comment by staskorobeynikov** [comment]
исправлено
