### ISSUE TITLE
Юзабилити 

### ISSUE THREAD

**Issue by tutbora** [peterarsentev/job4j_features_bugs#165]
Немного раздражает в управлении сайтом) то, что с первого раза не могу попасть по стрелочке, тк часто пользуюсь этим.
[скрин](https://prnt.sc/w3gbjm)
могу посоветовать увеличить количество стрелочек до 4 - 5 штук и поставить пробел или два между ними и словом Job4j

**Comment by peterarsentev** [comment]
Поправили. Но еще не обновил.
