### ISSUE TITLE
0. Map, HashMap [#212652 #309303]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1650]
https://job4j.ru/profile/exercise/29/task/220/309303

Предложил бы в конце урока сделать Заключение, добавить ссылку на документацию,
например:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Map.html

и добавить, типа того что:
1. Мы рассмотрели только основные методы MAP, на самом деле их намного больше.
2. Рекомендуем вам изучать эти методы, они часто используются в программах.

**Comment by staskorobeynikov** [comment]
исправлено
