### ISSUE TITLE
2. Экзамен. Структуры данных и алгоритмы. [#1000 #3937]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1654]
https://job4j.ru/profile/exercise/44/task/303/3937

Думаю, что Maven важная часть разработки, поэтому предложил бы добавить
один или несколько вопросов про него в данный экзамен.

Например открытый вопрос: Расскажите, что вы знаете о Maven

Или парочку закрытых, например
1. Расскажите о package
2. Расскажите о scope

**Comment by YarTsin** [comment]
@peterarsentev 

Еще предложил бы добавить вопросы по Итератору.
Как я понимаю, сейчас там только один вопрос
Что такое итератор.

Но в курсе уже  более широко рассмотрен этот вопрос:
- Это и поведение итератора - fail-safe  fail-fast
- и разница между List итератором и обычным итератором
- и ошибка итератора ConcurrentModificationException
и несколько других уроков.
Может быть имеет смысл добавить вопросов, просмотрев темы,
связанные с Итератором?

**Comment by peterarsentev** [comment]
Спасибо. Про Maven Добавили. а про итератор сейчас сделаем.
Просьба не писать в один issue разные темы.
