### ISSUE TITLE
Ошибки в 2х тестах для упражнения 147. Касса и билеты

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#1655]
Два последних теста (when10And821AThen2And0 и when5And678562Then1And3) с неправильными названиями и ожидаемыми значениями:

1) для предпоследнего теста (when10And821AThen2And0) должно быть название when10And821AThen2And1 и expected = "Покупатели: 2, отказано: 1" ln;

2) для последнего теста (when5And678562Then1And3) должно быть название when5And678562Then1And5 и expected = "Покупатели: 1, отказано: 5" ln;

**Comment by AlenaLosk** [comment]
@peterarsentev возьми, пожалуйста, в работу :)

**Comment by AlenaLosk** [comment]
@itfedorovsa, @AlexeyEsipov, @staskorobeynikov, помогите, пожалуйста, с правкой бага!

**Comment by AlexeyEsipov** [comment]
Исправления внесены.

**Comment by AlenaLosk** [comment]
Спасибо большое!

**Comment by AlenaLosk** [comment]
Спасибо большое!
