### ISSUE TITLE
Экзамен: Java Collection. Продвинутый уровень

### ISSUE THREAD

**Issue by alexvolchkov** [peterarsentev/job4j_features_bugs#1656]
https://job4j.ru/profile/exams/detail/10
Вопрос: Выберите наихудшую временную сложность для HashMap, c учетом того, что в ней присутствуют коллизии.
Система пишет ответ О(1)
В уроке https://job4j.ru/profile/exercise/43/task-view/1083 в таблице О(n)

Вопрос: Можно ли получить значение по ключу в качестве которого выступает объект у которого после сохранения изменилось внутреннее поле?
Система пишет ответ Нет.
Но если переопределить hashCode и изменить поле, которое не входит в расчет hashCode, то значение находится

**Comment by staskorobeynikov** [comment]
1. Исправлено
2. Согласен с кейсом, одна смысла в таком нет. Это лишь отклонения от нормы, которые могут привести лишь к тому, что в итоге разработчик может сильно запутаться и полностью забыть для чего это. Хорошая практика - использовать полностью неизменяемые ключи.
