### ISSUE TITLE
1. Что такое Сериализация? [#313163 #350551]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1659]
https://job4j.ru/profile/exercise/174/task-view/326

Небольшая поправка 1

Было:
"Сериализация – процесс преобразования объектов **в бинарный (т.е. последовательность битов**) или текстовый формат."

Если мы считаем, что у нас есть только потоки байтовые потоки и символьные,
то возможно имеет смысл написать так

Возможно должно быть
"Сериализация это процесс сохранения состояния объекта **в последовательность байт**".
Источник:
1 строка отсюда
https://habr.com/ru/articles/60317/

щщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщщ

Небольшая поправка 2

Было:
"Для стандартной сериализации объекта необходимо в классе имплементировать интерфейс Serializable, этот интерфейс является маркерным, т.е. **нет необходимости реализовывать его методы**"

Должно быть:
 Интерфейс Serializable это интерфейс-маркер; **в нём не задекларировано ни одного метода**.

**Comment by staskorobeynikov** [comment]
исправил
