### ISSUE TITLE
10. Операторы множества в SQL [#504896]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1660]
https://job4j.ru/profile/exercise/179/task-view/976

Цитата:
... "В качестве оператора множества мы можем использовать EXCEPT (в некоторых СУБД используется MINUS, поведение аналогично). Этот оператор вернет результаты, **которые найдены в первом запросе.**"...

Может быть более правильно: - ..."которые есть в первом запросе и отсутствуют во втором?"... - вычитание?

**Comment by staskorobeynikov** [comment]
Исправлено
