### ISSUE TITLE
7. Web. [#289478]

### ISSUE THREAD

**Issue by Sveeta2000** [peterarsentev/job4j_features_bugs#1664]
> _"Некоторые детали класса Grabber  в этом уроке не согласуются с той реализацией, которую делали в предыдущем:
> 
> -метод init не принимал ни каких параметров, теперь принимает
> 
> -конструктора без параметров наоборот не было, теперь он появился <...>
> 
> -что за метод cfg? Из реализации метода web видно, что cfg возвращает Properties. Но тогда  не понятно зачем мы вызываем его в main и ни чему не присваиваем его результат. Возможно внутри себя он еще и что-то инициализирует
> 
> -зачем добавляем в Grabber методы возвращающие объекты других классов, которые являются для Grabber служебными"_

- Это комментарий к уроку от ученика от августа 2023го года.

От себя добавлю, урок действительно сделан очень слабо :( Не понятно, что произошло и почему мне предлагают код, который не сходится с моим проектом, который уже проверил и принял ментор (все задания до этого). Обучение все же предполагает наличие объяснения происходящего на каждом уроке, особенно когда в процессе не участвует непосредственно учитель, которому по ходу можно задавать вопросы.

Очень прошу делать уроки понятными для новичков!

**Код который написан у ученика перед началом данного урока :**  
[мой коммит предыдущего урока](https://github.com/Sveeta2000/job4j_grabber/commit/01d6303284ca9f18e8cdfe11844a2193c569ae43)
**Скриншот из урока :** [7. Web. [#289478]](https://job4j.ru/profile/exercise/56/task-view/365) 
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/112828576/45dbfbb4-fae6-481e-8bac-adfaff326e8a)

**Comment by peterarsentev** [comment]
@Sveeta2000 Поправили описание. Спасибо.
