### ISSUE TITLE
Перенос шаблонов проектирования

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1665]
Предложил бы перенести все вопросы связанные с шаблонами проектирования
из Стажера как минимум в конец Джуниора.

Соображения.
- Стажер довольно сильно перегружен относительно Джуна по 
количеству задач
- Проектированием на Стажере ещё никто толком не занимается,
это довольно сложные вопросы для них.
- У них нет такой сложности задач, где можно применить паттерны.
Даже Синглтон можно применить только при появлении баз данных

А вот в конце Джуниора или дальше можно будет паттерны зарядить   
и алгоритмы повторить на основе например такого листа
https://telegra.ph/Voprosy-po-algoritmam-i-patternam-02-04

**Comment by peterarsentev** [comment]
@yarmail Ты знаешь учить отдельно шаблоны проектирования - это как учить иностранные слова и думать, что изучаешь язык. Без контекста - это неэффективное упражнение. 
В стажере они элегантно вписываются в конъюнктуру ООП. А отдельный блок писать по шаблонам нет смысла.
