### ISSUE TITLE
2. Сервис - Кинотеатр

### ISSUE THREAD

**Issue by gretskih** [peterarsentev/job4j_features_bugs#1666]
Если соблюдать Checkstyle, то количество параметров в конструкторе класса должно быть не более 7.
В техническом задании указана таблица films в которой 8 столбцов, соответственно будет класс с 8 полями.

create table films
(
    id                  serial primary key,
    name                varchar                    not null,
    description         varchar                    not null,
    "year"              int                        not null,
    genre_id            int references genres (id) not null,
    minimal_age         int                        not null,
    duration_in_minutes int                        not null,
    file_id             int references files (id)  not null
);

**Comment by peterarsentev** [comment]
@gretskih, А тут не нужно создавать конструктор. У нас модель данных - это POJO модель, с get set методами. 
Ее заполняет Hibernate.
