### ISSUE TITLE
1. Что такое полиморфизм. [#3819 #404356] 

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1671]
В уроке https://job4j.ru/profile/exercise/23/task-view/164 есть фраза: 

 "Интерфейсы обладают особыми свойствами.
1. Не могут хранить состояния. Внутри интерфейса нельзя создать поля для сохранения в них данных."

Как я понимаю здесь неверная инфа, тк интерфейсы могут содержать статические финальные поля.

Об этом также говорится в уроке https://job4j.ru/profile/exercise/23/task-view/1028

**Comment by oyvey1984** [comment]
Возможно, чтобы не было таких запутавшихся, как я, стоит написать так:
Интерфейсы обладают особыми свойствами.

Не могут хранить состояния. Внутри интерфейса нельзя создать поля для сохранения в них данных у их наследников или у имплементирующих их классов.

**Comment by staskorobeynikov** [comment]
Добавил информацию
