### ISSUE TITLE
0. Виды ссылок [#6854 #177418]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1672]
https://job4j.ru/profile/exercise/61/task/375/177418

Небольшие правки по оформлению
1. В примерах используется не рекомендованные на курсе коменты //
2. Возможно из-за этого часть кода примеров отображается серым

**Comment by staskorobeynikov** [comment]
Поправил. Правда стили оформления изменились, описанные в issue
