### ISSUE TITLE
Добавить вопрос к экзамену по Optional

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1673]
На днях в чате был интересный вопрос, который можно добавить к экзамену по 
Optional или куда-нибудь в темы

Вопрос: В чем разница между методами orElse() и orElseGet()
Ответ(как я понимаю): выражение в orElse() запускается на вычисление в любом случае,
есть ли значение в Optional или нет.
В orElseGet() выражение запускается только в том случае, если значения в Optional нет
Вывод: в некоторых случаях orElseGet() позволяет сэкономить больше ресурсов системы
за счет того, что не выполняет лишних действий

Источник:
https://www.baeldung.com/java-optional-or-else-vs-or-else-get

**Comment by staskorobeynikov** [comment]
Добавил вопрос
