### ISSUE TITLE
UI / UX

### ISSUE THREAD

**Issue by adarnopyh** [peterarsentev/job4j_features_bugs#1675]
При прохождении заданий часто выхожу на исходную страницу для того, что бы визуально понять сколько осталось заданий. Может есть смысл добавить какие-то наглядные поля с прогрессом. После нажатия Следующий хочется видеть шаг не который продвинулся.

Например кнопка Уроки с синим - 126 это поверено или вместе с теми, которые на рассмотрении, сразу не читается. Кнопка Было решено: - что это за цифры? Если отнестись к этому как к заданию, выяснить конечно можно, но это по всей видимости не совсем продуманное намеренное информирование.

**Comment by peterarsentev** [comment]
@adarnopyh, а может быть есть примеры по первому пункту? Что там хотелось бы видеть?
Например 130/12/300, 130 это завершенные, 12 - на проверке, 300 - общее.

**Comment by peterarsentev** [comment]
Поправим дизайн. Добавим к урокам статистику.

**Comment by adarnopyh** [comment]
Я вам отвечу сегодня/завтра. С моей стороны это не жалоба конечно.
Хотелось немного поучавствовать ). И у меня паралельно Coursera курс идёт
по фронту, там очень интерактивно. По силе у вас я думаю сильнее, т.к. всё
нужно читать и понимать самому, на курсере более разжовано и есть
возможность проходить некоторые вещи не вникая, что минус конечно. Пришлю
что имел ввиду по бару.

**Comment by peterarsentev** [comment]
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/694978/ed315f04-ad76-4312-a9d2-d2aac7ebc31b)
Сделали так.
