### ISSUE TITLE
Некоторые ссылки 403 -> 5. Виды тестов для TDD [#504793]

### ISSUE THREAD

**Issue by Svetlana44** [peterarsentev/job4j_features_bugs#1676]
5. Виды тестов для TDD [#504793]
https://job4j.ru/profile/exercise/63/task-view/788

пример не работающих:
![2023-11-11_19h04_56](https://github.com/peterarsentev/job4j_features_bugs/assets/66846228/29b4ad02-2f90-4d64-8b1e-e0cb5dbc0e4d)
![2023-11-11_19h04_16](https://github.com/peterarsentev/job4j_features_bugs/assets/66846228/ac19d24e-1e7b-4978-a771-0a23852c7853)

**Comment by staskorobeynikov** [comment]
Исправлено
