### ISSUE TITLE
Возможно урок не отображается в общем списке.

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1680]
Предпринятые шаги

Я открываю экзамен по многопоточности:
<pre> 
2. Экзамен. Многопоточность. [#1107 #243317]
https://job4j.ru/profile/exercise/77/task/425/243317
</pre>

Нахожу билет
12. Назовите отличия synchronized{} и ReentrantLock.
и кликаю ссылку подсказку: 

3.1.3. Синхронизация ресурсов 7. Блокировки
https://job4j.ru/profile/exercise/73/task-view/991

Значит у нас в разделе 3.1.3 должен быть урок
про блокировки, возможно с номером 7

<img width="594" alt="01" src="https://github.com/peterarsentev/job4j_features_bugs/assets/46091342/1faba87d-75c3-440f-9718-838cfc9b164c">

щщщщщщщщщщщщщщщщщщщщщщщщ

Открываем уроки, раздел  3.1.3.
Тут нет такого урока и такой ссылки

<img width="538" alt="2" src="https://github.com/peterarsentev/job4j_features_bugs/assets/46091342/4fea5070-c045-478f-b963-43f47edd2a7d">

Проверьте пожалуйста, в уроке написано, что он важный и его часто спрашивают

**Comment by staskorobeynikov** [comment]
Задача была перемещена
Ссылку исправил
