### ISSUE TITLE
4. Аттестация [#504878 #461302] 

### ISSUE THREAD

**Issue by 1oogabooga1** [peterarsentev/job4j_features_bugs#1681]
Добавьте пожалуйста упоминание метода getOrDefault() в этом уроке или хотя бы примечание, что требуется поиск доп информации по этой теме. Люди тратят часы в пустую, чтобы понять, что в уроке содержится не вся информация. После прохождения огромного количества уроков, в которых все разжевано до мельчайших деталей или же вся информация дана, человек начинает искать, в первую очередь, проблему в себе, думая что вся информация есть, просто надо ее правильно реализовать. Ссылка на урок - https://job4j.ru/profile/exercise/29/task/958/461302

**Comment by staskorobeynikov** [comment]
Информацию добавил
