### ISSUE TITLE
Введение в Thymeleaf [#505002]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1682]
https://job4j.ru/profile/exercise/183/task-view/1082

Несколько непонятно, два разных определения,
прошу уточнить, указано:

1. Диалект - это синтаксис и набор атрибутов типа "th:"

2. Диалекты - это иерархия шаблонов, тем самым Thymeleaf поддерживает возможность создания своих шаблонов, расширив уже существующие.

**Comment by peterarsentev** [comment]
Эти два определения связаны, но освещают разные аспекты понятия "диалект" в контексте Thymeleaf.

1. **Диалект как синтаксис и атрибуты:**
   Это первое и основное определение. В Thymeleaf диалект — это набор специфических синтаксических конструкций, включая атрибуты (например, `th:text`, `th:if`, `th:each`), которые предоставляют возможности для работы с шаблонами. Эти атрибуты добавляют логику в HTML, делая его динамическим и интерактивным. Например:
   ```html
   <p th:text="${user.name}">Имя пользователя</p>
   ```
   Здесь `th:text` — атрибут, принадлежащий стандартному диалекту Thymeleaf (Standard Dialect), который заменяет содержимое тега значением переменной.

2. **Диалект как иерархия шаблонов и расширение:**
   Здесь говорится о более широком понимании диалектов. Thymeleaf позволяет разработчикам создавать собственные диалекты, добавляя новые атрибуты или функциональность. Это означает, что можно расширить стандартный набор возможностей Thymeleaf, создав пользовательский диалект, который будет работать на уровне структуры иерархии шаблонов. Например, ваш собственный диалект может включать:
   - Пользовательские атрибуты, такие как `custom:attr`.
   - Новые правила рендеринга шаблонов.
   - Интеграцию с другими библиотеками или фреймворками.

Таким образом:
- Первое определение описывает базовые возможности существующих диалектов.
- Второе говорит о том, что диалекты могут быть расширяемыми и настраиваемыми, что позволяет создавать собственные решения поверх Thymeleaf.

**Пример пользовательского диалекта:**
Вы можете реализовать свой диалект для генерации сложных таблиц данных с кастомной логикой. Например:
```html
<table custom:generateTable="dataList"></table>
```
Где `custom:generateTable` — атрибут, принадлежащий вашему диалекту, который автоматически строит таблицу по данным.
