### ISSUE TITLE
Экзамен. Hibernate. [#2090]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1685]
2. Опиши, как конфигурируется Hibernate. Рассказать про hibernate.cfg.xml и про mapping.

В ответе на это вопрос упоминаются JNDI ресурсы
Может быть имеет смысл о них рассказать в курсе?

**Comment by peterarsentev** [comment]
@yarmail Спасибо. Урока не делал, но добавил в вопросы из собеседований.

https://job4j.ru/profile/interview/30/question/785
