### ISSUE TITLE
Каркас шахматной доски, хочется еще заданий на курсе + javafx

### ISSUE THREAD

**Issue by timk01** [peterarsentev/job4j_features_bugs#1687]
Задание крутое. Так, на подумать. Но сырое. 
Можно ли вставить еще блоки: 
1. на логику других фигур + тесты к ним 
2. На Java-fx (который все еще жив, да!!! - и используется), хотя бы теоретическая лекция с детальным разбором "почему сделано так" в классе chess
**Вот это пожалуй главное и первостепенное**

А вообще еще хотелось бы заданий на:
+ доработки логики, когда ты можешь съесть чужую фигуру (сейчас она по логике задачи считается как "непроходимый ландшафт", что никак не верно) кроме короля - ему можно поставить мат (тут еще логика шах - мат, когда оппонент вынужден двигаться королем или другой фигурой, чтобы оного защитить)
+ доработка становления пешки ферзем
+ рокировка
+ доработка интерфейса (чтобы было видно слева цифры, снизу буквы, как на нормальной доске)
+ доработка интерфейса для 1 или 2 игроков
+ таймер... 

Чтобы полноценный проект был, который не стыдно показать и рассказать как там что устроено.

**Comment by peterarsentev** [comment]
@timk01 Спасибо Тимур. Я бы и сам раз проработает этот проект, но ситуация на рынке изменилась. Ты я думаю это тоже видишь.
Я даже пост написал. https://t.me/java_kotlin_hub/75  Ознакомься.
