### ISSUE TITLE
Ну вы уж определитесь) 

### ISSUE THREAD

**Issue by 1oogabooga1** [peterarsentev/job4j_features_bugs#1689]
Тестовый экзамен по теме Stream API - https://job4j.ru/profile/exams/detail/20 
Вопрос "Для чего используется ключевое слово var"
Урок https://job4j.ru/profile/exercise/35/task-view/262
"Стоит подчеркнуть важную особенность - var не является ключевым словом согласно спецификации языка:" 
Правильный ответ на данный вопрос: "Ключевое слово заменяет тип переменной. var name = "Job4j";"

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
