### ISSUE TITLE
Ну, джавадок - все же на английском. Это пожалуй даже и обсуждать не нужно.

### ISSUE THREAD

**Issue by timk01** [peterarsentev/job4j_features_bugs#1690]
https://job4j.ru/profile/exercise/31/task-view/232

Программист пишет документацию не столько для себя, сколько для других программистов (достаточно привести в пример названия переменных/классов/методов на кирилице вместо нормльных английских названий). Если есть минимальный шанс, что мы наткнемся на англоязычного коллегу (или того, кто не так хорошо знает русский), **то давайте-таки писать джавадок на английском (хотя бы простом, я знаю что не все знают английский) и об этом упомянем в уроке.**

Документация на русском языке обычно лишена смысла.

Это как хэшкод и экуалс не переопределять в расчете, что они не будут использоваться в коллекциях -сета- никогда. А может будут ?)

**Comment by peterarsentev** [comment]
Понимаю ваше негодование по этому поводу. В рабочих проектах есть регламент на каком языке описывать JavaDoc. В курсе описание идет на русском.
