### ISSUE TITLE
Вопрос по аннотациям

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1692]
Уже в нескольких тестах и собесах заметил 
вопрос - как создать свою аннотацию?

Если я правильно понимаю, возможно речь 
идет об @interface

Может быть имеет смысл добавить эту тему в курс,
рассказать зачем это может быть нужно 
и привести примеры?

**Comment by peterarsentev** [comment]
@yarmail Спасибо, не стал делать, как отдельный урок, но добавил в раздел собеседования. 
https://job4j.ru/profile/interview/29/question/764 
Можешь проверить свои знания ).
