### ISSUE TITLE
Вопрос № 20 в тесте к экзамену по ООП.

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1693]
Разве в вопросе есть верный вариант ответа?
Разве неправильно  будет создать экземпляр класса как в примере ниже?
Пример:
Dogs dogs = new Dogs;
Dogs.Dog dog = dogs. new Dog();

https://job4j.ru/profile/exams/detail/7/question
20 из 73. Как правильно создать экземпляр внутреннего класса?
Пример

public class Dogs {
    private String name;
    public void eat() {
        System.out.println("Ham!");
    }
    class Dog {
    }
}

Варианты:
Dog dog = new Dog();
Dogs.Dog = new Dogs.Dog();
Dog dog = new Dogs().new Dog();

**Comment by staskorobeynikov** [comment]
Можно и так как указали, только смысл вопроса выбрать тот вариант, которые представлены в вопросе
