### ISSUE TITLE
Не могу удалить коментарий в обсуждениях

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1695]
Проверьте пожалуйста.
Решил перенести комментарий в обсуждениях.
Не могу удалить старый. Например здесь:
https://job4j.ru/profile/exercise/37/task/305/3935
Oт Циновский Ярослав 20.12.2023 22:24
За то смог сохранить пустой комент, что мне кажется неправильным
Может прав не хватает?

**Comment by peterarsentev** [comment]
@yarmail Спасибо, поправили.
