### ISSUE TITLE
Раздел упражнения, блок "Оператор ветвления", задание 19. Четно-красивое трехзначное число

### ISSUE THREAD

**Issue by mihanchik94** [peterarsentev/job4j_features_bugs#1696]
Тесты не учитывают варианта, когда в составе числа 2 цифры нечетные и 1 четная и из-за этого
сейчас для данного задания можно можно написать следующее решение: 

System.out.println((number / 100 + number / 10 % 10 + number % 10) % 2 == 0 ? "Да" : "Нет");

Тесты пропустят его, однако оно неверное (если взять число 112, или любое другое аналогичное по структуре,
оно противоречит условию и должно вывестись "Нет", но код выше выведет "Да").
Мне кажется, подобное условие нужно добавить в тесты, чтобы неверные решения не проходили.

**Comment by staskorobeynikov** [comment]
Внимательно с этим - ..., если каждая из его цифр - четная.
Т.е. на четность надо проверять каждое число отдельно, а не сумму всех чисел.
