### ISSUE TITLE
Исправить метод. Переменные и ссылочные типы данных [#505100 #469352]

### ISSUE THREAD

**Issue by podgorny-k** [peterarsentev/job4j_features_bugs#1698]
https://job4j.ru/profile/exercise/20/task-view/1180

Исправить метод. 

Убрать дублирующийся текст "**"weight: " +**":

    public String info() {
        return "weight: " + weight;
    }

Чтобы результат не был таким:

> weight: weight: 100
> copy of weight: weight: 100
> weight: weight: 110
> copy of weight: weight: 110

**Comment by staskorobeynikov** [comment]
Исправлено
