### ISSUE TITLE
Ошибка в разделе 2. Модель данных. [#398949]

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#17]
В Уровень - Стажер\Блок 2. ООП\3. Инкапсуляция\2. Модель данных ошибка.
 Говориться "Давайте рассмотрим пример модели данных - автомобильные права. В правах есть указания, кто владелец машины, какая марка машины, какой номер, когда собрана."
Но это не права, а тех.паспорт транспортного средства.

**Comment by andreiHi** [comment]
поправили
