### ISSUE TITLE
Откат изменений [#504830 #470377] - Добавить к заданию пункт о скриншоте 

### ISSUE THREAD

**Issue by GotfridW** [peterarsentev/job4j_features_bugs#1700]
В задании указано сделать несколько коммитов, а затем сделать мягкий reset для последующего объединения этих коммитов в один. Не помешало бы добавить пункт о _предварительном скриншоте_ этих коммитов, иначе в финальном объединяющем коммите результаты работы не отражены полноценно.

**Comment by staskorobeynikov** [comment]
Добавил
