### ISSUE TITLE
3.0. Импорт проекта в IDEA [#160822 #463848] - "таких кодов русских символов в таблице  UTF-8 нет"

### ISSUE THREAD

**Issue by kodarov** [peterarsentev/job4j_features_bugs#1701]
```
Потому что таких кодов русских символов в таблице  UTF-8 нет.
Нужно наладить работу IDEA для работы с русскими символами. 
```

[](https://www.charset.org/utf-8/2)
В Windows 11 с последней Idea c UTF-8 отображались русские символы в консоли.

**Comment by staskorobeynikov** [comment]
Такое вполне возможно.
Это уточнение необходимо для того, чтобы при возникновении подобного не было паники и долгих страданий, что с этим делать.
