### ISSUE TITLE
Для раздела 1.4.2. Stream API

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1702]
Нашёл интересный (может быть красивый) способ преобразования строки
чисел в массив чисел. Может быть добавить его в раздел?

Выглядит примерно так:
`String string = "12345"`
`int[] num = string.chars().map(x -> x - '0').toArray();`

**Comment by peterarsentev** [comment]
@yarmail Спасибо Ярослав, могу сказать по статистике собеседований сеньоров, что Stream API пользуются только на начальном уровне, поэтому лучше сфокусировать учеников на микросервисы, а не изящное использование Stream API.
