### ISSUE TITLE
3. Модели данных и HashSet. [#218530] Опечатка

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1704]
В этом уроке в тесте пропущено окончание 'ed' у имени объекта класса  HashSet<Account>

![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/c9a1e8ed-57d9-48a8-933e-85493c36936a)

**Comment by staskorobeynikov** [comment]
исправлено
