### ISSUE TITLE
Вопрос из экзамена ООП

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1705]
В вопросе из экзамена ООП утверждение "Экземпляр класса это описание объекта." считается верным.
Корректно ли это, учитывая что класс - это описание объекта?

Описание:
Какие утверждения верны?

Варианты:
Класс это описание объекта (его полей и методов).
 Правильный ответ
Конструктор используется для создания класса
Конструктор используется для создания объектов.
 Правильный ответ
Статические методы можно вызвать без создания объекта.
 Правильный ответ
Нестатические методы можно вызвать для созданных объектов.
 Правильный ответ
Экземпляр класса это описание объекта.
 Правильный ответ

![image](https://github.com/peterarsentev/job4j_features_bugs/assets/106574154/9a0fd0ca-a602-424b-ab6f-7c71231a5013)

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
