### ISSUE TITLE
Оплата курса

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1706]
Возможно у меня недостаточно информации, но вот какие мысли пришли.

Сегодня заметил вот что.
Люди в чате Стажера переживали за повышение оплаты.
Лично я не видел за последнее время сообщений о повышении

Может быть имеет смысл заранее предупреждать о повышении оплаты 
на Стажере, чтобы те, кто сомневается имели возможность оплатить 
до повышения. Это будет выгодно и для них и для вас.

**Comment by peterarsentev** [comment]
Спасибо, Ярослав. Я уже раз пробовал такое делать, но потом вышло боком. Многие ученики оплатили весь курс и потом не стали продолжать. Они начали писать мне, чтобы я вернул им оплату. Поэтому я так не делаю больше. Кто хочет продолжать найдет возможность и оплатит. 
Информирование о ценах обычно говорит о том, что хотят продать больше, чем нужно.
