### ISSUE TITLE
2. Комбинированный компаратор [#10036] Опечатка

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1707]
В названии тестового метода опечатка. Написано whenCompatorByNameAndPrority 
а должно быть whenCompatorByNameAndPriority 
![2024-01-16_07-32](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/094299ad-e50f-45ed-9483-3a3d60954c4a)

**Comment by hrodvar-one** [comment]
в этом же названии вторая опечатка: 
название метода должно быть whenComparatorByNameAndPriority

**Comment by staskorobeynikov** [comment]
Исправлено
