### ISSUE TITLE
Экзамен: Система ввода-вывода IO, NIO. Не корректный ответ на вопрос по классу Scanner.

### ISSUE THREAD

**Issue by MikeGTi** [peterarsentev/job4j_features_bugs#1708]
Экзамен: Система ввода-вывода IO, NIO.
Вопрос: Аргументы каких типов принимает класс java.util.Scanner?
Описание: Выберите верные ответы.
Варианты:
java.nio.Readable - проставлена галочка, и это неправильный ответ,

смотрим приложенную ссылку на документацию [java.util.Scanner](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Scanner.html#constructor.summary) и там:
[Scanner](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Scanner.html#%3Cinit%3E(java.lang.Readable))​([Readable](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Readable.html) source) Constructs a new Scanner that produces values scanned from the specified source.

**Comment by staskorobeynikov** [comment]
Исправлено
