### ISSUE TITLE
1.3. Чаты [#64599 #196800] - стажёрский блок.

### ISSUE THREAD

**Issue by WhiteVax** [peterarsentev/job4j_features_bugs#1710]
Не плохо было бы ещё добавить чаты interview и hr в лекцию. 
Сам их нашёл не так давно и то только в основном чате.

**Comment by hrodvar-one** [comment]
> Не плохо было бы ещё добавить чаты interview и hr в лекцию. Сам их нашёл не так давно и то только в основном чате.

ссылки на чаты можешь скинуть?

**Comment by peterarsentev** [comment]
@WhiteVax @hrodvar-one А там никто не пишет. У меня была идея собирать там информацию о собеседованиях или вакансиях, но как оказалось никто этим заниматься не хочет.
Сейчас вся актуальная информация публикуется через канал https://t.me/java_kotlin_hub
