### ISSUE TITLE
8. FP - функциональное программирование [#310021]

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1711]
Опечатка в тексте в начале урока.
Пропущена буква е
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/007a7bff-9c08-4000-ad6d-202c4b0d6c0d)

**Comment by hrodvar-one** [comment]
в этом же уроке в абзаце ниже опечатка в слове: 
библиотекА Stream API
а должно быть
библиотекЕ Stream API 
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/eb28625f-fb42-45e3-b9aa-50d9d503b38e)

**Comment by staskorobeynikov** [comment]
исправлено
