### ISSUE TITLE
1.3.7. Контрольные вопросы. Коллекции.

### ISSUE THREAD

**Issue by vaschenkoff** [peterarsentev/job4j_features_bugs#1712]
В вопросе из блока Коллекции "В каком из блоков кода есть серьезная проблема с производительностью" не один, а два верных ответа.

Прикладываю фото вопроса и правильного ответа и статью подтверждение, что еще один ответ верный

![IMG_20240131_140536_367](https://github.com/peterarsentev/job4j_features_bugs/assets/91215372/08e9cbeb-efae-4cf9-a11a-248055ce608b)
![IMG_20240131_140536_367](https://github.com/peterarsentev/job4j_features_bugs/assets/91215372/4e623353-21f7-4d5a-b156-8a37dcbd9bbe)

**Comment by staskorobeynikov** [comment]
Исправлено
