### ISSUE TITLE
Добавления к темам 4.4. Алгоритмы. 4.4.2. Сортировки и поиск

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1713]
Может быть будет интересным дополнением в тему?

Вопрос из собеса.
Мы знаем, что лучшая стандартная сортировка дает
результат не лучше O(n log n)
Можно ли теоретически приблизиться к скорости O(n)

Примерный правильный ответ
Да, можно, но для этого придется использовать 
дополнительные структуры и память под них.
Пример таких сортировок можно назвать - сортировки распределением.
Источник: https://habr.com/ru/companies/edison/articles/472466/

**Comment by peterarsentev** [comment]
@yarmail Спасибо, Ярослав, но не хотелось бы превращать курс в свалку полезных ссылок.
