### ISSUE TITLE
2. JDK [#158114 #158168]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1717]
https://job4j.ru/profile/exercise/1/task/10/158168
Не очень понятна структура урока 
Сначала предлагается установить 17 версию для Windows
а потом для мака - 21. 
Так и должно было быть? Может быть имеет смысл 
указать, что устанавливаем какую-то конкретную стабильную
версию, а потом для всех систем единообразно установить её?

**Comment by staskorobeynikov** [comment]
Нет тут универсальности для всего. Каждая система - свои особенности. В Linux и ставить не нужно, из коробки все есть.
Добавил уточнение, что рассматривается установка LTS версий
