### ISSUE TITLE
1. Инструменты [#504887] Ошибка

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1718]
если следовать по пунктам урока https://job4j.ru/profile/exercise/192/task-view/967
то при выполнении пункта 4 где нужно скачать файл checkstyle.xml

![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/ebfb4bf0-e079-41d2-8695-f23c4b086b97)

после загрузки и помещения этого файла в папку проекта и дальнейшей настройки правила checkstyle возникает ошибка которая не даёт сохранить правило job4j

![ошибка при подключении checkstyle](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/069e443e-b5b3-4a2b-ab74-323e6ddd80fb)

А если взять файл checkstyle.xml из папки стажёрского проекта job4j_tracker то он нормально работает и даёт сохранять правило checkstyle.

Просьба поправить данную ошибку.

**Comment by staskorobeynikov** [comment]
исправлено
