### ISSUE TITLE
Статические ресурсы: CSS, JS [#505079] Опечатки в текста

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1719]
Друзья, добрый день.

Вот в этой части текста подозрительно много ошибок:

Контроллеры в веб приложении использу**ется**, чтобы обработать запросы клиента. На стороне клиента есть часть данны**е**, которые никогда не меняются. Например, скрипты, таблицы стилей, картинки. Эти данные называют статическим контентом и обработку запрос на получение таких данных не делают.

Последнее предложение составлено очень косноязычно, его не просто сложно прочитать, его даже сложно понять.
Предлагаю переписать его на такой вариант:
>Эти данные называются статическим контентом, и запрос на их получение обработки не требует.

**Comment by staskorobeynikov** [comment]
Исправлено
