### ISSUE TITLE
0. Обзор K8n [#504784]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1721]
https://job4j.ru/profile/exercise/176/task-view/779

Ссылка на документацию на русском языке не сработала
Возможно потому, что она не из ru региона.
Предлагаю поменять источник полезной информации

**Comment by staskorobeynikov** [comment]
Открыл
Русская документация открылась. Правда ее там - кот наплакал, лишь только малая часть есть на русском.
Вставил ссылку на английскую доку, при желании всегда можно переключиться
