### ISSUE TITLE
Проект DreamJob html файлы

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1722]
Во многих уроках данного модуля мы редактируем html файлы. Обычно это происходит следующим образом:
Отредактируем представление *.html файла.
Дальше идет весь файл целиком и нужно прямо сильно постараться, что бы понять, что там было добавленно и в какое местое.
Если подразумевается, что учащийся должен отдавать себе отчет о том, что мы добавляем в файл, то надо как-то подсветить это в полотне текста, либо выделить в отдельные строки дополнительно.

**Comment by peterarsentev** [comment]
@dmarakov, Спасибо. поправили.
