### ISSUE TITLE
Логирование [#505129] Неконсистентность в размере лога

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1723]
Друзья, у вас сквозь урок совершенно разные данные касаемо размера *.log файла. Как я понимаю цель была продемонстрировать разные подходы к одному и тому же инструменту. Я бы привел их к какой-то консистентности:

1. Для этого в каталоге src/main/resources создадим файл logback.xml:

<maxFileSize>10MB</maxFileSize>
2. В следующем примере такая же опечатка
3. Дальше вот этот пример
>Вся конфигурация логирования будет размещена в файле application.properties:
Тут у нас уже появляются два параметра:
logging.logback.rollingpolicy.max-file-size = 1KB
logging.logback.rollingpolicy.total-size-cap = 10MB
Если я верно понимаю, то мы ограничиваем размер одного файла лога до 1Кб, а вот общий размер всех файлов 10MB?
Снова какая-то неконсистентность с прошлыми примерами
4. xml файл поправили, выглядит окей
5. И наконец log4j2.properties
Снова загадочный 1KB
appender.rolling.policies.size.size = 1KB

**Comment by staskorobeynikov** [comment]
Поставил 1МВ
