### ISSUE TITLE
1.6. Особенности обучения взрослых

### ISSUE THREAD

**Issue by WhiteVax** [peterarsentev/job4j_features_bugs#1724]
https://job4j.ru/profile/exercise/141/task-view/1020

"Например, задача на смекался. Используя 6 списочек сложите 4 равносторонних треугольника. Ломать списки нельзя. Вы потратите на эту задачу достаточно времени и ее решение принесет вам удовольствие, но цель курса в другом." - верхнем тексте опечатки.

"Например, задача на смекалку. Используя 6 спичек сложите 4 равносторонних треугольника. Ломать спички нельзя. Вы потратите на эту задачу достаточно времени и ее решение принесет вам удовольствие, но цель курса в другом." - так корректней будет.

**Comment by staskorobeynikov** [comment]
исплавлено
