### ISSUE TITLE
0.1. Интерфейс List [#4953] Опечатка

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1725]
Лишняя буква В в предложении.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/313a8cf7-bfc2-4fd7-b850-97e6c308d96e)

**Comment by VictorNuzhdin** [comment]
Почему разработчик до сих пор работает на ОС Windows в Java проекте?
Это паттерн или анти-паттерн? :)

**Comment by staskorobeynikov** [comment]
исправлено
