### ISSUE TITLE
ошибка задания  https://job4j.ru/profile/sqlExercise/2/show/18

### ISSUE THREAD

**Issue by AlekseiBB** [peterarsentev/job4j_features_bugs#1727]
в задании https://job4j.ru/profile/sqlExercise/2/show/18  ошибка 

по заданию необходимо выполнить так 
select distinct(name) , id, name, grade from subjects order by name desc

а проверка идет по такому ответу 
select distinct(name) as id, name, grade from subjects order by name desc

**Comment by staskorobeynikov** [comment]
В вашем запросе запятая лишняя, должно быть так
select distinct(name) id, name, grade from subjects order by name desc
