### ISSUE TITLE
ошибка на странице https://job4j.ru/profile/exercise/35/task-view/261 - лишний div

### ISSUE THREAD

**Issue by Eugene-prog** [peterarsentev/job4j_features_bugs#1728]
`<div` class="jfk-bubble `gtx-bubble">&nbsp;</div>`

[(![image](https://github.com/peterarsentev/job4j_features_bugs/assets/55286245/e7221b11-396d-4fa5-a96f-71972037c547))]

**Comment by staskorobeynikov** [comment]
В разметке нет никакой проблемы. Это у Вас установлено расширение, которое добавляет лишние элементы на некоторые страницы. Сам периодически с этим сталкиваюсь. По ссылке ниже - подробности
[click](https://stackoverflow.com/a/30538012)
