### ISSUE TITLE
Опечатка в упражнении ( 1.1.4. Оператор ветвления-47. Изменить трехзначное число в зависимости от условия)

### ISSUE THREAD

**Issue by WhiteVax** [peterarsentev/job4j_features_bugs#1729]
https://job4j.ru/profile/topics/13/task_code/323/new_task

- Для чисел, больших 500, переставляет местами числа единиц и сотен (вместо 347 - 743). - оригинал

(вместо 743 - 347) - так корректней будет.

**Comment by staskorobeynikov** [comment]
исправлено
