### ISSUE TITLE
3. Optional - empty, of [#214711] Непонятный баг

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1730]
https://job4j.ru/profile/exercise/43/task-view/301  в обсуждении к этому урок, один из учеников оставил ссылку на другой урок по теме Optional и его методы.
вот эта ссылка https://job4j.ru/profile/exercise/35/task/263/3677111.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/9e4b6342-58f7-48ba-b244-3a7bf8f7c091)

При переходе по ней меня перекидывает на пройденный мной урок (в вверху страницы есть флаг Выполнена), но внизу этой страницы нет приложенного мной решения отправленного на проверку.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/82f1d9f4-a513-4166-bd3f-9f6f3dde89e0)
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/daeb7850-8312-4979-8f5f-302c22b8eb0b)

Если я перейду в этот урок непосредственно через разделы со всеми уроками, то я захожу на страницу с другим адресом https://job4j.ru/profile/exercise/35/task/263/480684 где также есть статус о выполнении данного урока, но внизу уже есть приложенное мной решение и ответ ментора о выполнении.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/8bc21593-f617-4237-8bd1-cedc4a0575b1)
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/8fcacba2-3561-428a-9846-fab9094dc1ca)

У меня вопрос это баг?

**Comment by staskorobeynikov** [comment]
Это так построено API. По сути эта ссылка из обсуждений - уникальна для этого пользователя и будет работать только для него. Для всех остальных - будет показано только само задание, без возможности посмотреть решения - как свое так и этого пользователя. Только если перейти в саму задачу в своем трекере - тогда можно и увидеть свое решение. Это не баг, такая архитектура
