### ISSUE TITLE
Неверный вариант ответа в тесте Java Collection. Базовый уровень

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1731]
**В вопросе "Как упорядочить элементы в ArrayList", якобы верный вариант ответа:**
Используя java.util.Comparable и метод Collections.sort, 
НО Comparable не лежит в пакете util, а лежит в пакете package java.lang.
Поэтому этот вариант ответа неверный. 
В противном случае надо написать:
**java.lang.Comparable**

![image](https://github.com/peterarsentev/job4j_features_bugs/assets/106574154/44e111d0-c2ff-49cf-ae7c-bd1d7dc2b187)

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
