### ISSUE TITLE
5.2. BufferedOutputStream [#252490] - Неверное имя файла в примере урока

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1734]
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/5728b490-364e-435b-a8dc-f23ae9bd5461)
Файл должен называться dataresult.txt потому что в предшествующем уроке где мы этот класс создаём 2.0. FileOutputStream [#252488 #492714] https://job4j.ru/profile/exercise/45/task/306/492714 это файл называется dataresult.txt

![image](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/d3a73bc9-eef1-43f3-9536-ac5efa8b4af1)

**Comment by staskorobeynikov** [comment]
Исправлено
