### ISSUE TITLE
Расширение функционала для телеграмм бота

### ISSUE THREAD

**Issue by DropCoffee** [peterarsentev/job4j_features_bugs#1736]
Добрый день.
Просьба рассмотреть возможность расширение телеграмм бота.
- добавление информации сколько тасок сейчас на проверке.
- уведомление, что билд упал по отправленной задаче.
- возможность написать к таске комментарий в задаче.

**Comment by DropCoffee** [comment]
- Посмотреть комментарии от ментора. Почему урок отклонен.

**Comment by peterarsentev** [comment]
Спасибо. Добавили все пункты.
