### ISSUE TITLE
Урок про аннотации

### ISSUE THREAD

**Issue by DropCoffee** [peterarsentev/job4j_features_bugs#1738]
Просьба добавить урок про аннотации.
Каким образом их можно самостоятельно реализовать и добавить в свой код.

P.S.
Насколько читал это считается антипаттерном, но хотелось бы реализовать свою аннотацию, чтобы лучше понимать как они работают.

**Comment by peterarsentev** [comment]
Спасибо. Мы сделаем отдельный блок в курсе посвященный механизму рефлексии и в частности аннотациям.
