### ISSUE TITLE
Курс Стажер. Урок 5. Checkstyle с Maven [#257606] определение plugins

### ISSUE THREAD

**Issue by DropCoffee** [peterarsentev/job4j_features_bugs#1739]
Добрый день. 
У Вас написано, что plugins в maven:

Checkstyle разрабатывается как отдельная библиотека jar. Подключать мы ее будем через встроенный механизм расширений в Maven.
Такие механизмы называются плагинами. Плагины помогают сделать дополнительные действия с кодом проекта.
Например, проверить оформление кода, очистить папку, выполнить запуск сервера.
Чтобы подключить плагины, нужно в pom.xml добавить блок <plugins> ... </plugins>, а внутрь него добавить настройки нужного плагина.

Мне кажется формулировка немного сбивает с толку. Когда впервые читаешь.
Согласно обсуждению https://stackoverflow.com/questions/11881663/what-is-the-difference-in-maven-between-dependency-and-plugin-tags-in-pom-xml

One line answer - basic understanding
Plugin is a tool you use at the execution of your maven build
Dependency means kind of any library which you will use in your code

Такое объяснение дает более четкое понимание, что plugin нужен на этапе сборки проекта, а Dependency для работы внутри кода.

**Comment by DropCoffee** [comment]
Из урока как то не возможно сразу понять в чем отличие plugins от Dependency

**Comment by peterarsentev** [comment]
Спасибо. Поправил описание.
