### ISSUE TITLE
Ошибка как в задании так и в тестах

### ISSUE THREAD

**Issue by bannovdaniil** [peterarsentev/job4j_features_bugs#1740]
https://job4j.ru/profile/topics/42/task_code/552/192822

методы в шаблоне возвращают тип Long , а в тестах используется Int где нет явного приведения. В самой задаче уже оставлены комментарии по этому поводу.

для того чтобы решить задачу пришлось поменять возвращаемый тип методов на Integer.

- задача объемная, ее бы разбить на 3 подзадачи.

Тесты не достаточны. maxByThread можно решить как нахождением самой длинной строки так и подсчетом скобок.
в задании:
maxByThread - метод должен вернуть имя нити, которая больше всех записала логов.

Так в тестах нет такой нити они все встречаются ровно один раз, либо совсем не понятно задание. если названия это то что находится внутри скобок то взять всю строку явно не верно. 

задание находится в разделе Map но ее очень хочется решить через Stream

**Comment by peterarsentev** [comment]
@bannovdaniil Спасибо, поправил.
