### ISSUE TITLE
Не работает копирование кода в некоторых заданиях

### ISSUE THREAD

**Issue by DropCoffee** [peterarsentev/job4j_features_bugs#1743]
Не во всех заданиях можно скопировать код по нажатию на кнопку - java
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/167765150/becd979a-10a3-49ae-a011-03bc473b0356)

Например, 5. Очередь с приоритетом на LinkedList [#41670]  - шаблон кода для PriorityQueue

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
