### ISSUE TITLE
Блок Git

### ISSUE THREAD

**Issue by INviZEo** [peterarsentev/job4j_features_bugs#1744]
На курсе нужно уроки поправить немного

В блоке Git

Во первых написать что нужно создать новый репозиторий в самом начале который job4j_threads

И сам блок нерационально разбит.
В "Основы Git" в последнем задании нужно решить конфликт веток, там нужно решить конфликт в ветках hotfix и task_126...
Однако урока как создавать ветки нет.
И когда переходишь в "Ветки"(следующий подблок)
Только там говоритcя что нужно создать ветку hotfix и делать все в job4j_threads

Для будущих поколений это сильно упростит понимание

Так же в обзор блока гит, можно добавить ссылку на обучалку по гит в игровом стиле

[https://learngitbranching.js.org/?locale=ru_RU](https://vk.com/away.php?to=https%3A%2F%2Flearngitbranching.js.org%2F%3Flocale%3Dru_RU&cc_key=)

**Comment by staskorobeynikov** [comment]
Исправлено
