### ISSUE TITLE
Упражнения SQL 4. GROUP BY, WHERE, HAVING 37. GROUP BY, WHERE и HAVING 7

### ISSUE THREAD

**Issue by MikeGTi** [peterarsentev/job4j_features_bugs#1746]
Просто собрав данные, из таблицы 'movies' (select avg(budget) from movies group by company_id;),
по средним бюджетам - не получил ожидаемых в тесте цифр.
Данные:

Мои                 
5 600 000
3 160 000
5 125 000
5 640 000

В тесте ожидается 6 050 000

Вероятно что-то не так в тесте?!?

**Comment by staskorobeynikov** [comment]
Исправлено
