### ISSUE TITLE
Job4j Уроки 2. Джуниор 2.5. Чистая архитектура 2.5.5. DIP 0. Принцип инверсии зависимостей

### ISSUE THREAD

**Issue by MikeGTi** [peterarsentev/job4j_features_bugs#1748]
Опечатка в коде:

'public class SimpleOrderService implements OrderService {
    private OrderStore orderStore;
    
   public SimpleOrderStore(OrderStore orderStore) {
        this.orderStore = orderStore;
    }
}'
видимо должен быть конструктор SimpleOrderService.

**Comment by staskorobeynikov** [comment]
Исправлено
