### ISSUE TITLE
Дублирование записей в списке Были сегодня

### ISSUE THREAD

**Issue by JenBrainnet** [peterarsentev/job4j_features_bugs#1749]
Люди отображаются по несколько раз с одними и теми же выполненными уроками.

<img width="1111" alt="Снимок экрана 2024-06-27 в 23 22 17" src="https://github.com/peterarsentev/job4j_features_bugs/assets/29177893/d58736d9-4b08-46d1-be65-641249c9a047">

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
