### ISSUE TITLE
Экзамен "Java Collection. Продвинутый уровень". 

### ISSUE THREAD

**Issue by mihanchik94** [peterarsentev/job4j_features_bugs#1751]
В вопросе "Выберите наихудшую временную сложность для HashMap, c учетом того, что в ней присутствуют коллизии."

правильный ответ отмечается как O(1)

**Comment by MikeGTi** [comment]
а должно быть O(n) или O(log(n)), в зависимости от ситуации в bucket'е HashMap.

**Comment by staskorobeynikov** [comment]
Исправлено
