### ISSUE TITLE
Недоступны ссылки на ресурсы в уроке

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1752]
В уроке https://job4j.ru/profile/exercise/63/task-view/788

недоступны ссылки указанные на скриншоте
![1](https://github.com/peterarsentev/job4j_features_bugs/assets/86091103/c5af9ed7-bafa-436e-ac17-397fa3ac72ad)

**Comment by staskorobeynikov** [comment]
Исправлено
