### ISSUE TITLE
опечатки в уроке "Что такое полиморфизм"

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1753]
1. Что такое полиморфизм.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/1678973f-1755-4314-8906-e083b470608c)
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/8b2e35df-cf71-411c-a537-d4d31ce15b0f)

**Comment by staskorobeynikov** [comment]
Исправлено
