### ISSUE TITLE
баг в отображении заданий

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1755]
отображается
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/7af0e2f2-9346-46a6-b2c2-1a5da8b22cee)

но первое задание у меня не принято, но отмеченно как принятое
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/45582393-b941-4336-a9a9-d9c45711ba55)
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/f1537471-8e87-4384-aaea-45a887726c3a)

**Comment by peterarsentev** [comment]
@AlexeySapsay Это поправил. Спасибо.
