### ISSUE TITLE
предложение по дополнению задания

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1756]
В уроке "Именование классов реализующих интерфейс",  есть задание
выполнить рефакторинг кода по правилам, которые описаны в статье.
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/8628a283-1732-440f-a0aa-a6b7fbcd1bad)

тк. под рефакторингом можно понять как переименование классов так и разбивание на пакеты, возникли прения и недопонимание с проверяющим ментором. В моем представлении нужно было выполнить переименование и разбиение на пакеты. В его- только разбиение.

Поэтому, есть предложение, улучшающее статью - явно прописать в задании, выполнить рефакторинг используя только разбиение на пакеты, без переименование классов. Это сэкономит время менторов на проверку, и студентов, на исправление решений.

**Comment by staskorobeynikov** [comment]
исправлено
