### ISSUE TITLE
опечатка в уроке deque

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#1757]
![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/2d74ef09-9c00-48af-bab3-e409eb0a387e)

![image](https://github.com/peterarsentev/job4j_features_bugs/assets/13130875/60d95bbb-fd93-49b6-b593-e13d24eb3726)

**Comment by staskorobeynikov** [comment]
исправлено
