### ISSUE TITLE
неправильный тест в уроке 4.3.3 Логическое отрицание !

### ISSUE THREAD

**Issue by sergosar** [peterarsentev/job4j_features_bugs#1758]
ссылка на урок https://job4j.ru/profile/exercise/13/task/61/503099
Обязательно учтите, что 0 это не положительное число и не отрицательное. 
события описываемые в следующих тестах образуют полную группу событий и вообще оно понятно что второй тест должен выдавать true.
    @Test
    void whenNumIs0IsPositiveFalse() {
        int num = 0;
        boolean result = LogicNot.isPositive(num);
        assertThat(result).isFalse();
    }
    @Test
    void whenNumIs0NotPositiveFalse() {
        int num = 0;
        boolean result = LogicNot.notPositive(num);
        assertThat(result).isFalse();
    }

**Comment by staskorobeynikov** [comment]
ВСе тесты верные. 
0 разбивает числовое пространство на положительные и отрицательные числа, но сам является особым числом и не относится ни к одним ни ко вторым. В одном другом тесте должен быть false

**Comment by sergosar** [comment]
Со всем уважением, не согласен. Там два теста образуют полную группу событий в которой суммарная вероятность исхода равна единице. Это всё равно что отвечать на вопрос: апельсин это яблоко? (False) и апельсин это НЕ яблоко (True), в тестах на оба схожих вопроса даётся ответ false. То что ноль это абсолютная точка и не положительная и не отрицаиельная никак не влияет на результат...
--
Отправлено из Mail.ru для Android понедельник, 12 августа 2024г., 13:13 +03:00 от Stas Korobeynikov  ***@***.*** :

**Comment by sergosar** [comment]
хотя бы дописать что - метод notPositive(), проверяет, что число не положительное и не НУЛЬ (но тогда метод должен
 называться notPositiveAndNotZero() ) и на числовой прямой не положительное это <= 0.

**Comment by staskorobeynikov** [comment]
Переименовал метод, добавил уточнение
