### ISSUE TITLE
нет возможности удалить комментарий в заданиях

### ISSUE THREAD

**Issue by AVBaranov93** [peterarsentev/job4j_features_bugs#1759]
![удаление комментария](https://github.com/peterarsentev/job4j_features_bugs/assets/135685274/3d6fc793-6f38-4c5b-a6a7-6a692efd7b14)

кнопка для удаления есть, но комментарий она не удаляет )

**Comment by peterarsentev** [comment]
@AVBaranov93 Поправили. Спасибо.
