### ISSUE TITLE
Контрольные вопросы и экзамен "Алгоритмы на собеседовании". Тестовое задание "Посетители в банке"

### ISSUE THREAD

**Issue by MikeGTi** [peterarsentev/job4j_features_bugs#1761]
Ошибка в тесте: 'whenSimpleCaseThenCorrectMaxLoadTime',
вместо "...assertThat(result).containsExactly(3, 5);" - должно быть "...assertThat(result).containsExactly(4, 5);"

**Comment by peterarsentev** [comment]
@MikeGTi Спасибо, поправили.
