### ISSUE TITLE
Неправильный тест Упражнения -> Java Core

### ISSUE THREAD

**Issue by Kirbri** [peterarsentev/job4j_features_bugs#1764]
Job4j
Упражнения
1.1.4. Оператор ветвления
59. Решить линейное уравнение первой степени
https://job4j.ru/profile/topics/13/task_code/335/197542
Некорректный тест:  
@Test
    public void when8And0ThenNo() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        Task59.getLinearEquation(8, 0);
        String expected = "Нет решения" + ln;
        assertThat(out.toString(), is(expected));
    }
Линейное уравнение вида ax + b = 0 со значениями из теста примет вид 8x=0 -> x = 0

**Comment by staskorobeynikov** [comment]
Исправлено
