### ISSUE TITLE
Неоднозначное задание

### ISSUE THREAD

**Issue by Kirbri** [peterarsentev/job4j_features_bugs#1765]
Job4j
Уроки
1. Стажер
1.2. ООП
1.2.5. Полиморфизм
Именование классов реализующих интерфейс
https://job4j.ru/profile/exercise/23/task/1204/506129
Задание:
**2. Произведите рефакторинг кода используя правила описанные в этом уроке.**
В лекции даны правила именования интерфейса, правила именования классов реализующих интерфейсы, группировка классов по пакетам, в задании указано произвести рефакторинг кода, используя правила описанные в этом уроке. 
Ментор не принял коммит, где были сокращены названия - убрано последнее слово "Action", хотя в лекции про это было сказано и показано. 
Предложение явно прописать в задании что не нужно переименовывать названия классах в пакетах (action, input, output)
![image](https://github.com/user-attachments/assets/ded5c4e5-3c86-4f1a-875b-a5a25a04cc8a)

**Comment by staskorobeynikov** [comment]
Задание скорректировано
