### ISSUE TITLE
4.1. Элементы интерфейса [#504948 #505806]. Повторение текста в лекции

### ISSUE THREAD

**Issue by Kirbri** [peterarsentev/job4j_features_bugs#1767]
Job4j Уроки 1. Стажер 1.2. ООП 1.2.5. Полиморфизм 4.1. Элементы интерфейса
https://job4j.ru/profile/exercise/23/task-view/1028
Повтор два раза одного и того же текста про дефолтные методы.
Дублирующийся текст: 

_Дефолтные методы
Теперь рассмотрим дефолтные методы. Так же как и статические, они имеют реализацию, но при их объявлении используется ключевое слово default. Добавим дефолтный метод зарядки аккумулятора на транспортном средстве в интерфейсе Vehicle:

1
package ru.job4j.polymorphism;
2
​
3
public interface Vehicle extends Fuel {
4
    int WHEELS = 4;
5
​
6
    void changeGear();
7
    void accelerate();
8
    void steer();
9
    void brake();
10
​
11
    static void getDragCoefficient() {
12
        System.out.println("Формула расчета коэффициента аэродинамического сопротивления автомобиля");
13
    }
14
​
15
    default void chargeBattery() {
16
        System.out.println("Аккумулятор под капотом. Зарядить.");
17
    }
18
}
19
​
Главное отличие дефолтного метода в том, что он будет унаследован классом, который реализует данный интерфейс. При этом класс может как переопределить данный метод, так и воспользоваться реализацией по умолчанию. Метод процедуры зарядки аккумулятора сделан дефолтным, так как у большинства автомобилей аккумулятор находится под капотом, и процесс его снятия и зарядки будет одинаковым. Переопределим метод chargeBattery() в классе TownCar:

1
package ru.job4j.polymorphism;
2
​
3
public class TownCar implements Vehicle {
4
​
5
    @Override
6
    public void changeGear() {
7
        System.out.println("Коробка автомат. Поставить селектор в режим D.");
8
    }
9
​
10
    @Override
11
    public void accelerate() {
12
        System.out.println("Нажатие на педаль газа механически открывает дроссельную заслонку");
13
    }
14
​
15
    @Override
16
    public void steer() {
17
        System.out.println("Стандартное рулевое управление");
18
    }
19
​
20
    @Override
21
    public void brake() {
22
        System.out.println("Стандартная тормозная система");
23
    }
24
​
25
    @Override
26
    public void refill() {
27
        System.out.println("Заправить 60л бензина");
28
    }
29
​
30
    @Override
31
    public void chargeBattery() {
32
        Vehicle.super.chargeBattery();
33
    }
34
}
35
​
Метод chargeBattery() можно явно не переопределять, так как он уже унаследован от интерфейса Vehicle. В данном примере мы его переопределили для наглядности. В классе TownCar используется реализация по умолчанию в методе chargeBattery(), унаследованном из интерфейса Vehicle, через ключевое слово super:

1
@Override
2
public void chargeBattery() {
3
    Vehicle.super.chargeBattery();
4
}
5
​
Дефолтные методы удобно использовать, если в классах, имплементирующих один и тот же интерфейс, должен быть объявлен метод с одинаковой реализацией. Классов-реализаций интерфейса Vehicle может быть множество, и у многих из них метод зарядки аккумулятора ничем не будет отличаться. Поэтому мы вынесли этот метод в интерфейс и объявили его дефолтным, чтобы избежать дублирования кода.

В классах-реализациях интерфейса Vehicle, у которых аккумулятор находится не под капотом, например, в классе SportCar, мы переопределяем метод chargeBattery() своей реализацией:

1
package ru.job4j.polymorphism;
2
​
3
public class SportCar implements Vehicle {
4
​
5
    @Override
6
    public void changeGear() {
7
        System.out.println("Механическая коробка передач. Включить первую, дальше переключать до шестой");
8
    }
9
​
10
    @Override
11
    public void accelerate() {
12
        System.out.println("Электронная педаль газа");
13
    }
14
​
15
    @Override
16
    public void steer() {
17
        System.out.println("Укороченная рулевая рейка для ускоренного поворота руля");
18
    }
19
​
20
    @Override
21
    public void brake() {
22
        System.out.println("Усиленная тормозная система");
23
    }
24
​
25
    @Override
26
    public void refill() {
27
        System.out.println("Заправить 100л бензина");
28
    }
29
​
30
    @Override
31
    public void chargeBattery() {
32
        System.out.println("Аккумулятор в багажнике. Зарядить.");
33
    }
34
}
35
​
Также дефолтные методы наследуются производными интерфейсами от базовых. Рассмотрим некоторые проблемы, которые могут возникнуть при реализации интерфейсов, в которых определены дефолтные методы. Создадим интерфейсы FunctionOne и FunctionTwo и объявим в них дефолтные методы с одинаковой сигнатурой и типом возвращаемого значения:_

**Comment by staskorobeynikov** [comment]
Убрал лишнее.
