### ISSUE TITLE
Нет кнопки автоматической проверки задания в ознакомительном уроке. 

### ISSUE THREAD

**Issue by HelenaBond** [peterarsentev/job4j_features_bugs#1768]
https://job4j.ru/profile/exercise/45/task-view/1071

**Comment by staskorobeynikov** [comment]
Каждая задача в отдельности рассматривается как относящаяся к тому или иному типу, на данный момент пока эту задачу переводить в статус с автоматической проверкой не будем, возможно позднее это будет переделано
