### ISSUE TITLE
Про Ютуб

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#1769]
В связи с непонятной ситуацией с ютубом предлагаю
1. Посмотреть, какие ролики пользуются наибольшим успехом (за все время) и где больше всего каментов
2. Перенести эти ролики на другие платформы или сделать новые версии этих
роликов с учетом каментов.
3. все залинковать между собой - т.е. сделать ссылки и на ролики и на вебинары
из чата и других соц.сетей, возможно из вебинаров сделать ролики, т.е. ориентироваться на интерес пользователей

**Comment by peterarsentev** [comment]
Спасибо. Ярослав. Взял себе на заметку твою идею. Пока сделать только телеграм канал и там буду дублировать видео с ютуба.
