### ISSUE TITLE
Ошибки в экзамене Базовый синтаксис Java

### ISSUE THREAD

**Issue by nikdomarovsky** [peterarsentev/job4j_features_bugs#1770]
https://job4j.ru/profile/exams/detail/5
Вопрос: "Какая команда скопирует первые 5 элементов старого массива (oldArray) в новый массив (newArray)?":
Вопрос имеет 2 правильных ответа,но в тексте вопроса написано "Какая"

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
