### ISSUE TITLE
Экзамены/Hibernate задвоение и ошибки в рекомендациях

### ISSUE THREAD

**Issue by osipov-slava** [peterarsentev/job4j_features_bugs#1771]
https://job4j.ru/profile/exams/detail/42
Ошибки
![image](https://github.com/user-attachments/assets/5649bcd3-e253-4014-ac10-c0cd87c4d0ec)
Задвоение
![image](https://github.com/user-attachments/assets/d20b7d96-fd92-4dda-8676-c1f929cced75)

**Comment by staskorobeynikov** [comment]
Исправлено
