### ISSUE TITLE
Рейтинг по лайкам обнуляется при смене имени, абыдно

### ISSUE THREAD

**Issue by osipov-slava** [peterarsentev/job4j_features_bugs#1772]
было skybright@mail.ru - 3
стало Slava Osipov - n.d.

**Comment by peterarsentev** [comment]
Попробовал повторить. Но у меня все работает. Да и на сервисе у тебя рейтинг уже 4 просто ).
![Uploading image.png…]()

**Comment by osipov-slava** [comment]
да сейчас все ок ). но я не мог бы пропустить свой ник с зеленой подсветкой, значит он не выводился
