### ISSUE TITLE
Опечатка во всплывающей подсказке

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1774]
На странице любого урока при наведении на ФИО ответственного всплывает подсказка в которой есть орфографическая ошибка.
Надо заменить Отвественный на Ответственный

![Screenshot_20240816_080700](https://github.com/user-attachments/assets/40e1ed6e-fa19-4228-93a0-68e38cf54378)

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
