### ISSUE TITLE
1. Что такое итератор. [#4951] 

### ISSUE THREAD

**Issue by oyvey1984** [peterarsentev/job4j_features_bugs#1775]
В уроке https://job4j.ru/profile/exercise/38/task-view/272

1. задвоена строка assertTrue(iterator.hasNext()); в классе ArrayIteratorTest
2. задвоена строка assertThat(iterator.hasNext()).isTrue(); в методе whenMultiCallHasNextThenTrue в классе BackwardArrayIteratorTest
3. затроена строка assertThat(iterator.hasNext()).isTrue(); в методе whenMultiCallHasNextThenNext в классе BackwardArrayIteratorTest

**Comment by oyvey1984** [comment]
Или это проверяется утверждение Результат многократного вызова этого метода должен быть одинаковым?
Но не понимаю почему результат вообще мог бы отличаться? Мы же next() не используем.

**Comment by peterarsentev** [comment]
Они там специально, потому что можно сделать перевод указателя в методе hasNext. 
```
while (it.hasNext) {
    it.next

hasNext() {
    boolean check = array[i + 1] != null;
    if (check) { 
        i += 1
    }
    return check;
 } 
```
