### ISSUE TITLE
5. Просмотр, редактирование и удаление вакансии [#504850] Опечатка

### ISSUE THREAD

**Issue by hrodvar-one** [peterarsentev/job4j_features_bugs#1776]
Исправить орфографическую ошибку:
 нажнем на нажмём

![image](https://github.com/user-attachments/assets/dc0a14ce-329c-4c8a-9d79-f1fc0300d2c6)

**Comment by hrodvar-one** [comment]
ещё в этом месте опечатка. надо чтобы было слово обновление
![image](https://github.com/user-attachments/assets/c3aacc74-d1be-44df-95bf-c6a505406cd4)

**Comment by staskorobeynikov** [comment]
исправлено
