### ISSUE TITLE
В открытых уроках встречаются переходы на заблокированные уроки

### ISSUE THREAD

**Issue by dmcffueded** [peterarsentev/job4j_features_bugs#1778]
В открытых уроках есть ссылки на заблокированные уроки, например, [отсюда](https://job4j.ru/profile/exercise/17/task/125/510596) [сюда](https://job4j.ru/profile/exercise/1/task-view/15). Такое не раз встречал.

_На странице есть ссылка:_

![1](https://github.com/user-attachments/assets/d64c7a5c-3842-47f4-a672-652938cdaef2)

_Материал по ссылке недоступен:_

![2](https://github.com/user-attachments/assets/9aff390b-82cd-458b-baad-6bc8d96cf413)

**Comment by peterarsentev** [comment]
@dmcffueded Спасибо, поправил.
