### ISSUE TITLE
Отсутствует код в примере.

### ISSUE THREAD

**Issue by aleksLiss** [peterarsentev/job4j_features_bugs#1782]
Расположение ошибки:
    Job4j/Уроки/2. Джуниор/2.2. Ввод-вывод/2.2.1. Ввод-вывод/9.0. Файлы и директории. Класс File 

![Снимок экрана от 2024-08-31 23-48-19](https://github.com/user-attachments/assets/466e4156-b496-4b69-926c-6d5811ee73d3)

**Comment by peterarsentev** [comment]
@aleksLiss а я не нашел там кода. Почему ты думаешь, что там должен быть код?
Я только убрал вставки от правок GPT )).

**Comment by aleksLiss** [comment]
"Вот исправленное описание и улученный код для работы с классом File:"
поэтому и подумал что должен быть код

**Comment by peterarsentev** [comment]
@aleksLiss Понял. Это я поторопился и вставил правки напрямую из GPT. 
В целом я прочитал и повествование там верное.
Спасибо, что сообщаете про ошибки.
