### ISSUE TITLE
Теги в примерах кода

### ISSUE THREAD

**Issue by sergosar** [peterarsentev/job4j_features_bugs#1784]
во многих уроках присутствуют теги в примерах кода, мешает визуальному восприятию , а так же приходится удалять в случае копирования в IDE.
Список уроков:
1. https://job4j.ru/profile/exercise/21/task-view/150
2. https://job4j.ru/profile/exercise/31/task-view/230
3. https://job4j.ru/profile/exercise/21/task-view/147
Дополняется...

**Comment by staskorobeynikov** [comment]
Спасибо за информацию
По тем сссылкам что предоставили - исправил
В целом о проблеме известно. Все будет исправлено в кратчайшие строки. Больше скидывать ссылки на проблемные задачи не нужно
Приносим извинения за доставленные неудобства
