### ISSUE TITLE
Не виден пример кода

### ISSUE THREAD

**Issue by aleksLiss** [peterarsentev/job4j_features_bugs#1785]
Расположение:

     Job4j
    Уроки
    2. Джуниор
    2.6. Алгоритмы на собеседовании
    2.6.0. Обзор блока "Алгоритмы на собеседовании"
    3. О-нотация и сложность алгоритмов 
    
![изображение](https://github.com/user-attachments/assets/39e927c1-cfa3-4288-a663-dede57d92dec)

**Comment by peterarsentev** [comment]
@aleksLiss Спасибо, поправили.
