### ISSUE TITLE
4.3. Транзакции. Уровни изолированности транзакций. [#504812]

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#1786]
Результат не соответствует коду !!!

Чтение подтвержденных данных (read committed)

![Screenshot_5](https://github.com/user-attachments/assets/d266f089-c327-43f9-80b2-9e2a37f249ef)

**Comment by peterarsentev** [comment]
@grum1972 Спасибо, поправил.
