### ISSUE TITLE
Отсутствуют колонки status в таблицах

### ISSUE THREAD

**Issue by aleksLiss** [peterarsentev/job4j_features_bugs#1789]
1. Расположение:
     Job4j
    Уроки
    2. Джуниор
    2.3. SQL, JDBC
    2.3.4. Объекты Базы данных
    10. Операторы множества в SQL 
2.  В приводимом примере, при обращении в where  к WHERE status = 'Active' и  WHERE emp_status = 'Current' в указанных таблицах отсутствуют колонки status и emp_status
![Снимок экрана от 2024-10-09 14-28-12](https://github.com/user-attachments/assets/643e5795-ae37-4283-9236-d5af724f3b69)

**Comment by peterarsentev** [comment]
@aleksLiss Спасибо. Поправили.
