### ISSUE TITLE
DI, IoC, Beans, BeanFactory, ApplicationContext [#505289] ошибки в коде

### ISSUE THREAD

**Issue by s-bespalov** [peterarsentev/job4j_features_bugs#1791]
Урок: https://job4j.ru/profile/exercise/235/task-view/1370

Ошибки:

1. `import ru.job4j.bmb.content.Message;`
заменить на
`import ru.job4j.bmb.content.Content;`
2. `import ru.job4j.bmb.model.Message;`
заменить на
`import ru.job4j.bmb.content.Content;`
3. `public void content(Content content) {`
заменить на
`public void receive(Content content) {`

Пояснения:
Класса `Message` нигде не приведено и он нигде не используется, но зачемто импортируется. А `Content` везде используется но нигде не импортируется.
В уроке 2 места, где вызывается метод `TelegramBotService.receive(Content)`, но в приведенном коде этого сервиса есть только `TelegramBotService.content(Content)`

**Comment by peterarsentev** [comment]
@s-bespalov Спасибо, поправил.
