### ISSUE TITLE
BeanFactory | ApplicationContext [#505290] предложение по изменению терминов

### ISSUE THREAD

**Issue by s-bespalov** [peterarsentev/job4j_features_bugs#1792]
Ссылка на урок: https://job4j.ru/profile/exercise/235/task/1371/520149

1. 

> В настоящее время, BeanFactory используется реже, так как более продвинутая альтернатива, ApplicationContext, включает в себя весь функционал BeanFactory, добавляя дополнительные возможности, такие как работа с событиями, интеграция с Spring AOP, международная поддержка и так далее.

Тут предлагаю заменить `международная поддержка` на `поддержка локализации`

2.

> ApplicationContext — это один из ключевых интерфейсов в Spring Framework, расширяющий возможности BeanFactory. Он не только управляет жизненным циклом бинов (объектов) и их зависимостями, но и предоставляет дополнительные функции, такие как управление событиями, поддержку AOP (Aspect-Oriented Programming), работу с международными сообщениями и многое другое.

> Расширенные возможности по сравнению с BeanFactory, включая поддержку событий, работу с международными сообщениями, интеграцию с AOP и т.д.

В этих двух местах `международными сообщениями` надо заменить на `локализованные сообщения`, наверное.

**Comment by peterarsentev** [comment]
@s-bespalov Спасибо. Поправили.
