### ISSUE TITLE
[4. Многопоточность в базе данных] Отсутствуют кнопки регистрации юзера для view register

### ISSUE THREAD

**Issue by dmarakov** [peterarsentev/job4j_features_bugs#1793]
В данном уроке мы создаем view register, а в следующих заводим пользователей через это view. И максимально непрозрачно, что кнопки "Зарегистрироваться" мы должны написать самостоятельно в данном уроке.
Т.к очень часто бывает такое, что мы не пишем какой-то функционал в данном уроке и он будет написан позже. 
Мое скромное мнение, что этот момент нужно уточнить, что бы он не вызывал недопонимания в дальнейшем.
Спасибо!

**Comment by peterarsentev** [comment]
@dmarakov Спасибо. добавили уточнение в урок.
