### ISSUE TITLE
Отсутсвует final поле в классе

### ISSUE THREAD

**Issue by aleksLiss** [peterarsentev/job4j_features_bugs#1794]
Расположение проблемы:
     Job4j
    Уроки
    2. Джуниор
    2.4. Garbage Collection
    2.4.3. Профилирование приложения
    4. Найти утечку памяти. 
    
    Класс Menu
    В классе в методе start  используется поле: System.out.println(ID_FOR_DELETE);
    Данное поле отсутствует в классе Menu

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
