### ISSUE TITLE
Предложение. Пользовательская сложность в упражнениях, вопросах, задачах

### ISSUE THREAD

**Issue by enovoselovhi** [peterarsentev/job4j_features_bugs#1795]
Было бы круто сделать пользовательскую сложность для упражнений и для разных ресурсов с задачами.

Приблизительная работа такая, пользователь в любой момент может указать сложность задачи, которую решает или уже решил (например: легко, средне, сложно).

Собирать статистику и на задачу/упражнение вешать пользовательскую сложность, человек будет представлять, что сейчас придется попотеть или тут простая задача.

Наверное для этого есть какие-то формулы, но на ум пришло что-то подобное:

```
5 пользователей:
легко:   1 1 1
средне:  2
сложно:  3
(3+2+3) / 5 = 1,6 (средне)
```

Если собирать статистику, что пользователь указал, то в принципе можно будет пересчитать сложность по другой формуле в будущем

**Comment by peterarsentev** [comment]
Спасибо. Евгений. У нас есть в разделе упражнения уровни сложности.
По мере возможности будем заполнять. Благо GPT может нам помочь ).
