### ISSUE TITLE
Разные названия класса в тесте и задании

### ISSUE THREAD

**Issue by aleksLiss** [peterarsentev/job4j_features_bugs#1797]
Расположение:

     Job4j
    Уроки
    2. Джуниор
    2.6. Алгоритмы на собеседовании
    2.6.3. Сортировки
    Сортировки 
    
    
В задании: class Intervals 

В приложенных тестах: IntervalMergerTest

**Comment by peterarsentev** [comment]
@aleksLiss Спасибо, поправил.
