### ISSUE TITLE
4.4. Liquibase. Интеграционные тесты. Proxy.

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#181]
2. Уровень - Джуниор / Блок 3. SQL, JDBC / 5. JDBC

весь текст разбит на блоки вроде как не совсем логичные
"Здесь стоит уточни**ть. ч**то maven начинает" - запятая
"что в базе tracker создалась схема item." - нужно items
"проверяют все возможные случа**е**."
"работать только **с** режиме"
"Мы не може**т** изменять данны**х** код, потому что он будет работать не верн**о. е**сли мы добавим rollback. "
везде в коде написано TrackerSQL, но в задании 2. Трекер SQL был класс SqlTracker

объявление класса показано вот таким 
public class TrackerSQL implements ITracker, AutoCloseable {
а у нас в 2. Трекер SQL было 
public class SqlTracker implements Store {

"двумя пу**сти исп**ользовать"
"созд**аеть** объект"
"до полной схе**му к**ласса Item."

**Comment by reybos** [comment]
Еще в задаче сказано что настройки для подключения к тестовой базе нужно прописать вот так
```
 <profiles>
    <profile>
        <id>test</id>
        <properties>
            <db.url>jdbc:postgresql://127.0.0.1:5432/tracker</db.url>
            <db.username>postgres</db.username>
            <db.password>password</db.password>
            <db.driver>org.postgresql.Driver</db.driver>
        </properties>
    </profile>
    <profile>
        <id>production</id>
        <properties>
            <db.url>jdbc:postgresql://127.0.0.1:5432/tracker</db.url>
            <db.username>postgres</db.username>
            <db.password>password</db.password>
            <db.driver>org.postgresql.Driver</db.driver>
        </properties>
    </profile>
</profiles> 
```
но такой вариант не работал и судя по чату в телеге не только у меня, после того как прописал свойства вот тут
``` 
<properties>
        <maven.compiler.source>14</maven.compiler.source>
        <maven.compiler.target>14</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <db.url>jdbc:postgresql://127.0.0.1:5432/tracker</db.url>
        <db.username>postgres</db.username>
        <db.password>password</db.password>
        <db.driver>org.postgresql.Driver</db.driver>
    </properties> 
```
все заработало

p.s. оказывается во вкладке мавена есть выбор нужного профиля и тогда настройки все работают, думаю нужно написать об этом в задаче.

**Comment by ShamRail** [comment]
Не актуально. Задание обновлено.
