### ISSUE TITLE
Реализовать задания

### ISSUE THREAD

**Issue by ryabinintm** [peterarsentev/job4j_features_bugs#182]
3. Что такое JavaDoc [#403585]
4. Генерация документации по JavaDoc [#403586]
6. Тестовое задание из модуля коллекции Lite переделать на Stream API. [#403429]

**Comment by ryabinintm** [comment]
Напишите хотя бы когда ожидать

**Comment by staskorobeynikov** [comment]
Описания добавлены. Можете приступать к выполнению.
