### ISSUE TITLE
1. Наследование, композиция и агрегация 

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#184]
Ребят статья очень слабая, надо перерабатывать. Уже не первая статья от Вас где описание из далека и дальше вопросы.
Советую прорабатывать свой материал, то что мы ваши ученики должны дополнительно что-то искать и читать я понимаю.
Но это не значит что мы должны все время дочитывать чтобы понимать материал.
Ну если используете слово API, ну так потрудитесь распишите что это.
Даете пример композиции, ну так раскройте до конца чтобы по примеру было понятно что это.
Вот хороший пример **композиции**, по которой я все понял **https://javadevblog.com/chto-takoe-kompozitsiya-primer-kompozitsii-v-java.html**
Очень надеюсь на ваши понимание и оперативное действие от Вас. Очень хочется получать полноценный материал.

**Comment by peterarsentev** [comment]
Спасибо. Описание мы доработали.
