### ISSUE TITLE
Техническое задание. Аргегатора Java Вакансий. опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#185]
2. Уровень - Джуниор / Блок 3. SQL, JDBC / 6. Проект. Агрегатор Java вакансий.

задан**ие. Аргегатора J**ava - тут наверное либо точка не нужна либо просто "Агрегатор"
Программа долж**но с**читывать
вакансии относя**щие к Ja**va - наверное лучше относящиеся

**Comment by JelenaKar** [comment]
Исправлено.
