### ISSUE TITLE
Ошибка в условии упражнения.

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#186]
Без кода теста задача не очевидна.
Вместо в третей строчке вместо "квартира" должен быть "автомобиль".
![Screenshot_16](https://user-images.githubusercontent.com/75887570/102712533-d85e4c00-42e3-11eb-9907-5d23b4436dff.png)

**Comment by ShamRail** [comment]
Задание уточнено.
