### ISSUE TITLE
Цветовое оформнение строки "Job4j Courses С нуля до трудоустройства Ученики"

### ISSUE THREAD

**Issue by AshleySunsine** [peterarsentev/job4j_features_bugs#187]
В ночном режиме синий цвет этой строки становится плохо читаемым. Есть предложение сделать его светлее, голубым.
![ывывый](https://user-images.githubusercontent.com/19989087/102715319-9f26db80-42e5-11eb-8c34-472eeb22f1de.jpg)

**Comment by peterarsentev** [comment]
Темного интерфейса больше не будет.
