### ISSUE TITLE
1.1. Job c параметрами. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#188]
2. Уровень - Джуниор / Блок 3. SQL, JDBC / 6. Проект. Агрегатор Java вакансий.

коннект к ба**зу б**удет
Объект коннект будет передавать в Job. - скорее всего "передавать**ся**"
Job мы указывае**т** параметры
store является об**ш**им для
Создайте sql schema с таблицей rabbit и **после created date** - наверное "полем created_date"
В Job сделайте зап**ись таб**лицу

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
