### ISSUE TITLE
0. Spring Security [#348569] - Опечатка

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#19]
String **errorMessge** = null;
        if(error != null) {
            **errorMessge** = "Username or Password is incorrect !!";
        }
        if(logout != null) {
            **errorMessge** = "You have been successfully logged out !!";
        }
        model.addAttribute("**errorMessge**", **errorMessge**);

##############################################
errorMessge -> errorMessage - пропущена бука "a"
+++ это сказывается и далее:
##############################################

```
<c:if test="${not empty **errorMessge**}">
    <div style="color:red; font-weight: bold; margin: 30px 0px;">
            ${**errorMessge**}
    </div>
</c:if>
```

##############################################
+++ checkStyle
##############################################

```
\job4j_car_accident\src\main\java\controllers\LoginController.java:22:11: error: 'if' is not followed by whitespace.
\job4j_car_accident\src\main\java\controllers\LoginController.java:25:11: error: 'if' is not followed by whitespace.
\job4j_car_accident\src\main\java\controllers\LoginController.java:32:26: error: '=' is not preceded with whitespace.
\job4j_car_accident\src\main\java\controllers\LoginController.java:32:27: error: '=' is not followed by whitespace.
\job4j_car_accident\src\main\java\controllers\LoginController.java:33:30: error: '(' is preceded with whitespace.
\job4j_car_accident\src\main\java\controllers\LoginController.java:35:26: error: '{' is not preceded with whitespace.
```

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
