### ISSUE TITLE
Кнопка "Комментировать" после задач

### ISSUE THREAD

**Issue by aaterentev** [peterarsentev/job4j_features_bugs#192]
При нажатии на кнопку "комментировать" для составления ответа к задачам и урокам проматывает сайт к концу обсуждений (это не связанные по смыслу между собой блоки). Для обсуждений есть отдельная кнопка "обсудить".  
UPD.: при нажатии "Закрыть" та же ситуация.

**Comment by andreiHi** [comment]
исправлено
