### ISSUE TITLE
Неточность в тексте задачи Стажер 0. Что такое переменная.

### ISSUE THREAD

**Issue by aaterentev** [peterarsentev/job4j_features_bugs#193]
В тексте задачи Стажер 0. Что такое переменная указан размер памяти занимаемый boolean = 1 bit 
**boolean – описывают логический тип. 1 bit. Пример.**
В таблице 9.3. Преобразование примитивных типов указано другое значение: 
**boolean | От 8 до 32 бит в зависимости от способа использования**

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
