### ISSUE TITLE
Мотивирующая статья. Первые шаги и результаты. [#420808] | странное задание

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#196]
Странное нелогичное задание (видимо старое) здесь:
3. Мотивирующая статья. Первые шаги и результаты. [#420808]

![image](https://user-images.githubusercontent.com/35169516/103058584-9703c000-45b3-11eb-919f-4d51935626c1.png)

"2. Добавьте картинки в ваш пост с игрой пазл."
- игру пазл не делали, делали сокобан

"3. Добавьте ссылку на github, чтобы ваши друзья могли посмотреть код, запустить."
- для того чтобы запустить игру, ее надо выложить куда-то, пока не знаю куда код на java выложить, чтобы его запустить могли другие

**Comment by andreiHi** [comment]
спасибо поправили
