### ISSUE TITLE
Ошибка или так и должно быть?

### ISSUE THREAD

**Issue by Ivan-4884** [peterarsentev/job4j_features_bugs#199]
Доброго времени суток.
В 4.6.1. Switch [#384212] - в д\з есть строчка **public String nameOfDay(int day) {** там должно стоять static между public и String? Без неё у меня не получается выполнить:+
public static void main(String[] args) {
        System.out.println(SwitchWeek.nameOfDay(0));
}
Что бы протестировать, что будет выводить.

**Comment by staskorobeynikov** [comment]
Можно протестировать. Но нужно создавать объект. Об этом будет дальше.
Исправлено, спасибо.
