### ISSUE TITLE
в хроме с мака грузятся не все картинки

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#20]
mac os catalina
chrome 87

 в блоке **2.2. MSysGit. Установить и настроить.**

не все скриншоты видны
https://prnt.sc/vsea4d

ps в разметке есть ссылки на картинки и по ним все норм открывается

pss 81 ошибка в консоли и так же ученики пишут в комментах что не грузятся
![image](https://user-images.githubusercontent.com/35169516/100551552-6d949480-3292-11eb-834e-621f635a01f9.png)

**Comment by adelinyshka** [comment]
[по ссылке](https://job4j.ru/edu/task?action=task&taskId=0873958f76094d950176139e34d94d1c&number=420783)
в задании 9.2. Checkstyle [#420783]
картинка 8 не грузится, хотя в dom есть
![image](https://user-images.githubusercontent.com/35169516/100830151-0f270c00-3474-11eb-864f-2e1f8594e455.png)

**Comment by peterarsentev** [comment]
Это поправили во всем проекте.
