### ISSUE TITLE
Тесты для задачи "идеальный вес" [#384290] - whenWomen170Then80()?

### ISSUE THREAD

**Issue by Ivan-4884** [peterarsentev/job4j_features_bugs#200]
Доброго времени суток.
В задании - 2. Тесты для задачи "идеальный вес" [#384290] - указано: 2. Создайте в нем тест-методы для проверки идеального веса для мужчины и женщины. 

может тогда не whenMan170Then80(), а whenWomen170Then80()?

**Comment by aaterentev** [comment]
> Доброго времени суток.
> В задании - 2. Тесты для задачи "идеальный вес" [#384290] - указано: 2. Создайте в нем тест-методы для проверки идеального веса для мужчины и женщины.
> 
> может тогда не whenMan170Then80(), а whenWomen170Then80()?

а вы запускали этот тест через метод Fit.womanWeight(in)? попробуйте. там действительно whenMan

**Comment by Ivan-4884** [comment]
В задании просто указано создать тест для проверки расчета идеального веса для мужчины и женщины.
А оба метода для мужчин:
@Test
    public void whenMan180Then92() {
и
@Test
    public void whenMan170Then80() {

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
