### ISSUE TITLE
4.4. Вложенный оператор if else [#384217]

### ISSUE THREAD

**Issue by Ivan-4884** [peterarsentev/job4j_features_bugs#203]
Здравствуйте.
В задании 4.4. Вложенный оператор if else [#384217], в примере теста MultiMaxTest указана строка: import static org.hamcrest.Matchers.is. 
А как мне объяснили, что это устаревшая версия. В прочем и работает всё когда  - import static org.hamcrest.core.Is.is

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
