### ISSUE TITLE
Поиск по трекеру не работает

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#206]
Не работает поиск по сайту, хотел найти задачу по названию, но не смог, да и в принципе ни на что не реагирует поиск

**Comment by staskorobeynikov** [comment]
В новом интерфейсе все работает. Закрываю.
![image](https://user-images.githubusercontent.com/58299607/123995143-b2bea780-d9d6-11eb-93dc-8ecaf8103242.png)
