### ISSUE TITLE
Вопросы по изучению класса Scanner

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#207]
Упоминание и частичное описание и работу класса 
мы встречаем в
1.Уровень-Стажер/Блок 2.ООП/4.Полиморфизм/
1. Чтение из консоли. Класс Scanner. [#179514] или [#179518]

Там такая цитата:
... Далее, нужно создать объект Scanner. На данном этапе просто запомните конструкцию создания объекта Scanner. Он принимает в качестве параметра объект "System.in". 
Подробнее мы будет обсуждать это в другой части курса...

А далее мы видим уже вопросы в зачете курса Джуниор по второй части (IO) 

4. Что такое Scanner? 
5. Как работает Scanner внутри?
6. Какие базовые методы существуют в Scanner?

Нам уже нужно довольно глубоко его знать при том, 
что я не смог найти других лекции с описанием 
методов и свойств по данному классу (я могу ошибаться,
поиск работает плохо)

Возможно этот материал упущен либо пока не записан,
но знать его уже надо

**Comment by peterarsentev** [comment]
Добавили урок.
