### ISSUE TITLE
"Процесс обучения"

### ISSUE THREAD

**Issue by 777Egor777** [peterarsentev/job4j_features_bugs#209]
http://joxi.ru/YmEq60Ptw1pJ1m
Добавить отображения графика в новом интерфейсе.
В ТрэкСтудио вроде бы отображает

**Comment by staskorobeynikov** [comment]
После переезда на новую платформу все работает корректно, функционал даже несколько расширен
![image](https://user-images.githubusercontent.com/58299607/124283729-e7f10400-db54-11eb-8526-7f382fcd95bd.png)

Закрываю.
