### ISSUE TITLE
3. Модели данных и HashSet. Опечатка

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#211]
![2020-12-25_160840](https://user-images.githubusercontent.com/74650587/103133547-eab5fc80-46cc-11eb-8302-6afc7f4f869e.png)

В задании так же нужно поправить стиль шрифта. Так как текст в задании выделен красным цветом и другим шрифтом

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
