### ISSUE TITLE
5. PsqlStore. Опечатки?

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#214]
2. Уровень - Джуниор / Блок 3. SQL, JDBC / 6. Проект. Агрегатор Java вакансий.

по идее лишний импорт import ru.job4j.condition.Driver;

в этом задании у интерфейса Store появился метод Post findById(String id); хотя в 3. Архитектура проекта - Аргегатора Java Вакансий его нет

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
