### ISSUE TITLE
37. Массив без четных значений. Критика/предложение

### ISSUE THREAD

**Issue by Constantine-M** [peterarsentev/job4j_features_bugs#219]
Добрый день/вечер!

Во время прорешивания упражнений из раздела массивы столкнулся с бессмысленностью использования оператора.

В задаче 37 есть требование к методу решения: "В этой задаче будет необходимо использовать оператор continue.". 

Спросив совета в чате, выяснил, что ребята решили задачу без использования данного оператора, т.к. тоже не нашли в нем необходимости. Так вот, если все же есть необходимость использования данного оператора, то просьба указать направление, которое приведет к его правильному и уместному использованию. Процитирую Alex G: "ну в данном виде она позволяет слишком большие вольности)". Либо совсем убрать требование. Спасибо.

На всякий ссылка на коммит: https://github.com/Constantine-M/job4j_elementary/commit/364eafe2952c85996b4d596699fe8f490fdbcb2e

**Comment by andreiHi** [comment]
поправил
лучше не использовать его вообще
