### ISSUE TITLE
Стажер: 4.3.3. Логическое отрицание !

### ISSUE THREAD

**Issue by aaterentev** [peterarsentev/job4j_features_bugs#221]
Вообще, если читать задание, то получается какая-то абра-кадабра:

_"В нем уже есть методы..._

_Вам нужно написать код в_ **эти** _методы используя сочетания методов указанных_ **ниже:**"

Следуя этому высказыванию, следовало бы переписать уже написанные методы isEven() и isPositive(), применив методы: notEven(), notPositive(), notEvenAndPositive(), evenOrNotPositive().

Но, если я правильно понял суть задания, то оно должно звучать так:

_"В нем уже есть методы isEven() - проверяет, что число четное,

isPositive() -  проверяет, что число положительное._

_Вам нужно написать код в_ **оставшиеся** _методы используя сочетания методов указанных_ **выше**:"

**Comment by staskorobeynikov** [comment]
спасибо, исправлено.
