### ISSUE TITLE
0. Видео. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#225]
2. Уровень - Джуниор / Блок 4. Garbage Collection / 1. Понятие сборщик мусора

задание называется видео, хотя внутри текст
Объект**ы, а у к**оторых есть ссылки
Да, можно, но **не** виртуальная машина может это**т** проигнорировать.

**Comment by staskorobeynikov** [comment]
Раньше там было видео, сейчас текст. Им задания после генерации изменить нельзя. Поэтому так как есть.
Ошибки по описанию поправил.
