### ISSUE TITLE
5.1.2. Создать итератор четные числа [#150]

### ISSUE THREAD

**Issue by LuxCore** [peterarsentev/job4j_features_bugs#227]
В конце задания в разделе "Пожелания" добавить требования и/или рекомендации по реализации метода hasNext(). Например, метод hasNext() не должен изменять состояние объекта итератора по причине побочных эффектов, данный метод должен только проверять наличие следующего элемента. Либо: метод hasNext() может менять состояние своего объекта итератора в таких-то случаях.

**Comment by andreiHi** [comment]
спасибо поправил
