### ISSUE TITLE
0. Что такое полиморфизм. [#396102]

### ISSUE THREAD

**Issue by IvanKozhevnikov** [peterarsentev/job4j_features_bugs#23]
Сейчас обратите внимание на возникающую проблему. Для программиста, который будет читать этот код будет не понятно, почему мы записываем данные в файл, если у нас в коде прописана база. То есть на уровне самого кода возникает не допонимание. (недопонимание - слитно)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
