### ISSUE TITLE
Предложение для блока "Упражнения" -  сделать кнопку "Сброс"

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#230]
Кнопка "Сброс" находится внутри каждого упражнения, справа от кнопки "Проверить", она красного цвета/с красной обводкой.
Кнопка нужна для сброса прогресса по упражнению в котором находится пользователь, то есть удаляется код, написанный пользователем и остается только тот что был изначально в заданиие

Как вариант можно сделать кнопку "обнуление прогресса" по целому блоку, чтобы пользователь мог пройти заново упражнения, например, для тренировки

**Comment by staskorobeynikov** [comment]
кнопка добавлена, закрываю.
![image](https://user-images.githubusercontent.com/58299607/123989956-08dd1c00-d9d2-11eb-9d7a-1e22ebcdf2cd.png)
