### ISSUE TITLE
В обсуждениях Темы не могу вставить фото

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#231]
В обсуждениях Темы не могу вставить изображение, поясняющее суть проблемы.
Было бы удобнее, чем пользоваться сервисами.
<img width="856" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/103457881-efedf980-4d13-11eb-99cb-a1095aef0a27.png">

**Comment by peterarsentev** [comment]
Сделали.
