### ISSUE TITLE
Крестики-нолики на JavaFX [#173333]

### ISSUE THREAD

**Issue by ViktorJava** [peterarsentev/job4j_features_bugs#232]
Текст задания не соответствует названию задания.

![Screenshot_3](https://user-images.githubusercontent.com/54469691/103477003-8df0cb00-4dcb-11eb-9dff-cead74737104.jpg)

**Comment by staskorobeynikov** [comment]
дело в том, что после генерации заданий - название не меняется. а вот само задание поменять может, - пока проходили курс само задание изменилось а название поменять не можем. Сейчас оно выгялдит так
![image](https://user-images.githubusercontent.com/58299607/103905730-09c27e80-5110-11eb-8bdf-e91f92e48406.png)

Поэтому выполняйте согласно описанию, а ошибку закрываю.
