### ISSUE TITLE
2. Travis CI [#396051]

### ISSUE THREAD

**Issue by IvanKozhevnikov** [peterarsentev/job4j_features_bugs#234]
Ошибка№1: И открываем страница http://github.com/ на нем проекте.

Ошибка№2: Мы видим, что в прое,кте у нас теперь появилась статистика и любой может оценить наш проект по ней.

**Comment by ikioresko** [comment]
Дополню опечатки чтобы не дублировать тему

![2021-01-05_155905](https://user-images.githubusercontent.com/74650587/103643684-e1ebe300-4f76-11eb-9552-79e4e3f465a9.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
