### ISSUE TITLE
2. Комбинированный компаратор. Смысловая ошибка

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#238]
В уроке есть интересное предложение сделать комбинированный компаратор который сортирует по имени, приоритету и длине имени.

Если имя будет разное, то до проверки по приоритету и длине имени не дойдет.
Если имя будет одинаковое, приоритет разный, то до проверки длины имени не дойдет
Но, если имя будет одинаковое, приоритет одинаковый, то будет проверять длину имени, а если имя одинаковое то для чего проверять его длину?

![2021-01-05_095730](https://user-images.githubusercontent.com/74650587/103608215-a46a6400-4f3c-11eb-96c6-eb8320d6c881.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено. Поменял порядок вызовов.
