### ISSUE TITLE
Тёмная тема и ярко-белый шрифт

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#244]
В тёмной теме сайта шрифт ярко белый - пропадает смысл тёмной темы как отдыха для глаз. Прошу рассмотреть возможность настройки чуть менее яркого шрифта. Прилагаю картинку со сравнением реализовано в Idea. 

![изображение](https://user-images.githubusercontent.com/44730951/103804909-3cb33680-506c-11eb-8ecf-d9d0851a6ff1.png)

**Comment by peterarsentev** [comment]
Темного интерфейса больше не будет.
