### ISSUE TITLE
2. Группировка и агрегатные функции [#409285]

### ISSUE THREAD

**Issue by Just1kz** [peterarsentev/job4j_features_bugs#245]
В связывающей таблице 2 одинаковые ссылки на 1 источник, что противоречит принципу связывающей таблице.
create table students_subjects(
    id serial primary key,
    student_id int references **students(id),**
    subject_id int references **students(id),**
    -- оценка студента по предмету
    mark int
);
Требуется корректировка 2-ой ссылки на таблицу - subjects

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
