### ISSUE TITLE
Не корректное задание или не корректный тест. (Упражнения)

### ISSUE THREAD

**Issue by aaterentev** [peterarsentev/job4j_features_bugs#249]
Упражнения
 1.1.6. Массивы
 3. Объединить два отсортированных массива

"Даны два отсортированных по возрастанию массива. Как без сортировки их объединить в третий массив?"
Добавил по порядку сперва данные из массива 1, потом из массива 2. 
Выкинуло ошибку на тесте "whenReorder". Но, не было указано, что требуется вносить данные по возрастанию.

**Comment by staskorobeynikov** [comment]
Все корректно. Имеется ввиду не сортировать исходные массивы. Конечный массив должен быть отсортирован. Тут нужен алгоритм сортировка слиянием.
