### ISSUE TITLE
Опечатки в упражнении  Блок 3. Collections. Lite. 2. Коллекция Set, HashSet. 0. Set, HashSet, Iterator. 

### ISSUE THREAD

**Issue by extrausa** [peterarsentev/job4j_features_bugs#25]
В коллекциях типа java.util.Set _не(нет)_ возможности указать индекс. Так же здесь нет возможности заменить элемент.
boolean hasNext() - проверяет, _(если ли)_ можно заменить на наличие следующего элемента в списке.
T next() - возвращает элемент из коллекции и (переводить) переводит указатель на следующий элемент.
void remove() - удаляет элемент из коллекции и (переводить) переводит указатель назад.
(На данным момент) На данный момент, вам нужно запомнить, что для перебора элементов внутри java.util.List и java.util.Set нужно использовать цикл for-earch.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
