### ISSUE TITLE
1. Отчеты. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#254]
2. Уровень - Джуниор / Блок 5. ООД / 1. SRP

клас Employee а в коде местами используется Employer
public Employe**r**(String name, Calendar hired
Employe**r** employ**er =** (Employ**er) o**;
List<Employ**er> f**indBy(Predicate<Employee> filter);
employ**ers**.add(em);

В тесте мы ожидаем что после Salary будет точка с запятой, а после каждой строки перевод строки (что логично)
``` 
.append("Name; Hired; Fired; Salary;")
.append(System.lineSeparator())
...
.append(worker.getSalary()).append(";")
.append(System.lineSeparator());
```
но в ReportEngine::generate этого нет
```
text.append("Name; Hired; Fired; Salary");
for (Employee employee : store.findBy(filter)) {
  .....
  .append(employee.getSalary()).append(";");
}
```

**Comment by andreiHi** [comment]
поправил, спасибо
