### ISSUE TITLE
0. Видео. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#255]
2. Уровень - Джуниор / Блок 5. ООД / 2. OCP

 контекст, в котором буде**м** применяться сам класс
Подобный подход мешает **на сл**едованию
Поля должна также должны представлять тип абстракций.
т.к. чтобы расширить программу придется наследоваться, но всегда наследование возможно.

>- на создаваемые объекты
>- на поля
>- на параметры и возвращаемые типы методы.

было немного сложно понять что это все пункты списка, может как-то жирнее их сделать или по другому выделить?

В блоках кода есть лишние пустые строки, прям бросается в глаза

List<Car> cars = List.of(new Car(), new Car(), new NoSoundCar()); - думаю в первом блоке в листе не должно быть new NoSoundCar(), так как речь о новом типе машин идет только дальше по тексту.

**Comment by JelenaKar** [comment]
Исправлено.
