### ISSUE TITLE
1. Поддержка форматом XML, JSON, HTML в генераторе отчетов. Опечатка

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#256]
2. Уровень - Джуниор / Блок 5. ООД / 2. OCP

Поддержка формат**ом** XML
Из пожеланий к заданию: рассказать подробнее что сделать

**Comment by dmitrytishchenko** [comment]
все правильно - поддержка формата

**Comment by ViktorJava** [comment]
опечатка в фамилии: `4. Приложить ссылку и перевести ответственного на Петра Арсеньева`

**Comment by peterarsentev** [comment]
Поправил.. Спасибо.
