### ISSUE TITLE
1. Развернуть приложение на heroku [#348541]

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#257]
Middle / Блок 4. Spring / 7. Deploy / 1. Развернуть приложение на heroku

==============================
обновите команду:

git push heroku master

git push heroku main

или укажите 2 варианта.
* с новыми репами Первый вариант может не работать.

==============================
странная фича/бага - через IDEA терминал она не заработала, а через cmd всё норм.
* win 10

**Comment by reybos** [comment]
Возникли проблемы с этим заданием, помогли комментарии оставленные другими учениками:

Проблема с версией java в heroku, помогло 
в корень проекта файл system.properties с содержимым - java.runtime.version=14

и 
В классе WebSecurity удалите поле PasswordEncoder, если оно есть.

**Comment by ShamRail** [comment]
Задание исправлено.
