### ISSUE TITLE
Опечатка в задаче: 6.5.2. Поиск минимума в диапазоне. [#412268]

### ISSUE THREAD

**Issue by vukivur** [peterarsentev/job4j_features_bugs#26]
Задача: 6.5.2. Поиск минимума в диапазоне. [#412268]

В начале задачи написано: "Давайте начнем с каркаса ru.job4j.array.MinDiapason."
А в конце задачи идет задание:
"""1. Доработайте требуемый функционал класса ru.job4j.array.Min.
2. Залейте код в репозиторий. Оставьте ссылку на коммит.
3. Выставите ответственного Петра Арсентьева."""

Если класс назвали: "ru.job4j.array.MinDiapason" - видимо, надо его дорабатывать и заливать, а не класс: "ru.job4j.array.Min".
Спасибо.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
