### ISSUE TITLE
Хранилище продуктов. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#260]
2. Уровень - Джуниор / Блок 5. ООД / 3. LSP

Food **сп**олям**и.** **N**ame, e**xpaire**Date, dis**s**count
Food с полями: name, expiryDate, discount
зависимости от усло**виый.**
использовать шаблон проектирован**ие**
Пункты 3.1-3.4 визуально левее чем 1-3

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
