### ISSUE TITLE
2. Сервис - Кинотеатр [#357482]

### ISSUE THREAD

**Issue by VladimirGladkilh** [peterarsentev/job4j_features_bugs#264]
В тексте задания две таблицы
2. Создайте две таблицы. halls, accounts. 

а входе выполнения задания появилось замечание от ментора(М): 
М: - нужно добавить ограничения на таблицы.  У тебя сейчас при параллельных транзакциях данные затрутся. 
Я: - О каких именно ограничениях идет речь?
Если CONSTRAIN на уровне БД, то не уверен что сработает. У нас сейчас только апдейт существующих записей с местами и привязки Аккаунт-места в зале нету. Соответственно нельзя понять кто "занимает места"
М: в таблице ticket не может быть одного и того же сеанса, места и ряда. Это и нужно сделать уникальным полем.

Откуда ticket взялся? в описании его нет

**Comment by ShamRail** [comment]
Задание обновлено. Issue не актуально.
