### ISSUE TITLE
2. Сервис - UrlShortCut [#348586] - опечатки

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#267]
**Плаг** registration указывают, что регистрация выполнена или нет, то есть сайт уже есть в системе.

Нужно:
**Флаг** registration указывают, что регистрация выполнена или нет, то есть сайт уже есть в системе.

=========================================================================

4. Загрузите код в **githu**. Оставьте ссылку на проект.
Нужно:
4. Загрузите код в **github**. Оставьте ссылку на проект.

=========================================================================

Нумерация подзадач:
1. Регистрация сайта. 
1.1. Авторизация.
2. Регистрация URL.
2. Переадресация. Выполняется без авторизации. 
3. Статистика.

Лучше сделать так: (так понятнее сколько всего тут Реально нужно сделать)
1. Регистрация сайта. 
2. Авторизация.
3. Регистрация URL.
4. Переадресация. Выполняется без авторизации. 
5. Статистика.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
