### ISSUE TITLE
Опечатка в задаче: 6.5.3. Сортировка выборкой. [#412266]

### ISSUE THREAD

**Issue by vukivur** [peterarsentev/job4j_features_bugs#27]
После вводной части, после слова "Объяснение." написано:
"1. Создайте класс ru.job4j.SortSelected с методом указанным ниже."
И далее в примере с кодом показан класс с package: "ru.job4j.array.SortSelected". 

Вывод: в первом предложении пропущено слово "array."
Спасибо.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
