### ISSUE TITLE
Указанный размер float не соответствует действительности [#450169]

### ISSUE THREAD

**Issue by Camoukey** [peterarsentev/job4j_features_bugs#270]
В описании float "числа с плавающей точкой. Диапазон примерно такой же, как и у int." указана неверная информация.
Это подтверждается в открытых источниках, и даже в следующем уроке.
Размер int - от -2147483648 до 2147483647
Размер float от от 1.4e-45 до 3.4e+38
Разница в десятки порядков и речи о примерной равноправности даже не идет.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
