### ISSUE TITLE
Опечатки в упражнении

### ISSUE THREAD

**Issue by MarinaKurilova** [peterarsentev/job4j_features_bugs#272]
Упражнения - 1.1.2. Тип данных - 6. Возведения числа в степень

Часто может потребоваться возвести число в степень. Вспомним немного школьную математику. Что такое возведение в степень? Это умножение **числ** на само себя какое-то число раз. Например, 2 в степени 2 это 2 * 2 = 4, или 3 в степени 3 это 3 * 3 * 3 = 27. 

В Java **не готовых оператор** для возведения числа в степень, но есть библиотека Math.

**Comment by staskorobeynikov** [comment]
исправлено
