### ISSUE TITLE
Не закрывается упражнение (0.4. Понятие редукции. Метод reduce(). Редукция с начальным значением)

### ISSUE THREAD

**Issue by BogdanKopylov** [peterarsentev/job4j_features_bugs#276]
Ссылка на упражнение - [https://job4j.ru/edu/task_code?topicId=3&taskCodeId=100&solutionId=20429](url)
Ошибка - [https://prnt.sc/x0xcc1](url)

**Comment by kamikhaylov** [comment]
Подтверждаю ошибку. Не удается закрыть задание.
[https://prnt.sc/xa93hv](url)

**Comment by staskorobeynikov** [comment]
исправлено
