### ISSUE TITLE
4.3.6. Math.abs

### ISSUE THREAD

**Issue by snowflakes75** [peterarsentev/job4j_features_bugs#278]
Добрый день.

В данном разделе нету кнопки запуски кода в примере и как следствие нету вывода.
Прикладываю скрин проблемы.

![image](https://user-images.githubusercontent.com/77325744/104856247-a4963680-5922-11eb-98df-b808be43eb57.png)

**Comment by staskorobeynikov** [comment]
там и не должно быть никакой кнопки. там просто приложен скриншот. вернитесь и посмотрите, картинка там появилась
