### ISSUE TITLE
1. Уровень - Стажер  Блок 1. Базовый Синтаксис.  3. Тестирование

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#288]
Рекомендую добавить в раздел тестов материал на тему как использовать пакет
org.hamcrest.Matchers.*

Так как данный пакет используется в курсе, нормального понимания у меня лично к нему так и не появилось.

**Comment by staskorobeynikov** [comment]
org.hamcrest.Matchers в Базовом синтаксисе больше нет
