### ISSUE TITLE
Дополнить разделы блоков

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#289]
Думаю стоит дополнить разделы блоков ссылками на расширенное изучения тем.
Также допустим раздел должен состоять из базового материала, для желающих углубиться раздел должен содержать дополнительную информацию, методы, примеры. А не давать в конце блока список страниц в книгах.
То что мы должны искать нужный материал это понятно. Но не всегда в книгах или статьях все описано доступным языком.
Но это ИМХО. Вам решать чем наполнять курс.

**Comment by peterarsentev** [comment]
Спасибо. Я подумаю. Мы будем делать статьи на нужны темы.
