### ISSUE TITLE
2. Регистрация пользователя [#348567] - Опечатка

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#29]
```
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String password;

    ,private String username;

    @ManyToOne
    @JoinColumn(name = "authority_id")
    private Authority authority;
```

Лишняя запятая перед полем "username":
**,private String username;**

##################################

`import org.sprin,gframework.stereotype.Controller;`

Лишняя запятая в слове "**sprin,gframework**"

##################################

`<form name=,'login' action="<c:url value='/reg'/>" method='POST'>`

Лишняя запятая в слове: _**name=,'login'**_

##################################
```
insert into users (username, enabled, password, authority_id)
values ('root', true, '$2a$10$wY1twJhMQjGVxv4y5dBC5ucCBlzkzT4FIGa4FNB/pS9GaXC2wm9/W',
        (select id from authorities where authority = 'ROLE_ADMIN'));
```
sql запросе не работает, т.к. в INSERT не указан параметр "enabled" и по default ставится null. Для boolean null запрещён, поэтому нужно указать его явно.

Исправлено:
```
insert into users (username, enabled, password, authority_id)
values ('root', true, '$2a$10$wY1twJhMQjGVxv4y5dBC5ucCBlzkzT4FIGa4FNB/pS9GaXC2wm9/W',
        (select id from authorities where authority = 'ROLE_ADMIN'));
```
##################################

ДОП, хз так задумано или нет, короче, ещё одна лишняя замятая в codeBlock :

Не забудьте прописать доступ в SpringSecurity.
```
,
.antMatchers("/login", "/reg")
.permitAll()
```

P.s. Не задача, я запятая! :D :D :D

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
