### ISSUE TITLE
0. Checkstyle с Maven

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#290]
1. Уровень - Стажер
 Блок 3. Collections. Lite.
 5. Инструменты
 0. Checkstyle с Maven

Чтобы подключить плагин checkstyle, нужно в pom.xml добавить блок <plugins> ... </plugins>, а внутрь него добавить вот такой код. У вас не рабочий кусок для вставки в конфиг xml.
Вот рабочий вариант

<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <configuration>
                            <configLocation>checkstyle.xml</configLocation>
                            <encoding>UTF-8</encoding>
                            <consoleOutput>true</consoleOutput>
                            <failsOnError>true</failsOnError>
                            <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </pluginManagement>
    </build>

**Comment by peterarsentev** [comment]
@RuslanFajziev А в чем ошибка? Я перепроверил. У меня проект собирается.
