### ISSUE TITLE
2. Создания чата на Rest API. [#348547]

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#295]
1. Реализовать REST Api через Spring Boot
2. Сделать **три** модели **Person. Role. Room, Message.**
3. Приложение должно реализовывать чат c комнатами.

- Поясните тут 3 или 4 модели.
- поясните за модель Role - как она должна себя вести в проге? (я так понимаю что она тут не нужно, но когда-то, она была нужна.)

**Comment by dmitrytishchenko** [comment]
поправил
