### ISSUE TITLE
1. Запуск нити. Thread#start() Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#297]
3. Уровень - Middle / Блок 1. Multithreading / 1. Threads

**Поэтому** так не однозначно?
Давайте создадим новый модуль **chapter_007** - видимо раньше была другая структура проекта, сейчас кажется нелогичным такой номер
уже в **ните** с именем Thread-0.
System.out.println(Thread.currentThread().getName()); - во втором блоке кода цветом как комментарий
another.run(); **закомментировали оператор.**
не дает указания выполнить свои операторы в отдельной **ните**
операторы в той же **ните**

**Comment by reybos** [comment]
3. Уровень - Middle / Блок 1. Multithreading / 1. Threads / 1.1. Состояние нити

Напомню, что в этой программе присутствуют **все** нити: main и first

**Comment by reybos** [comment]
3. Уровень - Middle / Блок 1. Multithreading / 1. Threads / 1.2. Режим ожидания.

Через 1 секунду выводите на консоль информацию о за**грузку.** 
**Выводит** должна с обновлением строки.

**Comment by reybos** [comment]
1. Threads / 3. Прерывание нити

Thread.sleep **(1)**; /* симулируем выполнение параллельной задачи в течение 1 секунды. */
progress.interrupt(); **//**

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
