### ISSUE TITLE
3.1. Прерывание блокированной нити. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#299]
3. Уровень - Middle / Блок 1. Multithreading / 1. Threads

если нить находи**ться**
В этом случае методы sleep, join, wait **выкинуть** исключение
Нить **продолает** свою работу. 
**Этот** схема является шаблоном. Запомните, если используются методы sleep, wait, **но** нужно в блоке catch вызвать прерывание.

в задании "3. Прерывание нити" в пункте 
3. Внутри метода run нужно добавить цикл  с проверкой флага. Внутри цикла - сделать задержку в 500 мс. 
нужно добавить задержку внутри вечного цикла, при этом мы устанавливаем флаг прерывания для этой нити из главной нити и ловим исключение, но о том как с этим работать говорится только в следующем уроке, может стоит убрать из этого пункта требование с задержкой?

**Comment by ReyBos** [comment]
хотя если в 
1. Поправьте код в классе Wget. В блоке catch уберите исключение и добавьте прерывание.
имеется ввиду не Wget, а ConsoleProgress, то последнее мое замечание не актуально

**Comment by staskorobeynikov** [comment]
исправлено. Если не поставить задержку, то вы попросту не увидите что символ меняется.
