### ISSUE TITLE
Ссылка сюда

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#30]
Предлагаю уточнить ссылку сюда
https://github.com/peterarsentev/job4j_features_bugs/issues
а не на 
https://github.com/peterarsentev/job4j_features_bugs

**Comment by ShamRail** [comment]
> Предлагаю уточнить ссылку сюда
> https://github.com/peterarsentev/job4j_features_bugs/issues
> а не на
> https://github.com/peterarsentev/job4j_features_bugs

А где уточнить?

**Comment by peterarsentev** [comment]
Поправил. Сервер не обновлял еще.
