### ISSUE TITLE
0. ToOne[6873#378309]

### ISSUE THREAD

**Issue by dmitriyermoshin19** [peterarsentev/job4j_features_bugs#300]
Обратите внимание: при сохранении модели User Hibernate не требует весь объект Role. Ему нужен только ключ.

Пример.

Role role = create(Role.of("ADMIN"), sf);
Role recreated = new Role();
role.setId(role.getId());
create(User.of("Petr Arsentev", recreated), sf);

тут наверное не правильно стоит role.setId(role.getId());
должно быть recreated.setId(role.getId());

**Comment by reybos** [comment]
Добавлю. Лишние импорты 

import ru.job4j.tracker.Item;

import java.time.LocalDate;
import java.time.Month;

**Comment by staskorobeynikov** [comment]
Поправил
