### ISSUE TITLE
4. Скачивание файла с ограничением. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#301]
3. Уровень - Middle / Блок 1. Multithreading / 1. Threads

Что такое Callable. - первая строчка в задании, похоже что ее быть не должно

Внутри этого метода мы описываем действия, которые Java **выполнил** параллельно.
В этом задании **Нужно** написать

каркас класса Wget не оформлен как код

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
