### ISSUE TITLE
Что такое атомарность. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#302]
3. Уровень - Middle / Блок 1. Multithreading / 2. Общие ресурсы

Может возникнуть ситуация, что обе нити **выполнять** чтение переменной одновременно.
Атомарность - это свойство определяющее группу операций, **который** выполняется не разрывно. 
Все операции, где данные **зависит** от начального состояния не атомарны

**Comment by reybos** [comment]
наверное конструктор из задания должен быть public
**private** static Cache instOf()

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
