### ISSUE TITLE
3. Immutable объекты. 

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#304]
3. Уровень - Middle / Блок 1. Multithreading / 2. Общие ресурсы

в теле класса Node, Node по идее должно быть везде с параметром <T>
в этом задании появились аннотации @ThreadSafe, @NotThreadSafe и @Immutable, возможно стоит добавить пару слов о них, зачем нужны. ну и можно добавить пример импорта net.jcip в pom.xml

**Comment by reybos** [comment]
p.s. как оказалось дальше есть целый урок "2. JCIP. Настройка библиотеки", возможно стоит как-то раньше его дать

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
