### ISSUE TITLE
Общий вид составление заявки

### ISSUE THREAD

**Issue by snowflakes75** [peterarsentev/job4j_features_bugs#305]
Добрый день.

Было бы замечательно, если бы появился manifest по составлению заявки,

Цель. Существенно уменьшить кол-во повторных и дублирующих заявок по ошибкам, также сократит поиск заявки, если возникнет желание завести issue, поскольку пользователи заводят их по разному на данный момент.

Пример, manifest по составлению bug-а

titile - Уровень, Номер задания и имя полностью, как в tracker, Суть проблемы
descr - Полное описание, приложение скриншота ошибки. Алгоритм воспроизведение ошибки, если она воспроизводимая 

Таких инструкций сделать несколько(для бага по курсу, по трекеру, предложений).

**Comment by peterarsentev** [comment]
Спасибо за идею. Но пока у нас не так много багов и совсем мало предложений.
Если добавить схему, то ученики не будут ее заполнять и не будут оставлять даже эти баги и предложения.
