### ISSUE TITLE
2. Модель памяти Java. Пожелания

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#307]
3. Уровень - Middle / Блок 1. Multithreading / 2. Общие ресурсы

начиная с задания "1. Threads / 3.1. Прерывание блокированной нити." используется метод join(), но пока не было информации о том что он нужен что бы дождаться завершения потока, только у Шилдта прочитал об этом, возможно стоит дать информацию об этом. 

Про объект монитор и критическую секцию будет расказано только в "3. Синхронизация ресурсов / 0. Объект монитор, критическая секция", возможно стоит это сделать раньше, так как данное выражение и код вызвали недоумение 

лишний пробел в коде

![image](https://user-images.githubusercontent.com/30983051/105850566-f4e05900-5ff2-11eb-92bd-a0aedfadcf95.png)

**Comment by reybos** [comment]
в задаче "3. Синхронизация ресурсов / 2. JCIP. Настройка библиотеки"  в комментарии к тесту только появилась информация о том для чего нужен join().

**Comment by ShamRail** [comment]
Замечания учтены.
