### ISSUE TITLE
Опечатка в тексте задачи

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#31]
https://job4j.ru/edu/task_code?topicId=1&taskCodeId=5&solutionId=15935

закрыт**ь**

![image](https://user-images.githubusercontent.com/35169516/100649824-11924480-3354-11eb-947f-d6fa6dddeb6c.png)

Так же при загрузке задачи всегда вверху уведомление, что задача решена верно, либо неверно
Уведомления при открытии задачи впервые быть не должно

Так же в зависимости от того как решена любая задача - статусы меняются сразу у всех задач в разделе
Решил 1 - у всех статусы зеленые, не решил - у всех статусы красные

![image](https://user-images.githubusercontent.com/35169516/100650136-86657e80-3354-11eb-8657-91fcd4940159.png)

![image](https://user-images.githubusercontent.com/35169516/100650395-ecea9c80-3354-11eb-9d8e-b85ae12f083a.png)

**Comment by adelinyshka** [comment]
Опечатка в тексте задачи
![image](https://user-images.githubusercontent.com/35169516/100651388-6b940980-3356-11eb-9770-9878e60ee405.png)

https://job4j.ru/edu/task_code?topicId=1&taskCodeId=10&solutionId=new_task

"Напишите программу, которая вывод**ит** на консоль строчку "Сегодня я молодец!"

**Comment by adelinyshka** [comment]
![image](https://user-images.githubusercontent.com/35169516/100830381-95dbe900-3474-11eb-96e8-2d8bc17dac31.png)
[ссылка](https://job4j.ru/edu/task?action=task&taskId=0873958f76094d950176139e34d94d1c&number=420783)
в задании 9.2. Checkstyle [#420783]

**Comment by staskorobeynikov** [comment]
исправлено
