### ISSUE TITLE
8.1. Промежуточные операции. Метод distinct(). Уникальные числа

### ISSUE THREAD

**Issue by kamikhaylov** [peterarsentev/job4j_features_bugs#313]
8.1. Промежуточные операции. Метод distinct(). Уникальные числа
Не проходит тест в песочнице.
В IDEA все работает, тест не ругается.

[https://prnt.sc/xq1fn6](url)

`        return IntStream.of(data)
                .distinct()
                .boxed()
                .collect(Collectors.toList());`

Ошибка:
`error: invalid flag: /root/job4j_edu/sandbox/0873958f75835f7501758420bf7b33b7/
Usage: javac <options> <source files>
use --help for a list of possible options`

**Comment by staskorobeynikov** [comment]
исправлено
