### ISSUE TITLE
4. ThreadSafe динамический список

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#318]
Блок 1. Multithreading / 3. Синхронизация ресурсов

Возьмите класс ru.job4j.collection.DynamicList из задания из модуля коллекции - я так понимаю речь тут про ru.job4j.collection.SimpleArray
Копировать код коллекции ru.job4j.collection.**DynamicList** не надо. Вам нужно подключить модуль **chapter_005**. - у нас сейчас код этой коллекции в другом проекте, я так понимаю не получится просто подключить
В **chapter_009** нужно добавить зависимость модуля **chapter_005**
Этот код работает не верно. Он отдает ссылку на оригинальный итератор. Если мы будем... - текст внутри блока для кода
Метод copy - вы должны написать самостоятельно. - тоже текст внутри блока кода
![image](https://user-images.githubusercontent.com/30983051/106159098-7f60be00-6195-11eb-95fd-ff2d2357e114.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
