### ISSUE TITLE
0. Stream API улучшения. Опечатки

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#319]
Поля класса Student инициализируются в конструкторе в другом порядке, который отличается от того как создаются объекты Student в классе Теста.
![2021-01-29_111103](https://user-images.githubusercontent.com/74650587/106240678-8257bf00-6226-11eb-9824-304022b50574.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
