### ISSUE TITLE
0. Управление нитью через wait. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#323]
3. Уровень - Middle / Блок 1. Multithreading / 4. Wait, Notify, NotifyAll

Программа ждет, когда **в** порт**у со**едини**тьс**я клиент**а**.
Метод wait переводит нить в состояние ожидан**ие,** если программа не может дальше выполн**ятся**.
Когда нить заходи**ть в** метод check
У объекта монитора есть мет**од w**ait, notifyAll. 
Есть подозрение что в методе public void off() monitor.notifyAll(); вызывать не нужно

**Comment by reybos** [comment]
Переменная total содержит количество **вызовом** метода count().
2. Загрузите код в **gitbut**

**Comment by reybos** [comment]
3. Уровень - Middle / Блок 1. Multithreading / 4. Wait, Notify, NotifyAll / 2. Обеспечить остановку потребителя.

лишние импорты
import net.jcip.annotations.GuardedBy;
import net.jcip.annotations.ThreadSafe;
import java.util.LinkedList;
import java.util.Queue;

ну и нет привычного блока "Задание"

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
