### ISSUE TITLE
3. Junit тест для блокирующей очереди. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#325]
3. Уровень - Middle / Блок 1. Multithreading / 4. Wait, Notify, NotifyAll

в этих двух предложениях как будто немного логика хромает и опечатка
Если она пустая нужно произвести остановку нити и проверить результат.
Если очередь переполненная нужно приостановить потребителя и дать возможность просчитать **потребителю**.

Так же сложность возникает в **блокировки** потребителя или производителя
то мы не **сможет** прочитать все данные.
buffer - нужен, чтобы собрать все данные в список и проверить в конце выполнения теста. - цвет текста
есть лишние пустые строки в блоках кода
проверит состояние очереди и завершит цикл. - перенесено на новую строку
после текста Задание. можно удалить пару пустых строк

**Comment by andreiHi** [comment]
спасибо поправил
