### ISSUE TITLE
Небольшие опечатки

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#33]
[
<img width="674" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/100685511-951c5780-338d-11eb-8bed-a3b85eef6eb2.png">
](url)

**Comment by peterarsentev** [comment]
Этот проект к курсе не относиться. Я создал отдельный тикет.
https://github.com/peterarsentev/course_test/issues/8
