### ISSUE TITLE
0. CAS - операции. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#330]
3. Уровень - Middle / Блок 1. Multithreading / 5. Non Blocking Algoritm

Операции write и read по отдельности **атомарный**.

возможно поля узла можно сделать приватными
private static final class Node<T> {
        final T value;
        Node<T> next;

по идее классу не нужен параметр
public class CASСount<T> {

**Comment by reybos** [comment]
такое ощущение что в названии класса CASСount есть русская С, при копипасте чекстайл ругается )
![image](https://user-images.githubusercontent.com/30983051/106392246-074b0000-6402-11eb-8489-7b1e3c516066.png)

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
