### ISSUE TITLE
Стажер/ООП/4Полиморфизм/9.1 Зависимость от System.out

### ISSUE THREAD

**Issue by aaterentev** [peterarsentev/job4j_features_bugs#333]
3. В тесте проверяем, что Stub**Input** содержит вывод меню.

@Test
public void whenExit() {
    Output out = new StubOutput();
    Input in = new StubInput(
            new String[] {"0"}
    );
    Tracker tracker = new Tracker();
    UserAction[] actions = {
            new Exit()
    };
    new StartUI(out).init(in, tracker, actions);
    assertThat(out.toString(), is(
            "Menu." + System.lineSeparator() + 
                    "0. Exit" + System.lineSeparator()
    ));
}

Проверяется что в переменной out будет текст вывода меню, т.е. проверяется Stub**Output**

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
