### ISSUE TITLE
1. Неблокирующий кеш. Опечатки/оформление

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#334]
3. Уровень - Middle / Блок 1. Multithreading / 5. Non Blocking Algoritm
 
В целом задание выглядит недооформленным. То код не в блоке кода, то текст в блоке кода

1. Необходимо сделать кеш для **хранение** моделей. **в** кеше должны быть методы 
add(Base model), update(Base mod**el) d**elete(Base mode**l),**

Для этого в модели данных должно быть **после** int version.

Два пользователя прочитали данные task_1 - непонятно что за task_1 + нелогичный перенос строки после этой строки

Это **после** должно увеличиваться

сам**ое. ну**жно перед обновлением данных провери**ть. что** текущий пользователь не затер данные другого пользоват**еля. есл**и данные затерты

сам**ое. ну**жно перед обновлением данных провери**ть. чт**о текущий пользователь не затер данные другого пользовате**ля. е**сли данные затерты

**Comment by reybos** [comment]
вообще сложное для понимания задание, не хватает связности имхо

**Comment by reybos** [comment]
Чтобы это поправить нам нужно передать исключен**ие к гла**вную нить.

**Comment by staskorobeynikov** [comment]
задание переделано, взгляните на его текущую версию

**Comment by reybos** [comment]
Спасибо!
