### ISSUE TITLE
Доступность кнопки "Закрыть" для роли "Ученик"

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#335]
При выполнение задачи доступны две кнопки "Закрыть" и "Комментировать".
При этом, согласно инструкции, ученик должен нажимать "Комментировать", потом ожидать согласования задачи, и лишь потом нажимать "Закрыть".  Тогда не понятно, а - почему кнопка "Закрыть" доступна сразу? Похоже на недоработку.
Было бы удобно, если процесс следовал стандартному сценарию бизнес-процессов:
1. Ученик без согласования не может закрыть задачу (лучше вообще скрыть кнопку "Закрыть");
2. Если задача согласована, она автоматически закрывается тем, кто ее проверил.
3. Если задача не согласована, она возвращается ученику и он видит оповещение.

**Comment by DaniilsLoputevs** [comment]
Плюсую за решение! 
* Но тогда нужно сделать оповещение боту что "Такая-то, задача закрыта Таким-то, ментором".
П.С. Могу сделать эти изменения в коде, т.к. разбирался в устройстве этого бота и на связи с его реальным автором. )))

**Comment by peterarsentev** [comment]
@kalenikov Поправили. Теперь можно выполнить только комментировать.
