### ISSUE TITLE
баг с лайком и блоком на странице "Понравилось задание?" 

### ISSUE THREAD

**Issue by DaniilsLoputevs** [peterarsentev/job4j_features_bugs#336]
Если нажать лайк/диз, то пропадает этот блок, а ведь это шорт-кат к "критики и предложений".
Думаю что стоит, поправить эту фичу-баг.
* Можно этот шорт-кат перенеси, но он органично тут смотрится, так что проще сделать "Не убераемым и отмечать лайки и тут".

Обычно:
![image](https://user-images.githubusercontent.com/55362320/106505385-260fcc00-64c0-11eb-9d8a-85d3b2b78e02.png)
После нажатия лайк/диз
![image](https://user-images.githubusercontent.com/55362320/106505490-493a7b80-64c0-11eb-83ed-93306aaeb74f.png)

**Comment by peterarsentev** [comment]
Багу поправили. Спасибо.
