### ISSUE TITLE
0. ThreadSafe Singleton. Опечатки/оформление

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#337]
3. Уровень - Middle / Блок 1. Multithreading / 6. Пулы

много мест где текст перемешан с кодом

При реализации шабл**он S**ingleton необходимо учитывать проблему с visibility (**В**идимостью).
Многопоточные реализации аналогич**ный** не многопоточным.
Объект enum создается при **загрузки** класса и безопасно публикуется **всех** клиентам.
Реализация этого шаблона **аналогично** не многопоточной среде.
Если у вас нет необходимости в ленивой **загрузки** **используется** шаблоны из первой группы.

нет блока с заданием или указанием что задача ознакомительная

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
