### ISSUE TITLE
1. Реализовать ThreadPool. Опечатки/оформление 

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#338]
3. Уровень - Middle / Блок 1. Multithreading / 6. Пулы

текст в блоке кода

Пул - это **хранилища** для ресурсов, которые можно переиспользовать. - наверное хранилище
Клиент берет ресурс из пула, выполняет свою работу и **возвращается** обратно в пул. - наверное возвращает

текст на картинке выглядит не связным
![image](https://user-images.githubusercontent.com/30983051/106594509-42187980-6563-11eb-8362-75b9ee7a39e3.png)

не написано для чего нужен метод public void shutdown() (остановить выполнение потоков?) и нет блока с привычным заданием
SimpleBlockingQueue - Это класс из задачи **#1098  [#1098]** - 3. Уровень - Middle / Блок 1. Multithreading / 4. Wait, Notify, NotifyAll / 1. Реализовать шаблон Producer Consumer.

**Comment by reybos** [comment]
два лишних импорта
import java.util.Queue;
import java.util.concurrent.LinkedBlockingQueue;

**Comment by staskorobeynikov** [comment]
спасибо за замечания, исправлено
