### ISSUE TITLE
2. ExecutorService рассылка почты. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#339]
3. Уровень - Middle / Блок 1. Multithreading / 6. Пулы

Закрываем пул и ждем пока все задачи **завершаться**.
Через ExecutorService создайте задачу, которая будет **создать** данные
7. В своей папке добавьте задачу с этим именем. - возможно устаревший пункт

**Comment by reybos** [comment]
создайте метод public void send(String **suject**

**Comment by ReyBos** [comment]
"В классе будет метод emailTo(User user) - он должен через ExecutorService **отправлять** почту."
судя по заданию метод emailTo(User user) будет создавать данные для пользователя а вот public void send(String suject, String body, String email) уже отправлять

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
