### ISSUE TITLE
1. Техническое задание - проект "Pooh JMS". Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#341]
3. Уровень - Middle / Блок 1. Multithreading / 7. Проект - Pooh JMS

**2В** этом проекте мы сделаем
Приложение запускает Socket и **ждем** клиентов.
Клиенты могут быть двух типов: отправители (publisher), получатели (**subscriver**).

**Comment by reybos** [comment]
Все нужно сделать на Executors и **conccurent** коллекциях.

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
