### ISSUE TITLE
Пустые комментарии

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#344]
Просьба убрать возможность оставлять комментарий к задаче, если он пустой.
У меня уже несколько раз был ответ от проверяющего "нет ссылки", хотя я был всегда точно уверен, что оставлял ссылку. Было бы удобно, если бы система сразу выдала ошибку, если сообщение пустое.

**Comment by peterarsentev** [comment]
@kalenikov А каким ты браузером пользуешься?

**Comment by kalenikov** [comment]
@peterarsentev хром последней версии

**Comment by andreiHi** [comment]
![image](https://user-images.githubusercontent.com/29897507/111031279-5d529080-840f-11eb-91e2-579a94357223.png)
добавили
