### ISSUE TITLE
4.4. Вложенный оператор if else [#457865]

### ISSUE THREAD

**Issue by tarasu4ok** [peterarsentev/job4j_features_bugs#348]
я не понял где тут логично использовать вложенный if

если вот такой вариант:

int res = first;

if (second >= first) {
    if (third >= second) {
        res = third;
    } else {
        res = second;
    }
} else {
    if (third >= first) {
        res = third;
    }
}
return res;
то он не вполне укладывается в постановку задачи, где задано, что вначале нужно выбрать максимум из первых двух чисел (храним максимум в переменной result) и уже его сравниваем с третьим.

Мой вариант решения был такой:
[https://github.com/tarasu4ok/job4j_elementary/commit/82e5cfb6b961ead6a8c222fcd9ec221b63a487ca](url)
и в комментариях я описал эти свои сомнения. однако проверяющий написал, что я сделал правильно и задачу можно закрыть.
но у меня нет вложенного оператора if. так что, на мой взгляд, либо я всё же сделал неверно, либо нужно поменять постановку задачи.

**Comment by staskorobeynikov** [comment]
спасибо за Ваш комментарий, задание заменили. Можете ознакомиться с его новой версией.
