### ISSUE TITLE
2.2. Лямбда блок [#408963]

### ISSUE THREAD

**Issue by Slepchenko** [peterarsentev/job4j_features_bugs#349]
В условии под пунктом 3 сказано сделать задание, залить его в репозиторий, оставить ссылку на коммит, но в каком классе и пакете делать задание не указано. Я написал решение этого задания в комментариях, скорей всего этого и требовалось, раз после проверки была дана команда закрыть. Посему предлагаю внести изменение в условие пункта 3

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
