### ISSUE TITLE
1. JSTL замена Scriplets. Проблема с импортом

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#351]
3. Уровень - Middle / Блок 2. Servlet JSP / 4. Шаблон MVC

``` <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %> ``` - вот так не работает, помог коммент в задаче
``` <%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %> ```

**Comment by staskorobeynikov** [comment]
спасибо исправлено
