### ISSUE TITLE
Перевести время в 24-х часовой формат.

### ISSUE THREAD

**Issue by DenysMelnychenko** [peterarsentev/job4j_features_bugs#353]
Предлагаю перевести время в 24-х часовой формат, так как иногда возникают недопонимания, как например на следующем скрине.
![Screenshot from 2021-02-09 21-12-35](https://user-images.githubusercontent.com/15909135/107418428-50e0cc80-6b1f-11eb-977c-16252bb31e0a.png)

**Comment by andreiHi** [comment]
Спасибо поправил
