### ISSUE TITLE
1. Загрузка и скачивание файла. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#356]
3. Уровень - Middle / Блок 2. Servlet JSP / 5.1. Form

с такими импортами не работает нормально
<%@ page language="java" pageEncoding="UTF-8" session="true"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
заменил на импорты из предыдущих заданий 
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<%@ page contentType="text/html; charset=UTF-8" %>

<img src="<c:url value='/download?name=${image**}'"** width="100px" height="100px"/> - не закрытый тег <c
ru.job4j.**servlets** - в предыдущих заданиях пакет был ru.job4j.dream.servlet
Вначале мы создаем фабрику по которой можем понять, какие данные есть в **запросы**

скорее всего вот это 
<pre><code>File folder = new File("images");
if (!folder.exists()) {
    folder.mkdir();
}</code></pre>
нужно перенести из doPost в doGet, так как этот запрос раньше происходит, ну и я без переноса получал нулПоинтерЭксепшн

Загрузка картинки **производиться на** отдельной форме. Создайте в базе таблица **phote**(id). id генерируется базой. 

Файл должен **храниться на** файловой системе. в папке bin/images/**phote_id**

**Comment by staskorobeynikov** [comment]
задание переписано
