### ISSUE TITLE
Не понятно офрмлены примеры, не понятно что делать

### ISSUE THREAD

**Issue by iiuhenio** [peterarsentev/job4j_features_bugs#357]
В большинстве примеров дан просто код и я как-то должен понять, что он означает. Я так не могу, ничего не понятно. В Интернете видел код, и для КАЖДОЙ строчки есть описание, в котором написано, для чего она нужна. Без этого я вообще не понимаю, что происходит

**Comment by peterarsentev** [comment]
@iiuhenio Можете дать примеры задания? Все задания мы делали исходя из принципа рассказываем новое и даем задачу на закрепления. Если в коде есть, что-то новое, но это не было раньше в описании, то это нужно поправить. Но для этого мне нужны детали. Какие задания вызывали затруднения.
Так же в курсе есть принцип первого часа. Если не можешь сделать, то пишешь сразу Арсентьеву Петру.
