### ISSUE TITLE
Новичку непонятно, что делать

### ISSUE THREAD

**Issue by SafonovMikhail** [peterarsentev/job4j_features_bugs#358]
В разделе https://job4j.ru/edu, начиная с 3.1 Проверка числа на четность, стоит добавить пример выполнения. А именно, кратко рассказать, что такое функция и что уже передается аргумент, и по факту следует написать конструкцию [return], или же, как это было сделано в предыдущих примерах, на паре задач просто необходимо раскомментировать, чтобы ученик привыкал к коду.

**Comment by SafonovMikhail** [comment]
public class EvenCheck {
    public static boolean check(int num) {
       //здесь вообще непонятно, что писать, сама конструкция новая
    }
}
---------------РЕШЕНИЕ---------------

public class EvenCheck {
    public static boolean check(int num) {
        // return num ... 2 == 0;  
        // в первом примере из серии предложить что-то типа такого.
    }
}

**Comment by peterarsentev** [comment]
Это раздел упражнения. Их нужно делать после выполнения задания основного курса.
Видимо Вы перескочили основные задания. В основных заданиях идет подробный разбор методов, аргументов, параметров и понятия функции.
