### ISSUE TITLE
0. Страница Login.jsp. Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#360]
Уровень - Middle / Блок 2. Servlet JSP / 6. Filter, Security

два лишних иморта в login.jsp
<%@ page import="ru.job4j.dream.model.Candidate" %>
<%@ page import="ru.job4j.dream.store.PsqlStore" %>

в сервлете AuthServlet мы генерируем ошибку 
<code>req.setAttribute("error", "Не верный email или пароль");</code>
но нигде не обрабатываем ее, на странице login.jsp можно было бы добавить что-то вроде 
````
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<%@ page contentType="text/html; charset=UTF-8" %>
...............
<button type="submit" class="btn btn-primary">Войти</button>
<c:if test="${not empty error}">
<div class="alert alert-danger mt-4" role="alert">
<c:out value="${error}"/>
</div>
</c:if>
````

**Comment by staskorobeynikov** [comment]
поправил
