### ISSUE TITLE
Упражнения -> 1.1.6. Массивы -> 13. Доступ к остальным элементам массива

### ISSUE THREAD

**Issue by Rogovolod** [peterarsentev/job4j_features_bugs#361]
При решении упражнения выдаёт ошибку, выполнить упражнение невозможно. Прошу исправить

/root/job4j_edu/sandbox/0873958f71bc5b2a0171bedc0e280953/ru.job4j.array/LoopForArrayTest.java:16: error: cannot find symbol
        LoopForArray.main(null);
        ^
  symbol:   variable LoopForArray
  location: class LoopForArrayTest
1 error

**Comment by staskorobeynikov** [comment]
![image](https://user-images.githubusercontent.com/58299607/108882748-cb2c4900-7615-11eb-8412-8953a65b9d9c.png)
все работает корректно, проверьте свое решение
