### ISSUE TITLE
1. Написать тест на PostServlet.

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#365]
3. Уровень - Middle / Блок 2. Servlet JSP / 7. Mockito

private final Validate logic = ValidateService.getInstance(); - у нас до этого не было такого класса, возможно сейчас это PsqlStore
а вместо ValidateStub можно использовать MemStore

из комментариев к задаче я узнал что нужно еще вот это подключить
```
   <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>2.0.0</version>
    </dependency>
```

еще сборка в трависе падала, заменил версии подключаемых модулей и все заработало 
```
   <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>3.3.3</version>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>2.0.2</version>
    </dependency>
```

**Comment by staskorobeynikov** [comment]
все исправил Раиль
