### ISSUE TITLE
8. JS, JQuery, Ajax. Оформление

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#367]
3. Уровень - Middle / Блок 2. Servlet JSP / 8. JS, JQuery, Ajax

**1. index.html + bootstrap, form, table**
лишний пробел после 1 пункта
код из 2 пункта не оформлен как код
в задаче подключается бутстрап 3 и ссылка на примеры по нему, может есть смысл 4 использовать

**2. Валидация формы JS**
обычный текст в блоках кода
В форму из задан**ие** **#58522  [#58522]** для полей

**3. Заполнить динамически таблицу.**
часть кода не оформлена как код, часть текста в блоках кода
В задании **#58522  [#58522]** добавьте поведение, **которые** добавляет

**Comment by reybos** [comment]
**4. Ajax Jquery**
Вообще с первого задания этого раздела было не понятно в каком проекте выполнять задания, я продолжил в dream_job. Но в этом задании появилась инфа о проекте items из chapter_008, возможно это артефакты из прошлого, если так и нужно все-таки продолжать в dream_job работать, то есть замечания:
package ru.job4j.**servlets**; ru.job4j.**servlets**.GreetingServlet - в дрим_джоб это ru.job4j.dream.servlet
http://localhost:8080/ **items** /greet?name=Petr - в двух местах

еще немного смущает что везде в коде переменные name и а в форме у инпута имя exampleInputEmail1 и тип email

**Comment by staskorobeynikov** [comment]
Поправил
