### ISSUE TITLE
Блок 2. Servlet JSP. Пожелания

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#368]
Уровень - Middle / Блок 2. Servlet JSP / 4. Шаблон MVC / 0. MVC в Servlet.

Обратите внимание. Этот сервлет будет доступен по адресу /index.do. Тут есть расширение, оно нужно будет в разделе безопастность. 
В этом блоке так и не было информации зачем мы сделали расширение .do (ну по крайней мере что-то не припомню такого, вряд ли мимо себя пропустил)

мне кажется для логической завершенности проекта не хватает двух вещей, я то их добавил, но возможно есть смысл сделать на это задачи в курсе?
3. Уровень - Middle / Блок 2. Servlet JSP / 2. JSP / **6. Обновление кода без перезапуска сервера.**
на главной странице мы добавили раздел сегодняшние вакансии и кандидаты но так и не заполнили эти блоки
3. Уровень - Middle / Блок 2. Servlet JSP / 6. Filter, Security / **1. HttpSession**
добавили кнопку выйти но не реализовали функционал

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
