### ISSUE TITLE
Стажер. Блок 2. ООП  6. ООА\П  2. Singleton

### ISSUE THREAD

**Issue by Jazzik42** [peterarsentev/job4j_features_bugs#369]
Проект Tracker. Когда я начал делать тест Maven с JaCoCo то тестирование (тесты на каждый метод) выдало ошибки. Ошибки из - за того, что когда включаем весь класс тестирования, Maven так и делает, выявляются ошибки в тестклассе StartUI в методах Delete, Replace, FindAll и другие. Хотя если тесты этих методов отдельно запускать друг от друга то проблем нет, тесты проходят. Проблема эта потому что, у нас один объект Tracker (благодаря Singleton) и мы с ним работаем. А ведь тесты каждого метода ничего не знаю друг о друге. Вот и получается так, что в одном методе мы добавили один Item, в другом другой Item , в третьем что то удалили. А объект Tracker не меняется, следовательно не меняется и его поле List<Item>. Следовательно вылетают ошибки (допустим тестируем метод Add (добавляем Item1) потому тестируем метод Replace (добавляем item2). Но в методе Replace тест не знает о item1, но он в объекте Tracker есть. Я решил частично эту проблему делая зачистку tracker.findAll().clear() перед тестом каждого метода. Теперь лишних item нет. Но появилась другая проблема. Поле класса Tracker - private ids+ не обнуляется таким способом. Мы добавляем один, другой, третий item при проведении всего класса тестов, удаляем их, а счетчик растет и растет, и не обнуляется. Как решить этот вопрос?

**Comment by peterarsentev** [comment]
@Jazzik42 Мы изменили задание. У нас была ошибка в согласовании. Сейчас мы ее убрали. Спасибо, что сообщили.
