### ISSUE TITLE
Зависает отправка сообщения в режиме "Комментировать"

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#372]
Неоднократно сталкиваются с тем, что при нажатии на кнопку "Сохранить и перейти далее" кнопка блокируется и ничего не происходит.
![image](https://user-images.githubusercontent.com/12701878/108312879-62ce0980-71c8-11eb-8c54-6f41c3c822a7.png)
Если потом обновить страницу, то сбрасывается авторизация:
![image](https://user-images.githubusercontent.com/12701878/108312975-8b560380-71c8-11eb-9abc-be6bce8505f8.png)
Просьба починить, сильно мешает.

**Comment by peterarsentev** [comment]
Поправили.
