### ISSUE TITLE
Постоянно слетает авторизация

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#373]
При произвольных действиях слетает авторизация
![image](https://user-images.githubusercontent.com/12701878/108349384-f8cb5980-71f3-11eb-9438-8adf79f685c6.png)

**Comment by kalenikov** [comment]
![image](https://user-images.githubusercontent.com/12701878/108349800-7b541900-71f4-11eb-9ebc-693fc67c202d.png)

**Comment by kalenikov** [comment]
![image](https://user-images.githubusercontent.com/12701878/108350160-edc4f900-71f4-11eb-938a-aed1f2168b3b.png)

**Comment by peterarsentev** [comment]
@kalenikov Мы обновили сервер. Просьба сообщить, если будет повторяться.
