### ISSUE TITLE
1. Уровень - Стажер  Блок 2. ООП  4. Полиморфизм  8. Реализация меню за счет шаблона стратегия.

### ISSUE THREAD

**Issue by Krasobas** [peterarsentev/job4j_features_bugs#379]
в описании урока есть неточность:

![image](https://user-images.githubusercontent.com/36446403/108998647-46433d00-76b2-11eb-8ec8-5228fa4faa1d.png)

Однако

public String name() {
return "=== Create a new Item ====";
}
это не название пункта меню, это заголовок, который всплывает при выборе действия.

Если я правильно понял, то вместо этого должно быть:

@Override
    public String name() {
    return "Add new Item"; // Пункт меню
}

@Override
public boolean execute(Input input, Tracker tracker) {
    System.out.println("=== Create a new Item ===="); // Заголовок действия
    String name = input.askStr("Enter name: ");
    Item item = new Item(name);
    tracker.add(item);
    return true;
}

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
