### ISSUE TITLE
Задача: 6.6.8. Двухмерный массив. Таблица умножения. [#412258]

### ISSUE THREAD

**Issue by vukivur** [peterarsentev/job4j_features_bugs#38]
После задания идет строка:
"Например, если size = 9, у вас должна получиться таблица, представленная ниже."

- И ниже никакой таблицы не представлено. И непонятно, как делать, потому что нет наглядного примера, какой должен быть результат.

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
