### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by ruslandavydov** [peterarsentev/job4j_features_bugs#384]
В курсе много внимания уделяется тестам. Возможно стоит выделить маленький блок, в котором будет более подробно расписана тема написания тестов? Какие самые часто применяемые, в каком случае какой тест лучше применять и т.д.

**Comment by reybos** [comment]
Плюсую. Тоже как-то думал об этом

**Comment by klea0840** [comment]
1.1. Входные данные в тесте [#488563]

появляется Assert.assertEquals без каких-либо пояснений. Будет лучше, если включить краткое пояснение.

**Comment by peterarsentev** [comment]
Взяли в разработку.
