### ISSUE TITLE
2.4. Функции первого порядка [#368341]

### ISSUE THREAD

**Issue by i1rr** [peterarsentev/job4j_features_bugs#386]
Решил начну писать свои предложения.
В задаче идет в пример язык скала и мне вправду интересно увидеть примеры и понять разницу. Описание происходит очень поверхностное и чтобы разобраться что к чему, то нужно лезть в инет и не известно сколько изучать язык. Объясните что означает знак ":" и пошагово как работают эти функции и что они делают. В описании происходят манипуляция слов "функции, аргументы, параметры" и это просто запутывает. Я не Джун, и такая подача информации заставляет скроллить вниз и переходить на след. урок, оставляя этот урок бесполезным. 
 Возможно есть более умные ребята, кто это понимает с первого раза, но новичкам вроде меня при виде такого урока хочется закрыть лаптоп и начать плакать :) спасибо

**Comment by peterarsentev** [comment]
@i1rr Урок убрали из курса. Он не относится к теме Java Lambda.
