### ISSUE TITLE
4.1. Сканирование файловой системы. опечатка

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#39]
в описании задания
SearchFiles seacher = new SearchFiles(p -> p.toFile().getName.endsWith(ext));
не хватает скобок
SearchFiles seacher = new SearchFiles(p -> p.toFile().getName **()** .endsWith(ext));

**Comment by reybos** [comment]
2. Уровень - Джуниор / Блок 2. Ввод-вывод / 1. Ввод-вывод / 4.1. Сканирование файловой системы.

**Comment by staskorobeynikov** [comment]
исправлено
