### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by java73core** [peterarsentev/job4j_features_bugs#392]
Выявлен неправильный тест.
Блок массивы.
3. Объединить два отсортированных массива.

    @Test
    public void whenReorder() {
        int[] expect = {1, 2, 3, 4};
        int[] result = Merge.merge(
                new int[] {1, 3},
                new int[] {2, 4}
        );
        assertThat(result, is(expect));
    }

There was 1 failure:
1) whenReorder(ru.job4j.array.MergeTest)
java.lang.AssertionError: 
Expected: is [<1>, <2>, <3>, <4>]
     but: was [<1>, <3>, <2>, <4>]

**Comment by peterarsentev** [comment]
@java73core В результат объединения массивов должен получиться отсортированный массив.
Это упражнение на алгоритм слияния массивов.
Тест у нас верный.
