### ISSUE TITLE
error

### ISSUE THREAD

**Issue by java73core** [peterarsentev/job4j_features_bugs#393]
Ошибка в тесте.
6. Сумма элементов массива.

public class SumTest {

    @Test
    public void getSum() {
        int[] in = {1, 2, 3, 4, 5};
        int expected = 6;
        int result = Sum.getSum(in);
        assertThat(result, is(expected));
    }
}

There was 1 failure:
1) getSum(ru.job4j.array.SumTest)
java.lang.AssertionError: 
Expected: is <6>
     but: was <15>

**Comment by andreiHi** [comment]
А в какой это задаче или упражнении ?
Где искать ?

**Comment by peterarsentev** [comment]
@java73core В этом упражнении нужно сложить значение первого и последнего элемента. 
У программа считает не так.
