### ISSUE TITLE
2. Группировка и агрегатные функции [#373618]

### ISSUE THREAD

**Issue by peterarsentev** [peterarsentev/job4j_features_bugs#398]
Мне кажется в этом задании https://job4j.ru/TrackStudio/staticframeset.html#373618
есть ошибка в одном из скриптов.

TrackStudio
https://job4j.ru

Алексей 16:16
Напишем запрос, который выводит средний бал по предмету:
(в этом запросе все правильно)

select s.name, avg(ss.mark) 
from students_subjects as ss 
join subjects s on ss.subject_id = s.id
group by s.name;

Запрос по среднему баллу ученика будет аналогичным:
(мне кажется неверно, т.к. здесь используется то же условие on ss.subject_id = s.id что и в скрипте выше, но inner join делается не с таблицей subjects а с таблицей students, так что правильным условием будет ss.student_id = s.id)

select s.name, avg(ss.mark) 
from students_subjects as ss 
join students s on ss.subject_id = s.id
group by s.name; 

Найдем предмет, по которому ученики набрали более 4.5 баллов
(аналогично, здесь используется то же условие on ss.subject_id = s.id но inner join делается не с таблицей subjects а с таблицей students, так что правильным условием будет ss.student_id = s.id)

select s.name, avg(ss.mark) 
from students_subjects as ss 
join students s on ss.subject_id = s.id
group by s.name
having avg(ss.mark) > 4.5;

**Comment by ShamRail** [comment]
Спасибо. Поправил
