### ISSUE TITLE
Аргегатора - опечатка

### ISSUE THREAD

**Issue by Tatiana-N** [peterarsentev/job4j_features_bugs#411]
![image](https://user-images.githubusercontent.com/72814164/111367919-4da0a980-86a6-11eb-8ecb-1b585c5e7ae5.png)
[https://job4j.ru/edu/task?action=task&taskId=0873958f75232cd901752749fb066357&number=388108](url)

**Comment by andreiHi** [comment]
спасибо 
исправил
