### ISSUE TITLE
4.4. Liquibase. Интеграционные тесты. Proxy. [#95881]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#415]
Проверьте пожалуйста, по моим данным, в последних версиях класс Item
содержал только два параметра и один конструктор
...
public class Item implements Comparable<Item> 
    private String id;
    private String name;

    public  Item(String name)
        this.name = name;
...    
    В задании указано другое:
<img width="440" alt="Item" src="https://user-images.githubusercontent.com/46091342/111384384-7c287f80-86ba-11eb-8a2a-48194129dbfe.png">

**Comment by andreiHi** [comment]
спасибо поправил
