### ISSUE TITLE
0. Что такое интеграционное тестирование. [#456104]

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#417]
3. Уровень - Middle / Блок 3. Hibernate / 4. Интеграционное тестирование

в задании написано что база данных для каждого теста будет удаляться и создаваться новая

>После выполнения теста такая БД уничтожается и генерируется заново для каждого теста.

но по факту второй тест падает с ошибкой что такая таблица уже создана в БД, поискал в чате, другие решали это удалением таблицы в <code>@After</code>

**Comment by staskorobeynikov** [comment]
поправил
