### ISSUE TITLE
Упражнения 1.4.2. Stream API - не работает сортировка задач

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#427]
Сортировка идет в хаотичном порядке:

1. flatMap для итератора
2.5. Сборка элементов. Сборка в произвольную реализацию Collection
5.3. Промежуточные операции. Метод map(). Map с объектами
7.2. Промежуточные операции. Метод skip()
2.7. Сборка элементов. Сборка в строку
9.4. Промежуточные операции. Метод dropWhile()
0.4. Понятие редукции. Метод reduce(). Редукция с начальным значением
0.3. Понятие редукции. Метод reduce(). Произведение чисел
и т.д

Пример на скрине: https://prnt.sc/10sjz3o

**Comment by staskorobeynikov** [comment]
После переезда на новую платформу все работает корректно
![image](https://user-images.githubusercontent.com/58299607/124136958-e8729780-da8d-11eb-82ab-47ea64a41140.png)
