### ISSUE TITLE
Предложение по каналам/каналу телеграмм.

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#428]
Есть предложение сделать бота, для ТГ канала/каналов. Который раз в день будет публиковать какие то полезные советы. Например hotkeys среды разработки IDEA. Или какой то полезный/интересный метод, алгоритмы  и т.д.

**Comment by peterarsentev** [comment]
Спасибо за предложение. Полезную информацию мы добавляем напрямую в курс.
