### ISSUE TITLE
Выигрышные комбинации в сокобан 

### ISSUE THREAD

**Issue by vtorm-b** [peterarsentev/job4j_features_bugs#430]
https://job4j.ru/edu/task?action=task&taskId=0873958f7758004101776671c663548a&number=464557
В задании Игровое поле представляет собой массив, заполненный символами '_' (подчеркивание).
В проверки о подчеркивании речь не идет.
![image](https://user-images.githubusercontent.com/78522215/112435363-97ad1d80-8d7f-11eb-9acd-eeb4622f7d1b.png)

**Comment by andreiHi** [comment]
спасибо, исправлено
