### ISSUE TITLE
Упражнения  1.4.2. Stream API  2.6. Сборка элементов. Сборка в произвольную реализацию Map

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#432]
В тесте идет обращение к несуществующему классу

/root/job4j_edu/sandbox/0873958f7758004101775991ae7f770e/ru.job4j.stream/CollectToAnyMapTest.java:19: error: cannot find symbol
        Map<Integer, Integer> result = **CollectToMapWhenDublicate**.collect(data.stream());
                                       ^
  symbol:   variable CollectToMapWhenDublicate
  location: class CollectToAnyMapTest
1 error

В задании мы реализуем класс CollectToAnyMap

**Comment by andreiHi** [comment]
спасибо, исправлено
