### ISSUE TITLE
0. Видео [#453957]

### ISSUE THREAD

**Issue by BaceH** [peterarsentev/job4j_features_bugs#438]
Job4j /  Courses /  С нуля до трудоустройства / Ученики / any / 3. Уровень - Middle / Блок 2. Servlet JSP / 8. JS, JQuery, Ajax / 0. Видео
 
вместо видео отображается строка. видео нету (
DescLink{6871}

**Comment by peterarsentev** [comment]
Эта задача осталась от старой версии. Видео в курсе больше нет. Мы все заменили на текст.
