### ISSUE TITLE
0. Видео. Опечатки

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#439]
![2021-03-31_201222](https://user-images.githubusercontent.com/74650587/113168302-fa118c80-925d-11eb-8932-225e7f6b6f45.png)

**Comment by ikioresko** [comment]
2. Уровень - Джуниор
 Блок 3. SQL, JDBC
 5. JDBC
 0. Видео

**Comment by JelenaKar** [comment]
Исправлено
