### ISSUE TITLE
Добавить картинку в задание

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#44]
задание 9.2. Checkstyle [#420783]

не хватает картинки с указанием что в открытом окне коммита нужно нажать на иконку шестеренки, чтобы добавить проверку

здесь
![image](https://user-images.githubusercontent.com/35169516/100830597-1569b800-3475-11eb-8f91-0471ac1d36a1.png)

примерно такую
![image](https://user-images.githubusercontent.com/35169516/100830658-33cfb380-3475-11eb-9aa7-e11b1463a43d.png)

**Comment by staskorobeynikov** [comment]
спасибо, добавлено
