### ISSUE TITLE
Quartz [#293728]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#444]
Вопросы по теме Quartz [#293728]

При запуске программы все работает, но выдается ошибка (см скрин)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Раиль написал:
quartz использует slf4j, а для него нужен какой-то логгер. Добавьте зависимость log4j и его настройки, т.к. как мы это делали в разделе про логгирование

Если я правильно понимаю, порядок следующий:
- дописать в pom.xml зависимости
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.30</version>
        </dependency>

- создать или перенести настройки файла log4j.properties
log4j.rootLogger=DEBUG, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{ISO8601} %5p %c:%M:%L - %m%n		
		
- сделать Maven реимпорт
- сделать Maven Install

Предлагаю добавить эту информацию к уроку, либо ранее, к уроку по созданию
проекта job4j_grabber

<img width="951" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/113321361-30addc80-931c-11eb-8b39-6ee4a7bc5f6d.png">

**Comment by ShamRail** [comment]
Задание поправлено. Добавлен пункт по подключению логгера.
