### ISSUE TITLE
2. Каркас шахматной доски [#404515]

### ISSUE THREAD

**Issue by Krasobas** [peterarsentev/job4j_features_bugs#447]
ошибка в методе way: сначала в сигнатуре два параметра Cell[] way(Cell source, Cell dest);
а чуть ниже уже один:   Cell[] way(Cell dest);
![image](https://user-images.githubusercontent.com/36446403/113471467-1c292b80-9465-11eb-8993-7b4da519efc1.png)

**Comment by staskorobeynikov** [comment]
задача переделана, закрываю.
