### ISSUE TITLE
8. Индекс максимального значения

### ISSUE THREAD

**Issue by vtorm-b** [peterarsentev/job4j_features_bugs#451]
[https://job4j.ru/edu/task_code?topicId=2&taskCodeId=45&solutionId=new_task](url)
Метод должен вернуть индекс элемента который является максимальным из двух: первый элемент и последний элемент.
В первом тесте указано не максимальное число 5, а int expected = 4, и выдается ошибка
![image](https://user-images.githubusercontent.com/78522215/113654071-a2de4280-96c9-11eb-8440-9e56a455fbee.png)

**Comment by staskorobeynikov** [comment]
Вы путаете значение и индекс, поэтому и неразбериха. Вам нужно найти максимальное значение из двух и при этом вернуть не его значение, а индекс ячейки, в которой находится этот элемент.
Закрываю, в задаче все верно
