### ISSUE TITLE
Упражнение 15. Элементы с четными индексами

### ISSUE THREAD

**Issue by vtorm-b** [peterarsentev/job4j_features_bugs#453]
Условие: метод печатает элементы массива, которые имеют четные индексы.
В Проверке указаны нечетные индексы
@Test
    public void main() {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        System.setOut(new PrintStream(out));
        EvenIndexArray.main(null);
        String ln = System.lineSeparator();
        String expected = "1" + ln + "3" + ln + "5" + ln + "7" + ln + "9" + ln; 
        assertThat(out.toString(), is(expected));
    }
}

**Comment by AJIEKCanderG** [comment]
всё верно в тестах же.

**Comment by staskorobeynikov** [comment]
Там все верно, надо вывести элементы с четными индексами, а не нечетные элементы. Закрываю.
