### ISSUE TITLE
7. Метод удаления заявки Tracker.delete [#444626]

### ISSUE THREAD

**Issue by AleksFromBuk** [peterarsentev/job4j_features_bugs#457]
![image](https://user-images.githubusercontent.com/78998655/114090270-e3071600-98bf-11eb-942e-1d9a7816d2c0.png)
не, похоже вариант с минусом tems[size - 1] верный...

**Comment by staskorobeynikov** [comment]
Здесь все верно рассуждается, будьте внимательны. Но исправил другой недочет, можете вернуть и посмотреть.
Закрываю.
