### ISSUE TITLE
2. Travis CI заменить сылку в статье на рабочую

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#462]
1. Уровень - Стажер
 Блок 3. Collections. Lite.
 5. Инструменты
 2. Travis CI
 
 необходимо заменить утаревшкую ссылку проекта https://travis-ci.org/
 на https://travis-ci.com/ и обновить описание настрокий и картинки в статье. Т.к org в скором времени будет не доступен и уже сейчас не работает корректно с проектами

**Comment by AndreyPolegaev** [comment]
Да

**Comment by staskorobeynikov** [comment]
Неактуально. Все исправлено, разделено на 2 задачи, codecove и travis подключаются в отдельных задачах. Закрываю.
