### ISSUE TITLE
2. Парсинг HTML страницы. [#293730]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#463]
Вопросы по теме 
2. Парсинг HTML страницы. [#293730]

----

Цитирую:
"Нам нужна еще дата обновления поста.
Чтобы его извлечь нужно указать индекс." 

Не очень понятно, что за индекс, индекс чего, 
Как его получить?

Статья кажется незаконченной.

Я увидел, что используются методы сhild(),  parent(),
Интуитивно догадываюсь, что это предки и дети элементов
в структуре, но нее нашёл по ним понятных простых 
объяснений и примеров. 

Не могли бы вы несколько расширить объяcнение,
а также указать, почему именно эти методы 
вы использовали в примере, а не другие.
В чем разница? Более удобно или что-то ещё?

**Comment by peterarsentev** [comment]
Взяли в работу.
