### ISSUE TITLE
10. Еженедельная зарплата

### ISSUE THREAD

**Issue by Aleksandr-Molchanov** [peterarsentev/job4j_features_bugs#467]
В третьем тесте к задаче неправильно указан ожидаемый результат.  690 нужно заменить на 650.
@Test
    public void calculateIs690() {
        int[] hours = {10, 0, 12, 0, 8, 12, 4};
        int rsl = WeeklySalary.calculate(hours);
        assertThat(rsl, is(690));
    }

**Comment by Aleksandr-Molchanov** [comment]
Так же смущает то, что это упражнение помещено в раздел 1.1.4. Оператор ветвления

**Comment by AJIEKCanderG** [comment]
Все там верно указано.
пн  -10 часов. ЗП =  80 ( 8 часов по 10 баксов ) + 30 (2 часа по 15 баксов) =  110 баксов
вт - 0
ср  -12 часов. ЗП =  80 ( 8 часов по 10 баксов ) + 60 (4 часа по 15 баксов) =  140 баксов
чт - 0 
пт - 8 часов   ЗП =  80 ( 8 часов по 10 баксов ) = 80 баксов
сб - 12 часов = 160 ( 8 часов по 20 баксов ) + 120 (4 часа по 30 баксов) =  280 баксов
вс - 4 часа = 80 (4 часа по 20 баксов) = 80 баксов
итого за неделю = 110+0+140+0+80+280+80 = 690

**Comment by RomanKarczewski** [comment]
> Так же смущает то, что это упражнение помещено в раздел 1.1.4. Оператор ветвления

Присоединяюсь к этому смущению. Я в курсе еще не проходил массивы, хотя нахожусь на 1 раздел позже этого упражнения на 1.1.5.

**Comment by staskorobeynikov** [comment]
Основной посыл в задаче - сделать правильные проверки. Цикл нужен только чтобы перебрать массив
Можно пропустить задачу и вернуться после соответствующего раздела. 
AJIEKCanderG все верно пояснил. Спасибо.
Закрываю.
