### ISSUE TITLE
Повторяющиеся задания!

### ISSUE THREAD

**Issue by Quertte** [peterarsentev/job4j_features_bugs#468]
Блок 2 ООП. 0.2Автоматическая сборка Maven. Задания 0(Запуск Maven.Фаза тест) и 2(Подключение библиотек) содержат одинаковые задания на проверку. А именно: запуск операции test через инструмент Maven.

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by peterarsentev** [comment]
Поправили.
