### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#469]
Упражнения
 1.3.4. Сортировка
 2.2. Способы сортировки. Сортировка массива объектов.
 Видимо тут должно быть нет, вместо не.
![image](https://user-images.githubusercontent.com/13130875/115117573-fb55ef80-9fa7-11eb-856d-68ad7b458b58.png)

**Comment by staskorobeynikov** [comment]
исправлено
