### ISSUE TITLE
10. Расстояние Хэмминга

### ISSUE THREAD

**Issue by Aleksandr-Molchanov** [peterarsentev/job4j_features_bugs#470]
Упражнение "10. Расстояние Хэмминга" не выполнимо, поскольку во всех тестах к упражнению не верно указан параметр Is.
@Test
    public void checkStringsIs3() {
        int rsl = Hamming.checkStrings("2173896", "2233796");
        assertThat(rsl, is(3));
    }

    @Test
    public void checkStringsIs5() {
        int rsl = Hamming.checkStrings("abcde", "bcdef");
        assertThat(rsl, is(5));
    }

    @Test
    public void checkStringsIs0() {
        int rsl = Hamming.checkStrings("abcde", "abcde");
        assertThat(rsl, is(0));
    }

**Comment by staskorobeynikov** [comment]
Что конкретно не так? Формулировка задания верная, да и тесты верные.

**Comment by staskorobeynikov** [comment]
За неделю не поступило никаких дополнительных замечаний, значит закрываю за невостребованностью.
