### ISSUE TITLE
Опечатка задача #1070

### ISSUE THREAD

**Issue by AF3412** [peterarsentev/job4j_features_bugs#474]
Уровень middle -> Блок 4. Spring -> 1. DI. Внедрение зависимостей. -> 2. Скани**варо**вание проекта

**Comment by evgenkolesman** [comment]
0. Что такое Socket? [#449814]
1. out.write("HTTP/1.1 200 OK\r\n\".getBytes()); - эта строчка в задании написана не верно, должно быть так out.write("HTTP/1.1 200 OK\r\n".getBytes()) - так работает
2.

**Comment by ShamRail** [comment]
Исправлено.
