### ISSUE TITLE
формулировка задания "Комбинированный компаратор [#432538]"

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#475]
В описании задания "комбинации компараторов" слово "И" искажает понимание текста. 

1. Для модели ru.job4j.collection.Job создайте 4 компаратора:
 - по имени и по возрастанию
 - по приоритету и по возрастанию
 - по имени и по убыванию
 - по приоритету и по убыванию

предлагаю переформулировать пункты, например как 
 - по имени по возрастанию
 - по имени по убыванию
 - ...

**Comment by staskorobeynikov** [comment]
поправил
