### ISSUE TITLE
Сортировка заданий в разделе "Упражнения"

### ISSUE THREAD

**Issue by AJIEKCanderG** [peterarsentev/job4j_features_bugs#476]
Всем привет! 
Не знаю, только у меня такое или у всех.
В некоторых разделах "Упражнений", скорее всего там где нумерация упражнений с точками типа "1.1 , 1.2 " и тд, сбивается порядок нумерации.

![image](https://user-images.githubusercontent.com/70632594/115547840-6b69bb80-a2af-11eb-88d3-0b619d959379.png)
![image](https://user-images.githubusercontent.com/70632594/115547712-407f6780-a2af-11eb-8a41-ac0bb95c5c3b.png)
![image](https://user-images.githubusercontent.com/70632594/115547742-4c6b2980-a2af-11eb-837d-065b7d1ea23a.png)
![image](https://user-images.githubusercontent.com/70632594/115547788-5e4ccc80-a2af-11eb-9253-1ff1b9262e46.png)
![image](https://user-images.githubusercontent.com/70632594/115547900-7e7c8b80-a2af-11eb-81fd-5bf13ed7e30e.png)
![image](https://user-images.githubusercontent.com/70632594/115547948-8dfbd480-a2af-11eb-8946-88180cd7ea3c.png)
![image](https://user-images.githubusercontent.com/70632594/115548015-a370fe80-a2af-11eb-8b1d-02d964d02518.png)

**Comment by staskorobeynikov** [comment]
сортировку поправил
