### ISSUE TITLE
2. Регистрация пользователя [#477068]

### ISSUE THREAD

**Issue by Alexey710** [peterarsentev/job4j_features_bugs#480]
ошибка в SQL. 
Должно быть 
insert into users (username, enabled, password, authority_id)
values ('root', true, '$2a$10$wY1twJhMQjGVxv4y5dBC5ucCBlzkzT4FIGa4FNB/pS9GaXC2wm9/W',
(select id from authorities where authority = 'ROLE_ADMIN'));

**Comment by dmitrytishchenko** [comment]
поправил
