### ISSUE TITLE
1.1. Интерфейс проекта Job4j [#253322]

### ISSUE THREAD

**Issue by KhachaturB** [peterarsentev/job4j_features_bugs#483]
Неудобно читать текст урока из-за подписей под рисунками. Возможно, стоит уменьшить шрифт подписи.

**Comment by peterarsentev** [comment]
@KhachaturB Можешь картинку добавить с примером? Не пойму почему не удобно читать.

**Comment by KhachaturB** [comment]
Вот как сейчас выглядит:
![image](https://user-images.githubusercontent.com/58373478/117127132-63784400-ada4-11eb-93c7-21ee11ac7d24.png)

Возможно, стоит сделать шрифт меньше или курсивом выделить.
![1_1](https://user-images.githubusercontent.com/58373478/117127727-282a4500-ada5-11eb-9e4a-fed3611a4f34.PNG)


Это пожелания. Я может придираюсь)

**Comment by staskorobeynikov** [comment]
А без подписей будет лучше?

**Comment by peterarsentev** [comment]
Спасибо. Мы взяли эту задачу в работу. Быстро ее не сделать. Поэтому по порядку будем обновлять картинки.
