### ISSUE TITLE
Стажер, Коллекции, Задача 0. Сортировка [#404408]

### ISSUE THREAD

**Issue by Krasobas** [peterarsentev/job4j_features_bugs#484]
Не подгружается класс Job в песочнице
![image](https://user-images.githubusercontent.com/36446403/116405008-db3fef00-a837-11eb-839d-3cc0a8b31cce.png)

**Comment by staskorobeynikov** [comment]
И не подгрузится. Это нужно делать через вложенные статические методы, чтобы модель данных была прямо в используемом классе. Не входит в рамки задачи.
Закрываю.
