### ISSUE TITLE
Ошибка в упражнении 3.1. Consumer. Вывод строки. Метод andThen()

### ISSUE THREAD

**Issue by Rogovolod** [peterarsentev/job4j_features_bugs#486]
Упражнения/1.4.1. Lambda/3.1. Consumer. Вывод строки. Метод andThen()
![image](https://user-images.githubusercontent.com/64468174/116837523-c7183b00-ac05-11eb-8b6c-e011005daaff.png)

У Consumer есть всего два метода, согласно документации:
accept​(T t) и andThen​(Consumer<? super T> after)
![image](https://user-images.githubusercontent.com/64468174/116837655-4a399100-ac06-11eb-9c20-7c011fbf04d0.png)

соответственно, строка в упражнении "con.andThen(con2); // con.apply(2) выведет 3 и 4 " сбивает с толку

**Comment by Rogovolod** [comment]
Так и не догадался, что нужно было написать в return, в результате получилось решить упражнение только вот так, дав тесту то, что он просит:
![image](https://user-images.githubusercontent.com/64468174/116838669-3001b200-ac0a-11eb-8e8d-32aacfa1205f.png)

**Comment by staskorobeynikov** [comment]
По вызову метода поправил на accept. А по решению - все корректно работает
![image](https://user-images.githubusercontent.com/58299607/122783459-41864280-d2ba-11eb-8e8a-1b6b947bd9dd.png)
