### ISSUE TITLE
 1. Уровень - Стажер  Блок 2. ООП  0.1. Качество кода.  1. Чтение кода и базовые ошибки

### ISSUE THREAD

**Issue by IvanTimofeev87** [peterarsentev/job4j_features_bugs#487]
Вместо JavaDoc на курсе используется Maven

**Comment by peterarsentev** [comment]
@peterarsentev Нужно добавить объяснение, что такое JavaDoc. Сказать, что урок по нему будет далее в курсе.

**Comment by dmitrytishchenko** [comment]
добавил объяснение согласно указаний
