### ISSUE TITLE
Статус задач - требуется ли что-то от меня?

### ISSUE THREAD

**Issue by KhachaturB** [peterarsentev/job4j_features_bugs#489]
Сейчас после прохождения первого блока я не уверен, что отправил задачи на проверку. Они все сменили статус на "в процессе". Я честно не знаю требуется ли что-то от меня) Возможно нужен новый статус "на проверке" или переименовать текущий статус.

![image](https://user-images.githubusercontent.com/58373478/117128108-a5ee5080-ada5-11eb-9c64-ce061a479923.png)

**Comment by peterarsentev** [comment]
Нужно задачу вернуть обратно ментору. Теперь менторы закрывают задания.
