### ISSUE TITLE
Опечатки: Упражнения - 1.1.2. Тип данных - 8. Модуль числа

### ISSUE THREAD

**Issue by KhachaturB** [peterarsentev/job4j_features_bugs#491]
Опечаточки:
_Что если нам нужно получить число без его знака? Например, получить 3, если имеется -3. Для **ЭТОГО** мы можем использовать функцию модуля. Модуль числа это его часть без знака. Модуль положительно**ГО** числа равен ему самому._

В оригинале так:
_Что если нам нужно получить число без его знака? Например, получить 3, если имеется -3. Для его мы можем использовать функцию модуля. Модуль числа это его часть без знака. Модуль положительно числа равен ему самому._

**Comment by staskorobeynikov** [comment]
Исправлено
