### ISSUE TITLE
Неверное трактование sqrt

### ISSUE THREAD

**Issue by SileLence** [peterarsentev/job4j_features_bugs#492]
В разделе: Job4j - Упражнения - 1.1.2. Тип данных - 7. Получение корня из числа

Есть такая строка: _Чтобы получить корень, нам нужно использовать библиотеку Math, а именно метод Math.sqrt. sqrt это сокращение squart с английского, что значит квадрат._

Верным будет объяснение, что sqrt это сокращение от square root (дословно "квадратный корень").

**Comment by staskorobeynikov** [comment]
спасибо, исправлено
