### ISSUE TITLE
6.6.4. Размер элемента двухмерного массива. [#333583] - запоздал

### ISSUE THREAD

**Issue by KhachaturB** [peterarsentev/job4j_features_bugs#494]
Урок несколько запоздалый, т.к. в предыдущем уроке уже надо было написать код, который перебирает массивы разной длины)

На скрине тест из урока _"6.6.3. Двухмерный массив. If. [#306727 #1125]"_
![image](https://user-images.githubusercontent.com/58373478/117624575-baec2a80-b17d-11eb-9f96-3c06a453742a.png)

**Comment by staskorobeynikov** [comment]
Поправил порядок
