### ISSUE TITLE
Не отображаются новые задачи

### ISSUE THREAD

**Issue by mirraim** [peterarsentev/job4j_features_bugs#495]
На новой платформе:
1. Не отображается список новых задач в навигационной панели, видно только проверенные.
2. Куда-то делась структура курса: задания разложены по папкам самого низкого уровня. Папок, содержащих блок и уровень нет (пример пути к заданию :Job4j/ Курс/ 2.4.1. Понятие сборщик мусора/ 0. Видео)

**Comment by peterarsentev** [comment]
Поправили.
