### ISSUE TITLE
Некорректное отображение прогресса по выполненным ранее задачам

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#497]
По ссылке https://job4j.ru/profile/exercise выполнено якобы 2/7
![изображение](https://user-images.githubusercontent.com/44730951/117992494-0a825000-b350-11eb-81ef-8166e4dd8bac.png)

Но в то-же время, например в задаче 1.2. Начало обучения [#1150 #141903] уже есть решение, которое не учтено системой, и так с некоторыми задачами, у остальных решения не перенесены.
![изображение](https://user-images.githubusercontent.com/44730951/117992918-5208dc00-b350-11eb-820f-a43068a0676c.png)

**Comment by SamisheUN** [comment]
При этом группа Трэкер выполнена на 133%,
![изображение](https://user-images.githubusercontent.com/44730951/117994366-89c45380-b351-11eb-8ae0-89c45592cb2d.png)

Хотя там всего 3 задания
![изображение](https://user-images.githubusercontent.com/44730951/117994426-96e14280-b351-11eb-809c-65e7ca80ec53.png)

**Comment by peterarsentev** [comment]
Поправили.
