### ISSUE TITLE
Материалы по курсу Android не все отображаются.

### ISSUE THREAD

**Issue by zoicvill** [peterarsentev/job4j_features_bugs#499]
![Снимок](https://user-images.githubusercontent.com/49144982/117998356-7d89c780-b34c-11eb-898a-66e5608e52da.JPG)

**Comment by peterarsentev** [comment]
Поправили.

**Comment by zoicvill** [comment]
> Поправили.

![image](https://user-images.githubusercontent.com/49144982/120066462-322b2500-c07f-11eb-855a-31c9c0117b46.png)

Ничего не поменялось. Открывал в инкогнито.
