### ISSUE TITLE
7. Метод удаления заявки Tracker.delete

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#50]
Этот код выглядит элегантно, но он не эффективен. Мы оставляем пустые ячейки в начале массива. Хотелось бы, чтобы этот метод перемещал все ячейки справа на одну позицию. В этом случае пустой ячейки в середине **цикла** не будет.

Правильно **массива**

**Comment by RuslanFajziev** [comment]
Этот код выглядит элегантно, но он не эффективен. Мы оставляем пустые ячейки в начале массива. Хотелось бы, чтобы этот метод перемещал все ячейки справа на одну позицию. В этом случае пустой ячейки в середине цикла не будет.

Правильно массива

**Comment by peterarsentev** [comment]
Спасибо. Поправил.
