### ISSUE TITLE
Статусы задач.

### ISSUE THREAD

**Issue by stanovov** [peterarsentev/job4j_features_bugs#500]
## 1. Статусы задач
Что-то странное происходит с статусами задач, и мой комментарий к решению так же, то появляется, то пропадает, к слову, когда я делал скрины, на проверку уже отправил две задачи - 1)6. Тестовое задание из модуля коллекции Lite переделать на Stream API. и 2): 7. Как сделать ад с помощью Stream API. :
![image](https://user-images.githubusercontent.com/64577664/118007195-96967680-b354-11eb-983d-2b3446bbeb80.png)
![image](https://user-images.githubusercontent.com/64577664/118007437-ce9db980-b354-11eb-8443-766747d9788b.png)
![image](https://user-images.githubusercontent.com/64577664/118007305-b3cb4500-b354-11eb-94d8-e6ba87bb3f6a.png)
![image](https://user-images.githubusercontent.com/64577664/118007337-baf25300-b354-11eb-9e0a-a067a378199a.png)
![image](https://user-images.githubusercontent.com/64577664/118007366-c0e83400-b354-11eb-8d7c-a08bb97b85c7.png)

**Comment by peterarsentev** [comment]
Поправили.
