### ISSUE TITLE
Нет возможности отправить задание на проверку.

### ISSUE THREAD

**Issue by SemykinRU** [peterarsentev/job4j_features_bugs#502]
Пропала возможность отправлять задачи на проверку.
Нет кнопок ни вверху задачи, ни внизу.

![Сохраненное изображение 2021-5-12_19-21-32 193](https://user-images.githubusercontent.com/77810472/118010501-c7c47600-b357-11eb-9a17-7efdaad35b46.jpg)

![Сохраненное изображение 2021-5-12_19-21-42 165](https://user-images.githubusercontent.com/77810472/118010537-d01cb100-b357-11eb-8e14-e3b5385e18ba.jpg)

**Comment by staskorobeynikov** [comment]
После переезда на новую платформу неактуально
