### ISSUE TITLE
Не отображаются уровни и блоки

### ISSUE THREAD

**Issue by kamikhaylov** [peterarsentev/job4j_features_bugs#503]
Не отображаются уровни и блоки - все в одной стопке:
Было:
[https://prnt.sc/12unlqf](url)
[https://prnt.sc/12unmyy](url)
Стало:
[https://prnt.sc/12unkaw](url)

Не отображается прогресс.
Не отображаются новые задачи в левом меню.
Не отображаются блоки: задания с собеседования, реквизиты, доп.упражнения.

Спасибо!

**Comment by peterarsentev** [comment]
Поправили.
