### ISSUE TITLE
Не сохраняется сообщение при отправке на проверку

### ISSUE THREAD

**Issue by ainz713** [peterarsentev/job4j_features_bugs#504]
При нажатии кнопки "Отправить на проверку", ввожу текст с решением задания, но текст не сохраняется. Вообще не понятно отправилось что-то менторам или нет.

![image](https://user-images.githubusercontent.com/77198718/118025564-a91aab00-b368-11eb-8f2b-0510b4790d62.png)

**Comment by staskorobeynikov** [comment]
После окончательного переезда на новую платформу неактуально. Закрываю.
