### ISSUE TITLE
Пропали кнопки "Комментировать" и "Закрыть" 

### ISSUE THREAD

**Issue by AshleySunsine** [peterarsentev/job4j_features_bugs#506]
Пропали кнопки "Комментировать" и "Закрыть". Отправить решение на проверку теперь можно только через кнопку "Обсудить", но это общая 'беседа' и нехорошо решения выставлять на показ.

**Comment by peterarsentev** [comment]
Нужно перейти на новую платформу job4j.ru/profile/login
