### ISSUE TITLE
Не вижу ответа от ментора по проверенным задачам

### ISSUE THREAD

**Issue by studentjob4j** [peterarsentev/job4j_features_bugs#508]
Отправил задачу на проверку , вижу что ответственный вновь я , но не вижу ничего

**Comment by Dmitry8ms** [comment]
То же самое, ментор говорит, что видит свой комментарий, а у меня нет никаких комментариев и задача остается в статусе "новая".

**Comment by Dmitry8ms** [comment]
причем, когда смотрю на список тем, там она в статусе выполнения, а когда кликаю по ней и открываю, она в статусе новая и нет комментария, который оставил ментор.
![2021-05-13_18-16-10](https://user-images.githubusercontent.com/78461952/118118844-b17def00-b417-11eb-96a4-2f2bee81f272.png)
![2021-05-13_14-54-39](https://user-images.githubusercontent.com/78461952/118118890-be9ade00-b417-11eb-8949-1484147defab.png)

**Comment by staskorobeynikov** [comment]
после второго переезда на новую платформу неактуально.
