### ISSUE TITLE
Не показывает что задание выполнено, пропадают сообщения отправленные на проверку!

### ISSUE THREAD

**Issue by Selesito** [peterarsentev/job4j_features_bugs#509]
1. Когда выполнил задание и прикладываешь(ссылку, картинку и т.д) она бывает пропадает!
2. В общем меню подраздела не показывает что задание выполнено,  а в самом задание загорелась Выполнено!( и бывает наоборот, снаружи выполнено и внутри задания нет)(url)[https://prnt.sc/12vb9nu](url), и вот что внутри хотя показывает что оно выполнено[https://prnt.sc/12vba72](url), самого сообщения сданного задания тоже теперь нет[https://prnt.sc/12vbapo](url)!
3. Бот перестал работать и присылать о проверке задания!

**Comment by Selesito** [comment]
Вот еще немного перевыполнил), хотя выше я уже показывал что внутри показывает задания не выполненые![https://prnt.sc/12vbg7o](url)

**Comment by Selesito** [comment]
И еще дополнение ко 2 проблеме, если сдал задание и не появилась надпись в процессе и пропало задание которое сдал, нужно обновить страницу от 2 до 7 раз и тогда, через какое количество обновлений задание появиться, но если перейти к следующему заданию  и потом вернуться,  то это же задание могло пропасть и так обновляем пару раз и оно снова будет в процессе! Ну или проверено!

**Comment by staskorobeynikov** [comment]
После окончательного переезда на новую платформу неактуально, все работает.
