### ISSUE TITLE
Вопросы по темам в новом профиле

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#510]
Я сейчас нахожусь на Джуниоре, однако увидел темы, которые,  
как мне кажется, раньше видел на Стажере.
И они пустые. Там нет пунктов.
Возможно их стоит проверить, если только их специально не переносили.
<img width="802" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/118082793-7a332200-b3c6-11eb-97f4-962dee375fba.png">

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
