### ISSUE TITLE
на новом движке страница перекидывает на ввод логина и пароля

### ISSUE THREAD

**Issue by sergeykin** [peterarsentev/job4j_features_bugs#511]
учетка sergey.kinyapin
вначале зашел на страницу ввода логина(https://job4j.ru/profile/login), авторизовался,  увидел список задач - нажал на одну и меня снова перекинуло на страницу ввода логина(пароля)
далее или не заходит далее этой страницы или же по таймауту снова на нее переходит

**Comment by BaceH** [comment]
> вначале зашел на страницу ввода логина(https://job4j.ru/profile/login), авторизовался, увидел список задач - нажал на одну и меня снова перекинуло на страницу ввода логина(пароля)
> далее или не заходит далее этой страницы или же по таймауту снова на нее переходит

аналогично

**Comment by sergeykin** [comment]
возможно исправили, или же помог выход с предыдущей учетки(затерялась в браузере залогиненая страница)

**Comment by BaceH** [comment]
> возможно исправили, или же помог выход с предыдущей учетки(затерялась в браузере залогиненая страница)

аналогично ))

**Comment by peterarsentev** [comment]
Нужно обновить кеш браузера.
