### ISSUE TITLE
показывается пустая страница

### ISSUE THREAD

**Issue by Dniv2018** [peterarsentev/job4j_features_bugs#512]
учётка dmitry.nikolaev
после авторизации показывает пустую страницу. нет выполненных заданий, нет заданий по курсу. самого курса нет.
![Снимок экрана 2021-05-13 в 10 39 03](https://user-images.githubusercontent.com/44500459/118094586-97bcb780-b3d7-11eb-8c44-baeb51cddeb3.png)

**Comment by peterarsentev** [comment]
Поправил.
