### ISSUE TITLE
Не отображаются комментарии к задаче

### ISSUE THREAD

**Issue by k2250427** [peterarsentev/job4j_features_bugs#517]
В списке проверенных задач одна и та же задача отображается дважды, причем у самой задачи показан статус "Новая" и нет ни одного комментария, хотя уже была отправлена на проверку
(https://user-images.githubusercontent.com/45516217/118135589-e421ea80-b40b-11eb-8a92-b03a879f1467.PNG)

**Comment by peterarsentev** [comment]
Поправили.
