### ISSUE TITLE
Не совпадает ответственный

### ISSUE THREAD

**Issue by ilyapavlovru** [peterarsentev/job4j_features_bugs#519]
После отправки задачи на проверку на странице задачи не обновляется ответственный и не видно, что ссылка на гит репозиторий корректно отправлена проверяющему. Однако при переходе к списку задач видно, что ответственный - это уже ментор.

![image](https://user-images.githubusercontent.com/59793727/118138419-f7828500-b40e-11eb-9f73-fb157c4dcf73.png)

![image](https://user-images.githubusercontent.com/59793727/118138515-1c76f800-b40f-11eb-89d4-05dfa9845abd.png)

**Comment by peterarsentev** [comment]
Поправили.
