### ISSUE TITLE
1.1. Входные данные в тесте [#420805] | изменить имя теста на соответствующее

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#52]
![image](https://user-images.githubusercontent.com/35169516/100969666-8330e500-3544-11eb-8d1d-928d29858089.png)

тк входные параметры:
        int a = 10;
        int b = 0;
        int c = 0;
        int x = 2;

то название теста должно быть whenA10**B0**C0X2Then40

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
