### ISSUE TITLE
Добавить кликабельность ссылки в комментарии

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#528]
Чтобы перейти по ссылке из комментария, приходится ее выделять и вызывать контекстное меню, это неудобно.
Просьба добавить кликабельность.
![image](https://user-images.githubusercontent.com/12701878/118389908-fa5ebf00-b634-11eb-90a2-3d76adaa3731.png)

**Comment by staskorobeynikov** [comment]
Добавляйте ссылки с помощью этого
![image](https://user-images.githubusercontent.com/58299607/122779115-40531680-d2b6-11eb-9aec-5a4dde57f882.png)
и тогда ссылка будет кликабельной. Главное не убирайте эти галочки
![image](https://user-images.githubusercontent.com/58299607/122779221-57920400-d2b6-11eb-909d-8dcbaa8e1bf7.png)
