### ISSUE TITLE
0. Select [#506077] Опечатка с кавычками.

### ISSUE THREAD

**Issue by AshleySunsine** [peterarsentev/job4j_features_bugs#531]
0. Select [#506077] 
Оператор сравнения строк LIKE
.. LIKE “%abc” – строка должна кончаться с “abc”

.. LIKE “abc%” – строка должна начинаться с “abc”

.. LIKE “%abc%” – строка должна содержать “abc”
Следует убрать двойные кавычки и поставить одинарные апострофы.

**Comment by dmitrytishchenko** [comment]
поправил
