### ISSUE TITLE
1.2. Входные данные в тесте [#297750]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#535]
Название класса "X2"  у меня не проходит проверку checkstyle.
Или чекстаил у меня неправильный или название надо поменять.

**Comment by staskorobeynikov** [comment]
Все без проблем
![image](https://user-images.githubusercontent.com/58299607/122778732-e7837e00-d2b5-11eb-84be-630f6c603058.png)
проверяйте окнфигурацию чекстайла. Закрываю.
