### ISSUE TITLE
Планирование времени обучения.

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#539]
Вступление.
Мне кажется суперполезным воткнуть такую статью
в начало обучения, чтобы курсанты могли
хотя бы приблизительно оценить свои возможности
и не тратить впустую свое время и время преподавателей

==================================

Планирование времени обучения.
В курсе приблизительно 600 основных заданий.
Мы предполагаем, что в идеальном варианте,
если у вас достаточно соответствующей подготовки 
вы сможете выполнить эти задания за полгода, т.е.
примерно за 180 дней. Примерно 3-4 задания в день.
Мы также предполагаем, что вы будете заниматься
не менее 3-4 часов в день, и выполнять примерно 1 задание в час.
Таким образом вы потратите 600 учебных часов на 600 заданий.

Исходя из этих примерных расчетов вы можете прикинуть, 
сколько времени у вас может занять обучение.
Например.
1. Вы планируете заниматься не более 2-х часов в день.
2. Вы замечаете, что одно задание вы, в среднем, выполняете не менее 3-х часов.
Отсюда можно предположить:
600 заданий х 3 часа = 1800 учебных часов
1800 учебных часов / 2 часа в день = 900 дней

**Comment by AlexeySapsay** [comment]
Поддерживаю всеми руками за!

**Comment by peterarsentev** [comment]
1.2. Начало обучения - у курсе есть такой урок.
