### ISSUE TITLE
"Процесс обучения" на новой платформе

### ISSUE THREAD

**Issue by CyberfuzZ-Apps** [peterarsentev/job4j_features_bugs#542]
Пропал "процесс обучения" на новой платформе, где велась статистика прохождения курса. Очень было удобно и даже мотивировало заниматься больше, чтоб счётчик решённых заданий сильно не падал.

**Comment by AlexeySapsay** [comment]
Поддерживаю. Решение с прогресс баром на старой платформе было удачным и помогало учиться.

**Comment by peterarsentev** [comment]
Вернули.
