### ISSUE TITLE
Предложение: вернуть закрытие задач учеником

### ISSUE THREAD

**Issue by ilyapavlovru** [peterarsentev/job4j_features_bugs#544]
Когда закрывает задачу ментор, ученику не понятно какие задачи были проверены.

![image](https://user-images.githubusercontent.com/59793727/119100611-ce6e7f80-ba20-11eb-98a9-9aa82b0574fb.png)

**Comment by peterarsentev** [comment]
С этим много проблем у новых учеников. 
Они начинают выполнять операцию завершить до проверки.
Поэтому мы это убрали. У нас отвалились оповещения. Но сейчас мы все поправили.
По ним ученик видит, что задачу проверили.
