### ISSUE TITLE
Предложение: вернуть прогресс по заданиям (выполнено и осталось заданий)

### ISSUE THREAD

**Issue by ilyapavlovru** [peterarsentev/job4j_features_bugs#545]
Реально не хватает
![image](https://user-images.githubusercontent.com/59793727/119101696-f0b4cd00-ba21-11eb-8321-df64a96f6e34.png)

**Comment by AlexanderBanar** [comment]
Вот, тоже присоединяюсь! Это прям мотиватор отличный, видеть как процентики растут ежедневно! и свет в конце "туннеля", так сказать )))

**Comment by CyberfuzZ-Apps** [comment]
Поддерживаю!

**Comment by arturas-r** [comment]
Я бы ещё добавил, что нужно "починить" в тульбар кнопку "Проверенные задачи".  А то клик и стрелочка меняет на правление на противоположное, а "гармошка" не растягивается и проверенных задач не видно.

**Comment by peterarsentev** [comment]
Поправили по всем пунктам.
