### ISSUE TITLE
Введение комментария вне поля.

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#547]
Через кнтрл+а удалил введенное. После этого комментарий вводился как указано на скрине.
![image](https://user-images.githubusercontent.com/75887570/119299045-e8010880-bc66-11eb-9a2a-9fc5f25c08e7.png)

**Comment by peterarsentev** [comment]
@Oklevet Не могу повторить. У вас стабильно повторяется?

**Comment by Oklevet** [comment]
Нет. Было всего один раз.

сб, 10 июл. 2021 г. в 18:51, Petr Arsentev ***@***.***>:
