### ISSUE TITLE
[Предложение] Редактирование комментария

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#548]
Ввести возможность редактирования. Хотя бы последнего, пока на него не ответили. Время от времени заливаешь что-то не то, не конца или уже решил проблему.

**Comment by peterarsentev** [comment]
Это сделать нельзя. Если редактировать комментарии, то мы потом не найдем, кто прав, кто нет. 
Можно было бы добавить редактирование с историей правок. 
Пока просто добавляйте еще одно сообщение.
