### ISSUE TITLE
[Предложение] Структура курсов

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#549]
Может быть оформить их в виде раскрывающихся меню. С уровня блоков и ниже по дереву. Или сделать возможность сокрытия выполненных, или помечать нужные курсы, закладки и закреплять сверху таблицы. 
Учитывая, что нет возможности с помощью ПКМ открывать в соседней вкладке отдельные главы, становится неудобно работать с выбором курсов и переключениями между ними. На 2-м блоке, Джуне, уже насилие над колесиком мышки. Страшно за 3-й уровень.

**Comment by AlexeySapsay** [comment]
Поддерживаю. Было бы хорошим решением, организовать работу со структурой и доступ к материалу более удобно

**Comment by peterarsentev** [comment]
Мы добавили фильтры по уровням и категориями.
