### ISSUE TITLE
Кнопка "Избранное" работает только после перезагрузки страницы

### ISSUE THREAD

**Issue by adelinyshka** [peterarsentev/job4j_features_bugs#55]
https://prnt.sc/vvgou1

кнопка Избранное добавляет в избранное после первого нажатия только после перезагрузки
То есть:
нажимаешь 1 раз - сохраняет
переход на др струницу - нажимаешь и ничего
перезагружаешь страницу, нажимаешь, работает

![image](https://user-images.githubusercontent.com/35169516/101119150-c1d5a680-35fb-11eb-8d05-0b54144cff37.png)

**Comment by andreiHi** [comment]
спасибо поправил
