### ISSUE TITLE
toString

### ISSUE THREAD

**Issue by gthdeiby** [peterarsentev/job4j_features_bugs#551]
В уроке  "1.2.3. Инкапсуляция 9. toString" объясняется работа toString. В задании необходимо создать класс StartUI и вывести объект Item на консоль. 
Перед этим в уроке "1.2.3. Инкапсуляция 5. Tracker - хранилище" также требовалось вывести на консоль объект, может оттуда убрать этот пункт задания? либо описать там использование toString

**Comment by staskorobeynikov** [comment]
исправлено, про toString только в одном задании
