### ISSUE TITLE
Предложения-замечания по новой структуре сайта

### ISSUE THREAD

**Issue by AlexanderBanar** [peterarsentev/job4j_features_bugs#552]
1. **Общая структура.** Ранее было удобно видеть структуру курсов в укрупненном виде, т.е. если я, например, на Джуне, то мне доступны два блока Стажер и Джун, далее я могу в них "провалиться" и увидеть более детальную общую структуру и по каждой такой структуре - подструктуры и т.д.

2. **Процентовка.** Лично для меня это отдельный мотиватор прохождения курса. Видеть как проценты увеличиваются и начинают приближаться к отметке 100 - это дает силы заниматься дальше, двигаться.

3. **Закрытие задач.** Также один из приятных моментов (ну чисто субъективно может), когда можешь сам закрыть выполненную задачу, после слов ментора - хорошо, закрывайте. Мелочь, а приятно.

4. **Новые описания.** При прохождении курса неизбежно меняются прошлые пункты, добавляются новые. Мне кажется, стоит новые пункты вывести каким-то отдельным блоком.. т.к. они в родительском блоке снижают процент выполнения.. и кажется, будто этот раздел не пройден до конца.. хотя уже давно и экзамен сдан..

**Comment by peterarsentev** [comment]
1. Добавили фильтры.
2. Добавили бары по уровням.
3. С этим было много проблем у новых учеников. Сейчас приходят уведомления о проверенной задаче. 
Так же мы добавим таблицу с последними выполненными заданиями.
4. Тут просто перевести на ментора с указанием, что выполнил ранее. И мы закроем.
