### ISSUE TITLE
Реально ли увидеть общую статистику учеников проекта job4j ?

### ISSUE THREAD

**Issue by AMakutsevi4** [peterarsentev/job4j_features_bugs#553]
Думаю многим интересно увидеть прогресс учащихся (чтобы оставаться инкогнито можно добавить колонку с никнеймом в профиле для отображения в статистике), такой своего рода соревновательный подход к завершению обучения или может поиска собеседников (кто ближе к тебе по % ) для обсуждения проблемных моментов.

**Comment by peterarsentev** [comment]
Такое было раньше. Я это убрал. Большинство учеников - это вгоняет в стресс. Что они делают медленнее, хуже и тд. А это не так. У всех своя скорость.
Обсудить задания можно в чате или в разделе обсуждения.
