### ISSUE TITLE
Упражнения 2.7. Способы сортировки. Сортировка Map.

### ISSUE THREAD

**Issue by Dmitry8ms** [peterarsentev/job4j_features_bugs#557]
В задании написано - "Сортировка должна быть в обратном порядке", однако в тесте это не проверяется - 
`@Test
    public void test() {
        Map<Integer, String> input = Map.of(
                1, "1",
                2, "2",
                3, "3"
        );
        Map<Integer, String> expect = new TreeMap<>(input);
        Map<Integer, String> result = SortMap.sort(input);
        Assert.assertEquals(expect, result);
    }`

**Comment by ShamRail** [comment]
Комментарий не корректен. В задании сравнивается expect, получаемый из input с помощью компаратора для обратного порядка, с result, который тоже должен хранить ключи в обратном порядке.
