### ISSUE TITLE
[Предложение] Сделать в новом трекере оповещения о том, что задание проверено и зачтено.

### ISSUE THREAD

**Issue by mgbardakov** [peterarsentev/job4j_features_bugs#558]
В связи с тем, что теперь задания закрывают менторы, для того чтобы понять зачтено задание или нет приходится копаться в дереве заданий курса, что не всегда удобно. Оповещения о закрытии заданий могли бы улучшить UX приложения.

**Comment by peterarsentev** [comment]
Так они есть. Нужно в настройках профиля включить.
