### ISSUE TITLE
Курс Джуниор 2.2.4. Сериализация/4. JAXB. Преобразование XML в POJO

### ISSUE THREAD

**Issue by Jazzik42** [peterarsentev/job4j_features_bugs#563]
Пункт 3, код класса Contact. Используется аннотация **@XmlElement(value = "contact")**, которая подключает другую библиотеку com.sun.xml.txw2.annotation.XmlElement;, когда в уже использующейся библиотеке javax.xml.bind.annotation.XmlAttribute; есть точно такая же аннотация **@XmlRootElement(name =)**

**Comment by dmitrytishchenko** [comment]
поправил

**Comment by Jazzik42** [comment]
Забыли лишний импорт убрать, но это мелочь

**Comment by dmitrytishchenko** [comment]
спасибо, поправил
