### ISSUE TITLE
Курс по Андроиду. В новой версии не все задания.

### ISSUE THREAD

**Issue by zoicvill** [peterarsentev/job4j_features_bugs#564]
Хоть я и сохранил задания из старой версии, до тех заданий что в новой, но сдать я их не могу. Ссылка на старый закрытый тикет. https://github.com/peterarsentev/job4j_features_bugs/issues/499#event-4815869096

**Comment by peterarsentev** [comment]
@zoicvill У тебя не перенеслись решения? Или не отображаются сами уроки?

**Comment by zoicvill** [comment]
> @zoicvill У тебя не перенеслись решения? Или не отображаются сами уроки?

не отображаются сами уроки

**Comment by peterarsentev** [comment]
@zoicvill Поправил. Прощу подтвердить и закрывать тикет.

**Comment by zoicvill** [comment]
@peterarsentev Все появилось, спасибо
