### ISSUE TITLE
Закрытие задания

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#565]
Так как теперь закрытие производится ментором, тяжело отслеживать текущие состояния. 
Успешно ли было выполнено задание и можно приступать к его продолжению(когда код одной операции напрямую пишется в подряд идущих заданиях) или пока обратить внимание  в другую сторону.
Может задание просто висит и нужно его толкнуть.

Как вариант, чтобы закрытое ментором задание один раз появлялось в "Проверенных заданиях",  окрашенным в зеленый цвет. И исчезало, после того, как по нему один раз перейдешь.

**Comment by ViktorJava** [comment]
Я думаю, если телеграм бот будет присылать уведомления о закрытии, по ним, можно ориентироваться.

**Comment by staskorobeynikov** [comment]
Теперь есть 2 опции
1. Уведомления бота
2. Раздел выполненные задания:
![image](https://user-images.githubusercontent.com/58299607/124297741-0e6a6b80-db64-11eb-92e0-6edcd85004ff.png)

в них отражаются несколько последних выполненных задач.
Закрываю.
