### ISSUE TITLE
4. Процесс компиляции и запуска Java программы [#310020 #163381] малозначительная неточность

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#567]
```
Задание

1. Прочитать урок. 

2. Выполнить операцию закрыть.
```
_________________________________________________________
собсно малозначительно, но некорректный текст задания - "закрыть" операции нет. 
Предлагаю исправить на "Отправить на проверку с пометкой "ознакомлен"".

**Comment by dmitrytishchenko** [comment]
поправил
