### ISSUE TITLE
 Упражнения. Промежуточные операции. Метод dropWhile()

### ISSUE THREAD

**Issue by Dmitry8ms** [peterarsentev/job4j_features_bugs#568]
Задание - Ваша задача оставить в списке только положительные элементы. Порядок элементов исходного списка может быть произвольным.
Ничего не говорится про порядок элементов. Однако тест требует определенного порядка элементов.

**Comment by staskorobeynikov** [comment]
О порядке очень много написано в документации
https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/stream/Stream.html#dropWhile(java.util.function.Predicate) 
Так что в тестах все верно.
