### ISSUE TITLE
На сайте не правильно отображается статистика активности.

### ISSUE THREAD

**Issue by divergenny** [peterarsentev/job4j_features_bugs#574]
Заходил на сайт вчера, решал лёгкую задачу из раздела упражнений, решил и сабмитнул, пишет что последняя активность в курсе 14.05.2021 17:37, при том, что был вчера и сегодня на сайте.
Скриншот: https://prnt.sc/13zcnbp

**Comment by AlexeySapsay** [comment]
упражнения не засчитываются в активность. За активность принимается только решение задач, отправляемых на проверку ментору

**Comment by peterarsentev** [comment]
Поправили. Добавили график активности по дням.
