### ISSUE TITLE
Ошибка в описании термина - сигнатура метода

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#576]
https://job4j.ru/profile/topics/33/task_code/163/solution/new_task
путь:
Упражнения
1.4.1. Lambda
4.1. Method reference. Обращение через класс и объект
![image](https://user-images.githubusercontent.com/13130875/120811885-2515a680-c555-11eb-9a87-0d47fb33b835.png)
Ошибка в том, что в сигнатуру метода не входит тип возвращаемого значения.
![image](https://user-images.githubusercontent.com/13130875/120814484-96565900-c557-11eb-85e0-df4451932188.png)

https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html

**Comment by staskorobeynikov** [comment]
поправил
