### ISSUE TITLE
Упражнение 1.1.2 Тип данных. 1 Int число

### ISSUE THREAD

**Issue by RomanKarczewski** [peterarsentev/job4j_features_bugs#577]
Упражнение (https://job4j.ru/profile/topics/6/task_code/17/solution/new_task) явно превышает мой уровень, на котором я учусь на данный момент. Хотя я уже изучаю циклы, а это упражнение находится на несколько разделов раннее - "тип данных". (я в этом курсе на данном этапе не изучал ввод данных, а также оператор "new")

с уважением, Роман

**Comment by YarTsin** [comment]
Если я правильно понимаю, суть этого упражнения в том, что Java - строго типизированный язык, и переменные не могут жить, если мы строго не определяем их тип. Ошибку такого типа в коде легко найти и исправить, несмотря на другие "сложные и непонятные операторы"

**Comment by staskorobeynikov** [comment]
спасибо за комментарий и он верный, все что нужно поправить - это указать верный тип у переменной. Он есть прямо в названии задачи - перед value надо указать int
