### ISSUE TITLE
Доработка блока Упражнения

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#578]
В упражнениях кроме кнопки "Проверить", очень было бы неплохо добавить еще кнопку "Сбросить", чтобы возвращать первоначальное состояние задачи.

**Comment by staskorobeynikov** [comment]
В новом интерфейсе кнопка добавлена.
![image](https://user-images.githubusercontent.com/58299607/124297418-b6cc0000-db63-11eb-9db4-d888592df831.png)

Закрываю.
