### ISSUE TITLE
Предложение. Добавить задания в блок SQL

### ISSUE THREAD

**Issue by 777Egor777** [peterarsentev/job4j_features_bugs#58]
По 1 заданию на темы:
1. Индексы(кластерные, некластерные)
2. Нормализация.
3. Денормализация
4. Курсоры
5. Триггеры
6. Подзапросы
7. union
8. Хранимые процедуры
9. view
10. ACID, CAP теорема

В каждом задании - теория по данной теме

**Comment by staskorobeynikov** [comment]
Задание взято в обработку, в ближайшее время добавим
