### ISSUE TITLE
Предложение. Создание опции "Задать вопрос ментору(ам)" без привязки к конкретному заданию.

### ISSUE THREAD

**Issue by AlexanderBanar** [peterarsentev/job4j_features_bugs#580]
Предлагаю рассмотреть возможность. 

Иногда появляется потребность связи с ментором(ами)
для прояснения вопросов по курсу, орг моментов, или просто задать вопрос не по проходимой теме.

Да, это можно сделать через скайп/телеграм или в общем чате,
но тогда мы либо конкретно ментору пишем, **а не в пул менторов**, и данный ментор мб занят/в отпуске/болеть,
а в общ чате все-таки менторы редко отвечают, это больше из серии "вопрос залу" или "помощь клуба" 😁

Просто рекомендация по улучшению.
Спасибо

**Comment by peterarsentev** [comment]
@AlexanderBanar Так для этого и есть github issue. Тут прямо и отписать любой вопрос можно.
Пишешь номер задания и вопрос. Мы все ответим.

**Comment by AlexanderBanar** [comment]
Ясно. Ок, спасибо.
