### ISSUE TITLE
Упражнения / 1.1.6. Массивы / 39. Кинотеатр

### ISSUE THREAD

**Issue by ghost** [peterarsentev/job4j_features_bugs#581]
>При этом рассадить посетителей нужно так, чтобы рядом значения null могли быть только по диагонали
Почему по диагонали? Смежные клетки по вертикали и горизонтали.

**Comment by staskorobeynikov** [comment]
Это такое требование задание, чтобы сосед мог быть только по диагонали.

**Comment by staskorobeynikov** [comment]
закрываю, за невостребованностью проблемы, поскольку за неделю никаких вопросов не поступило
