### ISSUE TITLE
0. Что такое исключение.

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#582]
Если нет, то давай **это** сделаем пример программы, котор**ые** работа**ет** странным образом.
эту фразу явно надо привести в порядок :)

**Comment by alexlife9** [comment]
там же - Первостепенно давайте рассмотрим сообщени**я**, котор**ое** идет с именем класса Exception.

**Comment by alexlife9** [comment]
там же - Кликните по ссылк**у** и IDEA откроет класс и выстави**ть**

**Comment by alexlife9** [comment]
там же - Ошибка связана с **не верным** индексом - пишется слитно

**Comment by dmitrytishchenko** [comment]
поправил
