### ISSUE TITLE
Предложение добавить виджет активности как на GitHub

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#583]
Просмотр своей статистики учебы, выполненных задач, приносит порцию мотивации заниматься больше и методично.
Хотелось бы видеть активность, например как на коммитах в гитхабе.
![image](https://user-images.githubusercontent.com/13130875/121091863-57443400-c7f3-11eb-8864-b7a9b018a6fa.png)

Если вам нравится идея и есть дополнения или пожелания- пишите в комментах ниже. И поддержите + .

**Comment by ViktorJava** [comment]
Ещё добавить статусы, звания. Например, для тех кто сидит на курсе два года, автоматом даётся звание: "пердун старый и лентяй"

**Comment by AJIEKCanderG** [comment]
в чате уже давно обсуждали, надо сделать репозиторий своим и вся активность будет видна.

**Comment by AlexeySapsay** [comment]
Активность на гите - одно, а на сайте- другое. Можно решать упражнения и не коммитить в гит, но активность на сайте будет учитывать, что день прошел не зря, а в решении задачек.

**Comment by AJIEKCanderG** [comment]
> Активность на гите - одно, а на сайте- другое. Можно решать упражнения и не коммитить в гит, но активность на сайте будет учитывать, что день прошел не зря, а в решении задачек.

ну не знаю, для меня активность на сайте не несёт прям практической функции, в то время как любой заходящий на твой гит видит насколько активно ты коммитишь и делаешь какие то штуки. Поэтому даже решая упражнения я их добавляю на гит

**Comment by peterarsentev** [comment]
Мы добавили график активности. Сайт еще не обновлял.
