### ISSUE TITLE
3. Замена if-else-throw на if-throw

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#592]
Здесь производит**ь**ся проверка данных.

**Comment by alexlife9** [comment]
**Такую конструкцию всегда стоит разбивать на две части.
Это блок if-throw и полезную часть.**

Такую конструкцию всегда стоит разбивать на две части: на блок if-throw и полезную часть.

**Comment by JelenaKar** [comment]
Исправлено
