### ISSUE TITLE
Добавить описание метода в задании

### ISSUE THREAD

**Issue by SileLence** [peterarsentev/job4j_features_bugs#594]
В задании "2.2. Рефакторинг - Площадь треугольника." необходимо добавить описание метода period(), где указать, что это полупериметр треугольника, а не просто периметр. А так же, желательно переименовать метод в perimeter() или semiPerimeter(), т.к. на английском "периметр" - это именно "perimeter". Пруф: https://en.wikipedia.org/wiki/Perimeter

**Comment by staskorobeynikov** [comment]
исправлено
