### ISSUE TITLE
1. Наследование, композиция и агрегация

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#595]
Как вы видите, класс Dog содержит копировани**я** кода.

**Comment by alexlife9** [comment]
Композиция применя**ть**ся практически во всех шаблонах
Композиция _применяется_ практически во всех шаблонах

**Comment by alexlife9** [comment]
Дублирование кода по сравнению **с жестким связываем незначительный недостаток.**

Дублирование кода по сравнению _с жестким связыванием является незначительным недостатком._

**Comment by JelenaKar** [comment]
Исправлено
