### ISSUE TITLE
Нет возможности откатиться на начальные условия дополнительного упражнения

### ISSUE THREAD

**Issue by chulkovdmitry** [peterarsentev/job4j_features_bugs#598]
Хорошо бы добавить возможность вернуться к начальным установкам упражнения. Запоминаются все изменения.

**Comment by AlexeySapsay** [comment]
поддерживаю, такая возможность сброса в начальное состояния задачи была бы очень удобна. Сохранение последнего состояние не дает шанса исправить ошибку, когда перенес ее в проект, а потом из проекта в валидатор.
Сброс - очень нужен.

**Comment by AJIEKCanderG** [comment]
ранее, кстати, это было, можно было просто выйти из своей учётки и под анонимоусом зайти глянуть... а сейчас вот нет..

**Comment by peterarsentev** [comment]
Мы добавили кнопку сбросить решение.
