### ISSUE TITLE
0.1. Связи между таблицами

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#599]
Ошибка в тексте.

Данный способ использует, как и **many-to-many** вспомогательную таблицу, но опять же используется ограничения на внешние ключи unique. Иначе мы получим связь many-to-many.  

Правильно:
Данный способ использует, как и **many-to-one** вспомогательную таблицу, но опять же используется ограничения на внешние ключи unique. Иначе мы получим связь many-to-many.

**Comment by ShamRail** [comment]
many-to-one не использует вспомогательную таблицу. Замечание не корректно
