### ISSUE TITLE
Некорректное название операции.

### ISSUE THREAD

**Issue by vukivur** [peterarsentev/job4j_features_bugs#6]
В задаче - 6.0.3. Массивы и цикл for. [#412273] 
Написано, как у массива вызвать "метод length". Однако, если я не ошибаюсь, у массива "length" - это не метод, это переменная, мы же обращаемся к полю массива. Метод "length()" - есть у объекта типа String.  
Линк на screenshot:

[https://prnt.sc/vrqwcf](url)

**Comment by peterarsentev** [comment]
Согласен. Спасибо. Поправил описание.
