### ISSUE TITLE
6. Кодировка. [#404166] Опечатки

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#60]
2. Уровень - Джуниор /  Блок 2. Ввод-вывод / 1. Ввод-вывод

"Если говорить совсем простым языком, то кодировка для компьютера - это просто разные язык**а**, **как человека** английский, русский или китайский. Для кодировки есть отдельные таблицы, в котор**ом** указано"
"br.write(data + System.line**s**eparator());"
"Некоторое описан**и:**"
"слова-команды стоп/продолжить/закончить, **l**должны"

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
