### ISSUE TITLE
2. Одинаковые элементы для массивов

### ISSUE THREAD

**Issue by noslav7** [peterarsentev/job4j_features_bugs#602]
2. Одинаковые элементы для массивов (раздел "Упражнения" в части "Массивы").
Полагаю, что важно немного переформулировать задание.
Например, так:
...Нужно вывести на консоль числа, которые есть одновременно **в ячейках с одинаковым индексом** в первом и втором массиве.

**Comment by staskorobeynikov** [comment]
Нет, в задании все верно. Обратите внимание что в первом тесте выводится именно одинаковые элементы, стоят они под разными индексами. Индексы тут ни причем.
