### ISSUE TITLE
Входные данные в тесте

### ISSUE THREAD

**Issue by ViktorJava** [peterarsentev/job4j_features_bugs#604]
![Screenshot_2](https://user-images.githubusercontent.com/54469691/122591763-19a19f80-d06c-11eb-9fde-10654c28f01a.jpg)

**Comment by staskorobeynikov** [comment]
почистите кэш

**Comment by ViktorJava** [comment]
> почистите кэш
В хроме делал F5. Краем уха, слышал, что это обновление именно с очисткой кэша. Не буду утверждать. Буду дома, посмотрю, разберусь, очищу...

**Comment by staskorobeynikov** [comment]
Всему виной локальные настройки браузера, можете почитать тут
https://community.shopify.com/c/Shopify-Discussion/Unwanted-code-generated-at-the-new-products/td-p/772457
Закрываю, к проблемам самой платформы это не относится
