### ISSUE TITLE
0. Инструменты [#238814 #170548]

### ISSUE THREAD

**Issue by DSM4ik** [peterarsentev/job4j_features_bugs#607]
В задании 0. Инструменты [#238814 #170548] 
необходимо создать новый проект job4j_design.
Но в предыдущем задании мы его уже создавали (1. Создание проекта через maven. [#274135 #170524])
Каковы варианты:
1)Предыдущий  job4j_design удалять и создавать новый job4j_design в рамках текущей задачи
2) Оставляем job4j_design из предыдущего задания, а это начинаем с пункта 3. Добавляем git в наш созданный проект.

**Comment by ShamRail** [comment]
Исправлен текст задания.
