### ISSUE TITLE
0.5. Иерархия исключений и множественный catch. [#219368 #170788]

### ISSUE THREAD

**Issue by AleksFromBuk** [peterarsentev/job4j_features_bugs#608]
обратил внимание на первую диаграмму зависимостей среди исключений, что там все начинается с этого класса. Просто 

смутило то, что исходя из моего понимания текста, цитирую кусок: "... что в коде пропал блок ... " - и приводится кусок кода, но его ранее и не было, то есть во всем текущем шаге нигде более не встречается, в том числе и ранее. Вот и подумал, что может предполагалось его наличие,  а его нет.
![image](https://user-images.githubusercontent.com/78998655/123220398-9900fa00-d4d6-11eb-99fd-a3f4e59a22e7.png)

**Comment by staskorobeynikov** [comment]
исправлено
