### ISSUE TITLE
1. Экзамен. Sql [#1730 #167823]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#609]
Вопросы по теме:   Экзамен. Sql [#1730 #167823]

*Нарушена нумерация вопросов.

*Просьба расширить объем вопросов вопросами из списка Раиля по этому зачету

*Некоторые вопросы из зачета не рассмотрены в курсе.
Поэтому предложил бы добавить к зачету 
или в сам курс дополнительные материалы,
которые помогли немного лучше подготовится к зачету
или возможно на их основе можно сделать доп. лекции
или просто ознакомиться перед зачетом.

Базовый видеокурс о SQL
https://www.youtube.com/watch?v=KYIrnSmH-fc&list=PLtz_yutonf6uAKk4x7P9VBQN8RUWkN_Wd

Статья про триггеры
https://www.sql-ex.ru/blogs/?/Rukovodstvo_po_triggeram_v_SQL_nastrojka_otsleZhivaniJa_bazy_dannyh_v_PostgreSQL.html

**Comment by ShamRail** [comment]
1. Нумерация исправлена.
2. Список вопросов обновлен.
3. Список литературы дополнен.
