### ISSUE TITLE
Ошибка в тестах к заданию 7. ListIterator 

### ISSUE THREAD

**Issue by DrawMySoul** [peterarsentev/job4j_features_bugs#612]
В тесте whenAddAfterLast() метод ListUtils.addAfter() принимает 3 переменных, в тесте передается только 2, не хватает списка input. В глядит так ListUtils.addAfter(2, 3), а должно ListUtils.addAfter(input, 2, 3).

**Comment by ShamRail** [comment]
Тест поправили.
