### ISSUE TITLE
Чат курса. Замена Telegram?

### ISSUE THREAD

**Issue by GelfandKonstantin** [peterarsentev/job4j_features_bugs#615]
Петр, не рассматривал ли ты замену Телеграм на курсе? Может быть попробовать перейти на Discord, либо аналогичные мессенджеры? Там есть много интересных возможностей. К примеру, можно делать вставки кода, транслировать свой рабочий стол и т.д. По моему скромному мнению он гораздо удобнее Телеги для целей курса.

**Comment by AlenaLosk** [comment]
или как вариант Slack?

**Comment by enovoselovhi** [comment]
Считаю телеграмм отлично подходит и легковесен по сравнению с предложенными. Телега используется для краткого вопроса по заданию, где нужно описать проблему. Если нужно вставить немного кода можно использовать синтаксис markdown

**Comment by peterarsentev** [comment]
Мы добавили раздел Обсуждения. Там можно добавить код и картинки и обсуждать одну и туже тему 100500. 
Пока в таком режиме попробуем.
