### ISSUE TITLE
6.3. Массив заполнен true или false [#53857]

### ISSUE THREAD

**Issue by BakhtiyarTayir** [peterarsentev/job4j_features_bugs#616]
5. В классе CheckTest напишите 2 тест-метода, которые будут проверять вашу программу для случая, **кода** все элементы массива одинаковые и для случая, когда в массиве есть различающиеся элементы.

Наверное должно быть когда.

**Comment by staskorobeynikov** [comment]
Там уже есть все необходимые тесты, дописывать не нужно
Спасибо, исправил
