### ISSUE TITLE
Курс 2.3.1. Create Update Insert 0.1. Связи между таблицами

### ISSUE THREAD

**Issue by Jazzik42** [peterarsentev/job4j_features_bugs#618]
![image](https://user-images.githubusercontent.com/75524708/124248448-4cec3000-db3c-11eb-9222-4b2c1e190224.png)
![image](https://user-images.githubusercontent.com/75524708/124248480-537aa780-db3c-11eb-83b3-6aee9da6cffb.png)

тут ошибка. Стрелки должны наоборот идти в сторону Students и courses.

**Comment by ShamRail** [comment]
Иллюстрации обновлены. Связи исправлены.
