### ISSUE TITLE
Нужно объяснение в теме урока 2. Каркас шахматной доски [#792 #173571]

### ISSUE THREAD

**Issue by DDavydov911** [peterarsentev/job4j_features_bugs#619]
Добрый день!
Исходя их темы урока, понятно, что этот блок кода ловит исключение, но совершенно не понятно как он работает.
Могли бы Вы добавить пояснение к нему? 
https://prnt.sc/181pwfu

**Comment by peterarsentev** [comment]
Это раздел swing. В курсе его не проходят. 
catch ловит исключение, мы показываем сообщение, что так делать нельзя и фигуру возвращаем на старое место.
