### ISSUE TITLE
Опечатка. Задача 6.7.4. Выигрышные комбинации в сокобан

### ISSUE THREAD

**Issue by Constantine-M** [peterarsentev/job4j_features_bugs#62]
![image](https://user-images.githubusercontent.com/70433548/101163614-e7d36900-3644-11eb-84ad-7278568ae219.png)
Так как просили указывать даже на опечатки, то вот.. Тут не опечатка, а скорее просто не дописали.

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
