### ISSUE TITLE
4.4. Liquibase. Интеграционные тесты. Proxy. [#95881 #173455]

### ISSUE THREAD

**Issue by DashaSinkova** [peterarsentev/job4j_features_bugs#620]
![image](https://user-images.githubusercontent.com/35614404/124322112-90b85700-db87-11eb-82bd-93888751d53b.png)

![image](https://user-images.githubusercontent.com/35614404/124322153-9f9f0980-db87-11eb-847c-5a4ff43e7848.png)

Тест показывает разные результаты. Как выяснилось это происходит из-за LocalDateTime created = LocalDateTime.now();
Дата обновляется при вызове методов внутри теста whenSaveItemAndFindByGeneratedIdThenMustBeTheSame

даты отличаются в наносек

**Comment by peterarsentev** [comment]
Не использовать now(). Явно задать дату.
Либо в тест не проверять это поле. То есть сделать два теста, один без поля, другой с полем, но с явным указанием времени, а не now()
