### ISSUE TITLE
4.3. Булева логика [#242676 #173755]

### ISSUE THREAD

**Issue by traindriver-m** [peterarsentev/job4j_features_bugs#622]
В самом описании Конъюнкции и Дизъюнкции наверное можно добавить как они обозначаются т.е  & и  | .
В описании задания не ясно сформулирован вариант с логической дизъюнкцией.
Непонятно по условию разрешено ли парковаться только на парковке ? Может ли припарковаться сломавшаяся машина или она останется стоять посередине дороги? Т.е. желательно как то указать, что парковка вне зоны парковки для исправных транспортных средств запрещена, а сломавшаяся машина вынуждена будет припарковаться)

**Comment by staskorobeynikov** [comment]
спасибо, переделано
