### ISSUE TITLE
1.1. Что такое import [#504773]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#624]
Поправьте меня, если я не прав.
По поводу статического импорта я бы добавил следующее.

Мы можем использовать имена методов без полного пути
как раз потому, что в статике все загружается заранее,
при первой загрузке программы.

А в динамике мы загружаем объекты тогда, когда это необходимо,
и поэтому должны обращаться к какому-то объекту и вызывать
метод у конкретного объекта.

Мне кажется, чем раньше объяснить основные различия
между статикой и динамикой, тем лучше, это поможет 
дальше лучше понимать материал.

**Comment by peterarsentev** [comment]
У тебя два понятия слил в одно.
Есть импорт. В java можно импортировать класс, а можно импортировать методы из класса.
Это одно и тоже, только кода меньше писать приходится.
И есть загрузка классов. Это отдельных механизм в нем есть статическая и динамическая загрузка. Это другая тема.
