### ISSUE TITLE
4. Сравнение моделей. Метод equals [#174893 #174469] нужны дополнения

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#625]
В теле урока не хватает информации, что при автогенерации equals() в третьем окне [https://prnt.sc/18rptdd](url) все поля должны оставаться пустыми, тогда переменные класса будут сравниваться между собой, как объекты. Если в данных полях проставлены галки, то тест не проходит. Наверное, лучше дополнить урок?

**Comment by staskorobeynikov** [comment]
исправлено
