### ISSUE TITLE
Комментарии по заданию "Используя контейнер на базе связанного списка создать контейнер Stack [#71474 #174206]"

### ISSUE THREAD

**Issue by slesiv** [peterarsentev/job4j_features_bugs#626]
Пишу по просьбе ментора, для корректировки задания.
Ниже комментарии из задачи (https://job4j.ru/profile/exercise/4/task-view/283/solutionId/174206):

1. что то я совсем запутался с наименованием методов. Сначала в описании и каркасе класса указан метод pop(), уже в задании метод называется poll().
В тестах вообще все вместе и pop и poll. Поясните пожалуйста как именно должен называться метод удаляющий элемент и возвращающий его.

2. из примечания к описанию я понял что могу реализовать добавление/удаление с любой стороны, но обязательно с одной. Так как мы добавляем метод addFirst, значит и удаление должно быть с головы. Но при этом тест проверяет удаление с хвоста. Поясните пожалуйста как именно нужно реализовать удаление?

**Comment by ShamRail** [comment]
1. Имена методов исправлены.
2. Задание уточнено.
