### ISSUE TITLE
Неверное употребление слова

### ISSUE THREAD

**Issue by SileLence** [peterarsentev/job4j_features_bugs#627]
Задача: 0. Что такое исключение. [#3821]
https://job4j.ru/profile/exercise/24/task-view/189

Ошибка в строке из лекции: "Давайте теперь поправим исключение. В этой строчке используется переменная index, которая **_инкриминируется_** в цикле for + index."

Слово "инкриминируется" означает обвинение кого-либо в чём-либо.
https://ru.wiktionary.org/wiki/%D0%B8%D0%BD%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C

Правильно использовать слово: "инкрементируется"
https://ru.wiktionary.org/wiki/%D0%B8%D0%BD%D0%BA%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C

Итого: "Давайте теперь поправим исключение. В этой строчке используется переменная index, которая инкрементируется в цикле for + index."

**Comment by JelenaKar** [comment]
Исправлено.
