### ISSUE TITLE
Правка множественных опечаток в 2.5. Реализация класса StartUI. Изменение заявки [#500746 #174635]

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#629]
Добрый день!

Мануал по условным символам: в круглые скобки уберу опечатки и то, что следует исключить; большими буквами и в квадратных скобках у знаков препинания то, что нужно добавить.

В примечании к заданию несколько опечаток и неточностей в формулировке - "В каждом блоке, которо(м)Й (мы) реализуе(м)Т различные возможности нашего приложения [нужна обязательно запятая], должен быть вызов только одноГО метода классА Tracker, т.е. использовать для валидации в данном задании (существует заявка в хранилище заявка с необходимым id) метод findById() запрещено".

**Comment by staskorobeynikov** [comment]
исправлено
