### ISSUE TITLE
Отформатировать наименование класса.

### ISSUE THREAD

**Issue by Oklevet** [peterarsentev/job4j_features_bugs#630]
![image](https://user-images.githubusercontent.com/75887570/124599676-5e587380-de7f-11eb-98a5-887825da15af.png)

При выделении не видны 3 символа. 
В том случае если страница не до конца развёрнута по горизонтали.

![image](https://user-images.githubusercontent.com/75887570/124600024-bc855680-de7f-11eb-9d00-6f6dda92bc18.png)

**Comment by staskorobeynikov** [comment]
Проверил, все корректно отражается
Закрываю.
