### ISSUE TITLE
UI. Не сохраняется режим свертки блока "Выполненные задачи"

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#631]
Просьба сделать его свернутым по умолчанию или сохранять состояние свертки.

Сейчас вообще весь левый блок занимает не сильно значимые пункты меню и к новым задачам приходится постоянно скролить.

![image](https://user-images.githubusercontent.com/12701878/124734749-1b99a880-df1e-11eb-92e6-429967929833.png)

**Comment by peterarsentev** [comment]
Мы поменяли местами выполненные и проверенные.
