### ISSUE TITLE
Возможно дублирующие пункты в курсе

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#634]
Возможно нижеуказанные пункты дублируют друг друга
<img width="779" alt="Возможно пункты дублируют друг друга" src="https://user-images.githubusercontent.com/46091342/124884349-dbe4c680-dfda-11eb-9f00-b123199a621c.png">

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
