### ISSUE TITLE
Использование терминологии в геометрии

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#635]
8. Стороны прямоугольника. [#137735 #158189]

Возможно я не прав или придираюсь 
но для плоских фигур (на плоскости) используются термины Длина и Ширина. 
Они как бы лежат на земле.
Термин Высота используется для объемных фигур и означает вертикаль, а именно отрыв от земли
на определенное расстояние. Возможно имеет смысл подправить обозначения в задаче.

**Comment by staskorobeynikov** [comment]
Читаем по этому поводу вот тут
https://ru.wikipedia.org/wiki/%D0%92%D1%8B%D1%81%D0%BE%D1%82%D0%B0_(%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F)
Закрываю.
