### ISSUE TITLE
2.3.4. JDBC 0.2. PrepareStatement 

### ISSUE THREAD

**Issue by Jazzik42** [peterarsentev/job4j_features_bugs#636]
![image](https://user-images.githubusercontent.com/75524708/124928151-d0b08b80-e018-11eb-82af-e6712e5e90be.png)
// эквивалентно
ResultSet result = statement.executeUpdate(sql);
здесь, statement.executeUpdate(sql) возвращает int значение, и нельзя его приравнять к ResultSet.

**Comment by peterarsentev** [comment]
Поправили. Закрываю.
