### ISSUE TITLE
опечатка в уроке 0.2. Кидаем исключение - throw new RuntimeException [#219365]

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#637]
В тексте урока есть такой кусочек кода:
if (start > finish) {
            throw new IllegalArgumentException("Start should be less then finish.");
        }
Вместо then finish нужно написать than finish, т.к. then переводится, как "затем", а than переводится, как "чем"

**Comment by staskorobeynikov** [comment]
исправлено
