### ISSUE TITLE
В двух пересекающихся заданиях противоречивые типы дынных int vs String

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#638]
В задании 5. PsqlStore 
Уровень : 2. Джуниор Категория : 2.3. SQL, JDBCТопик : 2.3.6.
В каркасе класса PsqlStore, в переопределенном методе интерфейса Store 
@Override
    public Post findById(String id) {
        return null;
    }
указан тип  String,
в задании по созданию самого интерфейса Store 3. Архитектура проекта - Аргегатор Java Вакансий Топик : 2.3.6. Проект. Агрегатор Java
 в данном методе указан тип int
public interface Store {
    void save(Post post);

    List<Post> getAll();

    Post findById(int id);
}

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
