### ISSUE TITLE
ListIterator, опечатки

### ISSUE THREAD

**Issue by saimon494** [peterarsentev/job4j_features_bugs#64]
Джуниор - Блок 1. Структуры данных и алгоритмы. - 3. List - 7. ListIterator

В задании второй раз указан метод addBefore() вместо **addAfter()** - 
![image](https://user-images.githubusercontent.com/17360765/101206178-cfcd0b00-367f-11eb-9014-67277f7e94d0.png)

Ошибка в слове **допишите** - 
![image](https://user-images.githubusercontent.com/17360765/101206227-e3787180-367f-11eb-9588-b254d1431900.png)

Опечатки в предложении, должно быть **списком**, **итерирования** - 
![image](https://user-images.githubusercontent.com/17360765/101206083-ad3af200-367f-11eb-8d0c-4617e6a0adfa.png)

**Comment by staskorobeynikov** [comment]
Спасибо, исправлено
