### ISSUE TITLE
Наверное опечатка в задании 6.9. Жадный алгоритм. Сдача в кофе машине

### ISSUE THREAD

**Issue by traindriver-m** [peterarsentev/job4j_features_bugs#640]
В описании решения написано: Для решения этой задачи необходимо использовать жадный алгоритм.

Его смысл очень прост. Мы берем монету наибольшего номинала - 10. 

Далее вычитаем из суммы. Если остаток **больше 0**, то операцию повторяем, а если меньше, то берем монету номиналом меньше.

И так пока не дойдет до монеты в 1 рубль. 
Не имелось ли ввиду "**больше 10**" ? А то сильно вводит в заблуждение.

**Comment by AshleySunsine** [comment]
Исправлено.
