### ISSUE TITLE
Ошибка в лекции

### ISSUE THREAD

**Issue by SileLence** [peterarsentev/job4j_features_bugs#641]
Лекция 1. Наследование, композиция и агрегация [#95066 #176097]
https://job4j.ru/profile/exercise/25/task-view/202/solutionId/176097
содержит ошибку в предложении:
 "_В проекте tracker класс StartUI зависит от Tracker, Input через композицию. Объекты Tracker и Input записаны в полях объекта StartUI._"

В классе StartUI в полях определён только класс Output.

**Comment by peterarsentev** [comment]
Спасибо. Мы убрали эту задачу из курса. Для уровня стажер она была не нужна.
