### ISSUE TITLE
Опечатки в упражнениях

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#644]
Упражнения
1.4.2. Stream API
2.4. Группировка элементов и среднее значение. Метод averagingDouble()

![image](https://user-images.githubusercontent.com/13130875/125514014-4c8c04b9-1bea-4ece-ada1-7ed73c78d54e.png)
 Возможно в качестве аргумента принимает функцию или принимается функция.

**Comment by AlexeySapsay** [comment]
Упражнения
1.4.2. Stream API
3. Терминальные и промежуточные операции

![image](https://user-images.githubusercontent.com/13130875/125591405-5817c549-124b-4aa1-86e6-c1e3b902800f.png)

Возможно, имели ввиду стриме объектов
Который возвращает число элементов в стриме

**Comment by AlexeySapsay** [comment]
Упражнения
1.4.2. Stream API
4.2. Терминальные операции. Метод allMatch()

![image](https://user-images.githubusercontent.com/13130875/125608427-87ae2571-a9e4-441f-8c73-ae695e036305.png)

вероятно здесь должно быть: элементы стрима

**Comment by AlexeySapsay** [comment]
Упражнения
1.4.2. Stream API
5.4. Промежуточные операции. Метод mapToObj(). Стрим из символов строки

![image](https://user-images.githubusercontent.com/13130875/125743620-7774ef26-1592-4df8-ab16-58bb45905b6b.png)
Возможно имели ввиду в классе String

**Comment by AlexeySapsay** [comment]
Упражнения
1.4.2. Stream API
5.8. Промежуточные операции. Метод flatMap()

![image](https://user-images.githubusercontent.com/13130875/125759141-c53f6158-cae4-431a-9a95-99b0febac87c.png)

Потеряна буква S

**Comment by AlexeySapsay** [comment]
Упражнения
1.4.2. Stream API
9.5. Optional и Stream. Метод stream()
![image](https://user-images.githubusercontent.com/13130875/125782147-e7e41767-f838-4d51-ab83-83b16f8508e7.png)

**Comment by AlexeySapsay** [comment]
Уроки
2.1.2. Generic
0. Что такое обобщенные типы (generics)

![image](https://user-images.githubusercontent.com/13130875/126083196-f2da901d-156d-4c80-987f-5a30dbd660a9.png)

**Comment by AlexeySapsay** [comment]
Уроки
2.1.2. Generic
0. Что такое обобщенные типы (generics)

![image](https://user-images.githubusercontent.com/13130875/126136928-a1769356-16af-474f-af74-2e188ecff019.png)
Вероятно тут должно быть Wildcard, как во втором пункте этой статьи.

**Comment by AlexeySapsay** [comment]
Уроки
2.1.2. Generic
0. Что такое обобщенные типы (generics)
![image](https://user-images.githubusercontent.com/13130875/126161857-4d6a2bb3-0c07-4552-a514-38d0f41434a1.png)
Метод помещает и выводит

**Comment by AlexeySapsay** [comment]
Уроки
2.1.2. Generic
0. Что такое обобщенные типы (generics)
![image](https://user-images.githubusercontent.com/13130875/126172319-6cce6ea1-055d-4722-92de-f59b32dc4eda.png)
возможно здесь лучше использовать его, вместо ее

**Comment by AlexeySapsay** [comment]
Уроки
2.1.2. Generic
5.2.1. Реализовать SimpleArray<T>

https://job4j.ru/profile/exercise/39/task-view/277
 
 В конце статьи пропущено **задание** и не указанно что делать с тестами, самим писать?

**Comment by peterarsentev** [comment]
Спасибо. Взяли в работу. Большая просьба делать отдельные тикеты под ошибки.
Одна ошибка и один тикет.
