### ISSUE TITLE
Регулярно всплывают новые задачи в пройденных блоках

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#646]
Вот пример:
![image](https://user-images.githubusercontent.com/12701878/125656971-3948feaa-4b19-4624-912a-39ff83cca26a.png)

Хотя я сейчас занимаюсь уже в блоке Мидл

**Comment by peterarsentev** [comment]
Да. Мы добавляем задания. И они сразу публикуются. Их нужно либо пройти, Либо закрыть.
