### ISSUE TITLE
Упражнения 1.1.6. Массивы 2.9. Привести строку к верхнему регистру

### ISSUE THREAD

**Issue by AJIEKCanderG** [peterarsentev/job4j_features_bugs#647]
Всем привет!
Вопрос наверное больше к менторам, кто на курсе упражнения делает. Пётр сказал сюда написать.
Пришла мысль немного апгрейдить задачу из раздела:
Упражнения 1.1.6. Массивы 2.9. Привести строку к верхнему регистру.

_Получились примерно такие мыли по этому поводу:_
Заголовок  - **Привести строку к верхнему регистру, убрав лишние символы, цифры и пробелы**
 Дана строка, записанная в виде массив символов.
 В строке могут быть пробелы, символы, цифры, буквы, а также некоторые буквы уже в ВЕРХНЕМ РЕГИСТРЕ.
 Ваша задача создать новую строку в верхнем регистре, в которой будут только буквы исходной строки, которые были в нижнем регистре.
  Если символ является  уже буквой в ВЕРХНЕМ регистре или цифрой или любым символом '@','-','!','%' или пробелом,
 то просто не записывать в результат, а пропустить.
 В итоговом массиве символов должны остаться только буквы в ВЕРХНЕМ РЕГИСТРЕ, которые ранее в исходном были в нижнем.
 * Например, для a-123-B, получить A.
 * Например, для aLpha - 1-0!@#$5(2 пробела присутствуют), получить APHA.
 * Например, для aLpHa - 1-0!@#$5(2 пробела присутствуют и 2 буквы в ВЕРХНЕМ регистре изначально), получить APA.
 
 Использовать некоторые доп. методы и ознакомиться в остальными:
 * Character.isLowerCase() — возвращает значение true, если переданный символ в нижнем регистре.
 * Character.isUpperCase()) — возвращает значение true, если переданный символ в верхнем регистре.
 * Character.toLowerCase() — возвращает указанное значение в нижнем регистре.
 * Character.toUpperCase() — возвращает указанное значение в верхнем регистре.
 * Character.isLetter() — возвращает значение true, если переданный символ буква.
 * Character.isDigit() — возвращает значение true, если переданный символ цифра.
 * Character.isWhitespace() — возвращает значение true, если переданный символ пустое пространство ("пробел").

тесты
```   
@Test
    public void LettersLowerCaseWithDigits() {
        char[] input = "alpha012".toCharArray();
        char[] expect = "ALPHA".toCharArray();
        assertArrayEquals(expect, UpperCase.toUpperCase(input));
    }

```
```
    @Test
    public void LettersLowerCaseWithDigitsWithSymbols() {
        char[] input = "alpha-12@?-".toCharArray();
        char[] expect = "ALPHA".toCharArray();
        assertArrayEquals(expect, UpperCase.toUpperCase(input));
    }
```
```
    @Test
    public void LettersLowerCaseAndOneUpperCaseDigitsSymbolsSpace() {
        char[] input = "aLpha - 1-0!@#$5".toCharArray();
        char[] expect = "APHA".toCharArray();
        assertArrayEquals(expect, UpperCase.toUpperCase(input));
    }
```
```
    @Test
    public void LettersLowerCaseAndTwoUpperCaseDigitsSpace() {
        char[] input = "aLpHa - 1".toCharArray();
        char[] expect = "APA".toCharArray();
        assertArrayEquals(expect, UpperCase.toUpperCase(input));
    }
```

**Comment by peterarsentev** [comment]
Спасибо. Добавил в курс. Если будут еще идеи, то пиши. буду рад добавить.
