### ISSUE TITLE
Ошибка в задании 3.1. Прерывание блокированной нити. Уровень Мидл. Многопоточность.

### ISSUE THREAD

**Issue by amemelyanov** [peterarsentev/job4j_features_bugs#648]
В описании задания указано:
Задание.
1. Поправьте код в классе **Wget**.

Но судя по содержанию урока, правильный класс для правки - **ConsoleProgress** из задания "3. Прерывание нити".

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
