### ISSUE TITLE
Опечатка в статье к заданию: Мотивирующая статья. Команда. [#412432]

### ISSUE THREAD

**Issue by vukivur** [peterarsentev/job4j_features_bugs#65]
[https://prnt.sc/vw0rzy](url)

**Comment by ryabinintm** [comment]
В каждом разделе опечатки

**Comment by peterarsentev** [comment]
@vukivur Спасибо, Поправили.
@ryabinintm Если есть возможность, то скиньте картинки или номера задач и статьей, где есть ошибки. "Опечатки в каждом разделе"  - это не так.
