### ISSUE TITLE
3. Фабричный метод, абстрактная фабрика. [#95067 #4094]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#650]
Считаю, что указанное в уроке определение 

"Смысл этого шаблона в создании метода, который создает новый экземпляр объекта. "

нужно обязательно дополнить информацией о том,
что происходит не просто создание объекта, 
а создание разных объектов, в зависимости от некоторых условий. 
Думаю в этом суть шаблона, а не просто в создании объектов.

**Comment by peterarsentev** [comment]
Взяли в переработку. Спасибо.
