### ISSUE TITLE
2. Тестовое задание Блок Garbage Collection

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#652]
Можно попросить добавить диаграмму схема зависимостей, кто от кого.
По возможности добавить хотя бы частичное описание функционала методов

**Comment by peterarsentev** [comment]
@SlartiBartFast-art Пока расписывать задание не будем.
По причинам.
1. Это тестовое задание и оно специально так сделано.
2. На этом уровне ученик уже может в этом коде разобраться без диаграмм и описание архитектуры.
