### ISSUE TITLE
Сохранение в Закладки

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#655]
Добавил в закладки урок 4. Методы, выполнил задание, отправил на проверку.
При попытке переайти в урок 4 из бокового меню (блок "Ссылки") открывается урок 3. Арифметические операции.
Скрин:
![Ошибка сохранения закладки](https://user-images.githubusercontent.com/48833977/126867850-0e849064-de79-4535-a199-9b54c45321e6.png)
Win10, Opera 77

**Comment by bshevyrov** [comment]
Дополню.
![image](https://user-images.githubusercontent.com/85710572/127472247-4563e81d-bcc6-4b10-b37c-c047bb015a14.png)
 
 При нажатии на звездочку в закладки отправляеться не верная сссылка на урок.

**Comment by peterarsentev** [comment]
Поправили.
