### ISSUE TITLE
Не запускаются тесты в упражнении 1.1.4. Оператор ветвления 1.1. Стоит ли играть?

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#658]
![image](https://user-images.githubusercontent.com/48833977/127140199-d8505700-66fb-4a59-b9fd-ccaec3fcae1f.png)

**Comment by peterarsentev** [comment]
@MrShmiTT А в чем ошибка? Локально не запускается? Видимо нет зависимостей. Проверьте, что подключен hamcrest. 
На сайте код запускается.

**Comment by MrShmiTT** [comment]
@peterarsentev да, локально не запускался. Вроде подключен.
![image](https://user-images.githubusercontent.com/48833977/127462306-4b2d1d90-a65c-4a28-b02b-fcbc678fc561.png)
Теперь все тесты запускаются норм. Хз в чем проблема была, возможно из-за смены имен классов.
