### ISSUE TITLE
Практически все упражнения с ОГРЕХами в разделе сортировка

### ISSUE THREAD

**Issue by ryabinintm** [peterarsentev/job4j_features_bugs#66]

**Comment by peterarsentev** [comment]
@ryabinintm Это раздел упражнения или задания по курсу?

**Comment by ryabinintm** [comment]
упражнения07:54, 7 декабря 2020 г., Petr Arsentev <notifications@github.com>:
@ryabinintm Это раздел упражнения или задания по курсу?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
