### ISSUE TITLE
Коментарии

### ISSUE THREAD

**Issue by evgenkolesman** [peterarsentev/job4j_features_bugs#660]
Просьба: сделать возможность исправлять комментарии хотя бы до того как на них ответил ментор

**Comment by peterarsentev** [comment]
@evgenkolesman Можете описать сценарий? Зачем это нужно?
Мы не делали редактирование, чтобы видеть историю переписки. 
Потому что ученик может изменить ссылку на коммит. Это позволяет избежать конфликтов.

**Comment by evgenkolesman** [comment]
Сценарий такой ошибка в написании, или в грамматике, или в сообщении, которое написал ментору, которые хочешь исправить, поэтом получается по несколько комментариев надо писать в то время, когда можно исправить один, это нужно лишь для удобства.

Мое предложение, дать возможность исправлять комментарий, до тех пор пока на него нет ответа. 
Дальше он фиксируется как сейчас и остается неизменным. 
Поможет улучшить читаемость и вам, и нам.

Почему?
ошибки Т9, ошибки при печати.
Возможно, до того как тебе ответил ментор ты, что то понял, но появились новые вопросы и аналогичные ситуации

**Comment by peterarsentev** [comment]
Добавили. Спасибо. На сервере еще не обновлял. 
Теперь свои комментарии можно редактировать.
