### ISSUE TITLE
Не доступен 1.2.1 Статические и не статические методы.

### ISSUE THREAD

**Issue by traindriver-m** [peterarsentev/job4j_features_bugs#662]
Во вкладке "Новые уроки" доступен урок **1.2.1 Статические и не статические методы**. При попытке перейти на него, перенаправляет на страницу авторизации.

**Comment by bshevyrov** [comment]
Дополню 
https://job4j.ru/profile/exercise/20/task-view/801
![image](https://user-images.githubusercontent.com/85710572/127523306-f1f35442-a669-4db8-a296-7d70b35ce720.png)

**Comment by kalenikov** [comment]
Такая же проблема

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by andreiHi** [comment]
готово

**Comment by kalenikov** [comment]
Ничего не изменилось. При попытке перейти на пункт меню по-прежнему идет перенаправление на страницу авторизации.
