### ISSUE TITLE
Представление материала.

### ISSUE THREAD

**Issue by mannar88** [peterarsentev/job4j_features_bugs#664]
Просьба переработать материал, что бы он был представлен не только картинками, но и имел текстовый слой. Это нужно, что бы люди с плохим зрением, использующие screen reader могли иметь полный доступ к материалам. Поэтому так же желательно, кроме фраз "нажмите зеленую кнопочку" было еще и официальное название, так как она называется в Идее. Так же, в Идее очень хорошо реализована система горячих клавиш, и хотелось бы при подаче материала, кроме фраз " нажмите на верхний край", было бы описано, как можно это реализовать с помощью клавиатуры. На других ресурсах, я видел, что это было описано и это очень удобно.

**Comment by peterarsentev** [comment]
Взяли в работу. Объект этой задачи большой. Будем делать мере возможности.
Спасибо за предложение.
