### ISSUE TITLE
Описать назначение двойного переноса строки в задании 1. Бот [#7921 #182672]

### ISSUE THREAD

**Issue by k2250427** [peterarsentev/job4j_features_bugs#665]
В задании приводится пример ответа сервера
out.write("HTTP/1.1 200 OK\r\n\r\n".getBytes());
однако не указано, что сдвоенный перевод строки сделан не для оформления вывода, а является требованием спецификации протокола HTTP (метаданные от данных разделяются пустой строкой)

Стоит сделать на этом акцент в уроке

**Comment by peterarsentev** [comment]
Это добавили. Спасибо.
