### ISSUE TITLE
Закладка Прогресс обучения. График активности.

### ISSUE THREAD

**Issue by Ingerner** [peterarsentev/job4j_features_bugs#666]
График активности возрастает по нажатию кнопки "решить" (в закладке упражнения), а не по факту правильно решенной задачи.

**Comment by peterarsentev** [comment]
@Ingerner Да мы так и планировали. То есть он не учитывает прогресс, он учитывает активность.
По аналогии с github. Ты можешь сделать 100500 коммитов в день. Но они все будет с правками пробелов. Толку ноль, но активности много.
