### ISSUE TITLE
1.2.1. Статические и не статические методы. Нет доступа к теме.

### ISSUE THREAD

**Issue by kamikhaylov** [peterarsentev/job4j_features_bugs#668]
1.2.1. Статические и не статические методы.

Добрый день!

Появился новый урок: 1.2.1. Статические и не статические методы.

![image](https://user-images.githubusercontent.com/43637775/127782309-d7074b31-45b9-4788-82d9-c9714368595d.png)

При переходе в урок запрашивает авторизацию:

![image](https://user-images.githubusercontent.com/43637775/127782365-2e633d0d-76da-4cb9-940a-14cdd638f392.png)

Ввожу логин и пароль - перебрасывает на страницу профиля, и в урок все равно не пускает. Опять запрашивает логин и пароль.
Браузер Google Chrome, также пробовал в режиме ингокнито и с альтернативного браузера Safari.

Спасибо!

С уважением, Константин!

**Comment by kamikhaylov** [comment]
Другие уроки в очереди открываются без проблем: 

![image](https://user-images.githubusercontent.com/43637775/127782578-e0f85334-a098-42dc-9913-8ae1b0d59d2d.png)

![image](https://user-images.githubusercontent.com/43637775/127782595-77fe16aa-a106-47b1-926e-f0141fc9fb76.png)

**Comment by himax82** [comment]
Такая же проблема, пишет два урока не сделаны, в списках уроков их нет, висят слева где новые уроки, пытаюсь зайти в них выкидывает на страницу авторизации
![image](https://user-images.githubusercontent.com/80378936/127858862-ea65e505-9bf9-4d60-b6c2-03de5126c681.png)

**Comment by lenarsharipov** [comment]
Аналогичная проблема. В модуле "Классы и объекты" урок по статическим методам отсутствует. Задание высвечивается но зайти нельзя. При нажатии выкидывает на страницу авторизации. В контрольных вопросах есть вопросы по данной теме.
![Screenshot](https://user-images.githubusercontent.com/85287096/127979479-c92f22f7-85a4-4f44-98b0-927934e9f1ef.png)

**Comment by peterarsentev** [comment]
Багу поправили. Но на сервере еще не обновили. Спасибо.
