### ISSUE TITLE
Теперь я официально Джуниор

### ISSUE THREAD

**Issue by AshleySunsine** [peterarsentev/job4j_features_bugs#669]
Не могу зайти в упражнение "Теперь я официально Джуниор" . Выкидывает на страницу авторизации.

**Comment by peterarsentev** [comment]
@AshleySunsine Подскажите, из какой это темы?

**Comment by AshleySunsine** [comment]
Тема 2.5.5 DIP. В разделе уроки(там, где шкала прогресса у каждой темы видна) отображается 3 задачи. Когда заходишь в тему, там только 2 задачи. Как раз нет задачи #3 "Теперь я официально джун".
Но! Эта задача отображается слева в меню, где краткий список предстоящих задач. Туда кликаем и вылетаем.

**Comment by peterarsentev** [comment]
Поправили.
