### ISSUE TITLE
3.2. Зачем нужно приведение типов

### ISSUE THREAD

**Issue by RuslanFajziev** [peterarsentev/job4j_features_bugs#67]
**Отсутствует выходное изображение консоли.**

Как вы видите мы создали объекты каждого из классов, но при этом привели его к более общему типу, в таком виде мы всех можем добавить в массив, а потом в цикле for() для каждого из объектов вызвать его метод - однако нам в данном случае будет доступен только один метод - sound(). **Вывод в консоль будет следующим:**

**Comment by staskorobeynikov** [comment]
спасибо, картинки вернули
