### ISSUE TITLE
Количество заданий в папке "1.4.2. Stream API"

### ISSUE THREAD

**Issue by alaktyushin** [peterarsentev/job4j_features_bugs#670]
Добрый день!

В папке "1.4.2. Stream API" 10 или 11 заданий?
В самой папке находится 10 заданий (и сверху указано "Задания : 10"). При этом в общем списке уроков указано "1.4.2. Stream API - выполнено 0 из 11".

Возможно ли, что мне не доступно какое-то задание из папки?

**Comment by alaktyushin** [comment]
В перечне "Новых уроков" справа в интерфейсе присутствует задание " 7. Как сделать ад с помощью Stream API.". Но при нажатии на него меня выкидывает на страницу входа в интерфейс (для ввода логина-пароля). После входа снова вижу задание справа, но не вижу в блоке "Stream API".

**Comment by peterarsentev** [comment]
Спасибо. Эту багу поправили. но еще не обновляли сервер.
