### ISSUE TITLE
4.4. Вложенный оператор if else [#190 #182776]

### ISSUE THREAD

**Issue by GelfandKonstantin** [peterarsentev/job4j_features_bugs#671]
Мне кажется, что с вложенным оператором if else нужно указать, что дописывать ничего не нужно, а доработать существующий код путем исправления. Лично я запутался и написал очень много лишнего кода, хоть он и работал.

**Comment by peterarsentev** [comment]
Спасибо. Мы переписали задание. Сделали его понятным.
