### ISSUE TITLE
1. Хранилище продуктов Категория : 2.5. ООД Топик : 2.5.3. LSP

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#672]
Добавьте пожалуйста uml-схему.
Важно, что UML переводится как Unified Modeling Language. Главное здесь слово Unified. То есть наши картинки поймём не только мы, но и остальные, знающие UML. Получается, это такой международный язык рисования схем.
Спасибо

**Comment by peterarsentev** [comment]
Добавил. Спасибо.
