### ISSUE TITLE
Ошибочно указывается время ответа в разделе "Уведомления"

### ISSUE THREAD

**Issue by noslav7** [peterarsentev/job4j_features_bugs#673]
Здравствуйте!
Дело в том, что время ответа ментора на вопрос / проверка задания всегда указывается 03:00.

Это немного путает, поскольку не всегда сразу понятно, какие ответы ментора были последними.
Можно ли с этим что-то сделать?

**Comment by peterarsentev** [comment]
@noslav7 Можете добавить картинку?

**Comment by noslav7** [comment]
К сожалению, я не нашел, как добавить картинку непосредственно сюда. Через ссылку на файлообменник:
https://cloud.mail.ru/public/XAhs/N8xkhaa1w

**Comment by noslav7** [comment]
это как сейчас, чтобы показать, что время всегда одинаковое
когда таких сообщений становится много и все в один день, то путаешься

**Comment by noslav7** [comment]
Вот еще накопились комментарии. Теперь нагляднее видно: только если по дате смотреть, но это только с точностью до дня.
https://cloud.mail.ru/public/nhRx/Wgnsbfw3n

**Comment by peterarsentev** [comment]
Поправили. Сервер еще не обновлял. Ждите обновления.
