### ISSUE TITLE
Ошибка в расчете активности при пешении упражнений

### ISSUE THREAD

**Issue by maximazarkov** [peterarsentev/job4j_features_bugs#674]
Ошибка в том, что если решать задания по обучению, в результате решения и закрытия задач, значение в графике активности увеличивается штатно. Если решать дополнительно упражнения, но активность растет по экспоненте (не реально). Не удобно пользоваться аналитикой

**Comment by peterarsentev** [comment]
Мы так и планировали. То есть график активности - это все что ученик сделал в системе.
Мы добавим график по решениям.
