### ISSUE TITLE
Некорректная ссылка на задание

### ISSUE THREAD

**Issue by amemelyanov** [peterarsentev/job4j_features_bugs#675]
В списке новых уроков появилось задание - "1.2.1 Статистические и не статистические методы", при его выборе происходит переход на страницу авторизации.
![image](https://user-images.githubusercontent.com/13836413/128118136-7a854a74-dc12-4f9c-99a7-d28647608603.png)

**Comment by peterarsentev** [comment]
Спасибо. Мы это поправили. Но не обновили сервер.
