### ISSUE TITLE
В списке "Новые уроки" висит задача из курса Стажер, выполненная ранее

### ISSUE THREAD

**Issue by k2250427** [peterarsentev/job4j_features_bugs#677]
В списке "Новые уроки" висит задача из курса Стажер, выполненная ранее. При попытке eё просмотреть открывается окно авторизации курса
 
![image](https://user-images.githubusercontent.com/45516217/128175374-0455e895-298a-41f0-a271-8a8296b7be1b.png)

**Comment by peterarsentev** [comment]
Спасибо. Мы это поправили. Но еще не обновили сервер.
