### ISSUE TITLE
Неудачный пример класса и объекта

### ISSUE THREAD

**Issue by Adzami** [peterarsentev/job4j_features_bugs#679]
Урок 0. Классы и объекты
https://job4j.ru/profile/exercise/20/task-view/132
Пример с формой кекса кочует по все статьям/книгам про ООП, но он не корректен, т.к. форма это свойство кекса, а не его описание. В этой форме можно выпечь не только кекс, и кекс можно выпечь не только в этой форме, в одной и той же форме можно выпечь совершенно разные кексы, и т.д. Рецепт кекса и кекс будет корректнее.

**Comment by peterarsentev** [comment]
Согласен. Спасибо. Поправил на кулинарный рецепт.
