### ISSUE TITLE
Ошибка в задаче 0.4 с автотестом по теме Streams

### ISSUE THREAD

**Issue by AlexanderBanar** [peterarsentev/job4j_features_bugs#68]
Код проходит успешный тест в идее, но выдает ошибку на сайте.
[http://prnt.sc/vwhu6c](url)

Также подобная ошибка найдена в задаче 5.3
[http://prnt.sc/vwvrpu](url)

**Comment by staskorobeynikov** [comment]
указанные ошибки исправлены
