### ISSUE TITLE
2. Комбинированный компаратор

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#680]
**Если результат первого компаратора равен 0, то есть объекты равны, то комбинированный компаратор берет переданный в компаратор.**
Не законченная мысль.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.

**Comment by alexlife9** [comment]
то проверка переходит**ь** ко второму компаратору
мягкий знак лишний
