### ISSUE TITLE
Перепутаны скриншоты 3. Travis CI [#31727 #186906]

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#681]
После строки:
Для этого открываем файл README.md

Было непонятно где брать маркеры, долго искал, пока не просмторел все скрины и не нашел зеленую кнопку с иконкой gihub

Ссылка на урок:
[](https://job4j.ru/profile/exercise/19/task-view/231/solutionId/186906)

**Comment by peterarsentev** [comment]
Спасибо. Взяли в работу.
