### ISSUE TITLE
Панель быстрого редактирования

### ISSUE THREAD

**Issue by jeikhan** [peterarsentev/job4j_features_bugs#682]
Некорректное отображение всплывающих подсказок при наведении на кнопки в панели быстрого редактирования (см. скриншот)...

![быстрый редактор](https://user-images.githubusercontent.com/36795293/128594380-0d579283-dd25-45ca-8ad6-4b63c6a2a172.png)

**Comment by peterarsentev** [comment]
Дубликат. https://github.com/peterarsentev/job4j_features_bugs/issues/691
