### ISSUE TITLE
Возможно небольшая ошибка во фронте

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#683]
Не выделяется целиком прямоугольник при наведении на него мышью, как соседние
<img width="147" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/128595590-e34bf746-1a89-4284-abf6-0416a4e348da.png">

**Comment by peterarsentev** [comment]
Взяли в работу. Спасибо.
