### ISSUE TITLE
1. Реализация кеша на SoftReference [#1592 #178798]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#684]
Вопросы по теме: 
1. Реализация кеша на SoftReference [#1592 #178798]

---

Не очень понятны следующие фразы:
- загрузить содержимое файла в кэш
- получить содержимое файла из кэша

Если я правильно понимаю, мы не сами файлы в мапу заносим а
мягкие ссылки на них, может быть как-то уточнить этот момент в задании?

---

Как правильно заметил Раиль, данный урок является
хорошим примером шаблона Абстрактная фабрика.
Если бы он этого не отметил, я бы не догадался, не вспомнил.
Возможно имеет смысл об этом упомянуть, чтобы новички
смогли ещё раз повторить этот полезный шаблон и 
посмотреть реальный пример на него - так лучше можно его запомнить.

**Comment by peterarsentev** [comment]
Спасибо. Это поправили.
