### ISSUE TITLE
1. Экзамен. GC. [#1555]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#685]
Вопросы по теме:
1. Экзамен. GC. [#1555]

1. Просьба объединить и согласовать вопросы от Петра и списка Раиля.
2. Много вопросов из вопросника не освещено в курсе, приходится тратить много времени на них,
просьба добавить необходимые темы в курс

**Comment by peterarsentev** [comment]
Спасибо. Взяли в работу.
