### ISSUE TITLE
Нерабочая ссылка

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#686]
В блоке навигации слева висит урок
1.2.1. Статические и не статические методы
https://job4j.ru/profile/exercise/20/task-view/801
При клике по ссылке, перекидывает на страницу авторизации
![image](https://user-images.githubusercontent.com/48833977/128644025-b1787c8a-28eb-4182-836e-e31c1e259fb6.png)

**Comment by peterarsentev** [comment]
Поправили.
