### ISSUE TITLE
Ошибка в статистике.

### ISSUE THREAD

**Issue by RomanKarczewski** [peterarsentev/job4j_features_bugs#687]
Здравствуйте! Все уроки в разделе 1.2.1 выполнены. Но выше уровнем в разделе "уроки" написано, что выполнено 15 из 16 (94%). Почему так?

**Comment by peterarsentev** [comment]
Добрый день. Это бага в системе. Мы ее поправили. Но я сервер не обновлял.
В курсе есть задачи с закрытой видимостью. Они тоже считаются.
