### ISSUE TITLE
Нет доступа к одной задаче

### ISSUE THREAD

**Issue by noslav7** [peterarsentev/job4j_features_bugs#688]
Добрый день.
Нет доступа к заданию 7 раздела Stream API (картинку прилагаю).
В самом разделе с заданиями ее нет. Она есть в списке слева, но через кнопку в этом списке на страничку с задачей попасть нельзя: при попытке это сделать переправляешься на страничку авторизации, после чего просто на главную страницу.
[https://cloud.mail.ru/public/J4Ek/z5FoHcqzq](url)

**Comment by noslav7** [comment]
Ссылка перестала работать по-моему [https://cloud.mail.ru/public/J4Ek/z5FoHcqzq](url)
Такая же ситуация с задачей 1.9 Статические и не статические методы раздела 1.2.1 Классы и объекты.
[https://cloud.mail.ru/public/u8qK/eUqzqKbLZ](url)

**Comment by noslav7** [comment]
Почему-то ссылки на облако перестали работать.
Не подскажете, как еще мне сюда можно поместить картинку? Что-то не могу здесь такого найти...

**Comment by peterarsentev** [comment]
Мы поправили. Сервер обновили. Обновите кеш.
