### ISSUE TITLE
5.6. Простые числа [#156314]

### ISSUE THREAD

**Issue by starfirst57** [peterarsentev/job4j_features_bugs#689]
В каркасе теста на проверку числа 11 опечатка. Ожидаемое значение указано 5, хотя при не строгом неравенстве получается 6 чисел. Он не будет выполняться при не строгом неравенстве. Если ставить строгое неравенство, то тогда остальные два теста не выполняются. Исходя из задания видно, что в цикле должно быть не строгое неравенство

**Comment by peterarsentev** [comment]
Я явно указал, что высчитывать до числа включая само число.
Но все тесты там это учитываются.
для 11 будет 5
для 5 будет 3
для 2 будет 1.
В каком тесте ошибка?

**Comment by starfirst57** [comment]
Это я криво посчитал. Все ок. Прошу прощения
