### ISSUE TITLE
малозначительное несоответствие в тексте задачи 7. FP - функциональное программирование [#310021]

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#693]
В задаче из раздела Lambda приведён пример из задачи которая находится в следующем разделе  - Stream API, из-за чего наглядность примера для неознакомленного читателя уменьшается.

2. Второй подход концентрируется на том, что нужно сделать.
Например в задании - 6. Тестовое задание из модуля коллекции Lite переделать на Stream API - мы делали такой запрос карту для поиска студента по его данным:
public Student findByAccount(String account) {
    return students.keySet()
            .stream()
            .filter(s -> s.getAccount().equals(account))
            .findFirst()
            .orElse(null);
}

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
