### ISSUE TITLE
Предложение по комментариям в ответах

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#694]
Вместе со ссылкой на решение задания, бывает, задаешь вопрос ментору. Например, как сделать лучше/проще/удобнее. Когда задание выполнено правильно, ментор отвечает и закрывает задание. Хотелось бы видеть ответ ментора, а не просто уведомление о выполненном задании.
В худшем случае ты забыл о своем вопросе, а в лучшем - ищешь урок и мотаешь вниз, чтобы посмотреть ответ.

**Comment by peterarsentev** [comment]
@MrShmiTT Ответ ментора в уведомлениях?

**Comment by tasker312** [comment]
> @MrShmiTT Ответ ментора в уведомлениях?

Тоже хотел бы предложить. Было бы удобно сразу видеть комментарий ментора в уведомлении в телеграм (и на сайте), чтобы не приходилось открывать урок и пролистывать

**Comment by MrShmiTT** [comment]
> @MrShmiTT Ответ ментора в уведомлениях?

Да, ответ ментора, отображаемый в уведомлениях, решил бы вопрос.
И в уведомлениях появился бы смысл)

**Comment by peterarsentev** [comment]
Добавили. Телеграмм теперь отправляет и текст. В интерфейсе тоже добавили вывод комментария.
