### ISSUE TITLE
1. JaCoCo. Процент покрытие тестами

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#698]
Между тегами plugins добавляе**Т** код плагина указанный ниже
Т на М заменить

**Comment by alexlife9** [comment]
в целом мне кажется объяснение JavaDoc надо в начале обучения сразу вводить, а то все комменты-пояснения, которые я писал для себя в каждой строчке кода через два слэша, в одном из заданий надо было грохнуть...

**Comment by staskorobeynikov** [comment]
исправлено
