### ISSUE TITLE
3.4.1. DI. Внедрение зависимостей. Поправить описание задания 0. Что такое DI?

### ISSUE THREAD

**Issue by dvamedveda** [peterarsentev/job4j_features_bugs#699]
Там написано: "вернемся к проекту Tracker" и т.д. Там реализуется нашими силами контекст приложения и внедрение зависимостей. И мы уже писали несколько версий трекера (MemTracker, SqlTracker, HbmTracker)
Однако, если вернуться к уже написанным версиям проекта Трекер, то там в классах конструкторы требуют параметрами **интерфейсы**, для того, чтобы наши классы были тестируемыми и мы могли вызывать конструкторы заглушечными классами. И если писать внедрение зависимостей с учетом передачи интерфейсов, задача становится нетривиальной. А если не писать - то надо править код на передачу в конструктор классов, но тогда нужно либо переписывать, либо игнорить тесты, так как они ломаются.
Хотя я и написал хоть сколько-то работающее решение, но уточнив у Петра, оказалось, что надо было использовать код не уже одного из существующих трекеров, а использовать каркасы классов описанных в задании. Так как дальше этот код будет правится под спринг еще и еще, и все время ученик будет исправлять и спотыкаться об то, что сам же и писал ранее, как правильное.
Нужно поправить описание, с прямым указанием использовать код имеющийся в задании.

**Comment by peterarsentev** [comment]
Поправили.
