### ISSUE TITLE
Мало информации 2. Travis CI [#31727]

### ISSUE THREAD

**Issue by Ajderka** [peterarsentev/job4j_features_bugs#7]
![image](https://user-images.githubusercontent.com/33464241/100521017-ba507080-31a9-11eb-88b1-a5d9c1c86554.png)
картинка например такая
![image](https://user-images.githubusercontent.com/33464241/100521032-d81dd580-31a9-11eb-9414-0f6cb38b7f1f.png)

**Comment by Ajderka** [comment]
И одну картинку с сайта codecov было бы замечательно

**Comment by peterarsentev** [comment]
Спасибо. В описании отвалились картинки. Сейчас восстановили. Проверьте.
