### ISSUE TITLE
2. Что такое JavaDoc

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#700]
Тем более вернувшись к классу, который **Вы** писали несколько месяцев назад - вы можете и не вспомнить ту логику, которую **вы** закладывали при его написании.

избыточные определения - три раза "вы". 

надо так -
Тем более вернувшись к классу, который написан несколько месяцев назад - вы можете и не вспомнить ту логику, которую закладывали при его написании.

**Comment by alexlife9** [comment]
в целом мне кажется объяснение JavaDoc надо в начале обучения сразу вводить, а то все комменты-пояснения, которые я писал для себя в каждой строчке кода через два слэша, в одном из заданий надо было грохнуть...

**Comment by staskorobeynikov** [comment]
исправлено
