### ISSUE TITLE
Запутанная формулировка задания 2. Аттестация последней части Стажера 

### ISSUE THREAD

**Issue by DDavydov911** [peterarsentev/job4j_features_bugs#701]
Добрый день!
Просьба переделать описание задания.
Формулировка:
    "Метод averageScoreBySubject вычисляет средний балл ученика по его предметам.
    Возвращает список из объекта Tuple (имя ученика и средний балл).
    Метод averageScoreByPupil вычисляет средний балл по всем предметам для каждого ученика. 
    Возвращает список из объекта Tuple (название предмета и средний балл)."
затрудняет понимание, кажется что это одно и тоже. Метод ScoreByPupil можно было бы описать так:
    "Метод averageScoreByPupil вычисляет средний балл по каждому из предметов для всех учеников. 
    Возвращает список из объекта Tuple (название предмета и средний балл)." 
И если это средний балл каждого предмета, то наверное корректно поменять названия этих двух методов местами, чтобы  для учеников в названии было слово Puple, а для предметов - слово Subject.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
