### ISSUE TITLE
Опечатка в тексте (Junior, 2.2.3.1)

### ISSUE THREAD

**Issue by snowflakes75** [peterarsentev/job4j_features_bugs#704]
Добрый день!

Опечатка в тексте.

Lob4j необходимо заменить на Log4j. 5 строка с верху в задании. 1. Log4j. Логирование системы. 

![image](https://user-images.githubusercontent.com/77325744/129621511-d5fa1c3a-a904-47a8-b827-e3f9de7ee770.png)

**Comment by AshleySunsine** [comment]
Исправлено.
