### ISSUE TITLE
Опечатка в тексте (Junior, 2.3.3.0)

### ISSUE THREAD

**Issue by snowflakes75** [peterarsentev/job4j_features_bugs#705]
Добрый день!

В разделе задания, упражнение 2.3.3.0. Join, произвести замену с emploees на employees.
![image](https://user-images.githubusercontent.com/77325744/129621910-75ae54d3-0f09-4c42-8d87-e1e4aec3c7df.png)

**Comment by AshleySunsine** [comment]
Исправлено
