### ISSUE TITLE
2. Модель памяти Java [#267917 #191005]00

### ISSUE THREAD

**Issue by AshleySunsine** [peterarsentev/job4j_features_bugs#707]
В этом уроке нужно подробнее объяснить, что происходит в строке

synchronized (DCLSingleton.class) {..}

За три курса ученики с подобным сталкиваются только однажды(настройка драйвера БД) и там тоже ничего не сказано,
как это работает. Как работают эти кобочки с классом внутри? Как это использовать?

**Comment by peterarsentev** [comment]
Спасибо. Добавили описание.
