### ISSUE TITLE
Битая ссылка в задании 5.1.2. Создать итератор четные числа [#150]

### ISSUE THREAD

**Issue by alaktyushin** [peterarsentev/job4j_features_bugs#708]
Добрый день!

В задании 5.1.2. Создать итератор четные числа [#150] битая ссылка на тесты (https://job4j.ru/TrackStudio/download/task/150/0873958f719bb18c0171a7468d0833ac/EvenIteratorTest.java):

502 Bad Gateway

Затруднительно выполнить задание.

**Comment by staskorobeynikov** [comment]
неактуально, тесты теперь сразу в описании
