### ISSUE TITLE
Опечатка. 4.2. Результат работы метода [#232622]

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#710]
public class MathFunc {

    public static void func1(int x) {
        int y = x * x + 1;
    }

    public static void func2(int x) {
        int y = x * 10;
    }

    public static void main(String[] args) {
        MathFunc.func1(3);
        MathFunc.func1(5);
    }
}
По описанию вместо  MathFunc.func1(5); наверное имелось в виду MathFunc.func2(5);

**Comment by AshleySunsine** [comment]
Исправлено.
