### ISSUE TITLE
4.3.1. Оператор && [#333783]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#711]
Вопросы и замечания по темам: 
4.3.1. Оператор && [#333783]
4.3.2. Оператор || [#333784]

1. Расширил бы название, объединив несколько разных названий,
т.к. некоторые люди путаются,  а таким образом мы показываем,
что это все одно и тоже.
Предлагаю:
"Сокращенный логический оператор "И" (AND) - &&"

Тоже самое для следующей темы:
4.3.2. Оператор || [#333784]
Предлагаю:
"Сокращенный логический оператор "ИЛИ" (OR) - ||"

---

2. Проверьте пожалуйста. Насколько я помню, Важным
в сокращенных операторах является проверка Левой (первой) части.
В частности, это позволяет ускорить работу этих операторов.
Предлагаю добавить это в начало описания пп 4.3.1, 4.3.2

**Comment by peterarsentev** [comment]
Добавил. Спасибо.
