### ISSUE TITLE
Неверный подсчет выполненных заданий

### ISSUE THREAD

**Issue by astarichenkov** [peterarsentev/job4j_features_bugs#713]
В блоке 2.1.2 Generic было три задания. 
Было выполнено 2 задания. После одно выполненное убрали, "Реализовать SimpleArray<T>".
При этом прогресс блока показывает 100%, выполнено 2/2, а по факту осталось 1/2.
![image](https://user-images.githubusercontent.com/60018477/130371528-aafa3101-86a9-4573-b8d7-005f7cccb590.png)
![image](https://user-images.githubusercontent.com/60018477/130371665-3664e063-c53c-4e28-9005-9a88c29d69c9.png)

**Comment by AlexeySapsay** [comment]
аналогичная ситуация

**Comment by peterarsentev** [comment]
Поправил.
