### ISSUE TITLE
Предложение переместить раздел с доп. литературой из конца изучения темы, в ее начало

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#718]
Предлагаю переместить раздел с доп. литературой из конца изучения темы, в ее начало. 

Так она будет максимально полезна и наверняка приживется в организме. В начале изучения темы есть сильная потребность и "голод" по качественной информации и дополнительная литература слихвой компенсирует потребность.

А когда тема уже относительно изучена, решены задания, рассмотрена теория по курсу, то в момент подготовки к ревью довольно трудно себя заставить еще что либо читать дополнительно, ибо есть обманчивое ощущение "глубокого" понимая материала.

Если Вам нравится предложение - ставим + или если не согласны - и конструктивный коммент поясняющий Вашу позицию

**Comment by AlexeySapsay** [comment]
![image](https://user-images.githubusercontent.com/13130875/130767584-de7cc3e0-3a8e-4a4b-b85b-d41bd3c62e1a.png)

[](https://job4j.ru/profile/exercise/44/task-view/305/solutionId/193690)

**Comment by AlexeySapsay** [comment]
https://job4j.ru/profile/exercise/44/task-view/305/solutionId/193690

**Comment by peterarsentev** [comment]
Не будем так делать. Это противоречит моей идеи обучения.
Смысл ее в том, чтобы дать минимум теории и сразу перейти к ее использованию.
Возможно нужно добавить больше примеров в уроки, но точно не теории.
