### ISSUE TITLE
1. Реализовать коллекцию Set на массиве [#996]

### ISSUE THREAD

**Issue by himax82** [peterarsentev/job4j_features_bugs#719]
В задании написано Для хранения использовать SimpleArray из прошлого задания
в прошлых задания таких не было, в телеграмме нашел что оказывается было такое задание 
Блок 1. Структуры данных и алгоритмы.
2. Generic
5.2.1. Реализовать SimpleArray<T>
у меня же такого задания нет вообще  изображения прикрепил
Или у меня такого задания нет или оно не отображается
![image](https://user-images.githubusercontent.com/80378936/130898070-cb26153c-29ca-4d33-952c-41ec84346332.png)
![image](https://user-images.githubusercontent.com/80378936/130898247-0c047245-4cbd-48ef-a655-87a1648a9b93.png)

**Comment by andreiHi** [comment]
посмотрите в 
Job4j/Уроки/2.1.3. List/1. Динамический список на массиве.

![image](https://user-images.githubusercontent.com/29897507/147339997-14229607-5d81-47d6-a440-75fe12050079.png)
