### ISSUE TITLE
Первый модуль

### ISSUE THREAD

**Issue by EliseevSergey** [peterarsentev/job4j_features_bugs#72]
Я считаю, что нужно сделать больше заданий на цикл while в первом модуле.
Из-за того, что в основном все на for, while плохо откладывается в голове.

**Comment by peterarsentev** [comment]
У нас есть раздел "Упражнения". Там много задач, как на циклы, так и на массивы. Для отработки можно их попробовать.
По опыту циклы while используется редко.
https://job4j.ru/edu/topic?topicId=14
