### ISSUE TITLE
Разлогинивает при переходе в задание 5.1.4

### ISSUE THREAD

**Issue by dmitriiibulgakov** [peterarsentev/job4j_features_bugs#720]
Разлогинивает при переходе в задание 5.1.4 FlatMap для Iterator

**Comment by dmitriiibulgakov** [comment]
Дополню. Разлогинивает в любом задании при попытке отправить ответ на проверку

**Comment by peterarsentev** [comment]
Нужно обновить кеш. Мы поменяли АПИ.
