### ISSUE TITLE
Ошибочный порядок уроков

### ISSUE THREAD

**Issue by Adzami** [peterarsentev/job4j_features_bugs#726]
Вообще это по всему курсу встречается, но обычно не так заметно. Однако в лямбдах уроки ссылаются друг на друга, и начинается некоторый бардак:

1. https://job4j.ru/profile/exercise/33
Уроки 1.2 и 1.3 используют лямбды, информация по которым находится в уроках 2.1 и 2.2. Более логичный порядок уроков должен быть
Анонимные классы   [#214142 #196930]
Лямбда   [#58165 #196970]
Лямбда блок   [#249208 #196972]
Функциональный интерфейс   [#247497 #196943]
Встроенные функциональные интерфейсы.   [#249209 #196967]
...

2. Урок "7. FP - функциональное программирование   [#310021]" явно ссылается на "ранее выполненный" урок "6. Тестовое задание из модуля коллекции Lite переделать на Stream API", который на деле находится через 8 (!) уроков от него. Да, урок ознакомительный, но столь явная ссылка намекает на нарушение порядка уроков. Нумерация, впрочем, намекает на то же самое.

3. https://job4j.ru/profile/exercise/32/task-view/234/solutionId/196572 - 1. Экзамен. Коллекции. [#10097 #196572]
Вопросы 13 - 17 в ходе предыдущих уроков не рассматриваются, вместо этого прописано, что эти вопросы (итератор, устройство коллекций) будут рассмотрены в следующем модуле. Единственный встреченный итератор находится в "упражнениях". Хотя найти ответы на все эти вопросы труда не составляет, тем не менее, явно нарушена преемственность - в модуле "Junior" мы только будем рассматривать вопросы, ответить на которые надо уже сегодня. Зачем они тогда в Junior, может быть, логичнее их или утащить оттуда в Стажера, или перенести экзаменационные вопросы по месту соответствующих уроков?

**Comment by peterarsentev** [comment]
Это все поправили. Спасибо.
