### ISSUE TITLE
Дублируется сообщение при нажатии кнопки "сохранить и перейти далее"

### ISSUE THREAD

**Issue by astarichenkov** [peterarsentev/job4j_features_bugs#728]
**Шаги воспроизведения:**
Нажать кнопку "отправить на проверку"
Набрать текст.
нажать "сохранить и перейти далее"

Произойдет переход к следующему заданию. Однако, внизу появится то же сообщение из прошлого задания.
После обновления странички сообщение пропадает.

**Comment by peterarsentev** [comment]
Поправили. Сервис еще не обновлял.
