### ISSUE TITLE
5.7. Ипотека [#156315]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#73]
Вопросы по заданию 5.7. Ипотека [#156315]
У некоторых учеников возникают проблемы с работой с разными типами данных,
(например здесь: https://t.me/job4j_trainee/69461).
Может быть имеет смысл привести все к double и при необходимости округлять?

**Comment by peterarsentev** [comment]
Спасибо. Поправил описание.
