### ISSUE TITLE
3.1. Создания репозитория и привязка к исходному коду.

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#731]
3.1. Создани**Е** репозитория и привязка к исходному коду.

Никаких настро**Е**к больше не делайте.

2. Загрузите картинку в комментарии к уроке с командой. - поменять на  - **2. Загрузите картинку с командой в комментарий к уроку.**

**Comment by AshleySunsine** [comment]
Исправлено
