### ISSUE TITLE
Job4j Уроки 1.2.0.0. Техническое задание. Tracker. 1. Техническое задание - проект Tracker

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#737]
Если от заказчика придет требование добавить новое действие, мы сделаем еще один объект на основании этого элемента и добавим его в систему без внесения, изменений.

Если от заказчика придет требование добавить новое действие, мы сделаем еще один объект на основании этого элемента и добавим его в систему без внесения изменений.

**Comment by staskorobeynikov** [comment]
исправлено
