### ISSUE TITLE
Job4j Уроки 1.2.1. Классы и объекты 1.7. Конструктор

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#741]
То, что стоит после оператора new и есть вызова конструктора класса Computer и в данном случае после имени класс мы ставим круглые скобки, что подчеркивает, что это метод.

То, что стоит после оператора new и есть **вызова** конструктора класса Computer**,** и в данном случае после имени **класс** мы ставим круглые скобки, что подчеркивает, что это метод.

**Comment by staskorobeynikov** [comment]
исправлено
