### ISSUE TITLE
Размытая формулировка задания

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#743]
![image](https://user-images.githubusercontent.com/13130875/132256111-5ec687af-4a0c-4810-bb0d-32629e99a2c5.png)
Не понятно как программа должна сообщать о нахождении дубликата.
1. выводит на консоль имя файла?
2. выводит на консоль путь?
3.  выводит имя и путь?
4. выводит сообщение что N файл дублирован?
Путь:
Уроки
2.2.1. Ввод-вывод
4.2. Поиск дубликатов

**Comment by peterarsentev** [comment]
Дописал описание. Спасибо.
