### ISSUE TITLE
2.4. Данные об осадках

### ISSUE THREAD

**Issue by tasker312** [peterarsentev/job4j_features_bugs#744]
[https://job4j.ru/profile/topics/29/task_code/195/solution/new_task](https://job4j.ru/profile/topics/29/task_code/195/solution/new_task)

Ошибка (не хватает буквы): При это**М** эти объекты содержат два поля:
Ошибка (не хватает запятой): 2. rainfall - количество осадков(,) которые выпали в этом городе за период наблюдения.
Ошибка (не хватает запятой): Необходимо реализовать метод так, чтобы в результате вернулся список объектов Info(,) в котором будет указано имя города наблюдения и общее количество осадков за период наблюдения. 

Непонятна сортировка элементов в expected листе, написанное решение через HashMap и merge() выводит правильные результаты, но в ином порядке

**Comment by staskorobeynikov** [comment]
По тексту исправлено.
Решайте с помощью computeIfPresent и все с порядком будет хорошо.
