### ISSUE TITLE
Job4j Уроки 1.2.1. Классы и объекты 3. Перегрузить метод max для трех чисел

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#746]
Более развернуто:

public double add(double first, double second, double third) {
    **double tmp = add(second, third);
    return add(first, tmp);**
}

Изменить код (чтобы курсант получал более наглядный пример, чтобы менторы не тратили время на рекомендации по исправлению, чтобы курсант не тратил время на исправления):
public double add(double first, double second, double third) {
    **return add(first, add(second, third));**
}

**Comment by staskorobeynikov** [comment]
указанный код в задании представлен выше
Закрываю.
