### ISSUE TITLE
Отсутствуют импорты упражнение "1. flatMap для итератора"

### ISSUE THREAD

**Issue by tasker312** [peterarsentev/job4j_features_bugs#749]
[https://job4j.ru/profile/topics/3/task_code/14/solution/new_task](https://job4j.ru/profile/topics/3/task_code/14/solution/new_task)

В упражнении отсутствуют базовые импорты, необходимые по условию:
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

**Comment by peterarsentev** [comment]
Добавил. Спасибо.
