### ISSUE TITLE
Неверный порядок упражнений 2.6 и 2.8 Сборка элементов

### ISSUE THREAD

**Issue by tasker312** [peterarsentev/job4j_features_bugs#750]
В упражнении [2.6. Сборка элементов. Сборка в произвольную реализацию Map](https://job4j.ru/profile/topics/3/task_code/68/solution/new_task) используется перегруженный toMap с 4мя аргументами и упоминается об использовании toMap с 3мя аргументами, который будет только в упражнении  [2.8. Сборка элементов. Сборка в Map, когда есть дубликаты](https://job4j.ru/profile/topics/3/task_code/66/solution/new_task)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
