### ISSUE TITLE
3.3.2. Mapping - Модели и связи. Машины и владельцы

### ISSUE THREAD

**Issue by nvavilov** [peterarsentev/job4j_features_bugs#752]
@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  @JoinTable(name = "history_owner", joinColumns = { 
  @JoinColumn(name = "driver_id", nullable = false, updatable = false) }, 
 inverseJoinColumns = { @JoinColumn(name = "car_id", 
 nullable = false, updatable = false) })
public Set<Driver> getDrivers() {
   return drivers;
}

поменять местами joinColumns и inverseJoinColumns

**Comment by peterarsentev** [comment]
@nvavilov А зачем их нужно поменять?

**Comment by peterarsentev** [comment]
Я посмотрел. Мы этот урок переписали. Поэтому закрываю.
