### ISSUE TITLE
2.2. Реализация класса StartUI. Вывод меню [#500743]

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#756]
В этом задании мы начнем разрабатывать консольное приложение для работы с классом **ru,job4j**.tracker.Tracker.

**Comment by veiuper** [comment]
Вспомним какие **методы методы** мы реализовали в классе Tracker:

**Comment by veiuper** [comment]
0. Add new **Item**

**Comment by veiuper** [comment]
"Add new **Item**", "Show all items", "Edit item",

**Comment by veiuper** [comment]
В уроке нет пункта меню "Update item", который упоминается в "Job4j Уроки 1.2.4. Полиморфизм 5.1. Тестирование. Подготовка данных.".

**Comment by veiuper** [comment]
Давайте рассмотрим ситуацию в нашем проекте "Трекер". У нас есть метод Start.replaceItem.

Класса Start нет, есть StartUI.

**Comment by veiuper** [comment]
1. Напишите тест на метод StartUI.replaceItem.

Нет такого метода.

**Comment by staskorobeynikov** [comment]
то, что касается этой задачи исправлено
