### ISSUE TITLE
3.1. Прерывание блокированной нити. [#408715] - Опечатки

### ISSUE THREAD

**Issue by VitaliyNasypov** [peterarsentev/job4j_features_bugs#76]
_Нить продолает свою работу._ 
**Нить продолжает свою работу.** 

_Этот схема является шаблоном. Запомните, если используются методы sleep, wait, но нужно в блоке catch вызвать прерывание._
**Эта схема является шаблоном. Запомните, если используются методы sleep, join или wait, то нужно в блоке catch вызвать прерывание.**

**Comment by andreiHi** [comment]
поправил спасибо
