### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 2.5. Реализация класса StartUI. Изменение заявки

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#761]
http://job4j.ru/api/images/imageTaskPreview?imageId=405
http://job4j.ru/api/images/imageTaskPreview?imageId=407
http://job4j.ru/api/images/imageTaskSource?imageId=409

На картинках должны быть даты создания заявок при их выводе в консоль.

**Comment by staskorobeynikov** [comment]
исправлено
