### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 2.6. Реализация класса StartUI. Удаление заявки

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#762]
http://job4j.ru/api/images/imageTaskPreview?imageId=412
http://job4j.ru/api/images/imageTaskPreview?imageId=414

На картинках должны быть даты создания заявок при их выводе в консоль.

**Comment by staskorobeynikov** [comment]
исправлено
