### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 2.8. Реализация класса StartUI. Вывод заявок по имени

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#763]
3. Выполняем вызов метода поиска заявок **введенному имени**, результат вызова записываем в переменную;

по введенному имени

**Comment by veiuper** [comment]
http://job4j.ru/api/images/imageTaskPreview?imageId=419

На картинке должны быть даты создания заявок при их выводе в консоль.

**Comment by staskorobeynikov** [comment]
исправлено
