### ISSUE TITLE
Работа CI Bot

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#765]
После выполнения задания
https://job4j.ru/profile/exercise/13/task-view/66
CI Bot прислал - Проект содержит ошибки
https://job4j.ru/profile/projects/project-view/6649

при том, что у меня в компе и на сайте все собирается нормально
<img width="621" alt="Test AttSortTest" src="https://user-images.githubusercontent.com/46091342/132889371-f73f103b-53e0-4c02-a999-c67ff87afd9c.png">
<img width="750" alt="Sborka" src="https://user-images.githubusercontent.com/46091342/132889387-9c39f550-7971-41e3-9788-90a020e70eaf.png">

Возможно настройки бота нужно как-то изменить и (или) согласовать их настройками на сайте

**Comment by peterarsentev** [comment]
@yarmail Можешь прислать номер решения? Я посмотрю по нему.

**Comment by YarTsin** [comment]
Посмотрите мою переписку со Стасом по темам
4.5. Отладка программы в IDEA [#159464 #194201]
5.4. Протеиновая диета [#156313 #204035]

Я полагаю, что бот слишком быстро начинает проверку, а происходит это так:

Ученик завершает задание и быстро отправляет (комит)ссылку на проверку
Бот не дожидаясь пока закончатся все работы на сайте отдает текущий результат.
Если предыдущий коммит был с ошибками, то бот показывает ошибку (время не прошло)
После этого ученик запускает проверки и у него все нормально - получается непонятная ситуация
и для куратора и для ученика.

По ощущениям предложил бы запускать бота через  5-15 минут после прихода ссылки на коммит ученика,
тогда сайт уже успеет проверить сборку и результат будет более разумный.

**Comment by peterarsentev** [comment]
Мы это поправили. Проблема была во времени. То есть время сборки у нас ограничено. если сборка идет больше то проверку не прошли. Но это мы убрали за счет разбивки всех модулей на отдельные проекты.
