### ISSUE TITLE
4.6.2. Switch - matcher [#334071 #200377] Помогите

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#766]
При выполнении задания 4.6.2. Switch - matcher [#334071 #200377]
Idea отказывается воспринимать лямбда подобный синтаксис

<img width="957" alt="15654" src="https://user-images.githubusercontent.com/46091342/132890194-20ff73fa-56cd-4705-98f6-ac13a43764c2.png">

По совету Стаса поставил 16 версию
<img width="583" alt="Настройка" src="https://user-images.githubusercontent.com/46091342/133141946-1dd432bc-4e44-4399-8e84-b2aa2b19210d.png">

Подправил пом
https://github.com/yarmail/job4j/blob/master/pom.xml

Ошибка не уходит

Большая просьба помочь разобраться, что нужно ещё настроить, чтобы появилась возможность
сделать это задание.

И описать эти настройки в задании - что посмотреть проверить, что настроить и т.д.

**Comment by YarTsin** [comment]
Дополню сообщение.
Проблему удалось решить установкой новой IDEA и настройкой уровня языка.

Полагаю, что проблема появилась, т.к. это единственное задание среди многих соседних,
где используются новые функции языка, и в старых Idea возникают непонятные ошибки,
они просто не понимают такой стиль написания.

Предлагаю задание дополнить следующей информацией:
Для выполнения данного задания нужна 
SDK не ниже 14 и свежая Idea с  
Project language level не ниже "14 - Switch expressions"

**Comment by staskorobeynikov** [comment]
сейчас при установке JDK мы требуем чтобы была версия не ниже 14. Поэтому такой проблемы не возникает.
Закрываю.
