### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 3.2. Зачем нужно приведение типов

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#768]
**Т.е. в мы** создавали объекты разных классов, при этом приводя все их к общему для каждого из этих классов типу Animal.

**Comment by veiuper** [comment]
В таком случае наш код становится более гибким, поскольку мы в любой момент можем заменить реализацию интерфейса не нарушив общую структуру нашего кода.

В таком случае наш код становится более гибким, поскольку мы в любой момент можем заменить реализацию интерфейса**,** не нарушив общую структуру нашего кода.

**Comment by veiuper** [comment]
А в том, что мы можем все что мы писали в этом задании переписать на интерфейс Animal, в который мы вынесем метод, который будет доступен всем животным, однако для каждого он будет иметь собственную реализацию.

А в том, что мы можем все**,** что мы писали в этом задании**,** переписать на интерфейс Animal, в который мы вынесем метод, который будет доступен всем животным, однако для каждого он будет иметь собственную реализацию.

**Comment by staskorobeynikov** [comment]
все исправлено
