### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 4.2. Статические методы.

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#769]
public class StartUI {

    public static void createItem(Input input, Tracker tracker) {
        System.out.println("=== Create a new Item ====");
        String name = input.askStr("Enter name: ");
        Item item = new Item(name);
        tracker.add(item);
    }

public class StartUI {

    public static void createItem(Input input, Tracker tracker) {
        System.out.println("=== Create a new Item ====");
        String name = input.askStr("Enter name: ");
        Item item = new Item(name);
        tracker.add(item);
        **System.out.println("Добавлена заявка " + item);**
    }

**Comment by staskorobeynikov** [comment]
поправил
