### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 4.2. Статические методы.

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#770]
1. Создайте статические методы createItem, replaceItem, deteleItem и тд.

Нет метода в StartUI, имеющего ключа "replaceItem" на текущий момент.

**Comment by veiuper** [comment]
Есть метод editItem, который использует replace класса Tracker.

**Comment by staskorobeynikov** [comment]
исправлено
