### ISSUE TITLE
Job4j Уроки 1.2.4. Полиморфизм 6. Manifest для проекта Tracker

### ISSUE THREAD

**Issue by veiuper** [peterarsentev/job4j_features_bugs#771]
Наш проект соберется успешно, при этом будет в дереве **проект** создана папка target:

**Comment by veiuper** [comment]
В которой будет добавлен файл с расширением jar который мы можем запустить и использовать его в других местах.

В которой будет добавлен файл с расширением jar**,** который мы можем запустить и использовать его в других местах.

**Comment by staskorobeynikov** [comment]
исправил
