### ISSUE TITLE
Критика по курсу

### ISSUE THREAD

**Issue by HEAVYxRAIN** [peterarsentev/job4j_features_bugs#773]
Не хватает пару уроков по навигации и горячим клавишам в IntelliJ IDEA и Github.

**Comment by MaratKhatipov** [comment]
[](url
[ReferenceCardForMac.pdf](https://github.com/peterarsentev/job4j_features_bugs/files/7983579/ReferenceCardForMac.pdf)
[ReferenceCard.pdf](https://github.com/peterarsentev/job4j_features_bugs/files/7983580/ReferenceCard.pdf)
)

KEYMAP для Intellj Idea

**Comment by peterarsentev** [comment]
Взяли в работу.
