### ISSUE TITLE
Ошибка в уроке

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#778]
Противоречие в формулировке задания. Дан файл csv, а запускается командной строкой txt
![image](https://user-images.githubusercontent.com/13130875/133069107-5a8eae0e-dbc0-424a-806d-9529d4b8bc96.png)
Джуниор
Уроки
2.2.1. Ввод-вывод
7. Scanner

[Урок[](url)](https://job4j.ru/profile/exercise/45/task-view/786)

**Comment by staskorobeynikov** [comment]
исправлено
