### ISSUE TITLE
Некорректно отображается progress bar упражнений

### ISSUE THREAD

**Issue by dheaven92** [peterarsentev/job4j_features_bugs#779]
Progress bar имеет значение 100% в то время, как не все 100% упражнений выполнены. См. скриншот:
![progress-bar-bug](https://user-images.githubusercontent.com/12449870/133128234-f78aa92f-db6e-43af-b992-c357a6642063.PNG)

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by peterarsentev** [comment]
Поправили.
