### ISSUE TITLE
0. Checkstyle с Maven [#257606]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#780]
Возможно имеет смысл обновить это задание,
как сделано здесь:
https://github.com/peterarsentev/job4j_elementary/blob/master/pom.xml

**Comment by YarTsin** [comment]
А также проверить pom всех проектов, возможно где-то, что-то уже пора обновить

**Comment by AshleySunsine** [comment]
Исправлено.
