### ISSUE TITLE
pom.xml

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#781]
По поводу файла
https://github.com/peterarsentev/job4j_elementary/blob/master/pom.xml
Если я правильно понимаю Гитхаб просит обновить junit до версии 4.13.1
<img width="609" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/133140663-01decc11-2103-4a39-a574-b36b723dec3c.png">

Ссылка на сообщение
https://github.com/yarmail/job4j/security/dependabot/pom.xml/junit:junit/open

**Comment by peterarsentev** [comment]
Верно. В курсе везде заменил 4,12 на 4,13,1
