### ISSUE TITLE
2. Тестовое задание. Hibernate - используется неактуальное решение

### ISSUE THREAD

**Issue by kalenikov** [peterarsentev/job4j_features_bugs#783]
В задании написано "использовать библиотеку apache fileuppload".
Во-первых, название библиотеки написано неправильно, во-вторых в Servlet API есть нативные инструменты для загрузки файлов.

https://stackoverflow.com/questions/2422468/how-to-upload-files-to-server-using-jsp-servlet

**Comment by peterarsentev** [comment]
Спасибо. Мы заменили блок на Spring boot + thymeleaf. Там все из коробки идет без этого раритета.
