### ISSUE TITLE
2.1.3. List / 0. Внутри ArrayList и LinkedList

### ISSUE THREAD

**Issue by tasker312** [peterarsentev/job4j_features_bugs#785]
_Пропущено слово:_ В основе работы обоих методов лежит метод E unlink(Node<E> x), различия лишь состоят в том, что удаление по значению предполагает первичный **ПОИСК?** индекса удаляемого значения и только потом происходит удаление, которое заключается в уже упомянутой ранее "перелинковка" ссылок на узлы:

**Comment by staskorobeynikov** [comment]
исправлено
