### ISSUE TITLE
2. Создать контейнер на базе связанного списка [#409305]

### ISSUE THREAD

**Issue by Just1kz** [peterarsentev/job4j_features_bugs#79]
Отсутствует каркас с тестами и на метод E get(int index); - требуется комментарий относительно реализации, со старта когда ты знаешь что в двусвязном списке у элемента нету индекса, а 2 ссылки и Value не ясно, что требуется перебор со счётчиком и return Value.

**Comment by andreiHi** [comment]
поправили
