### ISSUE TITLE
1. Maven web проект. [#276373 #204205] - избыточное задание

### ISSUE THREAD

**Issue by georgRusanov** [peterarsentev/job4j_features_bugs#795]
Уровень : 3. МидлКатегория : 3.2. Servlet JSP
В проекте 1. Техническое задание - проект "Работа мечты" [#260362 #202822] требуется создать репозиторий и добавить maven сборку.
В последующем задании 1. Maven web проект. [#276373 #204205] создать maven web проект и подгрузить код в гит.

Первое задание вводит в заблуждение, так как там создаем обычный веб проект, а не веб. Кажется, что оно избыточно и можно его удалить.

**Comment by peterarsentev** [comment]
Заменили. Спасибо.
