### ISSUE TITLE
Ошибка в описании

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#796]
![image](https://user-images.githubusercontent.com/13130875/134050213-947053d1-a6f4-429f-b429-1af3a273f25f.png)
Во всем тексте, и примерах кода не указаны строки, отмеченные красным цветом.

[https://job4j.ru/profile/exercise/4/task-view/809](url)
Путь:

Уроки
2.1.3. List
0.2. Внутри ArrayList

**Comment by AshleySunsine** [comment]
Исправлено.
