### ISSUE TITLE
3.2. Удаление моделей из массива. [#411983] 

### ISSUE THREAD

**Issue by Alexey710** [peterarsentev/job4j_features_bugs#8]
во втором тесте в уроке ошибка. Вместо Milk должен быть Bread.

**Comment by peterarsentev** [comment]
@Alexey710  Не вижу ошибки. Мы создали массив на два элемента и удаляем второй. Индекс у него 1. Останеться Milk.
    
    @Test
    public void whenDropLast() {
        Product[] products = new Product[2];
        products[0] = new Product("Milk", 10);
        products[1] = new Product("Bread", 4);
        Product[] rsl = ShopDrop.leftShift(products, 1);
        assertThat(rsl[0].getName(), is("Milk"));
        assertThat(rsl[1], is(nullValue()));
    }
