### ISSUE TITLE
Инструмент для быстрой отправки опечаток.

### ISSUE THREAD

**Issue by Danil0101** [peterarsentev/job4j_features_bugs#805]
Чаще всего видя опечатку мне, да и наверняка многим учащимся лень создавать по этому поводу тему.
На мой взгляд было бы удобнее, если бы был внедрен инструмент, позволяющий выделить опечатку, и при помощи кнопки, или горячих клавиш сразу отправить обращение.
Нашел вот такой пример: http://orphus.ru/

**Comment by peterarsentev** [comment]
Спасибо. Мы это правим.
