### ISSUE TITLE
Работа рейтинга

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#811]
Странно, что у вас два одинаковых имени занимают два места в рейтинге,
Или это полные тезки?
<img width="705" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/134554597-01c1710e-46a7-48a2-9e66-42595cb229b4.png">

**Comment by YarTsin** [comment]
Вот ещё сегодняшний свежий пример, может это фронт так криво выдает?
<img width="904" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/134764340-0005955c-2576-464a-b050-7a60df7ad240.png">

**Comment by YarTsin** [comment]
Вот сегодня и свое имя дважды увиде
<img width="940" alt="Screenshot_2" src="https://user-images.githubusercontent.com/46091342/136335327-12afa365-1d03-4487-a4cd-eed543dcac39.png">

**Comment by peterarsentev** [comment]
Взяли в работу.
