### ISSUE TITLE
6.5.1. Поиск минимального числа в массиве. [#179803 #207893]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#819]
по итогам переписки со Стасом по этой теме предложил бы 
внести изменения в задачу и 
начинать проверку с 1, т.к. нулевой элемент 
уже присвоен 
int min = array[0];
и проверять его не надо.
<img width="454" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/134763969-c6a89b77-34da-4200-9a5d-469c85965e52.png">

**Comment by staskorobeynikov** [comment]
исправлено
