### ISSUE TITLE
Опечатка в упражнении

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#824]
![image](https://user-images.githubusercontent.com/13130875/134813655-458867bc-ed28-48e2-9ae1-e79a2919b0eb.png)

[https://job4j.ru/profile/exercise/52/task-view/341](url)
Нет пунктов

 Залить скрипт в репозиторий.

 Перевести ответственного на Петра Арсентьева.

**Comment by staskorobeynikov** [comment]
исправлено
