### ISSUE TITLE
1. Динамический список на массиве. [#158 #207516] опечаток

### ISSUE THREAD

**Issue by tutbora** [peterarsentev/job4j_features_bugs#826]
В последнем тесте в названии, говорится про удаление, а проверяется добавление:

@Test(expected = ConcurrentModificationException.class)
    public void whenRemoveAfterGetIteratorThenMustBeException() {
        Iterator<Integer> iterator = list.iterator();
        list.add(0);
        iterator.next();
    }

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
