### ISSUE TITLE
2.4. Данные об осадках не проходит тест.

### ISSUE THREAD

**Issue by traindriver-m** [peterarsentev/job4j_features_bugs#827]
В решенном задании в List объекты заносятся в порядке их следования в исходном списке  а в expected листе в тесте они отсортированы по непонятному принципу - т.е.  после решения все объекты есть, но из за того, что расположены не в том порядке, тест не проходит, упражнение считается не решенным.  Необходимо или тест поправить или в условии задания отразить необходимый порядок сортировки.  Также неплохо бы поправить описание, для понимания задачи. А то условие до конца понятно лишь после просмотра теста. Вместо " ... чтобы в результате вернулся список объектов Info в котором будет указано имя города наблюдения и общее количество осадков **за период** наблюдения ... ". Написать "... за **ВСЕ ПЕРИОДЫ** набдюдения...".

**Comment by peterarsentev** [comment]
Поправил.
