### ISSUE TITLE
В списке уроков 1.2.6. ООА\П неправильно отображается количество выполненных уроков. 

### ISSUE THREAD

**Issue by traindriver-m** [peterarsentev/job4j_features_bugs#828]
По факту там есть 3 выполненных задания из 3, но отображается вот так
![2021-09-27_14-19-40](https://user-images.githubusercontent.com/77443750/134899188-3c4f41e7-be54-4d6f-a158-b3a496b1633d.png)
.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
