### ISSUE TITLE
CI Bot: Нарушения по правилам Job4j CQP

### ISSUE THREAD

**Issue by rsitdikov** [peterarsentev/job4j_features_bugs#829]
Выдается сообщение об ошибке при отправке задания. Лог содержит строку - "Нарушение - Код содержит однострочные комментарии. Их нужно заменить на JavaDoc." При этом, в коде комментариев нет, но присутствует присваивание переменной типа String значения, содержащего последовательность "//",

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
