### ISSUE TITLE
Id разных типов в 1. Spring boot repository [#2095 #209018]

### ISSUE THREAD

**Issue by rmk1409** [peterarsentev/job4j_features_bugs#830]
В модели id int, в репозитории long, нужно привести к одному какому - то типу.

public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

public interface PostRepository extends CrudRepository<Post, Long> {

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
