### ISSUE TITLE
Возможно удалить избыточный вызов класса Class.forName("org.postgresql.Driver")

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#832]
Class.forName("org.postgresql.Driver");

In the past, it was required to load a JDBC driver before creating a java.sql.Connection. Nowadays, when using JDBC 4.0 drivers, this is no longer required and Class.forName() can be safely removed because JDBC 4.0 (JDK 6) drivers available in the classpath are automatically loaded.

Упражнение:
0. JDBC [#6863 #209482]

[https://job4j.ru/profile/exercise/55/task-view/344](url)

**Comment by peterarsentev** [comment]
Пока оставим. Он через раз работает у учеников.
