### ISSUE TITLE
Ошибка в рисунке в порядке бит

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#833]
Путь:
0. Hash структуры
Ошибка в рисунке. 7 бит вместо 8 в старших разрядах, что запутывает. Общее количество бит не верное, из-за ошибки сдвиг на n бит отображается не правильно
[https://job4j.ru/profile/exercise/42/task-view/289](url)
![image](https://user-images.githubusercontent.com/13130875/135055714-6ef6503f-7f16-40b7-a190-2c060050e7a2.png)

**Comment by itfedorovsa** [comment]
Исправлено. Не отображался только крайний 0 или 1, на отображение остальных битов не влияло. Спасибо!
