### ISSUE TITLE
Нет цветовой разметки кода в половине урока

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#835]
![image](https://user-images.githubusercontent.com/13130875/135091445-66b57c30-6612-4a9b-8e92-b560de585251.png)

[https://job4j.ru/profile/exercise/55/task-view/345](url)

Путь
Job4j
Уроки
2.3.5. JDBC
0.1. Statement

**Comment by peterarsentev** [comment]
Спасибо. Поправил.
