### ISSUE TITLE
Прописан но не использован ResultSet

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#836]
![image](https://user-images.githubusercontent.com/13130875/135119728-f128de1f-0f83-4167-b513-4026c351638a.png)
[https://job4j.ru/profile/exercise/55/task-view/345](url)
Путь:
Уроки
2.3.5. JDBC
0.1. Statement

В классе StatementDemo говорится про использование ResultSet, но в примере он не использован. Возможно его нужно прописать вместо var? Или я не найду, где он содержится

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
