### ISSUE TITLE
CI Bot: Нарушения по правилам Job4j CQP

### ISSUE THREAD

**Issue by grum1972** [peterarsentev/job4j_features_bugs#837]
Если в  JavaDoc  стоит //TODO CI Bot выдает ошибку про комментарии

**Comment by peterarsentev** [comment]
И верно, что бот такое вывод. Не должно быть такого. Это осталось в курсе?

**Comment by grum1972** [comment]
Да . Это было в играх по-моему я правда уже не помню

**Comment by peterarsentev** [comment]
В коде убрали. Спасибо.
