### ISSUE TITLE
CI Bot: предложение по дополнению урока 3.4. Кто такой - CI Бот?

### ISSUE THREAD

**Issue by MrShmiTT** [peterarsentev/job4j_features_bugs#838]
Предлагаю дополнить урок скриншотами с примерами ссылок страниц бота "Коммит" и "Лог", чтобы было понятно, где искать, что нужно исправлять. Я долго не мог понять где искать проблему ошибки.

**Comment by peterarsentev** [comment]
Спасибо. Добавил.
