### ISSUE TITLE
 Уроки 1.1.5. Циклы

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#841]
Может быть имеет смысл к Теме Циклы добавить Рекурсию,
как частный случай циклов.
(если ещё где-то не добавляли, в поиске не нашёл)
Тема периодически вплывает, мне кажется её полезно будет знать.
В качестве неплохого примера, вот здесь смотрел
https://www.youtube.com/watch?v=9Hs7DuIJ3LE

**Comment by peterarsentev** [comment]
Рекурсия - это плохой вариант. Все нужно заменять массивами. 
Я в курсе уже добавил лишнего. Теперь нужно это чистить. 
Мы стараемся дать только нужные инструменты, а не справочник по языку Java.
Ярослав. Тебе отдельное спасибо. ты вносишь много идей для размышления.
