### ISSUE TITLE
2. GC. Out Of Mem. Тестовое задание. [#504790 #209827]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#843]
1. 
Ошибка в описании названия базы данных
на странице: https://github.com/peterarsentev/job4j_articles
"Программа генерирует статьи из слов. Слова и статьи хранятся в базе данных HQLDB, хранимой в виде файла."
Вероятно БД называется HSQLDB.

2. 
Предлагаю добавить предупреждение о том, 
не сохраняли, удаляли после каждого запуска и 
не комитили все файлы из папки db-dir, такие как
 articles.lck
 articles.log
 articles.properties
 ...
иначе они могут получить лишние ошибки и сохранить очень большие файлы.

3.
Также сообщаю, что генерация 40 тыс статей заняла более 1,5 гб
Возможно имеет смысл предупредить ученика, что полная генерация
займет довольно много места или какие-то правки внести в задачу

4. 
Не прошёл проверку бота (по однострочным коментам)
Возможно имеет смысл обновить проверку Чекстайл, чтобы
эту ошибку я мог получить ещё до отправки на проверку.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
