### ISSUE TITLE
Предложение по оптимизации размещения предложения литературы ученикам

### ISSUE THREAD

**Issue by Futsey** [peterarsentev/job4j_features_bugs#844]
Закончил блок "Базовый синтаксис". В самом конце обнаружил прекрасный блок с "Дополнительной литературой" и само собой напрашивается решение об оптимизации этого блока. А именно разбиение и пошаговое размещение, согласно тематике параграфов.

_Дело в том, что эта информация как воздух необходима перед началом уроков (как минимум для тех, кто абсолютный null, как я, например). Это можно рекомендовать для начала просто прочесть, даже не прибегая к практическому закреплению. А практику оставить на закрепление материала после прохождения образовательного блока._

**ПРИМЕР:**

[### 1.1.2. Тип данных](https://job4j.ru/profile/exercise/6)

### 0. Полезно почитать

**_Типы данных:_**
 
           а) Java 8, Полное руководство - Герберт Шилдт. Глава 3. Типы данных (стр. 75 - 93)
           б) Библиотека профессионала. Java. Том 1. Основы - Кей Хостманн, Гари Корнелл.  Глава 3. Типы данных (стр. 61 - 75)

**_Операции (арифметические, поразрядные, логические):_**   
             
           а) Java 8, Полное руководство - Герберт Шилдт. Глава 4. Операции (стр. 103 - 123)
           б) Библиотека профессионала. Java. Том 1. Основы - Кей Хостманн, Гари Корнелл.  Глава 3. Операции (стр. 69 - 76

[### 1.1.4. Оператор ветвления](https://job4j.ru/profile/exercise/13)

### 0. Полезно почитать

**_3. Операторы условия:_**
 
           а) Java 8, Полное руководство - Герберт Шилдт. Глава 5. Условные операторы (стр. 125 - 133)
           б) Библиотека профессионала. Java. Том 1. Основы - Кей Хостманн, Гари Корнелл.  Глава 3. Условные операторы: if (стр. 97 - 100), swich (стр. 108 - 111)

**Comment by YarTsin** [comment]
Есть такое мнение, что Стажер сейчас довольно хорошо расписан, поэтому лучше прогнать побыстрее практику, а потом закрепить теорией, где было уж совсем непонятно. Заданий довольно много и чтобы сильно не застревать, лучше не тормозить. Поэтому и литература поставлена в конец. (ИМХО)

**Comment by peterarsentev** [comment]
Спасибо за отзыв. Мы стараемся добавить сколько теории, чтобы ученик мог сделать практику. 
Иначе ученик начинает читать книги, а толку от этого нет. Поэтому теория в конце. 
Если ученик не может сделать задание, то я прошу написать лично мне, чтобы я мог понять причину.
