### ISSUE TITLE
Строка поиска

### ISSUE THREAD

**Issue by Kotovalova** [peterarsentev/job4j_features_bugs#845]
Было бы очень удобно, если б поиск работал не только по названиям Уроков, но и искал совпадения в тексте.

**Comment by AlexeySapsay** [comment]
Поддерживаю.
Т.к сайт содержит очень много полезного материала и примеров решения задач, кода, часто приходится возвращаться к коду, но поиск ручками очень не удобен. Было бы очень круто, если через строку поиска можно было искать код и текст по всему сайту, уроками и заданиям.

**Comment by YarTsin** [comment]
Поддерживаю

**Comment by peterarsentev** [comment]
Взяли в работу.

**Comment by peterarsentev** [comment]
Добавили.
