### ISSUE TITLE
0. Что такое деревья? [#4956]

### ISSUE THREAD

**Issue by tasker312** [peterarsentev/job4j_features_bugs#846]
[https://job4j.ru/profile/exercise/43/task-view/299](https://job4j.ru/profile/exercise/43/task-view/299)
Опечатка: В случае с бинарным **дерево** (-> **_деревом_**) родительский узел может иметь от 0 до 2 **потоком** (-> **_потомков_**)

**Comment by AshleySunsine** [comment]
Исправлено.
