### ISSUE TITLE
Конфликт работы CI Bot с заданиями и javadoc

### ISSUE THREAD

**Issue by george129** [peterarsentev/job4j_features_bugs#847]
- 0. Что такое обобщенные типы (generics) [#4952 #148454]
В задании указано:"Он содержит ошибки компиляции, вам **необходимо их поправить, закомментировав строки** которые их вызывают.", **но CI Bot не пропускает решение** из-за наличия **однострочных комментариев**.

- Также CI Bot считает однострочными комментариями **"//"** **внутри многострочного комментария или javadoc**.

**Comment by peterarsentev** [comment]
Поправил описание. Спасибо.
