### ISSUE TITLE
4. Виды тестов для TDD [#504793]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#850]
<img width="696" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/135728396-12a00175-e155-4409-a139-2f279f8a087f.png">

**Comment by YarTsin** [comment]
Еще Предложил бы добавить к теме или выделить в отдельную тему.

Периодически возникает вопрос и спор с разработчиком у заказчика о том, 
нужно или не нужно проводить тестирование на этапе разработки. 
Некоторые заказчики говорят о том, что нам не нужно тестирование, 
не нужно на это время тратить,  да и денег на это лишних нет.

Довод в пользу как можно более раннего проведения тестирования,
на всех этапах, в том числе написания кода разработчиком.
Чем раньше найти и исправить ошибку, тем она встанет дешевле в итоге.
Например:
http://okiseleva.blogspot.com/2018/03/blog-post_59.html

Простой пример - при неполном, недостаточном или позднем тестировании
после выпуска готовых автомобилей могут отозвать всю партию
для переделки каких-то компонентов (много примеров из истории), 
что будет на порядок дороже чем плановое, 
полное и разностороннее тестирование на всех этапах
производства.

**Comment by YarTsin** [comment]
Возможно, если мы говорим о методиках разработки ПО, 
следовало бы начать с классической методики
Test Last Development (TLD), а уже потом переходить 
к TDD, BDD, и ATDD

**Comment by peterarsentev** [comment]
Спасибо. Добавил.
