### ISSUE TITLE
1.3. Вызов метода с аргументами. [#166086]

### ISSUE THREAD

**Issue by Futsey** [peterarsentev/job4j_features_bugs#851]
В примере задания мы в круглых скобках указываем переменные, с которыми хотим работать. В данном случае String lirycs,
![image](https://user-images.githubusercontent.com/89212538/135740667-675722dd-c1c8-436c-91fe-d2f910b35377.png)

но в методе мейн потом указываем переменную song, которая по логике должна быть той самой lirycs.
![image](https://user-images.githubusercontent.com/89212538/135740692-09589a8e-01bf-45d2-997d-e232e918d920.png)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
