### ISSUE TITLE
Тестовое задание - проект "Pooh JMS" - Ошибка в тесте!

### ISSUE THREAD

**Issue by CyberfuzZ-Apps** [peterarsentev/job4j_features_bugs#853]
Уровень : 3. Мидл. Категория : 3.1. Multithreading. Топик : 3.1.7. Контрольные вопросы.
В тексте задания, где написаны тесты на класс Req (ReqTest), в тесте whenGetMethod() ошибка - проверяем на GET, а в assert - POST.
![Снимок экрана 2021-10-04 в 16 24 37](https://user-images.githubusercontent.com/81745378/135976228-5e405605-83db-4021-91b5-eb4b0e37345b.png)

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
