### ISSUE TITLE
1.2. Начало обучения [#1150 #4034]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#854]
Я бы сейчас так сформулировал оценку времени обучения:

Если вы сможете дойти до решения 3-4 задач в день,
есть шанс, что вы потратите на весь курс меньше года.

Мне кажется курсантов надо заранее готовить к тому, что их может ожидать,
тогда они возможно не будут тратить столько времени, сколько я на это потратил

**Comment by peterarsentev** [comment]
Я уже оставил идею оптимизации времени, мы только правим материал курса, чтобы ученики не испытывали лишней сложности. Поэтому оставим, как есть. полгод - год ).
