### ISSUE TITLE
Опечатка в упражнении. Класс не расширяет, а реализует интерфейс

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#856]
![image](https://user-images.githubusercontent.com/13130875/136030122-73e5f570-6643-4fdc-95b3-2eb26c1ac986.png)

Расширять- extends
Реализовать- implements

Уроки
2.3.5. JDBC
2. Трекер SQL
[https://job4j.ru/profile/exercise/55/task-view/348](url)

**Comment by YarTsin** [comment]
Возможно формально вы правы,  но может быть здесь имелось ввиду смысловая нагрузка?
Сам по себе интерфейс ничего не может, а класс расширяет его возможности?

**Comment by AlexeySapsay** [comment]
Согласен с вами, интерфейс только предоставляет методы, который реализует класс его имплементирующий. Но это не расширение поведения, как я его понимаю.

Расширение- extends поведения идет для класса наследующего базовый класс. Т.е у базового есть урезанное, общее поведение, а наследник оверрайдит методы базового класса и добавляет свои, тем самым делая поведение наследника более специализированным. Т.е конкретное поведение есть в базовом  и его расширили. 
А у интерфейса конкретного поведения нет(не будем трогать default методы), его предоставляет имплементирующий класс.
Вот, немного путанно, но как понимаю. Возможно не верно, если что- поправьте.

**Comment by AshleySunsine** [comment]
Да, вводит в заблуждение. 
Исправлено.
