### ISSUE TITLE
1. Отчеты. [#850]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#859]
1. 
В условиях задачи тест падает с ошибкой
java.lang.AssertionError:
Относительно кода в тесте 
лишняя точка с запятой после Salary и 
лишняя строка
.append(System.lineSeparator());
Предлагаю согласовать  класс ReportEngine
и тест к нему, чтобы не плодить ошибок,
И так сложно.

-----

2.
Вывел на консоль посмотреть, что выдает тест,
с датой что-то страшное, с десяток строк непонятного
текста, начинающегося на 
java.util.GregorianCalendar[time=1633453181967,areFi....
Довольно сильно мешает сосредоточится на деле.
Предлагаю или убрать этот параметр или сделать его проще как-то.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
