### ISSUE TITLE
2. Сервис - UrlShortCut [#13799 #212726] Противоречат пункты друг другу.

### ISSUE THREAD

**Issue by rmk1409** [peterarsentev/job4j_features_bugs#860]
В з-нии 2. Сервис - UrlShortCut [#13799 #212726] 2й и 4й пункты противоречат друг другу

![image](https://user-images.githubusercontent.com/7755430/136173393-84e2cf5c-718e-4aa4-b334-0fc341b21087.png)

![image](https://user-images.githubusercontent.com/7755430/136173349-5ddd0323-2690-4e95-9d97-d46727c318f9.png)

**Comment by peterarsentev** [comment]
Убрал этот пункт. Спасибо.
