### ISSUE TITLE
0. Принцип открытости закрытости [#4914 #213038]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#861]
Поправьте меня если я не прав.
Одно из решений вопроса OCP - шаблон Стратегия.
Если это так - предлагаю внести информацию об этом 
в урок, дабы по смыслу привязать одно к другому,
так лучше можно их запомнить

**Comment by peterarsentev** [comment]
Все шаблоны проектирования - это реализации принципов SOLID. 
Декоратор тоже расширяет без изменения основного класса. 
Конкретно в нашем примере используется стратегия, но мы про это и написали.
