### ISSUE TITLE
Интересный прием с id объекта

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#863]
Нашёл, как мне кажется, интересный простой прием 
который показывает соединение статики и динамики классов и объектов,
до этого в курсе не встречал.

При создании объекта можно его самого заставить создавать себе уникальный 
порядковый номер например так

public final class CarBase implements Car {
    private static int nextId = 1;  // статическое поле для всех объектов
    private final String name;
    private final String sign;
    private final int size;
    private final int id = nextId++; // динамическое поле для каждого объекта
    
    Может быть имеет смысл добавить это в курс?
    Еще пример с текстом занятия можно посмотреть здесь:
    
    http://wiki.asistech.org/index.php/Статические_поля_и_методы

**Comment by peterarsentev** [comment]
Это можно, но все статические поля ведут к проблемам. Поэтому не будем их использовать.
