### ISSUE TITLE
Темная тема

### ISSUE THREAD

**Issue by Alexei-kor** [peterarsentev/job4j_features_bugs#867]
Рассмотрите пожалуйста возможность сделать темную тему сайта. 
github, idea, даже яндекс-переводчик - все в темной теме (когда же учиться, как не по ночам)

**Comment by peterarsentev** [comment]
Мы раньше делали его. Отказались от него.
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en 
Есть такое решение для сайта.
