### ISSUE TITLE
При обновлении страницы слетает сессия и сайт запрашивает логин с паролем

### ISSUE THREAD

**Issue by george129** [peterarsentev/job4j_features_bugs#868]
Если обновить страницу, пропадает сессия, но без обновления можно спокойно переходить между внутренними ресурсами, делать комментарии, отправлять решения и т.д. и никаких признаков умирания сеанса нет. Эта особенность может быть заметна, наверное, только по прошествии значительного времени после входа.

**Comment by peterarsentev** [comment]
Есть такое поведение. Сессия у нас бессрочная, но когда мы обновляем клиента, то браузер считает его новым контентом и удаляет ключ. Это связано со обновлением.
