### ISSUE TITLE
1. Загрузка и скачивание файла. 

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#870]
Уровень : 3. Мидл Категория : 3.2. Servlet JSPТопик : 3.2.5.1. Form

[](![image](https://user-images.githubusercontent.com/73285357/137769398-523b89e3-b14a-40a9-99e1-3b67bfab33d8.png))

ОБРАТИТЕ внимание - общался с несколькими людьми -у все одно и тоже.
при копипасте кода и вставке его в IDEA буква -с- идет на русском языке.  Не у все, но я нашел 3 человек. 
Код при компиляции встает колом. ошибка не очевидна. может скомпиливаться и подняться сервер и только потом упасть. Ошибка указывает совсем не на то, что в действительности.
При замене ее на -с- на анг раскладке происходит загрузка. поправьте в самой таске это момент
[https://prnt.sc/1wmmavp](url)
вот в этой части кода
public class UploadServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        List<String> images = new ArrayList<>();
        for (File name : new File("с:\\images\\").listFiles()) { //тут путь вставляется первая буква на русс
            images.add(name.getName());
        }

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
