### ISSUE TITLE
Runtime Environment bug

### ISSUE THREAD

**Issue by laruh** [peterarsentev/job4j_features_bugs#872]
Бот падает с данной ошибкой. Приходится делать небольшие изменения в файле (добавить пробел) и отправлять новый коммит. И тогда бот принимает практически тот же файл.
![Screenshot 2021-10-19 at 23-35-59 Job4j](https://user-images.githubusercontent.com/52405288/137954020-be76b59c-d6b0-40ff-adac-3b80c0fff5f9.png)

**Comment by peterarsentev** [comment]
Временно поправили.
