### ISSUE TITLE
1.8. Состояние объекта [#167388]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#873]
Может быть это очень наивно и для новичков, 
но мне кажется очень важным, т.к. в дальнейшем мы только и делаем,
что меняем либо состояние объектов, либо их поведение.

Вначале урока я бы предложил добавить такую фразу - определение.

Любой объект может обладать двумя основными характеристиками. 
Состояние объекта - некоторые данные, которые хранит объект. 
Поведение объекта - действия, которые может совершать объект.
Для хранения состояния объекта в классе применяются поля или переменные класса.
Для определения поведения объекта в классе применяются методы.

а далее уже приводить практические примеры

**Comment by peterarsentev** [comment]
Спасибо. Но мы это во всем курсе говорим. Не думаю, что еще текст добавит ясности ).
