### ISSUE TITLE
Мидл. Многопоточность. 4. CompletableFuture

### ISSUE THREAD

**Issue by AshleySunsine** [peterarsentev/job4j_features_bugs#874]
"Данный метод используется, если действия зависимы. Т.е. сначала должно выполниться одно, а только потом другое. Например, вам принципиально, чтобы сын **сначала выбросил мусор**, а только **потом сходил за молоком**. В ситуации можно записать так"
public static void thenComposeExample() throws Exception {
    CompletableFuture<Void> result = buyProduct("Молоко").thenCompose(a -> goToTrash());
    iWork();
}

По результатам получается наоборот: 
Сын: Мам/Пам, я пошел в магазин
Вы: Я работаю
Вы: Я работаю
Вы: Я работаю
Вы: Я работаю
Вы: Я работаю
Сын: Мам/Пап, я купил Молоко
Сын: Мам/Пам, я пошел выносить мусор
Вы: Я работаю
Вы: Я работаю
Вы: Я работаю
Вы: Я работаю
Вы: Я работаю
Сын: Мам/Пап, я вернулся!
Сначала купил молоко, потом выбросил мусор

**Comment by peterarsentev** [comment]
Поправил. Думал, там ошибка в методах, А там ошибка в описании и вызовах. )
