### ISSUE TITLE
0. Join [#6862]

### ISSUE THREAD

**Issue by tasker312** [peterarsentev/job4j_features_bugs#875]
[https://job4j.ru/profile/exercise/53/task-view/342](https://job4j.ru/profile/exercise/53/task-view/342)

_Ошибка_: Даны две сущности, представленные в таблицах departments и **emploers**. Отношение one-to-many. В таблицах только поле name.

Кажется правильнее использовать employees (сотрудники)

**Comment by peterarsentev** [comment]
Спасибо. Задание переписали.
