### ISSUE TITLE
2.2. Рефакторинг - Площадь треугольника. [#122642 #218673]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#876]
Это же вроде разные проекты, может быть убрать отсюда Tracker?
<img width="515" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/138490088-7d6ce7b8-e66e-4e6c-b7c1-105289c8a898.png">

**Comment by peterarsentev** [comment]
Тут новый класс нужно сделать. Именно в этом проекте.
