### ISSUE TITLE
4. Переопределение [#174890]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#877]
Поправьте меня, если я не прав.
Чтобы показать, что мы используем наследника класса, а не просто класс,
может быть лучше так написать?
TextReport report = new HtmlReport();
вместо скрина ниже
<img width="354" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/138505203-8b0886c6-4bd1-4af4-8198-a2a51e4adfc4.png">

**Comment by YarTsin** [comment]
Такой код не проходит валидацию, пишет: 
'+' should be on a new line. [OperatorWrap]

<img width="245" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/138507982-1811bcb2-466b-47e1-8e37-c19db7b43dbe.png">

**Comment by peterarsentev** [comment]
1. Не думаю, что это нужно здесь.
2. Поправил. Спасибо.
