### ISSUE TITLE
Добавление повторной сборки

### ISSUE THREAD

**Issue by snowflakes75** [peterarsentev/job4j_features_bugs#878]
Добрый день.

Иногда есть потребность в пересборки текущий версии. На данный момент решается путем создании фиктивного коммита.
Прошу Вас рассмотреть возможность добавление функционал по запуску CI бота через сайт.

**Comment by peterarsentev** [comment]
Добрый день. Можете указать сценарий, когда нужно повторно собрать тот же коммит?

**Comment by snowflakes75** [comment]
@peterarsentev , 

Да, конечно. Обычно связаны с временными проблемами CI бота.

1. Был добавлен коммит.
2. Сборка на сайте упала
3. Ошибка была связана с внутренний проблемы платформы
4. После ее устранения был отправлен тот-же коммит.
5. Платформа не принимает его для сборки.
6. Отправляется фиктивный коммит.

Пример ошибки, когда коммиты не проходили.
![image](https://user-images.githubusercontent.com/77325744/138551489-efcc8a6d-7bd9-4896-9436-224a35cf2a45.png)

**Comment by peterarsentev** [comment]
Именно эту проблемы мы поправили. 
А есть другой сценарий не связанный с ошибок платформы?

**Comment by snowflakes75** [comment]
На текущий момент это был единственный случай.

Предложил его добавить в качестве превентивной меры.

**Comment by peterarsentev** [comment]
Понял. Тогда закрываем. потому что такого не должно повториться.
