### ISSUE TITLE
Junior.List Динамический список на массиве.[#158 #218393] и  Создать контейнер на базе связанного списка [#159 #218468]

### ISSUE THREAD

**Issue by Krasobas** [peterarsentev/job4j_features_bugs#879]
Есть некоторая путаница со структурой.
Так в прошлом задании про Динамический список предлагалось создать интерфейс List в ru.job4j.list, а сам класс в ru.job4j.collection, а тесты снова в ru.job4j.list.
В уроке про связанный список структура уже такая ru.job4j.collection.list.

**Comment by peterarsentev** [comment]
Спасибо. Поправили.
