### ISSUE TITLE
Критика по IDEA и GIT

### ISSUE THREAD

**Issue by SergeyVolko** [peterarsentev/job4j_features_bugs#880]
Нужно больше обзорного материала по IDEA и использованию GIT с помощью IDEA. Бывает так, что делаешь коммит, а он из-за плохого интернет соединения не проходит. Повторно его сделать уже не получится, без дополнительных инструкций.

**Comment by AshleySunsine** [comment]
Этот вопрос подробно рассматривается на курсе Мидл.

**Comment by peterarsentev** [comment]
Этот раздел рассказывается в блоке Middle. Он был раньше в самом начале, но многие ученики начинали экспериментировать с git и это всегда плохо заканчивалось. Поэтому мы убрали это в третий уровень.
