### ISSUE TITLE
Уведомления в телеграме от бота job4j_notification

### ISSUE THREAD

**Issue by RuslanZb** [peterarsentev/job4j_features_bugs#882]
Бот не присылает уведомления об уроках на исправлении, присылает только о выполненных уроках. Проблема появилась, когда в уведомления начали вставлять комментарии менторов.  Подозреваю, что уведомления не приходят, если ментор в комментарии вставляет скрин или картинку, пока что не было урока на исправлении без скрина, чтобы точно утверждать об этом.  
Также не критично, но бот пересылает комментарии с HTML-разметкой.

**Comment by peterarsentev** [comment]
@RuslanZb Не могу повторить. Можете добавить ссылку на задачу, там где не было уведомлений.

**Comment by RuslanZb** [comment]
@peterarsentev  пока что только две задачи такие были:
https://job4j.ru/profile/exercise/24/task-view/199/solutionId/220033 
https://job4j.ru/profile/exercise/25/task-view/205/solutionId/220412

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
