### ISSUE TITLE
5. Реализация интерфейса  Уровень : 3. Мидл Категория : 3.2. Servlet JSPТопик : 3.2.8. JS, JQuery, Ajax

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#883]
5. Реализация интерфейса 
Уровень : 3. Мидл Категория : 3.2. Servlet JSPТопик : 3.2.8. JS, JQuery, Ajax
Задание.

1. Вернитесь к проекту dream_job.

2. Добавить проверку введенных данных на стороне клиента с помощью js. Все поля ввода должны был заполнены.
--Почему нельзя добавить скриншоты так как это видится автором после выполнения данного пункта?--

3. Добавить в модель Candidate поле city_id. 

4. В форме создания и редактирования, динамически через ajax загружать список городов. Список городов должен храниться в отдельной таблице.
---. В форме создания и редактирования, - кого, чего? (поста, кандидата, того и другого)
--Почему нельзя добавить скриншоты так как это видится автором после выполнения данного пункта?--
--- загружаться список городов, каких городов, с какой целью?  это рандомный список городов, или это список городов из поля кандидатов? ---

5. В одном из заданий на индексную страницу мы добавили вывод таблицы со списком кандидатов и вакансий за последний день, -- два раза про решал задания по этому проекту, не помню именного такого задания, именно в такой формулировке ( В одном из заданий на индексную страницу мы добавили вывод таблицы со списком кандидатов и вакансий за последний день), укажите пожалуйста в самом задании ссылку на эту задачу.
 однако данный функционал не был реализован. 
Ваша задача будет реализовать этот функционал - для этого:
- в PsqlStore добавить запросы, которые будут выбирать данные добавленные за последние сутки(тогда возможно следует указать про добавление поля Дата в модели данных, и конкретизировать)
- , в запросе будете использовать оператор between, для выполнения математических вычислений для даты можно использовать операторы согласно документации:

https://postgrespro.ru/docs/postgresql/12/functions-datetime

- в запрос добавить полученный список и вывести его на странице через jstl.
 
- --Почему нельзя добавить скриншоты так как это видится автором после выполнения данного пункта?--

6. Заполните README.md репозитория. В нем должны быть картинки интерфейса.
+ уровень у все разный, одни обучаются с нули другие уже работают и проходят курс
+ как уже просили, пожалуйста разделите задание на несколько.
 Спасибо

**Comment by peterarsentev** [comment]
Спасибо. Из курса убрали темы с JS.
