### ISSUE TITLE
1. Экзамен. ООД. [#857 #220396]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#885]
На зачете вы спрашивали у меня, знаю ли я Аджаил и Скрам.
Может имеет смысл добавить вопросы по этим технологиям
в Зачет и сделать пару вводных уроков и ссылок, чтобы люди 
могли хотя бы в общем представлять о чем идет речь?

**Comment by peterarsentev** [comment]
Да. Мы это сделаем. Но в другом уровне. Все же эти темы относятся к управлению, а не программированию.
