### ISSUE TITLE
Словарь в курсе

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#886]
Хотел бы внести предложение, если вы не посчитаете это излишним.

Предложил бы сделать в курсе вкладку 
"Словарь" терминов и понятий используемых на курсе, в котором
можно было бы давать краткое описание и определение терминов, 
а также указывать темы, в которых они используются и (или)
типичные ситуации применения

Это позволило бы как минимум:
- исключить разночтение в описании терминов из различных источников;
- сократить время поиска во внешних источниках, находя все необходимое в самом курсе;
- несколько сократить основной курс, вместо объяснений просто давая ссылку 
на тот или иной термин или ситуацию в словаре; 
- работа курсантов со словарем позволит им расширить кругозор до необходимого
курсу уровня возможно даже лучше, чем дополнительная литература.
- мне кажется знание терминологии повышает шанс пройти собес))

**Comment by peterarsentev** [comment]
@yarmail А можешь привести примеры таких слов? Если ты жаргон, то я стараюсь его из курса обрать.
Например, коммит заменить на фиксация изменений.
