### ISSUE TITLE
4. Скачивание файла с ограничением. [#144271 #221317]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#888]
После выполнения задания Стас сообщил, что: 

Параметры запуска надо валидировать,
надо проверять, что массив args имеет определенную длину

Возможно так:
        if (args.length < 2 ) {
            throw new IllegalArgumentException();
        }

Предлагаю сразу добавить это в код или прописать в задании.
Я бы сразу не догадался никогда.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
