### ISSUE TITLE
Отсутствует пример конфигурации для записи логов в файл

### ISSUE THREAD

**Issue by romankhiropulos** [peterarsentev/job4j_features_bugs#889]
В задании "1. Log4j. Логирование системы" сказано, что в разделе JDBC мы добавим конфигурацию для вывода информации в файл, а на данном этапе будем использовать только вывод в консоль, но пример с конфигурацией для вывода логов в файл в разделе JDBC отсутствует.

**Comment by peterarsentev** [comment]
Спасибо. Добавили.
