### ISSUE TITLE
1. Log4j. Логирование системы. [#404149] опечатка

### ISSUE THREAD

**Issue by reybos** [peterarsentev/job4j_features_bugs#89]
2. Уровень - Джуниор / Блок 2. Ввод-вывод / 3. Логгирование.
мы работаем в chapter_002 а в тексте и на картинке chapter_001

> Создайте файл /chapter_001/src/main/resources/log4j.properties.

**Comment by andreiHi** [comment]
а в какой задаче?
что то я не нашел

**Comment by reybos** [comment]
ну если по разделам то как в задаче написал
2. Уровень - Джуниор / Блок 2. Ввод-вывод / 3. Логгирование. / 1. Log4j. Логирование системы. [#404149]
не знаю как ссылку отправить, прямые на задачу не работают же вроде 
![image](https://user-images.githubusercontent.com/30983051/111070675-c86d9700-84e3-11eb-98a5-e9431a9eed7f.png)

**Comment by reybos** [comment]
посмотрел сейчас эту задачу, там еще и проблема с оформлением, обычный текст в блоках с кодом

**Comment by ikioresko** [comment]
Добавлю еще несколько опечаток

![2021-03-22_104923](https://user-images.githubusercontent.com/74650587/111947128-a8029580-8afe-11eb-942e-b3fe2cdd4146.png)
