### ISSUE TITLE
3. Класс хранилища пользователей UserStorage [#1104]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#892]
"В этом задании нужно сделать блокирующий кеш UserStorage для модели User"
Поясните пожалуйста что такое - **блокирующий кеш**, не нашёл нормальных 
объяснений в инете. Единственное, что помню, это то, что на основе одного
из типов ссылок, Soft Reference, можно сделать кеш. 
Судя по тому, что мы сейчас изучаем возможно это как-то связано с доступом
разными Нитями к этому кэшу?

**Comment by peterarsentev** [comment]
Спасибо. Переписал задание. Добавил уточнение.
