### ISSUE TITLE
2. JCIP. Настройка библиотеки [#268575 #222646]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#893]
Во время проработки урока (JDK 16) получил сообщение
от IDEA. Может быть использовать другие методы?
<img width="471" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/139644765-d52cf8dd-98cd-4cc6-bf95-1d3ef2187db1.png">

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
