### ISSUE TITLE
0.1. Интерфейс List [#4953]

### ISSUE THREAD

**Issue by alexlife9** [peterarsentev/job4j_features_bugs#895]
При этом у нас мо**_ЖЕ_**т быть один и тот же материал,

**Comment by alexlife9** [comment]
Сам**ЫМ** важн**ЫМ** для работы с коллекциями является набор CRUD

**Comment by alexlife9** [comment]
![изображение](https://user-images.githubusercontent.com/83451847/139711406-55aed012-a7e4-4e57-a865-c18e457a48e1.png)

**Comment by peterarsentev** [comment]
Поправил, спасибо.
