### ISSUE TITLE
проверка на однострочные комментарии

### ISSUE THREAD

**Issue by Dmitry8ms** [peterarsentev/job4j_features_bugs#897]
Данная конструкция ошибочно распознается как однострочный комментарий 
/** ____________________________________
___________________________//_________
___________________________________*/

**Comment by peterarsentev** [comment]
@Dmitry8ms  Можешь привести пример кода?

**Comment by Dmitry8ms** [comment]
Я уже исправил, это был двойной слэш внутри комментария JavaDoc, Бот отметил это как однострочный комментарий05.11.2021, 16:01, "Petr Arsentev" ***@***.***>:
Можешь привести пример кода?

**Comment by Dmitry8ms** [comment]
05.11.2021, 16:01, "Petr Arsentev" ***@***.***>:
Можешь привести пример кода?

**Comment by peterarsentev** [comment]
Понял. Пока не буду такое добавлять в поддержку. Разовый случай. Спасибо.
