### ISSUE TITLE
1. Неблокирующий кеш [#4741]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#898]
При выполнении метод main выдает ошибку.
Вероятно вместо
Base user1 = map.get(base); 
Должно быть 
Base user1 = map.get(1);

<img width="589" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/140545787-f0c7c4d2-0664-4cc8-bc24-fd6812998bc9.png">

**Comment by YarTsin** [comment]
Также, если в этом методе мы выводим на консоль
System.out.println(map);
то, как я понимаю, мы должны в Base сгенерировать toString

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
