### ISSUE TITLE
опечатка в теме 0. Сортировка [#10096 #177844]

### ISSUE THREAD

**Issue by AlenaLosk** [peterarsentev/job4j_features_bugs#899]
В строке: "Например: {f, a, e, d} соответствуют кодам {102, 97, 100, 101}. После сортировки по возрастанию массив примет вид: {a, d, e, f}." перепутана нумерация символов, должно быть или {f, a, d, e}, или {102, 97, 101, 100}
[https://job4j.ru/profile/exercise/30/task-view/224/solutionId/177844](url)

**Comment by peterarsentev** [comment]
Поправили. Закрываю.
