### ISSUE TITLE
0. ThreadSafe Singleton [#102739]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#900]
В части
2.1. Single checked locking.

public class TrackerSingle {
    private static TrackerSingle INSTANCE;
    private TrackerSingle() {
    }
   
чекстайл ругается на переменную INSTANCE
Полагаю, либо код надо править, либо настройки чекстайла.
<img width="882" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/140621886-cf8101d6-9333-45b8-8202-d058543b7342.png">

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
