### ISSUE TITLE
2. Каркас шахматной доски [#792 #226026] малозначительная опечатка

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#901]
> 3. Слон может двигаться в четыре стороны. Эти движения можно описать двумя дельтами +1 -1. Например, если слон двигается вниз влево, то дельты будут **-1 -1.**

т.к. в упражнении начало цифровых координат находится в **верхнем** левом углу, и Y-последовательность обратна традиционному числовому ряду на доске (у которого начало слева **внизу**), то и дельта "вниз-влево" будет -1 по горизонтали (Х) и +1 по вертикали(Y).
+это указали в комментах в 9м месяце.

**Comment by peterarsentev** [comment]
Поправили. Закрываю.
