### ISSUE TITLE
[invalid] 0. Введение. Установка [#504784] дезинформация ))

### ISSUE THREAD

**Issue by ForLearningAtJob4J** [peterarsentev/job4j_features_bugs#902]
https://job4j.ru/profile/exercise/176/task-view/779 
2е предложение 1го абзаца:
"Часто можно встретить сокращение K8s, т.к. произношение этих двух слов созвучно."
неверно, так как в данном случае использован другой способ формирования нумеронима - замещение указанного количества букв. См. https://en.wikipedia.org/wiki/Numeronym, 1й абзац, 4е предложение: 
Alternatively, the letters between the first and last are replaced with a number representing the number of letters omitted, such as "i18n" for "internationalization". Sometimes the last letter is also counted and omitted. These word shortenings are sometimes called alphanumeric acronyms, alphanumeric abbreviations, or numerical contractions"

**Comment by peterarsentev** [comment]
Поправил. Интересный факт, Я не знал.
