### ISSUE TITLE
2. ExecutorService рассылка почты. [#63097]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#903]
Мне кажется здесь идет дублирование кода, проверьте пожалуйста
<img width="523" alt="Screenshot_1" src="https://user-images.githubusercontent.com/46091342/140939128-5a8bf7c6-1708-4df6-8343-486d52f9fcbd.png">

**Comment by peterarsentev** [comment]
Поправил. Спасибо.  Это как копирование, я так задачи добавил.
