### ISSUE TITLE
Предложение по отображению кода в курсе

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#904]
Предложил бы весь код в уроках перевести в png, 
или другим способом защитить от копирования.
Это позволит: 
- уменьшить копипаст, который постоянно делаешь из-за рационального
мышления (лени);
- перенабор кода позволит лучше запоминать, прорабатывать, повторять этот код - 
это как при изучении английского языка - когда просто читаешь "про себя",
работают одни отделы мозга, когда ещё вслух проговариваешь - работают
другие отделы, суммарно работа с языком получается лучше.

**Comment by peterarsentev** [comment]
Добрый день, Не стоит так делать. Здесь же на наборщиков текста учатся. Раньше я думал, что это будет полезно. А сейчас считаю, что лучше сделать много заданий, а не текста набрать.
