### ISSUE TITLE
0. ToOne [#6873] Уровень : 3. Мидл

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#907]
0. ToOne [#6873]10
Уровень : 3. Мидл Категория : 3.3. HibernateТопик : 3.3.2. Mapping
Задание

1. Откройте проект TODO список. 

2. Добавьте в проект схему user-item. 

3. Добавьте форму авторизации и регистрации. - Пожалуйста, вынесете это отдельным заданием. Задание объемное, чтобы не создавать путаницу.

При добавлении в проект все что требуется по задании , требуется еще написать ряд методов под нечего через Хибернате, что только усложняет задание.

Как итог только этот пункт уже стоит вынести в отдельное задание.

4. В таблице выводить все задания и автора задания.

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
