### ISSUE TITLE
1. ToMany [#301848]

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#909]
1. ToMany [#301848]
Уровень : 3. Мидл Категория : 3.3. HibernateТопик : 3.3.2. Mapping
   1)  В этой и последующей задаче просят переделать существующие модели 
и разместить их в другой папке(каждая новая задача, своя папка)
package ru.job4j.many; и тд 
что приводит к переписыванию файла конфигурации хибернате как минимум, если делать разные ветки в последующем это затруднит слияние.
       Т.е. у нас сейчас рабочий проект TODO со своей архитектурой, в задании(в этом и последующих) просят менять существующие модели со всеми вытекающими последствиями
     Пожалуйста укажите, в проекте как решать данную ситуацию.
Посмотрел, цать заданий назад решали в проекте Тракер.  Попробовал, после небольших манипуляции и создания там новых таблиц все сработало.Быть может тогда стоит про это указать в задании?
Спасибо

**Comment by peterarsentev** [comment]
Спасибо. Поправили описание. Убрали из курса проект job4j_hibernate.
