### ISSUE TITLE
Нарушение логики

### ISSUE THREAD

**Issue by DDavydov911** [peterarsentev/job4j_features_bugs#910]
Job4j/Уроки/2.3.6. Проект. Агрегатор Java вакансий/2.3. Загрузка деталей поста и 3. Архитектура проекта - Аргегатор Java Вакансий

Пожалуйста, определите название безымянного метода, который возвращает описание вакансии. По идее он должен называться getDescription и возвращать описание вакансии в виде строки, которое потом помещается в поле description объекта Post. 
Но далее, в задании "3. Архитектура проекта - Аргегатор Java Вакансий" описан метод с названием называется **detail** , который выполняет работу этого безымянного метода - загружает детали объявления по ссылке - и тут же выше в описании интерфейса этот метод **Post detail(String link);** возвращает целиком объект Post, включающий в себя поле description с описанием вакансии. Так что должен возвращать этот метод: целиком объект или только поле объекта?

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
