### ISSUE TITLE
3. LazyInitializationexception Мидл

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#911]
3. LazyInitializationexception [#331987]
Уровень : 3. Мидл Категория : 3.3. HibernateТопик : 3.3.2. Mapping
В задании описывается новый материал, даются сущности.

@OneToMany(mappedBy = "category")
private List<Task> tasks = new ArrayList<>();
mappedBy у нас обозначает “хозяина” отношения и в данном случае это поле "category" класса Task.

Сохраним в базе данных следующие записи:
????????
После показывается скрин что эти сущности находятся в разных таблицах в Бд.
Важно! - 
Но, полностью отсутствует часть материала как эти сущности попали в БД (код ).
И дальше идет повествование уже как с ними (вставленными данными) работать. 
+ ниже идет задание по материалу.
Вопрос если не было показано как делать, как сделать?
или это такой ход?
Спасибо.

**Comment by itfedorovsa** [comment]
На данный момент урок уже переписан. Спасибо! Закрываю
