### ISSUE TITLE
Названия уровней обучения

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#912]
В своих видео вы не раз упоминали, что нужно 
пройти все три уровня, чтобы получить работу.
Предлагаю изменить названия уровней на сайте, в курсе,  чатах,
чтобы они были одним целым (частью одного целого), 
а не отдельными курсами.

Например было: Стажер, Джуниор, Мидл
Предлагаю:
 1 класс, 2 класс, 3 класс или уровень

Или как-то продумать названия, чтобы человек не думал, что 
сразу после стажера можно пойти на Стажера, 
после Джуниора - на Джуниора и т.д. и спокойно
занимался до конца всего курса.

**Comment by AlexeySapsay** [comment]
Пусть человек думает, и пробует пойти на стажера, джуна и мидла. После того как потыкается, и ничего не получится придет доучиться дальше.
Не вижу смысла переименновывать в классы, вроде логичное название стажер, джун и мидл мотивирует быстрее прокачиваться, примерно показывая уровень теоретической и практической подготовки. А класс1 ничего не говорит о навыках и опыте.
Как бы наивно полагать, что сразу после медицинского универа ты 100 качественный врач,  тоже и с курсом программирования.

**Comment by peterarsentev** [comment]
Тут маркетинг еще. Уровни оставим, как есть.
