### ISSUE TITLE
4. Категории в TODO List [#331991] Хибернате

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#913]
Я прошу прощения, но хочется спросить - в каком все же проекте делается этот раздел упражнений по Хибернате?
т.е. делаем мы примеры в проекте Траскер. Потом, бам, задание 4. Категории в TODO List [#331991]
и тут уже не получиться его сделать в проекте Тракер без танцев с бубнами ибо появились Сервлеты и jsp а jsp не будет работать без Томкат и Сервлеты и тд.
  а в проект Тракер никто не добавлял зависимостей не прописывал томкат, у томката не прописывал БД .
и это только все чтобы выполнить задание из примера. 
Пожалуйста, нужно либо все примеры для связи сущностей и работы в Хибернате делать в проекте Траске и соответственно это 
указать в начале раздела, установив зависимости, плугины, прописав и настроив Томкат., а также все атрибутики для вебпроекта Мавен (webapp/WEB_INF) и всего остального, проект Траскер совершенно не заточен на это.
либо это делать все в проекте TODO - тоже указав в начале раздела где выполнять все тестовые задания.
Ведь если все задания будут сделаны в одном проекте, это ведь должно быть удобнее и практичнее?
+ опять задание на фронт. можно разделить такие задания на 2?
Спасибо

**Comment by itfedorovsa** [comment]
На данный момент задания уже разделены. Спасибо, закрываю!
