### ISSUE TITLE
Упражнение 1.6. Еженедельная зарплата

### ISSUE THREAD

**Issue by Archer7777** [peterarsentev/job4j_features_bugs#914]
вот написал такой код, и он работает несмотря на то что одна из переменных не использована, вероятно в самой задаче что то не верно, ибо переменная должна быть использована, вот код 

{
    public static int calculate(int[] hours) {
        int regular = 10;
        int extra = 15;
        //int doubleRegular = 20; // вот эта переменная не зайдействована, когда ее используешь тесты задача не проходит
        int doubleExtra = 30;
        int salary = 0;

        for (int i = 0; i < hours.length; i++)
            if (i < 5) {
                if (hours[i] <= 8) {
                    salary = salary + hours[i] * regular;
                }
                else {
                    salary = salary + (hours[i] - 8) * extra + 8 * regular;
                }
            } else {
                if (hours[i] <= 8) {
                    salary = salary + hours[i] * extra;
                }
                else {
                    salary = salary + (hours[i] - 8) * doubleExtra + hours[i] * extra;
                }
            }
        return salary;
    }
}

**Comment by peterarsentev** [comment]
@Archer7777 Так этот код ты сам написал? Зачем ты создал эту переменную?
В условии задании дан только каркас метода. Кода внутри метода нет.
