### ISSUE TITLE
2. Тестовое задание - проект Pooh JMS [#268841]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#929]
Вопросы и предложения по теме.
2. Тестовое задание - проект Pooh JMS [#268841]

Уточните пожалуйста, что означает название Pooh

.....

В названии присутствует JMS - как я понимаю,
для асинхронной передачи сообщений.
В курсе, у нас была пока только одна тема про асинхронность:
CompletableFuture [#361626 #227647]

Может быть имеет смыл расширить эту тему про асинхронность
и добавить туда инфу про JMS и, например RabbitMQ 
(если это связано)
Или мы делаем аналог этих технологий? Непонятно.
.....

class PoohServer
Сообщение от Mikhail Lukonin

private final HashMap modes = new HashMap<>();

не видит типы данных. Используйте так:
private final HashMap<String, Service> modes = new HashMap<>();

.....

Цитата:
"Для выбора метода GET или POST используйте 
константы "GET".equals(req.method()), 
а не на оборот. req.method.equals("GET")."

Поясните пожалуйста подробнее фразу. Есть смутно предположение,
почему так, но хотелось бы услышать объяснение куратора.

.....

Поясните пожалуйста, зачем нужен класс
CASMap

.......

Для меня, как для слабого ученика, сложность 
вызвало правильно подобрать структуру данных
для хранения в сервисах. Может быть имеет смысл
сделать один или несколько уроков, в которых
показать на нескольких примерах, как можно 
было бы подобрать составную структуру данных 
исходя из условий задач.
Как вариант можно было бы обобщить несколько задач
из курса и объяснить как лучше подбирать 
(составлять) структуру.

**Comment by itfedorovsa** [comment]
Отвечу что знаю:
1) "Или мы делаем аналог этих технологий?" - В курсе мы делаем аналоги многих систем, многие из которых присутствуют в составе других фреймворков, и код всех этих систем с нуля писать не нужно будет, но чтобы понимать как устроено то, с чем придется работать, поддерживать, дополнять и тд, нужно иметь серьезное представление о том, как работает механизм внутри. 

2) "Для выбора метода GET или POST используйте
константы "GET".equals(req.method()),
а не на оборот. req.method.equals("GET")." - если первое сравниваемое значение будет null, выпадет NullPointerException, а если во втором null, то просто false.

3) CASMap - дан как пример методов коллекции, работающей в многопоточной среде. Непосредственно к программе не относится.

**Comment by peterarsentev** [comment]
Я переписал задание. Добавил тесты и ясности в описание.
