### ISSUE TITLE
не виден текст в упражнениях в темной теме сайта

### ISSUE THREAD

**Issue by tutbora** [peterarsentev/job4j_features_bugs#93]
по этому адресу упражнения
https://job4j.ru/edudark/topics

скрин упражнения - не виден текст, он белого цвета, на белом фоне
https://prnt.sc/vy2l4t

выделил содержимое страницы Ctrl + A, и стало понятно что текст есть.
https://prnt.sc/vy2m5x

https://prnt.sc/vy2ns9
https://prnt.sc/vy2s8h

**Comment by peterarsentev** [comment]
На новой платформе не будет темного интерфейса. Неактульно.
