### ISSUE TITLE
Опечатка в тексте 

### ISSUE THREAD

**Issue by ArtemPolshchak** [peterarsentev/job4j_features_bugs#933]
В разделе Упражнения  -> 1.4.2 Stream API -> 0.2 Понятие редукции. Произвольный Collector для подсчета -> ОПЕЧАТКА В НАЗВАНИИ КЛАССА "CollectorAriphmetic" - вместо буквы "p" должна быть буква "t". CollectorArithmetic

**Comment by peterarsentev** [comment]
Поправили. Закрываю.
