### ISSUE TITLE
1. select fetch [#331990]

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#936]
1. select fetch [#331990]10
Уровень : 3. Мидл Категория : 3.3. HibernateТопик : 3.3.3. HQL, Criteria
 - В задании используется сущности Student, Book, Account.
При этом сущность Book уже была использована ранее в примерах к разделу manytomany. 
Сущность вызывает конфликт у хибернате (при условии если эти все примеры делаться в одном проекте) со ссылкой на использование в manytomany класса Book.
- В задании в очередной раз опущен скрипт создания сущностей и их вставки в БД только приложены скрины - итого получается.
- Можно хотя бы попросить вставить код ниже в задание, если все верно
             Journal first = Journal.of("Двенадцать стульев", "АСТ");
            Journal second = Journal.of("Одноэтажная Америка", "MANNING");

            Student one = Student.of("Иванов Иван", 20, "Москва");
            Account account = Account.of("root");
            account.addJournal(first);
            account.addJournal(second);
            one.setAccount(account);
            session.save(account);
            session.save(one);
Спасибо.

**Comment by itfedorovsa** [comment]
На данный момент этот урок уже заменен другим. Спасибо! Закрываю
