### ISSUE TITLE
0. Объект монитор, критическая секция [#6857 #222287]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#939]
Предложил бы обновить статью за счет этой
https://javarush.ru/groups/posts/2174-v-chem-raznica-mezhdu-mjhjuteksom-monitorom-i-semaforom
и последовательно объяснить,
что такое Mutex, Monitor, (возможно, но необязательно Semafor) 
и потом переходить к Synhronized. и критической секции.
Мне кажется важным, что 
"В блоке кода, который помечен словом synchronized, происходит захват мьютекса нашего объекта obj."
Также  обновление статьи поможет лучше ответить на вопрос 4 зачета:
4 Объясните следующие термины: монитор, мьютекс, критическая секция,

**Comment by alexlife9** [comment]
актуально. подниму.

**Comment by itfedorovsa** [comment]
Данный урок был создан ранее и позже дополнен. В том числе соответствует всему перечисленному в этом посте. https://job4j.ru/profile/exercise/73/task-view/409 Спасибо! Закрываю.
