### ISSUE TITLE
Общие предложения

### ISSUE THREAD

**Issue by Frenchfan** [peterarsentev/job4j_features_bugs#943]
1. Доработать бота - нужна расшифровка ошибок желательно с указанием файла и строк с ошибками, из лога не всегда понятно, где конкретно допущена ошибка (особенно это касается checkstyle), иногда даже с установленным checkstyle в IDEA все в порядке, а коммит не принимается
2. Нужно пояснить, являются ли упражнения обязательными для прохождения курса. Предлагаю их также учитывать в рейтинге - например, с массивами 59 упражнений едва ли возможно за один день решить, а на рейтинг они вообще никак не влияют.

**Comment by peterarsentev** [comment]
@Frenchfan А можешь по первому пункту привести пример лога, где было не понятно, что править?

**Comment by peterarsentev** [comment]
По второму пункты мы добавили его в рейтинг. Упражнения решить желательно.
