### ISSUE TITLE
Продление времени доступа к курсу

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#944]
Если текущие правила не изменились, при неактивности 30 дней, 
блокировался доступ к курсу и его можно было продлить 
только двумя способами, написав куратору, или написав сообщение
в курсе (например самому себе)
Сейчас отрезали возможность написать самому себе.

При длительной подготовке к сложному зачету или по другим причинам 
(ковид, переезд и т.д. ), мне кажется было бы неплохо оставить возможность
продления доступа без привлечения куратора.

Предложил бы в личном кабинете сделать видимость количества оставшихся 
дней до блокировки и кнопку Продления.

Например:
До приостановки действия учетной записи по 
причине неактивности осталось: 25 дней 
 ПРОДЛИТЬ

**Comment by YarTsin** [comment]
Не проверял, являются ли Упражнения к курсу тоже активностью - хорошо бы что бы да.

**Comment by peterarsentev** [comment]
Я этот функционал отключил. Теперь мы не блокируем.
