### ISSUE TITLE
1. Запуск нити. Thread#start() [#1016 #220254]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#945]
1. Предложил бы изменить название на  "Создание и запуск нити (потока)"

2. Думаю сюда же можно добавить абзац о создании потоков-демонов - такой вопрос есть в зачете.

**Comment by staskorobeynikov** [comment]
1. Исправлено
2. Для этого уже есть отдельная задача
Закрываю
