### ISSUE TITLE
Раздел 3.1.1. Threads - задание join()

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#946]
Предложил бы добавить в раздел 3.1.1. Threads
дополнительное задание на понимание работы
метода join().
[ThreadOrder.txt](https://github.com/peterarsentev/job4j_features_bugs/files/7643407/ThreadOrder.txt)
В зачете есть вопрос: как работает метод join()

**Comment by itfedorovsa** [comment]
Реализовано. Спасибо! Закрываю.
