### ISSUE TITLE
0. Что такое атомарность? [#6856 #221360]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#947]
Предложил бы добавить в тему то,
что проблема доступа к несинхронизированному ресурсу,
если я правильно понимаю, 
имеет название Race Condition (состояние гонки)

В зачете есть вопрос:  Что такое race condition

**Comment by staskorobeynikov** [comment]
Спасибо
Для этого добавлена отдельная задача
Закрываю
