### ISSUE TITLE
1. Синхронизация общих ресурсов. [#1096 #221415]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#948]
Поправьте меня, если я не прав

Цитата:
"Одновременно с объектом может работать только одна нить."
Объяснен механизм, как там работает, но очень понятна причина.

Предложил бы  альтернативное объяснение с примером. Возможно 
оно будет более понятным и наглядным для студентов.
[SynchMethod.txt](https://github.com/peterarsentev/job4j_features_bugs/files/7651599/SynchMethod.txt)

**Comment by itfedorovsa** [comment]
Исправлено.
