### ISSUE TITLE
3. @ModelAttribute. Создание инцидента. [#261013] Уровень : 3. Мидл

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#950]
3. @ModelAttribute. Создание инцидента. [#261013]11
Уровень : 3. Мидл Категория : 3.4. SpringТопик : 3.4.2. MVC
Откройте класс WebInit.

java
package ru.job4j.accident;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.FilterGenerator;
import org.springframework.web.WebApplicationInitializer;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;
import org.springframework.web.filter.CharacterEncodingFilter;
import org.springframework.web.servlet.DispatcherServlet;

import javax.servlet.FilterRegistration;
import javax.servlet.ServletContext;
import javax.servlet.ServletRegistration;

public class WebInit implements WebApplicationInitializer {

    public void onStartup(ServletContext servletCxt) {
        AnnotationConfigWebApplicationContext ac = new AnnotationConfigWebApplicationContext();
        ac.register(AppConfig.class);
        ac.refresh();
        CharacterEncodingFilter filter = new CharacterEncodingFilter();
        filter.setEncoding("UTF-8");
        filter.setForceEncoding(true);
        filter.setForceRequestEncoding(true);
        FilterRegistration.Dynamic encoding = servletCxt.addFilter("encoding", filter);
        encoding.addMappingForUrlPatterns(null, false, "/*");
        DispatcherServlet servlet = new DispatcherServlet(ac);
        ServletRegistration.Dynamic registration = servletCxt.addServlet("app", servlet);
        registration.setLoadOnStartup(1);
        registration.addMapping("/");
    }
}

ранее, ни разу не было упоминания про данный класс, 
ни в одной таске его не просили создать. и не создавали в примерах, теперь его просят использовать и запустить код и получить результат.

Добавим контроллер.

java
package ru.job4j.accident.control;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import ru.job4j.accident.model.Accident;
import ru.job4j.accident.repository.AccidentMem;

@Controller
public class AccidentControl {
    private final AccidentMem accidents;

    public AccidentControl(AccidentMem accidents) {
        this.accidents = accidents;
    }

    @GetMapping("/create")
    public String create() {
        return "accident/create";
    }

    @PostMapping("/save")
    public String save(@ModelAttribute Accident accident) {
        accidents.create(accident);
        return "redirect:/";
    }
}

   accidents.create(accident); - ранее, т.е. с начала проект и речи не было о создании данного метода в классе AccidentMem
+ теперь в данном задании тоже нет речи его создать, но просят запустить код ?
с учетом отсутствия целого класса + метода считаю, следует поправить или задание или пример.
Спасибо

**Comment by peterarsentev** [comment]
@Halsyon Мы обновили этот блок. Это уже не актуально.
