### ISSUE TITLE
3.1. @RequestParam. Форма редактирования [#308708]

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#951]
Уровень : 3. Мидл Категория : 3.4. SpringТопик : 3.4.2. MVC
в методе 
@PostMapping("/save")
public String save(@ModelAttribute Accident accident) {
    accidents.save(accident);
    return "redirect:/";
}
указан метод  accidents.save(accident); -  НО в предыдущем к этому задании указан метод  -> accidents.create(accident);
@PostMapping("/save")
    public String save(@ModelAttribute Accident accident) {
        accidents.create(accident);
        return "redirect:/";
    }
}

**Comment by peterarsentev** [comment]
@Halsyon Спасибо, но уже не актуально. Мы обновили этот блок на Spring boot,
