### ISSUE TITLE
3.3. Фиксация изменений на github и пожелание

### ISSUE THREAD

**Issue by kazisyudaitis** [peterarsentev/job4j_features_bugs#952]
1. При первом коммите, в IDEA выводилось сообщение об ошибке с окончаниями. Если не ошибаюсь, то текст такой
 LF will be replaced by CRLF
2. При выполнении задания 4.1. Разбор первой программы.
Не понятно как при проверке через бот, в файле с ошибками определить, где именно в коде находится ошибка. было 3 ошибки с пробелами. Если бы строк в коде было несколько десятков или сотен, то проблематично было бы искать. 
![Screenshot_1](https://user-images.githubusercontent.com/30861954/145675209-9201f54b-fb9c-48b0-a123-30e661c19bc9.png)

**Comment by AshleySunsine** [comment]
Строка ошибки по середине имеет имя файла и какие-то цифры:
Multiple.java:4:29
Так вот 4 - это строка
29 - позиция курсора в этой строке. 
Собственно это координаты места, где возникли проблемы.
