### ISSUE TITLE
3. Checkstyle с Maven [#257606 #238954]

### ISSUE THREAD

**Issue by as310788** [peterarsentev/job4j_features_bugs#954]
В задание перед копированием кодом написано:" Чтобы подключить плагин checkstyle, нужно в pom.xml добавить блок <plugins> ... </plugins>, а внутрь него добавить вот такой код." И кода вставляешь код естественно нечего не получается. Далее идет описание того как должен выглядить код в pom., и тут понимаешь что нужно не просто было скопировать код, а добавить дополнительно еще помимо <plugins> ... </plugins> блок  <build>, куда соответветственно и копируется код. И самое главное что код должен заканчивается блоком </project>.  Я поначалу скопировал только этот код без build, а уже потом понял где совершил ошибку когда дальше посмотрел что не получается запустить код. Хорошо что предыдущий pom был сохранен в GitHub. Прошу сделать более четкое описание, так как в комментариях не я один пролетел с этим моментом. Спасибо.

**Comment by as310788** [comment]
В задание перед копированием кодом написано:" Чтобы подключить плагин checkstyle, нужно в pom.xml добавить блок plugin plugins , а внутрь него добавить вот такой код." И кода вставляешь код естественно нечего не получается. Далее идет описание того как должен выглядеть код в pom., и тут понимаешь что нужно не просто было скопировать код cблоком plugin, а добавить дополнительно еще помимо plugin блок build , куда соответственно и копируется код. И самое главное что код должен заканчивается блоком project . Я поначалу скопировал только этот код без build, а уже потом понял где совершил ошибку когда дальше посмотрел, что не получается запустить код. Хорошо что предыдущий pom был сохранен в GitHub. Прошу сделать более четкое описание, так как в комментариях не я один пролетел с этим моментом. Спасибо. Поправил описание на более понятное).

**Comment by AshleySunsine** [comment]
Задание было пересмотрено. Принято решение ничего не менять(пока), т.к в уроке достаточно необходимой информации. Вопросы заданные в комментариях рассматривались в предыдущих заданиях.
