### ISSUE TITLE
Мидл Threads Синхронизаторы

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#955]
Если я правильно понимаю, в текущей версии курса 
отсутствует тема Синхронизаторы, хотя вопросы на эту 
тему в зачете есть (Semaphore, CountDownLatch, Barrier)

Предлагаю:
1. Пока темы нет, поставить временную заглушку в виде
ссылки на статью с картинками в доп. материалах.
https://habr.com/ru/post/277669/
(Справочник по синхронизаторам)

2. На основе этой же статьи можно будет донести материал в курс

3. При необходимости могу добавить по синхронизаторам примеры,
которые у меня есть.

**Comment by staskorobeynikov** [comment]
Спасибо
По данной теме задача добавлена 
Закрываю
