### ISSUE TITLE
0. Spring DataSource [#6878]

### ISSUE THREAD

**Issue by Halsyon** [peterarsentev/job4j_features_bugs#956]
0. Spring DataSource [#684 
Уровень : 3. Мидл Категория : 3.4. SpringТопик : 3.4.3. Template, ORM
Идет описание для подключения проекта Spring-JDBC и фраза
Подключим класс конфигурации. 

ac.register(WebConfig.class, JdbcConfig.class);
  укажите пожалуйста в задании, что Вы ссылаетесь
(public class WebInit implements WebApplicationInitializer ) 

Создадим схему db/schema.sql. Для упрощения кода в модели будет два поля: id, name. В вашем проекте их должно быть по техническому заданию 6.

sql
CREATE TABLE accident (
  id serial primary key;
  name varchar(2000)
);
Для упрощения кода в модели - ? по итогу задания остается не ясным момент, какой должна быть создана таблица в БД PostgreSQL. на сколько полей, в след задании приводится создание сущности через хибернате. там тоже два поля у класса. уточните пожалуйста в задании как его выполнять (создать отдельный схожий класс на 2 поля или полностью работать с существующим классом и полностью усложнять себе изучение материала на старте аннотациями @ManyToMany итд так как это необходимо в рамках если полностью задействовать все поля класса Ассидент что усложнит в разы вход в материал Спринг-Хибернате) 
Спасибо

**Comment by peterarsentev** [comment]
@Halsyon Спасибо. Это переписали.
