### ISSUE TITLE
Мидл Threads deadlock

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#957]
В зачете есть вопрос
6. Что такое DeadLock? Приведите примеры.

В некоторых источниках видел более широкий вариант этого вопроса.

Предложил бы расширить вопрос и дать в курсе 
соответствующую информацию по нему,
например вопрос:
6. Расскажите о deadlock, livelock, lock starvation?

Ответ (кратко):
deadlock - потоки заблокированы навсегда, ожидают друг друга и ничего не делают

livelock - потоки заблокированы, ожидают друг друга, проделывают 
какую-то работу без прогресса (как бы постоянно уступают друг другу)

Lock starvation (голодание) - ситуация, когда менее приоритетные потоки ждут 
долгое время или все время для того, чтобы запуститься.

**Comment by staskorobeynikov** [comment]
Задание добавлено
Закрываю
