### ISSUE TITLE
Место переопределения toString()

### ISSUE THREAD

**Issue by Futsey** [peterarsentev/job4j_features_bugs#958]
Добрый день!
Выполняю задание 2. Преобразования List в Map. [#10093] и метод toString() переопределен в каркасе не в последнюю очередь, хотя менторы очень сильно рекомендуют переопределять его прям последним.
Не самое фатальное замечание, но норматив, если уж он есть для учеников, должен быть применим одинаково ко всем участникам процесса обучения =)))

**Comment by peterarsentev** [comment]
Написал менторам, чтобы такое не требовали. Такого правила нет в Java. Есть правила расположения полей, конструкторов и методов. Но по поводу расположения переопределенных методов такого правила нет.
