### ISSUE TITLE
Не копируется код.

### ISSUE THREAD

**Issue by bannovdaniil** [peterarsentev/job4j_features_bugs#959]
на странице:
https://job4j.ru/profile/exercise/2/task-view/98/solutionId/241976
Каркас тест-класса:
 не правильно сделана разметка кода, исправьте ошибку.

**Comment by peterarsentev** [comment]
@bannovdaniil А в каком ты браузере проверяешь?

**Comment by peterarsentev** [comment]
Я проверил в хроме, яндексе. Код копируется. Пока закрываю.

**Comment by bannovdaniil** [comment]
> Я проверил в хроме, яндексе. Код копируется. Пока закрываю.
Chrome и FireFox
[записал видео](https://cloud.mail.ru/public/mY5i%2FUqgwNhnta)
