### ISSUE TITLE
Ошибка в ТЗ к задаче 3.8. Исключить элементы из двумерного массива. 

### ISSUE THREAD

**Issue by bannovdaniil** [peterarsentev/job4j_features_bugs#960]
https://job4j.ru/profile/topics/2/task_code/179/solution/98690

в ТЗ
`1. Если сумма индексов при переборе двумерного массива равна sum, то элемент с такими индексами должен принять значение 0.`

в Тестах, данные элементы исключены.

**Comment by peterarsentev** [comment]
Спасибо. Я добавил тестов. Тут условие такое, что его нужно сделать 0 и убрать из массива.
