### ISSUE TITLE
Упражнение Массивы 5.8. Четные vs Нечетные

### ISSUE THREAD

**Issue by alexvolchkov** [peterarsentev/job4j_features_bugs#963]
[https://job4j.ru/profile/topics/2/task_code/212/solution/99097](https://job4j.ru/profile/topics/2/task_code/212/solution/99097)
Первый тест 
@Test
    public void whenWinOdd() {
        assertEquals(2, EvenVsOdd.whoWin(new int[] {5, 10, 4, 3}));
    }
Должен же вернуть 0, так как 5<10 - победа второго
                                                4>3 - победа первого
Итого Ничья

**Comment by AshleySunsine** [comment]
"Выигрывает та команда, которая набрала наибольшее число очков."
1я команда: 5+4=8
2я команда: 10+3=13
8<13 победа 2й команды.
