### ISSUE TITLE
0. Spring Security

### ISSUE THREAD

**Issue by ikioresko** [peterarsentev/job4j_features_bugs#964]
На задаче добавляются 3 зависимости в pom :
spring-security-core
spring-security-config
spring-security-web

Но добавлять spring-security-core - явно - не обязательно, так как эта зависимость уже содержится внутри проекта spring-security-web

![2022-01-02_130649](https://user-images.githubusercontent.com/74650587/147869856-6350713f-f24d-42f8-9ae5-e90260df9fb2.png)

Итого для работы проекта достаточно импортировать только :
spring-security-config
spring-security-web

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
