### ISSUE TITLE
из сообщения для ментора пропадает ссылка

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#965]
![изображение](https://user-images.githubusercontent.com/44730951/147875970-b9b44e4d-14ee-4270-adc1-c4111d6d4bb7.png)

Не знаю баг ли это именно job4j, но ссылки часто пропадают, если отправлены без иного содержимого.  Это уже год минимум.

Подробных условий нет - браузер mozilla, обновлённая, без каких-то влияющих плагинов. (NoScript и всё).

**Comment by peterarsentev** [comment]
Да. Бага есть. Пока не знаю, как ее поправить. Не могу понять в чем она связана.
