### ISSUE TITLE
Дополнение в тексте задания

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#970]
[https://job4j.ru/profile/exercise/79/task-view/428](https://job4j.ru/profile/exercise/79/task-view/428)

В задании изначально не понятно где вводятся команды для работы с git.
Пробовал Bash git, не прошли. Только спустя время осознал что возможно в терминале IDEA.
Предложил бы явно прописать в начале статьи что все команды исполняются в терминале IDEA.

**Comment by peterarsentev** [comment]
Спасибо. Добавил описание.
