### ISSUE TITLE
commit VS фиксация. Пожелание для правки в тексте задания

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#973]
![image](https://user-images.githubusercontent.com/13130875/148881335-f16652f5-f995-4622-a402-e5bdb961a90a.png)
[https://job4j.ru/profile/exercise/79/task-view/431](https://job4j.ru/profile/exercise/79/task-view/431)
фиксация- звучит довольно странно и не разу не встречал такое употребление термина, возможно тут лучше будет применить commit?

**Comment by peterarsentev** [comment]
Поправил. Спасибо.
