### ISSUE TITLE
Противоречивые задания

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#978]
Есть задание:
[https://job4j.ru/profile/exercise/80/task-view/437/solutionId/249874](https://job4j.ru/profile/exercise/80/task-view/437/solutionId/249874)
1. Техническое задание - проект "Работа мечты"   [#260362 #249874]
И задание [https://job4j.ru/profile/exercise/81/task-view/439](https://job4j.ru/profile/exercise/81/task-view/439)
1. Maven web проект. [#276373]
И они противоречат друг другу. Точнее мы создаем два проекта, которые похожи, но в первом случае просто мавен проект, а второй мавен с артифактами. Так по факту, с каким мне нужно будет работать?
Возможно первое задание нужно удалить? Т.к оно вводит в заблуждение. Я его выполнил, создал мавен проект без артефактов. И теперь проект придется удалить, и создавать новый, а это путает.
Возможно я чего то здесь не понял в задании.

**Comment by peterarsentev** [comment]
Поправили. Спасибо.
