### ISSUE TITLE
Опечатки в задании

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#979]
![image](https://user-images.githubusercontent.com/13130875/149308414-cf46f961-090c-44df-bd11-e1ae68588e9e.png)
[https://job4j.ru/profile/exercise/81/task-view/439](https://job4j.ru/profile/exercise/81/task-view/439)

**Comment by peterarsentev** [comment]
Неактульно. Этот блок убрали.
