### ISSUE TITLE
Опечаточка в задании

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#982]
![image](https://user-images.githubusercontent.com/13130875/149411761-68d080f1-607d-4d55-89af-9d6fb959eb94.png)
[https://job4j.ru/profile/exercise/82/task-view/445](https://job4j.ru/profile/exercise/82/task-view/445)

**Comment by peterarsentev** [comment]
Неактуально. Мы убрали этот блок.
