### ISSUE TITLE
Job4j Уроки 2.5.4. ISP 1. Создать меню.

### ISSUE THREAD

**Issue by DDavydov911** [peterarsentev/job4j_features_bugs#983]
Добрый день!
Не первый раз замечаю, что из-за расплывчатости или двусмысленности формулировок заданий,  приходится переделывать их решения.
Формально мой код работает в соответствии с требованиями, описанным в задании, но ментор возвращает, - оказывается, тут нужно было сделать по-другому, а это не было ясно видно из условия. Возможно так и задумано, - но это отнимает время на переделку у учащихся  и на проверку у менторов.
Большая просьба, прописывать условия более детально. 
Было бы здорово, если бы такие задания (хотя бы некоторые) были бы оформлены в  BDD подходе.
Тогда двусмысленность исчезнет и будет навык работы с таким описанием задачи.

**Comment by peterarsentev** [comment]
Спасибо. Мы стараемся расписывать задания подробно. Это задание поправили.
