### ISSUE TITLE
Добавить "помощь" в решении задач

### ISSUE THREAD

**Issue by EugeneVovk** [peterarsentev/job4j_features_bugs#991]
Некоторые задачи сложны и не хватает навыков разбивать задачу на подзадачи.
Было бы хорошим дополнением (для уровня джуниор) под самими задачами сделать кнопку с всплывающим окном, в котором лежал бы псевдокод с построчным решением. 
Главное же, наработать решение задач на языке джава и заложить это в навык.
Ведь логически думать и принимать самостоятельные решения, это уже уровень мидл.

PS: просто уже крик души...

**Comment by AshleySunsine** [comment]
Логически думать и принимать самостоятельные решения это минимум с которым берут на работу. Джуниор от мидла отличается разной ответственностью. Мидл не только  умеет писать чистый, хороший код, но и участвовать в процессе проектирования архитектуры приложиния. Т.к приложение может разрастаться со временем и одни части нередко мешают другим. Джуны в свою очередь так же пишут хороший качественный код, просто не несут ответственности в масштыбах проекта. Их ответственность лежит в области их задачи.
 "Некоторые задачи сложны и не хватает навыков разбивать задачу на подзадачи." Это вопрос к составлению задач к урокам. Не могли бы Вы указать в каких уроках не хватает подробностей в описании задачи?

**Comment by peterarsentev** [comment]
@EugeneVovk @AshleySunsine поддерживаю его слова. Если есть сложные задания, то стоит писать мне напрямую, а я уже переработаю материал. Просто решения выкладывать нет смысла, потому что мы в самом описании стараемся дать его. Объяснить, Показать примеры.
