### ISSUE TITLE
Возможно не верный пример

### ISSUE THREAD

**Issue by Dmitry8ms** [peterarsentev/job4j_features_bugs#993]
Раздел 0. Виды ссылок [#6854 #248925], пункт PhantomReference.
Код в примере возможно не верный - после его выполнения очередь queue  продолжает содержать ссылки на объекты.

**Comment by peterarsentev** [comment]
В этом коде мы создаем фантомные ссылки. а сами управляем их видимостью в обход GC. 
Вызов GC ссылки не удаляем. а удаляем их мы сами через очистку очереди.
