### ISSUE TITLE
5.1.2. Создать итератор четные числа [#150] ошибочное утверждение

### ISSUE THREAD

**Issue by SamisheUN** [peterarsentev/job4j_features_bugs#994]
` - it.hasNext() - возвращает true, только если в массиве есть четные **перед указателем.** Например, если мы дернем два раза метод next(), то указатель сместится на второй элемент. При вызове метода hasNext() - он вернет false, т.к. после указателя больше нет четных чисел.`
 
метод возвращает тру, если есть нечто ПОСЛЕ указателя.

**Comment by AlexeySapsay** [comment]
Все правильно написано в задании. Этот итератор вам нужно реализовать самостоятельно. 
Не четный номер(порядковый номер) проверяйте, а четное число(значение)

**Comment by SamisheUN** [comment]
Порядковый номер и моё выполнение тут не при чём. В любом случае в тексте противоречие:
 - возвращает true, только если в массиве есть четные **перед указателем.**  (это неверно)  
[3, чётное_перед_указателем, указатель, 11, 13, 15] ===> hasNext(2) - перед указателем есть чётное, как и в утверждении, но метод не вернёт тру. даже в значении "рядом" тут неприменимо слово "перед".

 - вернет false, т.к. после указателя больше нет четных чисел. (это верно и прямо противоречит вышеуказанному)
 [чётное,3,указатель,11, 13, 15]

**Comment by AlexeySapsay** [comment]
[3,**указатель,** 4,  11, 13, 15] => true
перед  это значит с  права от указателя
если предполагаем нормальную итерацию в прямом порядке с лева на право

**Comment by SamisheUN** [comment]
тут я не в ту степь ушёл.

**Comment by SamisheUN** [comment]
В любом случае там противоречие и тогда некорректна вторая часть:

`При вызове метода hasNext() - он вернет false, т.к. после указателя больше нет четных чисел.`
(речь о массиве  {4, 2, **1**, 1});)

По этой логике он вернет false, не потому что после указателя нет чётных чисел, а потому что их нет перед ним.

**Comment by AlexeySapsay** [comment]
Вы правы, видимо тут ошибка
"т.к. после указателя больше нет четных чисел.- видимо должно быть **перед** указателем"

**Comment by peterarsentev** [comment]
Поправили описание. Спасибо.
