### ISSUE TITLE
Ошибка в задании

### ISSUE THREAD

**Issue by AlexeySapsay** [peterarsentev/job4j_features_bugs#997]
![image](https://user-images.githubusercontent.com/13130875/150620937-b0594d25-a93d-403c-9ee7-8cc32bdc54b2.png)
[https://job4j.ru/profile/exercise/84/task-view/454](https://job4j.ru/profile/exercise/84/task-view/454)

По условию задания нужно реализовать Candidate**s**Servlet, и это противоречит заданиям в конце статьи создать CandidateServlet.

В итоге что какой сервлет создавать CandidateServlet или CandidatesServlet?

**Comment by peterarsentev** [comment]
Неактуально. Этот блок убрали.
