### ISSUE TITLE
3.4. Временное хранение. git stash. [#309409 #255395]

### ISSUE THREAD

**Issue by YarTsin** [peterarsentev/job4j_features_bugs#998]
Не сразу нашёл, как использовать функцию.
Возможно картинки от старых версий и их нужно обновить
У меня idea 2021.2.2 и меню другое:
<img width="649" alt="git stash" src="https://user-images.githubusercontent.com/46091342/150968378-a740b20f-e0ac-4bd8-97e8-75423c54eead.png">

**Comment by peterarsentev** [comment]
Обновил. Спасибо.
